### ISSUE TITLE
Error while installing through the extension manager

### ISSUE THREAD

**Issue by greg-hutchinson** [turnermm/ckgedit#100]
I received some errors while installing.  (See attached)
![image](https://cloud.githubusercontent.com/assets/13004198/8512692/dd9afe6e-230b-11e5-9db4-1e145ab5ec18.png)

Was there other things I needed to install first?
Thanks

**Comment by turnermm** [comment]
You are probably running a version of Windows which does not allow for creating links, or else creating links requires administrator privileges.  See:
http://www.mturner.org/fckgLite/doku.php?id=docs:auto_install&s[]=mklink#troubleshooting
http://www.mturner.org/fckgLite/doku.php?id=media#security_and_the_media_directory

However on a windows system you should not need links. But you may have to move 
 ``plugins/ckgedit/fckeditor/userfiles/.htaccess.security`` to ``data/media`` and rename it ``.htaccess``

**Comment by greg-hutchinson** [comment]
Thanks for the quick reply. I will check that out.
... Greg ...

On 5 July 2015 at 14:29, Myron Turner <notifications@github.com> wrote:

> You are probably running a version of Windows which does not allow for
> creating links, or else creating links requires administrator privileges.
> See:
>
> http://www.mturner.org/fckgLite/doku.php?id=docs:auto_install&s[]=mklink#troubleshooting
>
> http://www.mturner.org/fckgLite/doku.php?id=media#security_and_the_media_directory
>
> However on a windows system you should not need links. But you may have to
> move
> plugins/ckgedit/fckeditor/userfiles/.htaccess.security to data/media and
> rename it .htaccess
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turnermm/ckgedit/issues/100#issuecomment-118665716>.
>



--
