### ISSUE TITLE
Title not supporting other modifications

### ISSUE THREAD

**Issue by MrBramard** [turnermm/ckgedit#103]
Hi, 

When I try to apply modifications on a title (for example add color or make it bold), the changes look good on the preview but when I save the modifications, the result looks bad.

If I try to make my title "Test" yellow and italic, the result looks great on the preview but when I save, I have this texte as a title : 
![image](https://cloud.githubusercontent.com/assets/1318811/8615640/be3e9b88-26f4-11e5-8267-73b275302879.png)

Here is the generated source code : 
![image](https://cloud.githubusercontent.com/assets/1318811/8615629/a8b0ff4a-26f4-11e5-82ed-657db452d709.png)

Dokuwiki : 2014-09-29d "Hrun"
Server : Windows Server 2008
ckgedit : The one you get via plugin manager

**Comment by turnermm** [comment]
Dokuwiki doesn't support text formatting in titles.  So, you would get a similar result whether or not you used the font styles.  
![title](https://cloud.githubusercontent.com/assets/176447/8617306/19d2610a-26c8-11e5-8b0b-fbd2eb9264bd.png)
