### ISSUE TITLE
Blogtng syntax not handled correctly

### ISSUE THREAD

**Issue by bailantilles** [turnermm/ckgedit#106]
When editing a page that already has syntax from the blogtng plugin included in the text of the page, the syntax gets corrupted when saving the page with ckgedit. Specifically the spacing down below:

    <blog newform>
    title  Add a new request:
    blog   cm
    format change_management:%Y-%m-%d:%{title}
    </blog>

Turns into:

    <blog newform> title Add a new request: blog cm format change_management:%Y-%m-%d:%{title}      </blog> 

Which makes it render incorrectly. This even happens when you just view the page in ckgedit without saving it.

**Comment by turnermm** [comment]
See: http://mturner.org/fckgLite/doku.php?id=features#multi-line_plugins

**Comment by bailantilles** [comment]
Thanks. I thought something the multi line macro was around, but I didn't find the information when I was searching.
