### ISSUE TITLE
Not loading properly in IFrame

### ISSUE THREAD

**Issue by rolandmichely** [turnermm/ckgedit#113]
re latest available download.    
When using ckgedit within an iframe the editor does not load.    The following error message:
TypeError: top.ckgedit_language_chk is not a function   in config.js:1:7751
Works great when not run in iframe.

Thx

**Comment by turnermm** [comment]
This is an old issue that arose almost from the start of this plugin 5 years or so ago.  I suggest that you search for IFRAME on both the forum and the mailing list for where you should find attempts at solutions, each a bit different.

**Comment by rolandmichely** [comment]
You are very correct.  I just came across it and I thought I'd check back here to let you know all is ok.  Thank you very much for the very quick response.        Great editor - Thank you very much.....
