### ISSUE TITLE
Wrong Image/PDF Path

### ISSUE THREAD

**Issue by basetrick** [turnermm/ckgedit#116]
Hello I've got a problem with the CKGEdit
The Dokuwiki is on a Windows 2012 R2 Server.

If i want to Upload a png Image or PDF it creates this path in the Sourcecode:
/dokuwiki/%255Chtdocs/lib/plugins/ckgedit/fckeditor/userfiles/image/test/mammooth_512x512.png

but the correct path is: (replace %255chtdocs with htdocs)
/dokuwiki/htdocs/lib/plugins/ckgedit/fckeditor/userfiles/image/test/mammooth_512x512.png

Thank you for your support

**Comment by turnermm** [comment]
What do you mean by Sourcecode?

**Comment by basetrick** [comment]
Nevermind it's just the wrong URL.
