### ISSUE TITLE
Various possible vulnerabilities

### ISSUE THREAD

**Issue by splitbrain** [turnermm/ckgedit#118]
A static scan of this plugins code revealed several possible problems with the code. Input values from the REQUEST variables and COOKIES seem to be outputted back to the browser unescaped leading to many possible XSS vulnerabilities.

See http://php-grinder.com/project/view/19092 for the scan results. Each of the found problems should be assessed and fixed if needed.

**Comment by turnermm** [comment]
I'm afraid I don't follow all of these entries.  For instance, the following in scripts/prev_delete.php is flagged:
```
$cname = $_REQUEST['draft_id'];
$cname = urldecode($cname);
```
But as you see it has been escaped in the javascript and unescaped here.  And the REQUEST variable is created in the editor (php) and passed to the javascript which then calls the script where the above lines  appear.  And what it is doing is completely internal to the editor and does not have a public face.

Many of the others which are flagged  come from the FCKEditor code, and I'll take a look at them  But most of those are internal to the CKEditor and not entering from an external source.

**Comment by splitbrain** [comment]
As far as I read the code at https://github.com/turnermm/ckgedit/blob/master/scripts/prev_delete.php this script allows me to delete any file on the server PHP has write access to.

Eg. calling ``http://example.com/dokuwiki/lib/plugins/ckgedit/scripts/prev_delete.php?draft_id=..%2F..%2F..%2Fconf%2Flocal.php`` (or similar) would allow me to delete the DokuWiki configuration file.

**Comment by turnermm** [comment]
I see your point. I thought by 'escaped' you meant urlencoded.

**Comment by turnermm** [comment]
See the recent updates, where I've implemented file checking in all my scripts which do input and output on the server from ajax calls.  So they should now have no vulnerability to outside access.  
Next I'll see what I can do about the scripts inherited from the FCKEditor.

**Comment by turnermm** [comment]
I've also fixed the REQUEST issues in my own code, but I haven't gotten to the FCKEditor code.  So that now from 79 vulnerabilities I'm down to 60.  The 60 are all in the FCKEditor code, and I'm not sure I fully understand yet what some of these are.    I'll have to look more closely.

**Comment by turnermm** [comment]
As I said in our [other conversation](https://github.com/turnermm/ckgedit/commit/8ac5f6d7564db1f43ae8ae2bb9b7025a8f03d057#commitcomment-14659719), these have all now been fixed.  merged a test branch with the master.
Here's the merged result: [Github turnermm/ckgedit/tree/test_cd 20151129](http://php-grinder.com/project/view/19928)
