### ISSUE TITLE
Can't switch to ckg edit, whet DW editor set as default

### ISSUE THREAD

**Issue by jbenicky** [turnermm/ckgedit#123]
Hi,
I set DW editor as default one. And when I try to switch to CKG edit, when editing some page, I always get DW editor.

I'm using latest version of DW (2015-08-10a "Detritus") and also ckgedit plugin (2015-12-09).

Could you please help me to resolve this issue? Thanks.

**Comment by turnermm** [comment]
Clear your browser cache.

**Comment by jbenicky** [comment]
It helped only for first load. Now it doesn't work again. :(

**Comment by turnermm** [comment]
Don't  know what to tell you; I can't reproduce the problem.  You should be able to switch back and forth without any issues.

**Comment by jbenicky** [comment]
Just to be really sure. Are you testing this with option "plugin»ckgedit»dw_priority Make Dokuwiki editor the default editor" checked, right? If I have DW editor set as default, pressing "CKG edit" button doesn't remove FCKG_USE cookie. Or maybe, this cookie is removed, but set again because of this checkbox in general settings.

**Comment by turnermm** [comment]
Yes.  I implemented this feature for my own convenience and use it.

**Comment by jbenicky** [comment]
Clean installation of dokuwiki helped. Anyway, thank you for your help.

**Comment by turnermm** [comment]
Glad to know this.  One benefit of this option is faster initial startups.
