### ISSUE TITLE
Formating buttons dosnt work

### ISSUE THREAD

**Issue by hubbamsn** [turnermm/ckgedit#124]
Hi
i've installed the plugin on two dokuwikis. one on Windows Server, one on Linux.
on both installations the complete formating-toolbar (bold, italic etc) dosnt work.
klicking the buttons dosn't Change anything within the selected text.
pressing ctrl+B and ctrl+i works.

Second question:
functionality of scayt dosnt work either.
Klicking the Buttons to Change language or dictionaly or info dosnt result in any Action.
Changing language in configuration-utility also dosnt change anything?

How can i solve These two Problems?
Thanks for answer.

Heiko

**Comment by turnermm** [comment]
I have fixed the Scayt plugin.  And while I didn't have the formatting issues, I believe the Scayt fix should also take care of the formatting buttons.  Let me know.
