### ISSUE TITLE
Internal Link

### ISSUE THREAD

**Issue by 1vkom** [turnermm/ckgedit#125]
I cannot add an internal link to new page. I tried 

1) Add Link to exiting page. Link Type " internal link"
2) Find "Search" and choose an existing page
3) After changing the name for example 
   :my namespace:startpage2
i confirmed it with "ok" 

startpage2 was not created. I must edit this new link an change the name to stratpage2 AGAIN. Only after this step startpage2 has been created.

**Comment by turnermm** [comment]
You can't change link names in the textbox.  I just uploaded a fix which disables the textboxes for internal linksand media links.
