### ISSUE TITLE
Editing of interwiki links

### ISSUE THREAD

**Issue by marcink** [turnermm/ckgedit#126]
Hi,

When editing a page with interwiki links, the ckgedit editor presents them as full URLs.  Anyone editing such a link will not know it was originally entered as an interwiki link - any edits will replace the interwiki link with a full URL.  Is there any way to make ckgedit provide access to editing the 'exact' text in the page source as opposed to enforcing the structure it currently does?  Any other suggestions for handling this?

Thank You.

**Comment by turnermm** [comment]
I don't see where that is happening.  Here is a page that has interwiki links:
http://mturner.org/devel/playground/links#interwiki

The editor show some of these as seen in the attached image.
![playground_links](https://cloud.githubusercontent.com/assets/176447/12469938/be2058bc-bfb5-11e5-85bc-e96698a82588.png)

**Comment by marcink** [comment]
The issue is when attempting to edit an interwiki link with the editor.  It replaces the interwiki part with a malformed full address.  The resulting URL is not only no longer an interwiki link, but also includes “oIWIKIo” and “cIWIKIc” text in it.

I’ll try to get some screenshots to show it.

Marcin

**Comment by marcink** [comment]
Looks like I can not re-open this issue.  I'll create a new one.

**Comment by turnermm** [comment]
As it stands now, you have to delete the current interwiki link and 
replace it.  This is in effect what is done in the native dw editor. 
I'm not sure if and when I will get around to doing what you want.
