### ISSUE TITLE
Trademarks disappear

### ISSUE THREAD

**Issue by rdealexb** [turnermm/ckgedit#128]
Hi,

The Trademark special character seems to disappear after Saving when using DokuWiki CKGEditor.
When looking at the Source before saving, the correct code is used: &trade;

However after saving, this is gone.

Can anyone else replicated, if so can it be fixed?

Many thanks

**Comment by turnermm** [comment]
You have to add it to your entities database, as described in the ENTITIES.HOWTO in 
ckgedit/action/entities.  This how-to is also found on the fckgLite web site: 
      http://www.mturner.org/fckgLite/doku.php/entities

You have to create a new file named add.ent in ckgedit/action/entities and create the new database as described in the documentation.  Here is the entity data that you have to add to add.ent:
``` 
™
&#8482;
&trade;
```
If you need any other new entities, just add them to this file and recomplie.  You can find lists of entities and their coding in the entities/utilities directory.

**Comment by turnermm** [comment]
I've done it for you. Just update the plugin.

**Comment by rdealexb** [comment]
Hi, that's great thanks - I've updated and it's working as expected.

Really appreciate the quick response, thanks again.
