### ISSUE TITLE
First issue ;-( authentication is lost when selecting internal link

### ISSUE THREAD

**Issue by Laurent3170** [turnermm/ckgedit#129]
Hi,
Firstly, I'm "honoured" to add the first bug ;-)
I have installed the latest version (maybe it has something to see with the bug).
I can edit what I want using the plugin but when I want to add an internal link and select "Internal link" the box below become gray and disabled but I'm still able to explore the server, so I choose a file, validate, and when I want to record, I have this message "Désolé, vous n'avez pas répondu correctement au test anti-spam. Peut-être n'êtes vous pas humain ?" which means "Sorry you have not well answered to the anti-spam test. Maybe you are not a human ?"...

Any idea ?
Thanks
Laurent

**Comment by turnermm** [comment]
Actually you are #129.
The text box is disabled because you can't use it to make changes.  It's only for information.  The message is from the captcha plugin.  You can't use the captcha plugin with ckgedit because the captcha is not displayed.

**Comment by Laurent3170** [comment]
Thanks.
Yes I saw #129 after posting ;-). I'll disable captcha as I don't see where it's used. It was working with before...
For the text box, it was not disabled before and it's useful to add a link to page that doesn't exist yet on the server, otherwise I don't know (using the plugin and not viewing the source) how to do.

**Comment by Laurent3170** [comment]
Oops :-( I have de-activated the captcha and uninstalled it (after first try) and it's still the same. Authentication lost

**Comment by turnermm** [comment]
That is not coming from ckgedit.  Clear the browser cache.   Then, disable the ckgedit plugin and create a page using the Dokuwiki editor.  Then clear the browser cache again and re-enable the ckgedit plugin.

**Comment by turnermm** [comment]
To create an internal link for a page that does not exist, just enter it into the editor as you would in the Dokuwiki editor.  So if you want to create a link to a page named __:documents:new_topic__, enter the folowing:

```
:documents:new_topic
~~

**Comment by Laurent3170** [comment]
So I've cleared the cache, etc. and I still have the same, I loose the authentication rights...
For the new page I have typed ":sujets:produits-menagers:essai" in the window's editor but it's taken as text.
Don't want to bother you...

**Comment by Laurent3170** [comment]
Ah you meant using Dokuwiki syntax, so with the [[ ]].

**Comment by turnermm** [comment]
Sorry.  Type as in Dokuwiki:  
```
[[:sujets:produits-menagers:essai|essai]]

```

**Comment by Laurent3170** [comment]
same time ;-)

**Comment by Laurent3170** [comment]
I did it once again, to be sure.
- I have de-activated the cache using the web developer toolbar in firefox(GNU/Linux)
- checked with firebug that there are really no cache.
- disabled the plugin
- refresh the page (even if no necessary)
- creation of a page, adding external, internal links, with saving (worked perfectly)
- re-enable the plugin
- refresh the page
- add external link with saving (worked perfectly)
- add internal link... and didn't worked (print screen attached)
![dokuwiki](https://cloud.githubusercontent.com/assets/16478286/12592530/18229314-c46d-11e5-874d-308760f22b29.jpg)

**Comment by turnermm** [comment]
First, as I asked before:  do you get the same result if you use the dokuwiki editor?  How did you install ckgedit:  did you use the extension manager?  

As for this message, it is not coming from Dokuwiki.  It must be coming from your server.   Where is your dokuwiki hosted?

I would treat this as suspicious, until I knew where it was coming from.  Why would you be asked for your login?  If you enter your userid, the next thing  you might be asked is for your password.

**Comment by Laurent3170** [comment]
No I don't have the same results using DW as it works.
I have installed the wiki by hosteur.com on a dedicated server (not ). The site is not yet one-month old. The plugin has been installed using the extension manager and everything worked perfectly. I did almost (some misunderstandings with bootstrapwrapper occured that I needed to fix with DW editor) every content using ckedit (including internal links, even using the [now] disabled text-box). And I've updated the plugin 2-3 days ago.

I don't know why I'm losing the authentication rights... But if I identify, I have access back. I don't think it's a security problem as it occurs only when I set an internal link.

**Comment by turnermm** [comment]
This is a  [previous version](https://github.com/turnermm/ckgedit/archive/8102bd73bb5628455219485debc32e1882ee71f9.zip) which comes just before I disabled the textbox.  Install it and see what the result is.

**Comment by Laurent3170** [comment]
it didn't work. Same results, authentication lost... So I have updated 4-5 plugins at the same time, including captcha (nos uninstalled) I need to investigate...

**Comment by Laurent3170** [comment]
For info here are the plugins I've updated... If it says something to you
avatar
bootswrapper
edittable (2015-10-05) but shown as to be updated
gallery
pagelist
redirect
vshare

**Comment by turnermm** [comment]
Disable all of these, then enable them one at a time.  I would suspect first redirect.  Also, ckgedit might conflict with edittable.

**Comment by Laurent3170** [comment]
Yes great idea (tired haven't think of disabling them) but I have suspected the same ;-) I'll let you know

**Comment by Laurent3170** [comment]
Don't know :-( I've disabled almost all of the plugins and still the same errot when setting an internal link...

**Comment by turnermm** [comment]
Disable all ans start from a clean wiki.

**Comment by Laurent3170** [comment]
I can't... the site is live

**Comment by Laurent3170** [comment]
Thanks a lot for your help and time

**Comment by turnermm** [comment]
I think you said you had some problems with the bootstrap template.  There is a plugin which will let you switch to another template when you access a certain page:
     https://www.dokuwiki.org/plugin:loadskin
So, create a page for yourself and have the dokuwiki template open when you access that page.  See if you get this problem when you are not using the bootstrap template.

**Comment by turnermm** [comment]
I thought about the way you use the internal link textbox and it is a valid use.  So, I have made a change.  

Now if a file  has not been selected, the textbox remains editable.  But if a file has been selected, then it is disabled for editing, because editing the textbox once a selection has been made does not change the selection. And users become confused by that and assume they have changed the selection when in fact they have not.  

Thanks.

**Comment by Laurent3170** [comment]
No it's with the Bootstrap Wrapper (not the template) that I have "problems" in fact they are not problems. Some of the "complex" instructions such as jumbotron where not understood as instructions by ckgedit but read as text and converted so, so for these I had to use the DW editor. But thanks for the idea.

Good news for the text box, this issue will have serve to this ;-) What you wrote sounds good to me.
