### ISSUE TITLE
Tags not working in IE11

### ISSUE THREAD

**Issue by proxymus** [turnermm/ckgedit#130]
Hello,
when I try to insert a tag with the IE11 nothing happens. The editor/site is grayed out but nothing else happens. It is working with Firefox and Chrome.
Regards,
Proxymus

**Comment by turnermm** [comment]
I see that.  Same thing in Edge.   But at this time I don't plan to fix this.  It works in every browser but Microsoft's, including Safari and Opera.

**Comment by turnermm** [comment]
I should add that the tag plugin was contributed by a user.  So I would first have to go back to him to see if he wants to look at this issue.  Also see https://www.dokuwiki.org/browser?s%5B%5D=internet%20explorer

**Comment by isf-val** [comment]
I do not plan to fix anything for IE. Please use a real browser.

**Comment by proxymus** [comment]
I will recommend this to my users.

**Comment by turnermm** [comment]
Thank you.  I will consider the issue closed.
