### ISSUE TITLE
Editing of interwiki links corrupts the source of the link

### ISSUE THREAD

**Issue by marcink** [turnermm/ckgedit#131]
(this is a re-opening of Issue #126)

It appears that when I edit a page using the ckgedit WYSIWYG editor, and specifically edit an interwiki link on that page, the resulting URL gets corrupted in two ways:

1. it is converted from an interwiki link to a regular internet address
2. the new URL includes “oIWIKIo” and “cIWIKIc” text in it

## Screenshots of the behaviour

The following is the starting state of the page (using DW's editor to show source code):
![page source before editing with ckgedit](https://cloud.githubusercontent.com/assets/282949/12760398/39d3b8ac-c9b4-11e5-9e46-d8f0db9f3219.png)

Than I switch over to using CKG Edit.  The link appears as expected in the editor:
![at start link appear correct in editor](https://cloud.githubusercontent.com/assets/282949/12760533/cef1548a-c9b4-11e5-9541-d264117815a9.png)

I than position the cursor on the link text and click on the 'link' button in the toolbar.  The dialog that comes up already shows a malformed full-URL (not an interwiki link):
![incorrect link on link edit dialog open](https://cloud.githubusercontent.com/assets/282949/12760665/6aedf2bc-c9b5-11e5-833b-78273e0c8027.png)

Modifying the link or even just clicking on OK without any changes shows the link changed in the editor:
![link in editor post edit](https://cloud.githubusercontent.com/assets/282949/12760739/d782dcee-c9b5-11e5-8e71-2c220e5f64d8.png)

At this point saving the page edit results in corrupted link being saved for the page:
![2016-02-02 14_05_38-corrupted link after save](https://cloud.githubusercontent.com/assets/282949/12760791/29da9fae-c9b6-11e5-9794-d376a22d0df6.png)

Opening this page in DW Edit to see source code reveals that the interwiki link syntax has also been removed:
![2016-02-02 14_08_11-corrupted page source after edit](https://cloud.githubusercontent.com/assets/282949/12760847/890f5d34-c9b6-11e5-882f-415ca4aa14d2.png)

**Comment by turnermm** [comment]
What the link dialog shows does not matter.  What matters is that the link as saved in the browser is correct.  Here is a short video which show that the wiki links are correct and that they work:

http://www.youtube.com/watch?v=UjUWNHfYE5g

**Comment by marcink** [comment]
Creating of the links works for me too.  Editing of the links does not.

**Comment by marcink** [comment]
It appears that the editor has extra trouble with an interwiki link that contains brackets, so `[[wp>bc_(programming_language)]]` for example

**Comment by turnermm** [comment]
I didn't find the parenthesis to be a  problem.

**Comment by turnermm** [comment]
As it stands now, you have to delete the current interwiki link and replace it.  This is in effect what is done in the native dw editor. I'm not sure if and when I will get around to doing what you want.

**Comment by turnermm** [comment]
I just refreshed myself on how those extra characters function:  they are inserted by the preprocessor and are part of the mechanism by which the interwiki link is marked up for later processing by the parser.  To do what you want would require adding an entirely new choice to the link dialog which would (1) create interwik ilnks and (2) recognize them and allow them to be revised in the same way that urls can be revised.

**Comment by marcink** [comment]
Much appreciate you looking at this.  This does sound like quite a bit of work.  Would there be, perhaps, an easy way for the editor to exclude interwiki links from being processed like regular links, so they would still appear like in the source?

**Comment by turnermm** [comment]
What is the benefit?  It seems simpler to me just to delete the old and rewrite the new.

**Comment by marcink** [comment]
I agree that this is simpler.  If there was a limited handful of individuals editing the wiki they could be educated to remember this special treatment of interwiki links.

In case of a large audience of contributors in a busy organization, I expect that only a subset will remember this requirement and most will _edit_ the links instead of _replacing_ them.  This will create ongoing work correcting such changes for anyone maintaining the wiki and I am very conscious about minimizing maintenance footprint for the website.

Does this make sense?

**Comment by turnermm** [comment]
What kind of organization?
