### ISSUE TITLE
Switching back to DW Edit mode uses most recent revision instead of selected revision

### ISSUE THREAD

**Issue by fslone** [turnermm/ckgedit#134]
Reported this bug to dokuwiki here:

https://github.com/splitbrain/dokuwiki/issues/1469

but @splitbrain thinks that it has to do with a plugin, so I think it's related to CKG Edit.

Original report:

Found a bug that made editing confusing, since I usually edit a page in DW Edit mode. How I triggered the error:

1.) Visit a page with multiple past revisions
2.) Under the "Old Revisions" link, choose to display a version before the most recent version
3.) Choose "Edit this page" to edit this past version
4.) Note that when the editor loads in GUI mode the past page revision is displayed as expected.
5.) Click "DW Edit" to edit via dokuwiki syntax. Note that now the most recent version of the page is being used for editing, instead of the revision that had been selected.

**Comment by turnermm** [comment]
This is not a bug.  The same thing happens in reverse.  If you are in the native dokuwiki editor and click on the ckgedit button, you are switched into the current version of the page, even if you are viewing an old revision.  This is because ckgedit does not keep a record of the last selected old revision loaded into the editor;  it  loads the current page from the disk.

**Comment by splitbrain** [comment]
TBH that sounds like a bug to me. The editor should honor the value of the $REV global. Being able to switch to an old revision and edit it (thus creating a new revision) is a core feature of DokuWiki.

**Comment by turnermm** [comment]
On 2016-02-15 2:01 PM, Andreas Gohr wrote:
> TBH that sounds like a bug to me. The editor should honor the value of
> the $REV global. Being able to switch to an old revision and edit it
> (thus creating a new revision) is a core feature of DokuWiki.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turnermm/ckgedit/issues/134#issuecomment-184365985>.
>
You can do that.  That's always been there.
