### ISSUE TITLE
FCKEditor doesn't show images in Firefox and IE11 

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#141]
Open the FCKEditor to upload an image. It correctly lists the files but doesn't display any image. The problem appears both on Firefox and IE11 of course.

http://image.noelshack.com/fichiers/2016/08/1456412429-display1.png
http://image.noelshack.com/fichiers/2016/08/1456412429-display2.png
http://image.noelshack.com/fichiers/2016/08/1456412429-choseimage.jpg

"Edit" : My data folder contains the default htaccess file with the following content (in order to avoid browsing it by typing the URL in the address bar) :

> order allow,deny
> deny from all

Removing the htaccess file fixes the issue but adds some kind of security problem. 
What can I do ? 

Thank you for you help.

**Comment by turnermm** [comment]
Move .htaccess.security from fckeditor/user files to data/media and rename it .htaccess. Then restore the original .htaccess to data/.  See: 
http://www.mturner.org/fckgLite/doku.php/doku.php?id=media&b_disp=1#security_and_the_media_directory

**Comment by blacklord049** [comment]
Nice it's working as expected, thank you!
