### ISSUE TITLE
[Enhancement] Language translations (CKGeditor Media and image popups)

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#142]
Open the CKGeditor, click on the "Image" button.

Some parts of the popup window are not correctly translated. Here are some translations you can add for the french JS file. It goes the same for the media popup and FCKEditor.

Link type = Type du lien

_"Link Type" Combo_
 -> No link = Aucun lien
 -> Link only = Lien simple
 -> Detail = Détail de l'image
(what's the difference between "direct" and "link only" ?)

In the CKGeditor, chose "Link" button to create a new link. Some translations are missing.

_"Link Type" Combo_ (already translated here)
 -> Internal Link = Lien interne.
 -> Internal Media = Fichier
 -> E-mail.
 -> Samba Share = Partage Réseau
 -> Interwiki = Lien interwiki

**Internal link choice**
Internal link = Lien interne
Use the advanced tab to create page anchors and query strings = Utilisez l'onglet Avancé pour créer des signets et des liens paramétrés.

**Internal media choice**
Link to media file = Lien vers le fichier

**Samba Share choice**
Enter your share as: \\Server\directory\file = Saisissez le lien au format UNC : \\serveur\dossier\fichier.ext
Samba Share = Partage Réseau

**Interwiki link**
Interwiki Replacement Text = Texte de remplacement interwiki
Interwiki Type = Type Interwiki

**Comment by turnermm** [comment]
Hopefully you will find the answers to you questions here: https://www.dokuwiki.org/plugin:ckgedit#language_support

**Comment by blacklord049** [comment]
Thank you it's working !

**Comment by blacklord049** [comment]
I've added some translations to the fr.js files. You can grab the files here : 
http://www.mediafire.com/download/qywl5n9r233u0nj/fr_lang.rar

Some translations are too literal (eg : font assist) so if someone wants to review them you're free to go. Would be nice to include them for the next release of the plugin :-)

**Comment by turnermm** [comment]
Thank you for the translations.  There were two that were missing, and I've temporarily added from the English:
```
CKEDITOR.lang['fr']["indent"] = {
        "indent": "Nested List",
        "outdent": "Decrease Nesting"
 };
CKEDITOR.lang['fr'] ["stylescombo"]["label"]= "Code";

```
Also in reference to [#144](https://github.com/turnermm/ckgedit/issues/144), I fixed the link plugin so that all that is now needed is the ``SMBLabel`` entry in fr.js.  Thaks for all the work.

**Comment by blacklord049** [comment]
See this : https://github.com/turnermm/ckgedit/issues/145 (image.js improvement and language update)

**Comment by turnermm** [comment]
There are now fixes for all of the missing language strings that you reported.  They can all be handled through converting the strings in ckgedit.en.js to your language and appending it  to your language file.
