### ISSUE TITLE
[Enhancement] FCKEditor French translations for some fields

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#143]
Some fields are hardcoded in the html files... Like : 
- Upload = Envoyer (button)
- Create Folder = Créer un dossier 
- Move Ctrl+xxx = Déplacer...
- Uploadable = Téléchargement autorisé / Téléversable.
- Read-only = Lecture seule.
- Resource type = Type de média / Type de ressource.
- File = fichier.
(ect) 

Would be nice to have a dynamic translation regarding the chosen browser language.

**Comment by turnermm** [comment]
See: https://github.com/turnermm/ckgedit/issues/142
