### ISSUE TITLE
Any way to add figure captions?

### ISSUE THREAD

**Issue by billzt** [turnermm/ckgedit#146]
Is there any way to add figure captions for uploaded images using ckgedit (Or other WYSIWYG method) ? [Imagereference](https://github.com/Klap-in/dokuwiki-plugin-imagereference) is a nice plugin, However it only support editing from source code.

**Comment by turnermm** [comment]
I can't test all of the imagereference types but many of them can be entered into the edtiro as you would in the Dokuwiki editor:  http://www.mturner.org/devel/playground/imageref

```
~~MULTI_PLUGIN_OPEN~~

<imgcaption label|John Doe>{{:wiki:dokuwiki-128.png}}</imgcaption>

The Dokuwiki image can be seen in <imgref label>.
~~MULTI_PLUGIN_CLOSE~~

<imgcaption mynewimg| This is my little caption>{{:wiki:dokuwiki-128.png}}</imgcaption>

<tabcaption tablelabel| This is my other caption>
^ Heading 1  ^ Heading 2       ^ Heading 3          ^
| Row 1 Col 1  | Row 1 Col 2     | Row 1 Col 3        |
</tabcaption>
```
Of these three only the top one is fussy, but if you insert it into the Dokuwiki editor and get it  tow work, once  you save, it tends to hold.  If it loses its formatting then just go back to the Dokuwiki editor, get it to work and re-save.

Read the documentation on how to handle plugins on the ckgedit plugin page.

**Comment by turnermm** [comment]
It's also helpful if, when entering the markup into the Dokuwiki editor, you add an extra line break:

```

~~MULTI_PLUGIN_OPEN~~

<imgcaption label|John Doe>{{:wiki:dokuwiki-128.png}}</imgcaption>
\\
The Dokuwiki image can be seen in <imgref label>.
~~MULTI_PLUGIN_CLOSE~~
```
