### ISSUE TITLE
CKEditor French Translation 20160301 Update

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#149]
It appears that I uploaded the wrong file. The link type translations for the combo were missing.
http://www.mediafire.com/download/6pi5rp6tbffsb5x/ckeditor_lang_fr_20160301.rar

**Comment by turnermm** [comment]
You are still mikssing the following:
```
CKEDITOR.lang['fr']["indent"] = {
        "indent": "Nested List",
        "outdent": "Decrease Nesting"
 };
CKEDITOR.lang['fr'] ["stylescombo"]["label"]= "Code";
CKEDITOR.lang['fr']["indent"] = {
        "indent": "Nested List",
        "outdent": "Decrease Nesting"
 };
```

**Comment by blacklord049** [comment]
I don't.

"fr.js.unc"

Line 406
```
    "indent": {
        "indent": "Augmenter le retrait (tabulation)",
        "outdent": "Diminuer le retrait (tabulation)"
    },
```

Line 570

```
    "stylescombo": {
        "label": "Styles",
        "panelTitle": "Styles de mise en page",
        "panelTitle1": "Styles de blocs",
        "panelTitle2": "Styles en ligne",
        "panelTitle3": "Styles d'objet"
    },
```

**Comment by turnermm** [comment]
ckgedit replaces  "Styles"  the Code elements , which you have already translated.

I've completed the translation updates and have modfiied image,js to use the new translations.  You can get it from github in the master branch and in the 4.5.7 branch, which is the latest version of CKEditor, whereas the master is at 4.5.1.

Thanks for all your work.
