### ISSUE TITLE
Tags become lowercase

### ISSUE THREAD

**Issue by billzt** [turnermm/ckgedit#150]
It seems as if ckgedit support adding tags. #78 
However I didn't find any relative instruction(document) either in ckgedit or in dokuwiki main site.
How to add tags?

**Comment by turnermm** [comment]
https://www.dokuwiki.org/doku.php?id=plugin:ckgedit#tags_plugin

**Comment by billzt** [comment]
OK. However there is still something seems strange: If I enter a tag called "EB". After save it, it appear as "eb". Lowercase. Is it a bug?

**Comment by turnermm** [comment]
NO.  Dokuwiki uses lower case for links.  And tag are links.
