### ISSUE TITLE
New line character is sometimes inserted 

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#151]
Seems to happen when there is a table in the edited section : 
- Position your cursor at the very end of your text.
- Insert a new line at the end and write some stuff.
- Save page, see the result. 
- Return in edit mode ; a \\ line has been inserted.
- Removing it doesn’t delete the \\ ; you need to go back to the DW editor to remove the character.

Problem description with screenshots : http://www.mediafire.com/download/cndk9z62i7hy9w6/New_line_issue_when_there_is_table.docx

**Comment by turnermm** [comment]
Could not reproduce but it's true that in some circumstances newlines are inserted.
