### ISSUE TITLE
Tag plugin Language enhancement (french)

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#152]
Can you add this to the french language file ?
Thank you ! 

in fr.js.unc (+fr.js) => 

`CKEDITOR.lang['fr'] = {`

Add : 

```
	"tags": {
		"dlgTitle": "Mots-clés / Tags",
		"customTags" : "Personnalisé - Liste de mots séparés par des espaces. Les espaces dans les mots doivent être remplacés par des tirets bas _."
	}
```

**Comment by blacklord049** [comment]
Updated files : http://www.mediafire.com/download/mcmhpwytmy36cnq/ckeditor_lang_fr_20160303.rar

**Comment by turnermm** [comment]
done
