### ISSUE TITLE
Argument #2 is not an array in C:\\xampp\\htdocs\\wiki\\inc\\init.php on line 176

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#153]
Posted to the Dokuwiki github
(maybe this is not caused by CKGEditor)
See https://github.com/splitbrain/dokuwiki/issues/1491

**Comment by turnermm** [comment]
On 2016-03-04 9:14 AM, blacklord049 wrote:
> A few minutes ago I was working on a page. I made many changes ; edit,
> save, edit, save...
> Suddenly after a click on the Save button, I've been thrown on the main
> page with the following error:
>
> |[Fri Mar 04 15:31:59.983172 2016] [:error] [pid 7504:tid 2044] [client
> 132.128.100.115:54134] PHP Warning: array_merge(): Argument #2 is not an
> array in C:\\xampp\\htdocs\\wiki\\inc\\init.php on line 176, referer:
> http://intranet.dilibel.int/wiki/doc/dilibelint/adelia/start|
>
> Access.log :
> http://pastebin.com/tmRBnTG6
>
> Unable to access to the configuration page or the editor.
> I had to restart the server to resolve the issue.
>
> I wonder what could cause this issue.
>
> Thanks for your help
> Apache 2.4 x86 (Windows Server 2008 R2), DokuWiki Detritus stable
> release, PHP 7.0.3, Bootstrap3, Bootstrap Wrapper, CSV Plugin,
> CKGEditor, DataTables, Note plugin, Pagelist, Tag, Video Sharing,
> Cleanup, Searchindex Manager, Include.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turnermm/ckgedit/issues/153>.
>
Something like this should go to the forum first.

**Comment by turnermm** [comment]
What do you find in the  error log?  The access log doesn;t give the info needed.
