### ISSUE TITLE
[Feature Request]: Add support for WRAP Plugin

### ISSUE THREAD

**Issue by Mannshoch** [turnermm/ckgedit#155]
https://www.dokuwiki.org/plugin:wrap

Please add the rendering of the correct content position in ckgedit.

**Comment by turnermm** [comment]
On 2016-03-15 9:03 AM, Mannshoch wrote:
> https://www.dokuwiki.org/plugin:wrap
>
> Edit a Page with this addon should as a minimum show a Frame and

Don't know what you are talking about.  See: 
http://www.mturner.org/devel/playground/wrap_examples

**Comment by Mannshoch** [comment]
Srange in my CKGEDIT window I only see the Tags. no rendered elements.
Do I have to activate the support of the WRAP Plugin somewhere?

**Comment by turnermm** [comment]
Try reinstalling Wrap and make sure you haven't accidentally disabled it.

**Comment by Mannshoch** [comment]
Wrap it self work fine.
But it is not rendered in CKGEDIT.

![playground_wrap_edit](https://cloud.githubusercontent.com/assets/7795891/13839442/5cfffa46-ec1b-11e5-979a-7a6a642e8b09.jpg)
![playground_wrap](https://cloud.githubusercontent.com/assets/7795891/13839443/5d040bfe-ec1b-11e5-9b35-0e4dea16a634.jpg)

**Comment by turnermm** [comment]
See the ckgedit documentation: https://www.dokuwiki.org/plugin:ckgedit#plugin_handling
Example: http://www.mturner.org/devel/playground/ckgedit_wrap

**Comment by Mannshoch** [comment]
The Enhancement to get WRAP rendered is my Request to you.

I'm sorry for this misunderstanding. I wish a correct position of the Content in ckgedit. I do not need every function somehow implemented. I wish only a correct position in ckgedit.

**Comment by turnermm** [comment]
I'm not sure that you understand the way ckgedit works.  It **does not** render plugins in the editor.  They are rendered only in the browser.  There are no exceptions to this.

**Comment by turnermm** [comment]
You can try the fckg plugin.  That does attempt to render plugins in the editor, but it is no longer being maintained.

**Comment by Mannshoch** [comment]
I do not need a full WRAP support. I only need the possibility to set up the position. Isn't it possible to render WRAP as html tag like described here:
http://stackoverflow.com/a/11467718
and use some javascript magic to setup some position options?

```
<WRAP> => <div>
<wrap> => <span>
30% = style="width=30%;"
```

Never seen it but it seems that there is a posibility to claculate in CSS: 
for the **half ** tag there seems something like.

```
.dokuwiki .wrap_half:nth-of-type(2n+1), .dokuwiki .wrap_third:nth-of-type(3n+1), .dokuwiki .wrap_quarter:nth-of-type(4n+1) {
    clear: left;
}
```
in a css file. (If Firebug tells me right)

I thought about something like this:
![wrap](https://cloud.githubusercontent.com/assets/7795891/13886914/9098003c-ed39-11e5-819c-cc76b43d8068.png)
Rendered WRAP and a small overlay Icon which allow to edit the tag.

**Comment by turnermm** [comment]
I don't know what you want to achieve because you do not mtake clear the distinction between the ckgedit editing window and the final page as it is rendered in the browser.  

1.  If you want this to show up in the final page, as rendered in the browser:
    the wrap plugin already has the ability to float objects and, moreover, with some ingenuity it is possible to create your own classes and have the the wrap containers appear any way you like.
2. If you want this to render in the editor:
     then you can modify contents.css in  ckgedit/ckedtior .  This is a compressed file; its uncompressed version is contents.css.unc, where you can make your changes and then rename it contents.css.  But whatever classes you create in contents.css must then be reproduced in the wrap plugin's classes if you want them to display in the page (i.e. 1).

**Comment by turnermm** [comment]
On 3/18/2016 10:47 AM, Mannshoch wrote:
> I do not need a full WRAP support. I only need the possibility to set up
> the position. Isn't it possible to render WRAP as html tag like
> described here:
> http://stackoverflow.com/a/11467718
>
Not possible.  You are confusing the text that you see in the editor 
with the underlying HTML.  The HTML is what you see when you click on 
the Source button.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
