### ISSUE TITLE
[Enhancement Request] Add a textbox to edit Linktext

### ISSUE THREAD

**Issue by Mannshoch** [turnermm/ckgedit#156]
Please add an ability to edit the Linktext. (most of the time replacing a text with CTRL+v split or replace the Link instead editing it.

![2016-03-15](https://cloud.githubusercontent.com/assets/7795891/13780980/e4239d58-eac1-11e5-9d56-1dea9145e0c5.jpg)

**Comment by turnermm** [comment]
Not sure I entirely follow but if I do: enter the link text into the editor, select it with mouse, then create link. The link will point to www.whatever but the link text will display as whatever you have highlighted.

**Comment by Mannshoch** [comment]
Yes that's right but I'm not able to change the Name of the Linktext if I wish to copy/paste it

**Comment by blacklord049** [comment]
In fact the only way to edit the text link is : 
- to edit the text directly inside the link.
- to recreate it.
Would be nice to do that with the popup editor.

**Comment by turnermm** [comment]
There are too  many link types and so too many variables to make it worthwhile for something that can be easily done manually.  You can always copy and paste a link and edit the display text in the editor, if by ``Name of the Linktext``  you mean the text which is displayed in the browser.

**Comment by blacklord049** [comment]
In fact it goes the same with links to an uploaded file ("internal file"). Would be interesting, precisely in this case, to have a text box to give the link description of the file we're inserting. 
Yes we mean the `name of the linktext`.

Ex : 
`[[http://www.google.be|Google Search Engine]]`

In this case, you would type "Google Search Engine" in this new text box.
