### ISSUE TITLE
[Feature Request] Add search bar and/or Sort to FCK Resource Broswer

### ISSUE THREAD

**Issue by MOEditor** [turnermm/ckgedit#157]
First off, thank you so much for this amazing plugin and all of the work you've put into it.

When uploading images into the editor through the FCK Resource Browser (accessed from the images icon in the toolbar > browse server), it can be a bit of a hassle to find images right after uploading them, since the image list is alphabetical and some namespaces can become quite packed with image files to scroll through. When I upload a new image, it disappears into the list of files, and I have to scroll through and remember what I named it to find it in the list.

It's not a major issue, but it's a chance to enhance the system a bit :) . It would be a great addition if the FCK Resource Browser had a search bar so that users could search for images already on the server, or find the image they just uploaded.

It would also be great it the images listed in the resource browser could be sorted to have the newest uploaded files show up first. In fact, if the search feature was too much trouble to work with, a sort feature would go a long ways in itself.

Thank you for your consideration, and for offering this plugin!

**Comment by turnermm** [comment]
On 2016-03-17 10:40 AM, MOEditor wrote:
> It's not a major issue, but it's a chance to enhance the system a bit :)
> . It would be a great addition if the FCK Resource Browser had a search
> bar so that users could search for images already on the server, or find
> the image they just uploaded.
>
> It would also be great it the images listed in the resource browser
> could be sorted to have the newest uploaded files show up first. In
> fact, if the search feature was too much trouble to work with, a sort
> feature would go a long ways in itself.
>
These are things to think about.  Thanks.

**Comment by proxymus** [comment]
This sounds useful for me too. 
Have you tried to paste an image from clipboard directly into the editor (STRG+V)? I'm doing that, so I don't need the FCK Resource Browser for uploads. 
The only problem I've noticed that you have to save the article before you can resize or move the inserted picture. Otherwise you will get something like this:

`base64_ivborw0kggoaaaansuheugaaagkaaacgcaiaaaajjgigaaagaeleqvr4no2d_1sur7rh_sm0yznk4zlnd9fisjgnnngeokuyrhfj9jhoedj4jtekgo2bigjaqnnoeowlri03ikkrgoqueyeigk_oiioxqblqbgii1xlu3y3s_afmenqql9pdjidwfz_pd9pdvf3w29317bo[...]`

when you save the page afterwards.

**Comment by turnermm** [comment]
Yes, that's because the image, while it appears on the screen, exists only as embedded data until it is saved.

**Comment by turnermm** [comment]
See:  https://github.com/turnermm/ckgedit/archive/fb_search.zip
Search and sort functions have been added to a revised file browser.  The sort functions are excluded from IE but not from Edge.  Tested in Safari on current OS X, on Edge, Chrome, Firefox.  Try it and see if  it works for  you.  The sorting all goes from lowest to highest, meaning that you most recent entries are at the end of the list.

**Comment by MOEditor** [comment]
Thank you for addressing this so quickly!

This is probably my own lack of knowledge, but I can't seem to get it to work.

I downloaded the .zip file, extracted it, and copied both the ckgedit and the ckgedit-fb_search folders into the plugins folder. I received some symbolic links errors on DW (I'm on a Windows server...), and I wasn't sure what to do about them, but I was still able to upload files. However, I didn't see any new features in the file browser.

I tried removing the ckgedit folder and renaming the ckgedit-fb_search folder to "ckgedit" and everything seemed to still work fine, except I still didn't see any indication of search or sort functions.

I'm sure I'm missing something in the install process. I'm afraid I need a little guidance.

**Comment by turnermm** [comment]
On 2016-04-04 11:14 AM, MOEditor wrote:
> Thank you for addressing this so quickly!
>
> This is probably my own lack of knowledge, but I can't seem to get it to
> work.

Try refreshing your browser cache and then open the configuration 
manager and click the save button.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by turnermm** [comment]
This is what you should be seeing:

![fb_search](https://cloud.githubusercontent.com/assets/176447/14268540/b922178e-faa1-11e5-89f6-e619c2311c43.png)

**Comment by MOEditor** [comment]
Works great! Refreshing the cache and saving configuration did the trick!
This is an exciting new feature; thank you so much for sharing it!
