### ISSUE TITLE
troubleshooting with image insertion

### ISSUE THREAD

**Issue by itivet** [turnermm/ckgedit#158]
Image insertion doesn't work anymore. When I'm editing the page everything goes right. But right after saving it, the images doesn't appear anymore. I've only got a small image that show the name of the file. If I'm editing the text again and that I edit the properties of the image I don't have the image but a white cross with red background. If I search the server for my image again I can find it in the folder of the namespace of my page. 

Things that are strange is that if I check other namespace folder I can't see any other images and If I open the media manager I can browse those other namespace folder except the one where is located the images that doesn't appear.

Any idea?

**Comment by itivet** [comment]
I found that the image that does not show are located  here: /dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image

and previously there where putted here: /dokuwiki/data/media

**Comment by turnermm** [comment]
``userfiles/image`` should be a symbolic link to ``data/media``.  If it is a directory, then the link was not created after an upgrade.

**Comment by itivet** [comment]
Si what should I do to fix it?

**Comment by itivet** [comment]
So what should I do to fix it?

**Comment by turnermm** [comment]
If you can make changes to the file system, try this.  First go to the userfiles directory and remove the directory, file and link entries which you find there.  Then go to data/meta and remove the fckl directory.  Then reinstall ckgedit.

**Comment by itivet** [comment]
It worked perfectly! Thanks a lot.
