### ISSUE TITLE
Create a sub-namespace with an empty start page when creating an internal link

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#159]
Hi,

In fact the idea is in the title. I have the permission to create or delete pages into the current namespace. However I'd like to use the FBrowser to create a sub-namespace. You know for end-users who are not used to Wiki syntax, creating a link to a page that does not exist is not easy at all, even with the wizard. The thing is, it would be interesting to have a button to create a new namespace with an empty "start" page, then the link would refer to it.

What do you think ?
Thank you

**Comment by turnermm** [comment]
See either the addnewpage or newpage plugin
