### ISSUE TITLE
Restoring a page (even if deleted) without updating the content does not restore it

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#160]
Hi,

I made those steps : 

- Delete a page (click on Delete in CKGeditor).
- DokuWiki says "the page does not exist".
- Go to "Older versions" page
- Click on the page you want to restore.
- Modify it with CKGeditor.
- Save it. 
- Page is not restored.

Try to restore another revision : doesn't work, unless if I type some new text or add something to the page. It seems that it only restore a page if you bring some updates to it.

Switched to DW editor to test if it occurs. Restoring a page works perfectly with the base editor.

**Comment by turnermm** [comment]
Good point.  I'll fix that. but in the meantime, just a carriage return or a push of the space bar will suffice.  Normally ckgedit doesn't save a page unless it knows that there has been activity on that page.  But it should save if it is a revision.

**Comment by turnermm** [comment]
Should be fixed.  Give it a try.

**Comment by blacklord049** [comment]
Updated the code ; seems to works fine now ! Great, thank you a lot.

**Comment by turnermm** [comment]
Thank you!
