### ISSUE TITLE
Issue with PHP7

### ISSUE THREAD

**Issue by jfha73** [turnermm/ckgedit#164]
Hey guys,

This doesn't happen all the time, but from time to time, this extension gets stuck and it won't show, I have PHP7 on my PC, I don't know if this might be why, but since it's fairly new, I guess the code for the extansion has not been completely ported to work with it.

**Comment by turnermm** [comment]
I need more than this to go on.   It's been synced with PHP 7.0 and I have run it on a php 7 Windows test site without any problems.  See if you can get anything back from a browser debugger, like firebug in firefox.  And you might try disabling all of your plugions and then adding them back in one by one.  There could be a conflict.

**Comment by jfha73** [comment]
Today it's working fine, but I'll try to gather as much info as I can when
it happens again.

Thanks.
