### ISSUE TITLE
FTP links are being destroyed after saving

### ISSUE THREAD

**Issue by MarekWo** [turnermm/ckgedit#165]
Here is how to reproduce that bug:
- Create URL link in the following format:

[[ftp://user:password@ftp.sample.com|Description 1]]

- Save and close DokuWiki entry
- Go to edit mode and add another link with similar URL

[[ftp://user:password@ftp.sample.com|Description 2]]

- Save and close again
Result: The first URL will be converted to internal link

If you try to repair the URL 1, save and close - the URL 2 will get destroyed and converted to Internal Link.

It is really, really annoying. Please advise!

**Comment by turnermm** [comment]
> It is really, really annoying.
Should be fixed now, even without the annoying emphasis.

**Comment by MarekWo** [comment]
Thanks for your quick reply and sorry for the 'annoying' emphasis :)
So, does it mean that the new version can be downloaded somewhere?

**Comment by turnermm** [comment]
Yes.  It's ready for update using the extension manager.  It's the current master version found here on github.  It's best that you use the extension manager for updating.
