### ISSUE TITLE
Code blocks

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#166]
Hi,

Displaying a code block in CKGEditor : 

  * Before update : http://image.noelshack.com/fichiers/2016/14/1459933423-editcodeblock1.jpg
  * Then after update, go to edit mode and see that the code block is "extended" : http://image.noelshack.com/fichiers/2016/14/1459933423-editcodeblock2.jpg . (however it does not affect the look & feel in the page).

I don't know if it's possible to fix the display behavior...
Thanks in advance

**Comment by turnermm** [comment]
That''s intentional.  Otherwise Ckedtiro doesn;t let you add to end of the block.
