### ISSUE TITLE
Create internal Link : Browse the server then link field being disabled

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#167]
To reproduce the "issue" : 

* Select your text.
* Create a new link on it.
* Chose "Internal link".
* Chose "Browse the server".
* Chose a page.
* The field Internal link is greyed out and disabled too (= unable to write manually). 
* You have to click OK and then edit the link to have the field enabled again.

**Comment by turnermm** [comment]
intentional.  Because editing the text  and saving does not have the desired effect.
