### ISSUE TITLE
FBrowser Windows resizing but the content doesn't adapt itself

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#168]
See for yourself : 

http://image.noelshack.com/fichiers/2016/14/1459938251-biggestsize.jpg
http://image.noelshack.com/fichiers/2016/14/1459938251-normalsize.jpg

Cleaning the cache and save the configuration doesn't change anything.

Edit : maybe I was too quick, it seems to be for those who are using zoom browser...

**Comment by turnermm** [comment]
The size of the fil ebrowser does not change.  Only the size of its enclosing window --   to accommodate higher than the default zoom levels in the browser (not the file browser).  See the file browser help.

**Comment by blacklord049** [comment]
Thank you. In fact I read it but too late...
