### ISSUE TITLE
PlantUML's <uml> tag has been escaped

### ISSUE THREAD

**Issue by h920526** [turnermm/ckgedit#170]
PlantUML's <uml> tag like this

```
<uml>
@startuml
title Sample 1
@enduml
</uml>
```

It has been escaped after editing page content by ckgedit plugin,

dokuwiki (2014-09-29d "Hrun")
ckgedit plugin (version 2015-10-30)

thank a lot.

**Comment by turnermm** [comment]
I'm not sure what you are referring to.  This is what I get:
http://www.mturner.org/devel/playground/line_spacing#single_line_spaced_html-style
