### ISSUE TITLE
Cell in table gets set to horizontal alignment 'Right' upon save after entering a carriage return

### ISSUE THREAD

**Issue by slysi123** [turnermm/ckgedit#172]
Create a table 3 rows, 3 columns, first row headers, enter text into the headers, then enter text into a data cell and press return, the text jumps down slightly, type some more text on next line and press save, the cell gets horizontal alignment set to 'Right'

Also if you add a numbered list at the same time the data in that cell usually ends up outside and below the table when you save.

Thanks in advance.

**Comment by turnermm** [comment]
If you want to add lines to a cell, you have to single space.  This is done by holding down the shift key while pressing return.

As far as I know, you can't put lists inside cells in Dokuwiki.  Lists are coded against the left-hand origin of a new line, each item ending in a new line.  The left-hand origin of a table cell is a vertical bar and a true right-hand new line would destroy the cell.

**Comment by slysi123** [comment]
Thank you for your quick response and explanation. This makes sense.
