### ISSUE TITLE
CKGEdit sometimes creates "code" elements

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#173]
I don't know why and I didn't use any copy/paste functionality but it happens that CKGedit creates code blocks where it shouldn't. Here I added an image in my text, added a white line under and then some text. Everything below the image was in a code block after I clicked Save.

**Comment by turnermm** [comment]
Never saw this myself.

**Comment by blacklord049** [comment]
Damn I'm not lucky at all ;-)
