### ISSUE TITLE
Add a timestamp button (plugin Timestamp)

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#175]
-> https://www.dokuwiki.org/plugin:timestamp

**Comment by turnermm** [comment]
I've used this as an  opportunity to add a new feature, namely the ability to add a new toolbar button based on a user-defined plugin.  The CKEdtor docs come with a sample plugin for developers which is in fact a timestamp plugin.  I've modfied this and included it in ckgedit.  If you want to use it, you can download the latest distro and go to the configuration settings for ckgedit, and add 'Timestamp' to the current final option: ``extra_plugins``.  If you don't like the format, and you have someone with Javascript experience, make the change in ckeditor/plugins/timestamp/plugin.js.

**Comment by blacklord049** [comment]
Thank you!
