### ISSUE TITLE
SMB Links, issue and idea

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#176]
Create a SMB Link but to a folder, with a backslash.

E.g. `\\server\folder1\folder2\`

Note that the backslash is important to see the problem here.
Save your page : the link appears in your page. Target is a little bit strange : 

`file://///server/folder1/folder2/%22%20title=`

Then edit the page : the link is gone !

Now, an idea : are Firefox and IE able to browse or see if drive letters exist ? Users in our company are linking to files on shared drives with letters like T, V, S, or K. But it's not possible right now to put the path like `V:\Folder1\Folder2\File.docx`. The idea is to allow this kind of link but I don't think that browsers are allowed to read letters and their real paths...

**Comment by turnermm** [comment]
You can use shares only in IE, though I think there may be a plugin for  Firefox that accepts them.  The  `file:////server` notation is the way the share is represented internally by Windows.  To use a share, it seems that you can't use drive letters but must use the share name.
