### ISSUE TITLE
Extra plugin does not appear

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#180]
I saw that you added timestamp (+ ability to add custom plugins).

I set "timestamp" in the new DokuWiki config parameter.

However I cleared Dokuwiki, CSS and Browser cache, saved Dokuwiki config, restarted the Apache server, but the button doesn't appear :-)  Even if I add "fr" in "plugin.js" for timestamp, and the corresponding "fr.js" file, it still doesn't work...

What am I missing here ?

**Comment by blacklord049** [comment]
OK I think I know how it's supposed to work...

**Comment by turnermm** [comment]
You've posted so many updates and revisions, I don't know where we are with this.  Can you get the timestamp or not?

**Comment by blacklord049** [comment]
I updated to the latest official version via Plugin Manager. Then I set "timestamp" in the configuration but the icon doesn't show in the editor.

**Comment by turnermm** [comment]
`timestamp` is incorrect.  It must be `Timestamp` with an upper case `T`.   See the [config page](https://www.dokuwiki.org/plugin:ckgedit:configuration#extra_plugins), as suggested in the Settings.

**Comment by blacklord049** [comment]
Damn... My bad ;-)
