### ISSUE TITLE
How should I handle the updates for the farm branch?

### ISSUE THREAD

**Issue by proxymus** [turnermm/ckgedit#183]
We use the farm branch for our dokuwiki environment. In the dokuwiki extension manager I'm getting updates offered for the ckgedit plugin. But I can see that the plugin URL has changed. 

![2016-04-28 11_51_01-dokuwiki extensions](https://cloud.githubusercontent.com/assets/1539498/14882208/b664af9a-0d37-11e6-9008-1e1b22c32c96.png)

How should I handle the updates for the farm branch? I believe the the master branch won't work for farm setups - I'm right?

Thank you in advance.

Kind regards
Proxymus

**Comment by turnermm** [comment]
On 2016-04-28 4:57 AM, proxymus wrote:
> We use the farm branch for our dokuwiki environment. In the dokuwiki
> extension manager I'm getting updates offered for the ckgedit plugin.
> But I can see that the plugin URL has changed.
>
> 2016-04-28 11_51_01-dokuwiki extensions
> <https://cloud.githubusercontent.com/assets/1539498/14882208/b664af9a-0d37-11e6-9008-1e1b22c32c96.png>
>
> How should I handle the updates for the farm branch? I believe the the
> master branch won't work for farm setups - I'm right?
>
> Thank you in advance.
>
> Kind regards
> Proxymus
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/turnermm/ckgedit/issues/183>
>
The description of the farms branch on the ckgedit plugin page says that 
it is kept "relatively" current.  I haven't had time to bring it up to 
date.

Myron Turner

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by turnermm** [comment]
Correct -- the master branch doesn't support farms.

Sent from Outlook Mobile




On Thu, Apr 28, 2016 at 2:57 AM -0700, "proxymus" <notifications@github.com> wrote:












We use the farm branch for our dokuwiki environment. In the dokuwiki extension manager I'm getting updates offered for the ckgedit plugin. But I can see that the plugin URL has changed. 







How should I handle the updates for the farm branch? I believe the the master branch won't work for farm setups - I'm right?



Thank you in advance.



Kind regards

Proxymus

**Comment by turnermm** [comment]
I've created an upgrade for the farms distribution which incorporates all of the recent changes, including an upgrade of the CKEditor from 4.5 to 4.7 and an enhanced file browser:
   https://github.com/turnermm/ckgedit/archive/farms_4.7.zip
It involved major changes,  I've given it a quick test and it seems ok.  I leave it  to you to give it a good try and to report back.  Thanks.

**Comment by proxymus** [comment]
You are awesome! I will give it a try and report back how it works. 

ckgedit is one of the best dokuwiki plugins. It should be the dokuwiki default editor.  :+1: :smile:

**Comment by proxymus** [comment]
I've tested the updated farm branch. I haven't noticed any problems so far. Again thank you for the great plugin!
