### ISSUE TITLE
Remove plugin options "Functions to remove from CKEditor toolbar" and add the opposite

### ISSUE THREAD

**Issue by q2apro** [turnermm/ckgedit#184]
I think it would be much easier for usability to give the user one input field (one line), where he can add what buttons he needs for the editor (comma separated). 

With the recent `Functions to remove from CKEditor toolbar` the user cannot remove all elements. The paste bar for example still persists, also many other buttons. 

So instead of "what don't you want", I would suggest to give an input field "what do you want" to appear. Very simple and full freedom user-side. Of course, by default showing most of the buttons.

And also provide a link to all [available ckeditor buttons](http://ckeditor.com/forums/CKEditor/Complete-list-of-toolbar-items).

I am a minimalist and only need B | I | U for example...

**Comment by turnermm** [comment]
See http://mturner.org/fckgLite/doku.php/faq#how_do_i_make_a_change_to_the_toolbar.  You can create your toolbar.

**Comment by q2apro** [comment]
Mhh, is it not possible to provide this option in the admin panel? 

Each update will override fckconfig.js and remove the changes (thinking of standard users or user groups)...

**Comment by turnermm** [comment]
fckconfig.js applies to the fckg plugin, which is the antecedent to ckgedit.  In ckgedit the file is config.js, which is a compressed version of ckeditor/config.js.unc.  You can always back up config.js and config.js.unc; the back-ups won't won't be overwritten.  For compression, see the ckgedit documentation on dokuwiki.ig.

> thinking of standard users or user groups)...
Don't know what you mean.

**Comment by q2apro** [comment]
> thinking of standard users or user groups

If the users are not developers and just know that in order to update, you have to copy the files to the server, overriding them. A developer probably notices or remembers that there is one file that was changed x years ago :)

**Comment by turnermm** [comment]
You can include a comma separated list in the textbox below the checkboxes.  I  updated the description to make that clear. See current version.

**Comment by q2apro** [comment]
I still can't get it to work. How do I get: 

B | U | I | subscript | superscript | Textcolor | special chars | Link | Table | Source

I have tried all admin options, also adding "TextColor" separately for instance. No chance.

**Comment by turnermm** [comment]
You can do this mostly from the Dokuwiki configuration manager, in the ckgedit section. See: 
https://www.dokuwiki.org/plugin:ckgedit:configuration#alt_toolbar.  Any toolbar items without a checkbox can be listed in the textbox below the checkboxes, comma-delimited.
![configuration settings](https://cloud.githubusercontent.com/assets/176447/15099868/d5e285ca-1527-11e6-8fb0-b82fc26095f8.png)

**Comment by turnermm** [comment]
Configuration Manager:
![configuration settings](https://cloud.githubusercontent.com/assets/176447/15099965/c6413636-152a-11e6-9f0a-3888bbbaed46.png)

ToolBar:
![tools](https://cloud.githubusercontent.com/assets/176447/15099964/c38e2656-152a-11e6-8811-b320a053eb46.png)

**Comment by q2apro** [comment]
Checking all checkboxes to remove "all" elements (which are not all), I get: 

![capture](https://cloud.githubusercontent.com/assets/6764548/15100212/716c2298-1574-11e6-9a47-85fc72ae298d.PNG)

But I need: 

B | U | I | subscript | superscript | Textcolor | special chars | Link | Table | Source

**Comment by turnermm** [comment]
On 2016-05-08 3:27 PM, q2apro.com wrote:
> Checking all checkboxes to remove "all" elements (which are not all), I
> get:
>
> capture
> <https://cloud.githubusercontent.com/assets/6764548/15100212/716c2298-1574-11e6-9a47-85fc72ae298d.PNG>
>
> But I need:
>
> B | U | I | subscript | superscript | Textcolor | special chars | Link |
> Table | Source
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/turnermm/ckgedit/issues/184#issuecomment-217744192>
>
That's the point of the textbox, where  you can list all the items you 
want to remove that do not have check-boxes.

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by q2apro** [comment]
Sorry, but still I think it would be extremely easier to just provide an option: 

> Enable what you want

instead of the way it is implemented now. I dream "usability", so maybe that's why I see that clearly :)

**Comment by q2apro** [comment]
Can you help out one more time regarding the `config.js`?

I have added my own code to it, and set ckeditor configurations, however, the config.js is not loaded on the website. But the ckeditor.js. What is the step to get the ckeditor with the new config?
