### ISSUE TITLE
Any chance to have CKEditor inline editing by default on each wiki page?

### ISSUE THREAD

**Issue by q2apro** [turnermm/ckgedit#185]
It would be fantastic to have the CKEditor feature of Inline Editing http://sdk.ckeditor.com/samples/inline.html activated by default on all pages (of course by admin option). 

Would it be possible to be implemented into this ckgedit plugin?

I think this would increase the number of wiki participants dramatically.

**Comment by turnermm** [comment]
Not that I am contemplating.

**Comment by turnermm** [comment]
Configuration Manager:
![configuration settings](https://cloud.githubusercontent.com/assets/176447/15099965/c6413636-152a-11e6-9f0a-3888bbbaed46.png)

ToolBar:
![tools](https://cloud.githubusercontent.com/assets/176447/15099964/c38e2656-152a-11e6-8811-b320a053eb46.png)

**Comment by q2apro** [comment]
But I assume you see the picture. It would help the community tremendously.
