### ISSUE TITLE
Bug: ckgedit inserts extra whitespace after format character

### ISSUE THREAD

**Issue by q2apro** [turnermm/ckgedit#186]
If you enter: 

    <strong>a</strong>b 

"ab" it leads to: "a b" (space between). 

maybe [this](http://forums.asp.net/t/1992574.aspx?CKEDITOR+is+adding+extra+line+breaks+br+paragraph+p+and+spaces+every+time+after+saving) helps somehow: 

             indent: false,
             breakBeforeOpen: false,
             breakAfterOpen: false,
             breakBeforeClose: false,
             breakAfterClose: false

My guess: `breakAfterClose` should always be `false` by default to prevent this bug. http://docs.ckeditor.com/#!/guide/dev_output_format

**Comment by turnermm** [comment]
This has no application to ckgedit, which converts html markup to plain text. T

**Comment by q2apro** [comment]
Of course, I mean the config of the CKEditor.

**Comment by q2apro** [comment]
Since I am not sure why the CKEditor settings do not work, I have opened a question on http://stackoverflow.com/q/37137356/1066234 - I guess it could also be dokuwiki...

**Comment by q2apro** [comment]
PS: I opened one of the pages as TXT file and just see now that it is indeed dokuwiki markup! I thought it would be saved as HTML directly... 

So then it is a bug in ckgedit which converts:

    Eingabe 3<strong>^</strong>x

to 

    Eingabe 3**^** x

Adding a whitespace when replacing the `</strong>` tag.

**Comment by turnermm** [comment]
Yes, I see this now.  Your original  statement wasn't clear.  It occurs only when adding formats to certain non-alphabetic characters.

**Comment by q2apro** [comment]
Is there a fix possible?

**Comment by turnermm** [comment]
Working on it.

**Comment by turnermm** [comment]
Just uploaded a fix.  All you need to do is to replace scripts/parse_wiki-cmpr.js  and scripts/parse_wiki-cmpr.js.unc.  It's not perfect, but works for most cases.

**Comment by q2apro** [comment]
Seems to be fixed for the caret ^ Thanks a lot.

But the issue still persists with underline _ 

> 3_x 

becomes 

> 3_ x 

PS: Caret and underline are the most used once, because we use this syntax for mathematics, superscript and subscript.

**Comment by turnermm** [comment]
It works for me.  It's probably a caching problem; if not, then reinstall the plugin.

**Comment by q2apro** [comment]
It is not cache, I checked again. Problem is the `>` I suppose that comes from `</font>`

Here you can see what I mean (also shows the [font bug](https://github.com/turnermm/ckgedit/issues/187)): 

![2016-05-11-bug](https://cloud.githubusercontent.com/assets/6764548/15182844/24c7d1d8-1797-11e6-95a2-f6e4b8949f8f.gif)

**Comment by turnermm** [comment]
The original issue has been resolved.  View this video clip on Youtube in theater mode:
https://www.youtube.com/watch?v=4RfdD0IRhTE
The font problem is a new issue and has nothing to do with #186.

**Comment by q2apro** [comment]
True, I have opened another ticket: https://github.com/turnermm/ckgedit/issues/189
