### ISSUE TITLE
Bug: ckgedit does not correctly save the font tag from HTML

### ISSUE THREAD

**Issue by q2apro** [turnermm/ckgedit#187]
Scenario: 

1. Inserting in HTML mode: `3_x` where the `_` gets the color red assigned.
2. Saving the document.
3. Saved gets in the TXT file: `3<font inherit/inherit;;#FF0000;;inherit>_</font> x`
4. Clicking on edit again, frontend in the editor appears `3<font inherit/inherit;;#FF0000;;inherit>_</font> x` instead of `3_x`

Screenshots:

![capture](https://cloud.githubusercontent.com/assets/6764548/15180463/83714c94-178a-11e6-8b5d-2df4480f5b9c.PNG)

![capture2](https://cloud.githubusercontent.com/assets/6764548/15180464/8541fff0-178a-11e6-872a-b197d6f20d05.PNG)

**Comment by turnermm** [comment]
The font plugin is not perfect.

**Comment by q2apro** [comment]
Please this open. My users cannot use ckgedit as long as this part of the parsing does not work :(

**Comment by turnermm** [comment]
Repeat:  
> The font plugin is not perfect.

See: https://www.dokuwiki.org/plugin:ckgedit:font_styling.  

You wanted formatted non-alphabetic text between single-spaced elements. That has been fixed. (https://github.com/turnermm/ckgedit/issues/186). Now you have upgraded the issue to using color. If unusable, then I would suggest that you look look for another solution.

**Comment by turnermm** [comment]
You can use the color plugin.  If you are not familiar with how ckgedit handles syntax plugins, read the  docs: https://www.dokuwiki.org/plugin:ckgedit#plugin_handling

**Comment by q2apro** [comment]
> I would suggest that you look look for another solution.

You are the only one who is providing a WYSIWYG for dokuwiki, which is extremely valuable. 

> You can use the color plugin

Do you mean this one from CKeditor: http://ckeditor.com/addon/colorbutton ? I think I am using it currently. 

> read the docs
I found this page about Font: https://www.dokuwiki.org/plugin:ckgedit:font_styling and also found the solution, thank you!

The option `plugin»ckgedit»nofont_styling` was enabled, I disabled it and now the font is parsed correctly. Thanks! :) 

You really have done an awesome work. I hope the community values that.

**Comment by turnermm** [comment]
The   [Color plugin](https://github.com/leeyc0/dokuwiki_plugin_color/zipball/master) is an old stand-by, which has nothing in it that updates can corrupt.  Plugin page: https://www.dokuwiki.org/plugin:color.
For blue text on a white background:
```<color blue/#ffffff>text</color>```
And in your case,  you can have a blue underscore in bold, because this works:
   ``3<color blue/#ffffff>**_**</color>F``

**Comment by q2apro** [comment]
I want all my users to use the CKEditor. They don't understand the dokuwiki syntax... or let's say the learning curve is too high so that they would not participate in the wiki. As I understand, the syntax you describe above is dokuwiki syntax extended by the color plugin.

**Comment by q2apro** [comment]
Okay, now I understand: I can direclty add the html syntax into the CKEditor: 

    This is <color #FF0000>colored text</color>

which gets parsed by the color plugin frontend. 

Unfortunately this is against "wysiwyg".

**Comment by turnermm** [comment]
I'm taking another look at this. I can't make any  promises.

**Comment by q2apro** [comment]
Thanks, we are starting the wiki over the next weeks: http://www.mathelounge.de/repo/

I will see by feedback of my users, if this "whitespace" issue gets noticed :) So for now: No hurries.

**Comment by turnermm** [comment]
I believe I've solved the white-space problem and have also cleaned up the font markup. Try this version, a temporary branch which I will merge with the master after I hear from you.

https://github.com/turnermm/ckgedit/archive/font_whitespace.zip

**Comment by turnermm** [comment]
@/blacklord049
