### ISSUE TITLE
Expand Menu "Link" with a protocol

### ISSUE THREAD

**Issue by Aggi85** [turnermm/ckgedit#188]
Hi,

i have trouble to expand the link menu in ckedit.
I tried to change the link.js.unc in lib\plugins\ckgedit\ckeditor\plugins\link\dialogs and compressed the file using yuicompressor. Afterwards i overwrite the original link.js with the new one.

Changes i have made:

    Add the protocol in line 594:
    [ 'file://\u200E', 'file://' ],

    Change Line 628:
    urlOnChangeProtocol = /^(http|https|ftp|file|news|m-files):\/\/(?=.)/i,

    Change Line 224
    urlRegex = /^((?:http|https|ftp|file|news|m-files):\/\/)?(.*)$/,

After all nothing changed. There is no new menupoint for the protocol 'file'

Thanks for help :)

**Comment by turnermm** [comment]
The accepted protocols are in a list starting at line 594.  But there is no 'file' protocol listed there; it is not available. The ``file:////`` syntax  is used by Samba, which you select from the Link Type menu, and it accesses shares.   Only IE supports these.

**Comment by Aggi85** [comment]
If i try to use a path like "T:\Ssedv\Testfile.xls" (valid mounted networkshare) with Samba it comes out with "http://server/dokuwiki/doku.php?id=t:ssedv_testfile.xls". A UNC Path works fine but several user don't even know what a UNC path is and where they can get them. So i decided to add a new protocoll.

I dont know why but today everything works fine. There is a new protocoll called "file:" and the path above works with it.
Maybe the planned restart at night was the solution.

**Comment by turnermm** [comment]
Could you be a bit more specific about what you did? Or fork a copy of ckgedit and add your changed files and create a pull request?

**Comment by turnermm** [comment]
Maybe you can attach the uncompressed Link.js?

**Comment by turnermm** [comment]
I spend a lot of time answering questions for people (not to mention of course the 100's of hours that have gone into giving you this  plugin), so it's nice when users occasionally give something back.
