### ISSUE TITLE
Bug: ckgedit inserts extra whitespace after font style

### ISSUE THREAD

**Issue by q2apro** [turnermm/ckgedit#189]
When giving part of a word a color: 

![capture-2](https://cloud.githubusercontent.com/assets/6764548/15191067/9a7f6fd4-17bb-11e6-93c6-c4c9aacf5f12.PNG)

and saving the page, it becomes: 

![result-2](https://cloud.githubusercontent.com/assets/6764548/15191076/a31b649a-17bb-11e6-94ab-bd50987e4e86.PNG)

I have seen the HTML, it seems that for each font style there is an extra span inserted, leading to multiple nested span tags.

**Comment by turnermm** [comment]
The font plugin is designed to work on contiguous blocks of text and not on infixes. This is why I suggest using the color  plugin.  https://github.com/turnermm/ckgedit/issues/187#issuecomment-218538982.  Here is the color plugin in action. In the editor, where the **B** shows that the underscore is in bold:
![2016-05-11 13_18_53- playground_links dw_hrun detritus](https://cloud.githubusercontent.com/assets/176447/15191780/cdba2654-177b-11e6-989b-63245618078e.png)
In the browser:
![2016-05-11 13_19_14-playground_links dw_hrun detritus](https://cloud.githubusercontent.com/assets/176447/15191805/ec0e0468-177b-11e6-9e71-f41bdc9dbfe8.png)

**Comment by turnermm** [comment]
I know about this but am not currently planning to work on it.  The font plugin is designed to work on contiguous blocks of text and not on infixes.  For that, as I suggested, in

**Comment by q2apro** [comment]
Okay, now I understand: I can direclty add the html syntax into the CKEditor:

    This is <color #FF0000>colored text</color>

which gets parsed by the color plugin frontend.

Unfortunately this is against "wysiwyg".

**Comment by turnermm** [comment]
You can simply use color the standard names: `3<color red>_</color>F`

**Comment by q2apro** [comment]
I personally would do this and know about: 

     3<color red>_</color>F

But a "simple" user does not even understand &lt; or &gt; - that's why what-you-see-is-what-you-get editors are so mighty and helpful

**Comment by blacklord049** [comment]
Same issue here and to be honest users won't be happy to use HTML directly in the WYSIWYG editor, especially because they aren't developers ore at least working in IT.

**Comment by turnermm** [comment]
At the moment, the white-space issue remains an insoluble problem.  The color plugin markup is not "HTML" but valid Dokuwiki markup which has been in use for many years.

**Comment by turnermm** [comment]
I believe I've solved the white-space problem and have also cleaned up the font markup.  Try this version, a temporary branch which I will merge with the master after I hear from you.

https://github.com/turnermm/ckgedit/archive/font_whitespace.zip

**Comment by blacklord049** [comment]
Don't know why but I tried your new version : 
- Moved ckgedit plugin folder to another location.
- Put the new plugin.
- Cleared dokuwiki and browser cache.
- Edit a page where I got the problem.
- Removed the whitespace.
- Saved. 
- Got an authentication error.

**Comment by turnermm** [comment]
Don't know what that means: authentication?  you mean on logging in?  I can't see what connection there could be.  Try clearing your browser cache.  And maklr sure the p lugin has installed correctly.

**Comment by turnermm** [comment]
I've installed the plugin on four sites--two on my LAN, two at mturner.org without incident.

**Comment by blacklord049** [comment]
DokuWiki authentication -> login and password were required after I clicked Save... But only with a specific page I wrote.
I don't even know why : the error came after I put your new ckgedit folder in my plugins. Clearing everything didn't solve the issue. Restoring the old version didn't solve it neither so I had to rollback my wiki from a previous backup. Very strange isn't it ?

**Comment by q2apro** [comment]
Reporting back for my case:

1. Installed the new ckgedit from https://github.com/turnermm/ckgedit/archive/font_whitespace.zip
2. Opened incognito (empty cache), logged in, changed page
3. Result: `3_x` becomes `3 _ x` (the _ is red colored)

Not yet the solution.

**Comment by turnermm** [comment]
What you are finding is that there is a space on either side?  Here is a page I created using the upgraded distribution: http://www.mturner.org/devel/playground/fonts_spacing

**Comment by turnermm** [comment]
I've since run that same page in a wiki on Ubunutu, accessed it from Safari on OS X, and have not found the problem you have reported above.

**Comment by blacklord049** [comment]
Working for me

**Comment by turnermm** [comment]
This fix is now merged into the master and so no longer needs a special url. It can be downloaded through the extension manager using the main url.

**Comment by q2apro** [comment]
It is working now for me too. Thanks a thousand!
