### ISSUE TITLE
Text code style not displaying when getting back in edit mode

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#190]
What I did : 

- Select text
- Click Styles -> Code text
- The text is displayed in the editor like a code text
- Save

Get back to the editor : 

- The text is now surrounded by ' instead of displaying like a code text.

is this a normal behavior ?
The code is correctly displayed when viewing the page.
Thank you

The screenshots below are taken in Edit mode : 

**Screenshot before**
![before](https://cloud.githubusercontent.com/assets/16919700/15247287/80b6ec68-1913-11e6-8c3c-24f727e57bec.jpg)

**Screenshot after**
![after](https://cloud.githubusercontent.com/assets/16919700/15247286/80b53062-1913-11e6-9fe7-10ca0638390c.jpg)

**Comment by turnermm** [comment]
No.  The double single quotes are Dokuwiki markup for code style formatting.  You should get the styled formatting in both the editor and the browser.  So, I have to assume that something has gone wrong in your CSS.  This is a screen shot taken from the editor after a save:

![2016-05-13 07_20_47- playground_fonts dw_hrun detritus](https://cloud.githubusercontent.com/assets/176447/15247662/40763894-18db-11e6-86e4-8b194a5c3b74.png)

**Comment by blacklord049** [comment]
Some other things I made now : 

- CSS purge.
- Save the configuration.
- Browser cache purge.
- Reinstall the ckgedit plugin.

Nothing works :-( damn...

**Comment by turnermm** [comment]
Or in Bootstrap 3.  Switch over to t he dokuwiki template and see if  these problems persist.  You could also go through your plugins and see if it is caused by one of those or a conflict between plugins.

**Comment by blacklord049** [comment]
My bad, it was related to this plugin https://www.dokuwiki.org/plugin:unformattedcode
Closing this.
