### ISSUE TITLE
Defining the default height of the editor (CKEditor)

### ISSUE THREAD

**Issue by q2apro** [turnermm/ckgedit#191]
I would like to predefine the height of the ckeditor, which I did in the config.js.

However, the plugin does "ignore" it since the height is set in https://github.com/turnermm/ckgedit/blob/master/action/edit.php#L532 with `height: $height`

I needed to comment-out this line to make my value from config.js work. 

It would be nice to be able to set a default height using the admin panel.

**Comment by turnermm** [comment]
There's a point at which it becomes counter-productive to keep adding configuration options, in particular for things which already have commensurate options in place or which can otherwise easily be handled.
