### ISSUE TITLE
How to set another upload folder?

### ISSUE THREAD

**Issue by q2apro** [turnermm/ckgedit#192]
I just realized that the uploaded images get stored into: 

    /lib/plugins/ckgedit/fckeditor/userfiles/image/testgrafik.png

How do I change the path to e.g. 

    /uploads/

I assume that can be done with ckedit (but could not find an admin option).

Shouldn't the editor take the default data path of dokuwiki?

**Comment by turnermm** [comment]
``image`` is a symbolic link to data/media, dokuwiki's media directory.

**Comment by q2apro** [comment]
Sorry, I dont understand. Do you mean that 

    /lib/plugins/ckgedit/fckeditor/userfiles/image/testgrafik.png

is pointing to 

    /data/media/testgrafik.png

?

**Comment by turnermm** [comment]
On 2016-05-17 3:03 AM, q2apro.com wrote:
> Sorry, I dont understand. Do you mean that
>
> |/lib/plugins/ckgedit/fckeditor/userfiles/image/testgrafik.png |
>
> is pointing to
>
> |/data/media/testgrafik.png |
>
> ?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/turnermm/ckgedit/issues/192#issuecomment-219647260>
>
yes.

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
