### ISSUE TITLE
How to do section linking? (ckgedit / CKeditor)

### ISSUE THREAD

**Issue by q2apro** [turnermm/ckgedit#193]
Using the ckeditor and specifing a `#section` to an existing link does not work. 

How to set the internal link + the section using CKeditor then?

Thanks in advance!

**Comment by q2apro** [comment]
Got it done by: 

    doku.php?id=logik#satz-und-aussage

**Comment by turnermm** [comment]
Use the Advanced Tab.  Click on ``Get Headings``.  This will produce a drop-down menu of section headers.  Select your header and the link tool will create your link to the selected section.
![playground_links](https://cloud.githubusercontent.com/assets/176447/15256782/b7e760c4-1908-11e6-9f92-a425cb63b0f3.png)

![anchors](https://cloud.githubusercontent.com/assets/176447/15256783/bab308c6-1908-11e6-89f3-ae62470d9996.png)

**Comment by q2apro** [comment]
Thanks, that was kind of hidden...
