### ISSUE TITLE
New CKGEdit font styling produces issues

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#195]
Hi,

The new CKGEdit update is installed. My JS and CSS cache has been purged through the Advanced Config plugin. 

First of all the plugin date in "plugin.info" says 2016-05-15 but in the DW repository the plugin date is 2016-05-16. Well I know : this is not a big deal.

But more important I already have new issues with the font style handling. In the editor, I try to put this text - "(recommandé)" - in green (see the picture).

![thistext](https://cloud.githubusercontent.com/assets/16919700/15313592/929b204c-1c0c-11e6-999e-ee334c6ba448.png)

If I click on Save I get a popup saying "Font styling cannot be included in links. Click OK to accept the following correction: [[(recommand&eacute;)]]. To revise, enter the full Dokuwiki link markup below, including brackets.  To return to Editor click Cancel"

Well ... Thank you... but this is not a link, this is just a text between parenthesis. 

But wait, there is something more ! 

If I click the "Switch to DW" button (on the same page, with the text in green), the popup appears too. But I was like, "I don't care, don't touch anything, just cancel". Well, the entire paragraph edited just disappeared from my page ! I had to restore a previous revision to get it back.

**Comment by turnermm** [comment]
On 2016-05-17 1:50 AM, blacklord049 wrote:

> In the editor, I try to put this text in green (see the picture).
>
> thistext
> <https://cloud.githubusercontent.com/assets/16919700/15313393/290eb6bc-1c0b-11e6-8c5e-87afdeb2877a.png>
>
> If I click save I get a popup saying "Font styling cannot be included in
> links. Click OK to accept the following correction: [[(recommandé)]]. To
> revise, enter the full Dokuwiki link markup below, including brackets.
> To return to Editor click Cancel"
>
This is fixed.

Please:  one issue at a time.  If you have another problem open a new issue.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by blacklord049** [comment]
Sorry, I'll do that to avoid confusion :-)
