### ISSUE TITLE
Section removed in some cases with Switch to DW Editor btn + New popup

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#196]
If I click the "Switch to DW" button, and if the popup to "fix font style with internal links" appears (initially referenced as https://github.com/turnermm/ckgedit/issues/195), clicking cancel will remove the entire section from the page.

**Comment by turnermm** [comment]
Will look at this.

**Comment by turnermm** [comment]
Should be fixed.

**Comment by blacklord049** [comment]
Yes !!!! :-)
