### ISSUE TITLE
Saving a page with nested lists and font style add blank lines between list members

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#198]
Here is an example :

```
===== Récapitulatif des compteurs =====

Chemin : menu //Gestion → Prestations du personnel → Récapitulatif des compteurs//.

Chaque année, nous recevons un résumé des congés pris, un calendrier reprenant ces données ainsi qu'un aperçu de la situation des divers compteurs (dont les heures supplémentaires). C'est grâce à cette fonctionnalité que le secrétariat peut nous imprimer ou même nous envoyer par mail ces informations essentielles.

{{  :doc:dilibelint:dilisched:dilisched_recape.png?nolink&800x600  }}

Pour afficher le récapitulatif d'une personne en particulier (et l'imprimer / envoyer par email) :

  * Indiquez l'année souhaitée.
  * Sélectionnez la personne dans la liste déroulante.
  * 12345678.
  * 34567890.
  * Abcdef
```

I add font style to the first line. Everything else looks fine in the editor. Then I click Save. If I look into the text file I can see the following line :

```
Chemin : menu <font inherit/inherit;;#800000;;inherit>//Gestion → Prestations du personnel → Récapitulatif des compteurs//</font>.
```

But in the meantime the editor added spaces between members of my nested lists (it only seems to affect the first three members).

The text file becomes : 

```
===== Récapitulatif des compteurs =====

Chemin : menu <font inherit/inherit;;#800000;;inherit>//Gestion → Prestations du personnel → Récapitulatif des compteurs//</font>.

Chaque année, nous recevons un résumé des congés pris, un calendrier reprenant ces données ainsi qu'un aperçu de la situation des divers compteurs (dont les heures supplémentaires). C'est grâce à cette fonctionnalité que le secrétariat peut nous imprimer ou même nous envoyer par mail ces informations essentielles.

{{  :doc:dilibelint:dilisched:dilisched_recape.png?nolink&800x600  }}

Pour afficher le récapitulatif d'une personne en particulier (et l'imprimer / envoyer par email) :

  * Indiquez l'année souhaitée.

  * Sélectionnez la personne dans la liste déroulante.

  * 12345678.
  * 34567890.
  * Abcdef
```

I can edit again with CKGEdit, remove spaces, but the spaces are re-created if I click Save.
The only way I found to fix it is to edit the text file...

_Edit 16:20 pm :
I made another test just a few seconds ago. I manually fixed the nested list by removing the lines between members, then I saved the text file. I came back into the editor, save, then a line has been added under the first member of the list... Unbelievable._ 

_I fixed the nested list again in the text file. I came back again in the editor, then removed the paragraph in which the font style was added. I clicked Save, and BAM! No space between list members._ 

Thank you !! 
:-)

**Comment by blacklord049** [comment]
Info : 16:30 pm -> reproduced in a new paragraph

**Comment by turnermm** [comment]
See the current distribution (master), which you can install directly from extension manager.

**Comment by blacklord049** [comment]
Thank you for the fix :-)
