### ISSUE TITLE
I found a case where the font markup adds a space

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#199]
Hello,

It's me... Again! (Did I quote Adele ?)
I found a case where font markup adds a space.

Steps : 
- I have this nested list on my page : 

```
Dans de nombreuses fenêtres vous aurez remarqué qu'il vous est proposé de choisir un groupe dans une liste déroulante. Il s'agit en fait de **groupes personnalisés **dans lesquels vous pouvez placer n'importe quel membre du personnel.

  * Cliquez sur le menu Edition → Gestion des groupes de membres.
  * hhhhhhhhhh
```

Then select the part "Edition → Gestion des groupes de membres" without the ending dot and do the following -> Add Italic style.

Save the page and see the result.

What you get : 

```
  * Cliquez sur le menu //Edition → Gestion des groupes de membres//.
  * hhhhhhhhhh
```

Edit the page and select the part "Edition → Gestion des groupes de membres", again without the ending dot. Change the color.

Save again and see the result.

```
  * Cliquez sur le menu <font inherit/inherit;;#800000;;inherit>// Edition → Gestion des groupes de membres //</font>.
  * hhhhhhhhhh
```

A space has been added after the last word, before the ending //. In fact this is not related to the list but to the Italic style. Happens too if you change the font weight into bold, or if you underline it.

**Comment by turnermm** [comment]
I cannot reproduce either of these.

**Comment by blacklord049** [comment]
I can reproduce in every section, every paragraph, on each page.

Just type a phrase like : 

```
My dog is a pet.
```

Select each word except the dot.
Chose :
- Italic / Bold / Underline (whatever you want).
- Font color.

Save.
A space is added after between the last word ("pet") and the dot.

**Comment by turnermm** [comment]
I have not been able to.  It could be a browser issue.

**Comment by blacklord049** [comment]
Does the same in :
- IE 11 (on Windows 10 x64) 
- Firefox 46.0.1

Purged the CSS and JS cache through Advanced Configuration Plugin.

**On IE**

Set the Italic and font color 
![color1](https://cloud.githubusercontent.com/assets/16919700/15391564/1341ccbc-1dc2-11e6-9ce3-9d2c9c873e38.png)

Save.

Result
![saveres2](https://cloud.githubusercontent.com/assets/16919700/15391587/3292e844-1dc2-11e6-9239-d3fd1acd5493.png)

**Comment by turnermm** [comment]
http://mturner.org/devel/playground/lists_markup

The only place I found this happens is when combining font markup with formats like bold.  But this extra space can be avoided if you apply the format after the font selection.

**Comment by blacklord049** [comment]
OK. I made a test and you're right about the formatting order :
- If I chose Bold then the text color, an extra space is added.
- If I chose Text color then Bold, the extra space isn't added.

**Comment by turnermm** [comment]
Added an instruction to the plugin page: [plugin:ckgedit](https://www.dokuwiki.org/plugin:ckgedit:font_styling#combining_font_styles_with_dokuwiki_formats
)

**Comment by blacklord049** [comment]
OK thanks , I'll close this

**Comment by turnermm** [comment]
I just uploaded a fix,  so that now formatting order should not be an issue.

**Comment by turnermm** [comment]
I think this can be closed now.

**Comment by blacklord049** [comment]
Thanks for the fix ! :-)
