### ISSUE TITLE
ckgedit encoding

### ISSUE THREAD

**Issue by taizoli** [turnermm/ckgedit#200]
Hello,

Ich have a problem with ckgedit. When I try to save a site with a link, that is pointing on a namespace with special caracters, the link broke.

before: :projektförderung
after: :projektf%C3%B6rderung

I use the newest version from ckgedit, there is.

please help
thank you

**Comment by turnermm** [comment]
I can't reproduce this.  See: http://www.mturner.org/devel/playground/links#links_with_entities

So, how have you created this link? Please give the exact steps?  And what are your Configuration settings for non-Roman characters?

**Comment by taizoli** [comment]
Hello turnermm,

I have create page1 and page2. Page2 has character "ö" in the name. Then i have created an internal-link on page1 that points on page2.
At the first time, when i save it, it is ok, but then, when i edit this page2 again and click on save, the internal-link is broken. (however i didnt touch it)

Where can i find out, what is my configuration setting for non-Roman characters?

**Comment by turnermm** [comment]
> Where can i find out, what is my configuration setting for non-Roman characters?

If you haven't changed anything it's not a problem and proabably wouldn't matter even if you did, but to be complete I asked.

As for your problem, I haven't been able to reproduce it, no matter how many times I edit and save either of the pages.  And it doesn't make any sense to me that changine page 2 should corrupt the link on page 1.

How did you create your link.  Did you use the link tool or did you create the link manually, using Dokuwiki syntax?  If the latter, then use the link tool.

**Comment by turnermm** [comment]
However, the character sequence  ``%C3%B6`` translates to ``ö`` and ``projektf%C3%B6rderung`` becomes ``projektförderung``.  And when used in a url it will work as expected.

**Comment by turnermm** [comment]
Example:
[http://mturner.org/devel/playground/projektf%C3%B6rderung/test](http://mturner.org/devel/playground/projektf%C3%B6rderung/test)

**Comment by taizoli** [comment]
thank you for your help.
I have gave you before a wrong problem description. So here again:
"I have create page1 and page2. Page2 has character "ö" in the name. Then i have created an internal-link on page1 that points on page2.
At the first time, when i save it, it is ok, but then, when i edit this page1 again and click on save, the internal-link is broken." (i didnt touch page2)
I have created this link with link tool.
When I use DW editor, i can save the page without problem, the link is untouched.

**Comment by taizoli** [comment]
on your test page, the pagename is projektfoerderung and not projektförderung.

**Comment by turnermm** [comment]
Dokuwiki normalizes Roman-style characters with diacritics.  See:
      http://mturner.org/devel/playground/projektfoerderung/test

**Comment by taizoli** [comment]
yes i know that, but by me it is turned off. So you say, that i shouldnt turn it off, because in ckgedit it will never work with special characters in the pagenames?

**Comment by turnermm** [comment]
> yes i know that, but by me it is turned off.

Yes, but you hadn't said that before.

**Comment by turnermm** [comment]
https://github.com/turnermm/ckgedit/tree/0b0cee1da1aea5c30f2ada05634cf53a56ddd1c7
