### ISSUE TITLE
Table Caption disappears on save

### ISSUE THREAD

**Issue by Braintelligence** [turnermm/ckgedit#201]
Hi there.

```
<h1>@@PAGE@@</h1>

<div class="level1">

<div class="table">
<table class="inline">
	<caption>Test</caption>
	<tbody>
		<tr class="row0">
			<td class="col0">Test1</td>
			<td class="col1">Test2</td>
		</tr>
		<tr class="row1">
			<td class="col0">Test3</td>
			<td class="col1">Test4</td>
		</tr>
		<tr class="row2">
			<td class="col0">Test5</td>
			<td class="col1">Test6</td>
		</tr>
	</tbody>
</table>
</div>

</div>
```

The above becomes the latter after saving:

```
<h1>@@PAGE@@</h1>

<div class="level1"><span class="np_break">&nbsp;</span>

<div class="table">
<table class="inline">
	<tbody>
		<tr class="row0">
			<td class="col0">Test1</td>
			<td class="col1">Test2</td>
		</tr>
		<tr class="row1">
			<td class="col0">Test3</td>
			<td class="col1">Test4</td>
		</tr>
		<tr class="row2">
			<td class="col0">Test5</td>
			<td class="col1">Test6</td>
		</tr>
	</tbody>
</table>
<span class="np_break">&nbsp;</span></div>

<p>&nbsp;</p>
</div>
```

Why is the caption disappearing? Any ideas?

**Comment by turnermm** [comment]
Dokuwiki does not support table captions.  Look through the Dokuwiki plugins, you might find help there.

**Comment by Braintelligence** [comment]
I tried activating https://www.dokuwiki.org/plugin:caption but that's not enough. Is it feasible to change ckgedit so it recognizes the presence of this plugin and handles table caption insertion differently?

If not then maybe it would be wise to remove this function from ckgedit?

**Comment by turnermm** [comment]
The extended table options crept back in when I upgraded from CKEditor 4.5.1 to 4.5.7.  I'll change that but in the meantime, you could rename table.js.unc to table.js in ckgedit/ckeditor/plugins/table/dialogs/, which will give you the stripped down version that goes with ckgedit. I'll be doing the upgrade shortly,  which includes compressing the file.

**Comment by turnermm** [comment]
I just now made the change.  All you have to do is to update the plugin.

**Comment by Braintelligence** [comment]
Thanks a lot. Updating via uploading the zip of this link (https://github.com/turnermm/ckgedit/archive/master.zip) strangely didn't help. 

I also have a table.js AND a table.js.unc in that folder. Removing the table.js and renaming the table.js.unc to table.js didn't help.

Did I do something wrong?

**Comment by Braintelligence** [comment]
Hmm... I replaced table.js with the raw content of your GitHub change but this didn't change the table preference dialog.
Do I have to erase cache somewhere?

**Comment by turnermm** [comment]
Browser cache

**Comment by Braintelligence** [comment]
Shouldn't CTRL+F5 erase it?

**Comment by turnermm** [comment]
shift-crL-delete
