### ISSUE TITLE
Weird issue with text color and tables

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#202]
I have this section, with the following content : 

![text1](https://cloud.githubusercontent.com/assets/16919700/15576437/2de214d2-2358-11e6-8ae9-9e8fc8a2476a.png)

Giving me something like 

```
==== Définir les droits sur les dossiers FTP/IIS ====

De retour dans la Console d'administration d'IIS, déroulez l'arborescence //XXXXXX649 → Sites → ftp_XXX//, sélectionnez dossier par dossier, et pour chacun, utilisez la fonctionnalité "Règles d'autorisation FTP". Voici la liste des autorisations définies pour l'instant.

^Dossier ^Groupe/Utilisateur ^Droits |
|\ |Groupe1|Lecture |
|\dossier1|User1|Lecture, Ecriture |
|\dossier2 |User1|Lecture, Ecriture |
|::: | User2|Lecture, Ecriture |

Et voilà :-)
```

I add a text color with the CKGEdit onto the text

```
//XXXXXX649 → Sites → ftp_XXX//
```

Then I click Save -> I get the following result

![text2](https://cloud.githubusercontent.com/assets/16919700/15576516/9b1e5f38-2358-11e6-9812-c636ff62f8e0.png)

Sometimes it just drops the table...

I can reproduce the issue on an empty page

- Add a page title (h1).
- Type "hello world".
- Add a table with 3 lines, 2 columns, and some content in it.
- Save.
- You have "hello world" with your table.
- Edit the page.
- Select "hello world".
- Chose a font color.
- Save.
- The table disappears.

CSS / JS cache purged many times and no change.

**Comment by turnermm** [comment]
There's a simple fix for this: enable complex tables, either by checking off the complex tables box in the bottom menu listings or by setting it in the Configuration settings.

**Comment by blacklord049** [comment]
I set the parameter and you're right , now I can use coloured text with a table in the same section/page ! Thank you.
