### ISSUE TITLE
Another case of space added with font color

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#203]
Hello,

![sans titre 4](https://cloud.githubusercontent.com/assets/16919700/15577434/d5143d1c-235c-11e6-9276-c5cf3d8fbc33.png)

Underline the first part of your text
Put the second part in any color of your choice
Save

-> Will add a space between the colored part and the underlined text

**Comment by turnermm** [comment]
The fix for this is in the [captcha branch](https://github.com/turnermm/ckgedit/archive/captcha.zip) which I've been working on.

**Comment by blacklord049** [comment]
Working! 
Thanks.
