### ISSUE TITLE
You-are-here Path not using URL Rewriting

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#204]
Hello,

When I'm in Edit mode, the links paths in the you-are-here section are redirecting to `doku.php?id=ns:sub:page` instead of `/wiki/ns/sub/page`

See : 
![editor](https://cloud.githubusercontent.com/assets/16919700/15609712/eb365592-2421-11e6-9605-1480e99bf667.png)

URL Rewriting is enabled and working well of course ;-)
I don't know if it's a DW issue or if it's caused by CKGEdit ...

Thanks

**Comment by turnermm** [comment]
I tink this is something you should be able to figure out for yourself.

**Comment by blacklord049** [comment]
ok
