### ISSUE TITLE
Code + Lists

### ISSUE THREAD

**Issue by tyl0re** [turnermm/ckgedit#205]
- Punkt1 <code>test
test
</code>
 -  Punkt2<code> test2</code>
Istnt shown correcty. in the editor

it shows
instead of 

1. Punkt1
test
test
2. Punkt2

in the editor
1. Punkt1
test
test
1. Punkt2

And when saving :
the code get
 - Punkt1 
<code>test
test
</code>
 -  Punkt2
<code> test2</code>

The Formating ist lost.In the Moment it ist Possible to Mix Numbering and Code with chgedit

**Comment by turnermm** [comment]
If you mean this:

```
 - Point One ''test test''
         - Point a ''test test''
    - Point 2
```

Yes. That works

If you mean this:
```

 - Point One <code>test test</code>
      - Point a <code>test test</code>
```

No. That will not work.
