### ISSUE TITLE
Ideas for Insert Tag Popup

### ISSUE THREAD

**Issue by blacklord049** [turnermm/ckgedit#206]
Hello,

If you have many tags, you will see all of them in the Insert Tag window.
Then the popup becomes this :

![tags](https://cloud.githubusercontent.com/assets/16919700/15649895/33583df4-2675-11e6-9248-7cb04515ecea.png)

You can scroll to click OK of course...

It would be good to chose a limit of displayed tags (parameter) 

**and / or**

Display some kind of "frame" with a scrollbar inside the popup with a list of tags and their checkboxes

What do you think ? 
Thanks :)

**Comment by turnermm** [comment]
I've notified the author of the tags plugin.

**Comment by isf-val** [comment]
I took a quick look at it. Sadly i did not find an easy way in the ckeditor dialog gui toolkit to do scrollbars.
Right now i do not have time to work on that, if anybody feels like doing it: go for it.

**Comment by turnermm** [comment]
I should add that I also gave this a try but couldn't see how to di  it.
