### ISSUE TITLE
Line break / newline

### ISSUE THREAD

**Issue by proxymus** [turnermm/ckgedit#207]
Hello, 
I use he latest farm branch of ckgedit. In the classic DW editor I can write a text with line breaks like this:

![2016-05-31 14_56_22](https://cloud.githubusercontent.com/assets/1539498/15674959/f2438e60-273f-11e6-922a-bba52c2e8a9d.png)

When I save this with ckgedit I will get the following:
![2016-05-31 14_57_48](https://cloud.githubusercontent.com/assets/1539498/15675026/32442a38-2740-11e6-8678-e20557c08d13.png)

How can I realize a new line / line break (without paragraph) with ckgedit? I can use SHIFT+ENTER, but this isn't saved.

Thank you in advance.

**Comment by turnermm** [comment]
SHIFT-RETURN creates a single line break.  RETURN on its own creates a new paragraph.

**Comment by proxymus** [comment]
I would like to have single line breaks with in my text, but this isn't working for me. When I edit the example above I can see that the single line break is saved, in the "view mode" I have paragraphs between each line.

**Comment by turnermm** [comment]
I'm afraid I don't follow the above.  If the single is saved then what is the 'view mode' where it shows as a paragraph?

**Comment by proxymus** [comment]
I use the version 4.5.7 (https://github.com/turnermm/ckgedit/archive/farms_4.7.zip).
![ckgedit-version](https://cloud.githubusercontent.com/assets/1539498/15813702/62336dc8-2bc1-11e6-8ca7-de7d93f7cd90.png)

I've written that:

![2016-06-06 08_31_21-line break](https://cloud.githubusercontent.com/assets/1539498/15813710/72c58fd6-2bc1-11e6-84ad-ce3a52d59397.png)
This is the source code view:
![2016-06-06 08_31_32-line break](https://cloud.githubusercontent.com/assets/1539498/15813712/77284942-2bc1-11e6-84d1-c1650c5ca69d.png)
After I've saved the page this is the result:
![2016-06-06 08_31_45-line break](https://cloud.githubusercontent.com/assets/1539498/15813714/7a0cbb98-2bc1-11e6-911b-5f4dba21be38.png)

I hope it is now a bit clearer.

**Comment by proxymus** [comment]
I found the difference. Ckgedit saves the line break as `\\` and the native dokuwiki editor doesn't use this.
CKGEDIT:
![2016-06-06 09_59_08_ckgedit](https://cloud.githubusercontent.com/assets/1539498/15815445/6d15635c-2bcd-11e6-920f-539b8944fe6f.png)

DWEDIT:
![2016-06-06 09_58_55_dwedit](https://cloud.githubusercontent.com/assets/1539498/15815446/6d1836f4-2bcd-11e6-8b31-ad2cc6311a8c.png)

`\\` is working in the list element, but not in normal text.
![2016-06-06 10_01_29-line break 2](https://cloud.githubusercontent.com/assets/1539498/15815502/cc9e0ca2-2bcd-11e6-8564-794d846099ea.png)
![2016-06-06 10_02_04](https://cloud.githubusercontent.com/assets/1539498/15815503/cca373c2-2bcd-11e6-933c-ee8364ec313b.png)

**Comment by turnermm** [comment]
https://www.dokuwiki.org/wiki:syntax#basic_text_formatting

**Comment by proxymus** [comment]
> https://www.dokuwiki.org/wiki:syntax#basic_text_formatting
This is working with ckgedit. I assumed that I could use Shift+Enter, because this is working in the default DW editor too. I've used the `\\` only within list elements.

**Comment by turnermm** [comment]
Truthfully, I am not following you.  SHIFT+ENTER is not a dokuwiki editor function, it is a ckgeditor function.  However, in the ckgeditor, you can actually insert the double backslash, just as in the default edtior, and you will get single line spacing.  In the dokuwiki editor, if you are in a list and hit SHIFT+ENTER, you will get another list item, not a single spaced line.  If you are not in a list and hit SHIFT+ENTER in the dokuwiki editor, when you save the document, the line break will disappear.

**Comment by proxymus** [comment]
You are right. We have installed the xbr plugin (https://www.dokuwiki.org/plugin:xbr) which preserves the line breaks. I did not think about that.

**Comment by proxymus** [comment]
Thank you for clarification. Now I can use the default rendering engine again. :)
