### ISSUE TITLE
Double Dash replaced in Code Text

### ISSUE THREAD

**Issue by Jaydabi** [turnermm/ckgedit#210]
When using the inline style "Code Text", double dash (--) gets replaced by hyphen (–).

Not sure if this is a wanted behavior, but this is very bad since a lot of "code" needs double dash.

Would be nice to have an option to disable this behavior.

**Comment by turnermm** [comment]
This is a default Dokwuwiki entity.
  See  https://www.dokuwiki.org/entities and http://www.mturner.org/devel/playground/entities
You can disable these by editing conf/entities.conf.
