### ISSUE TITLE
Fullscreen menubar issue

### ISSUE THREAD

**Issue by acidjames** [turnermm/ckgedit#213]
Hi Turner,

thanks for your plugin, works great

I found an issue : when the text is not and focus and when you press the "fullscreen" button, the menubar dissapears.

To get this working correctly, your first need to clic somewhere in the page content then press fullscreen.

Thanks in advance,

**Comment by turnermm** [comment]
> when the text is not and focus

I assume you mean "in focus"?  Truthfully, I don't follow this, i.e. 'in focus'.  But I assume by 'menu bar' you mean the menu items at the bottom and not the CKEditor toolbar items.  There's nothing I can do about this because the CKEditor takes over the browser when you click on full screen, eliminating all other content but its own.

**Comment by acidjames** [comment]
Hi @turnermm, it appears i can't reproduce the bug after dokuwiki "Eleonor of Tsort" update so this issue can be closed.



By "in focus", i meant you needed to have the blinking text icon somehere in the article area to have the fullscreen working correctly.

For example:

- you click on "Edit", then you click on "Fullscreen", menubar dissapears
- you click on "Edit", you click in the edit box so that the blinking typing thing is there, you click on "Fullscreen", menubar is there.

**Comment by turnermm** [comment]
I am re-opening this because after some testing, I see it may be a browser issue or combination of browser/template.  That is, in firefox, there is no problem with vector and bootstrap templates, but with the dokuwiki template the toolbar disappears when the page is longer than screen height.

**Comment by acidjames** [comment]
Hi,
i'm using Firefox 47, Windows 10, and DokuWiki theme 2015-07-26
