### ISSUE TITLE
Problem with inserting images and files in htaccess farms

### ISSUE THREAD

**Issue by simon-roderus** [turnermm/ckgedit#218]
Almost all features of the ckgedit-editor work fine now, but I have the problem that saving a page seems to corrupt the paths to inserted images and files.

Here is a more detailed explanation:
(In the example I replaced the name of my wiki with `mywiki` and the name of the image I inserted with `myimage.png`.)

1. I clicked "insert image", a popup appers where I can upload or choose an image (**works!**).
2. The insert-dialog shows a generated url that looks fine (`/dokuwiki/lib/plugins/ckgedit/fckeditor/mywiki/image/myimage.png`) (**works!**).
3. After clicking "OK" a preview of the image appears on the wiki page (**works!**).
4. After saving the page the image links becomes broken and the image is no longer displayed on the page. (**broken!**)

The dokuwiki-code of the saved page shows that the filepath was changed to `{{:​dokuwiki_lib_plugins_ckgedit_fckeditor_mywiki_myimage.png?​nolink&​100x100}}`. The correct path would be `{{:myimage.png|}}`.

Any ideas what went wrong?

P. S.: I use a DokuWiki farm installation with the .htaccess-method.

**Comment by turnermm** [comment]
This is a configuration error.  While the insert dialog looks correct and even works, it is not in fact correct.  That is the url as it should appear in the source, in the img tag.  In the text box of the link dialog it should be:  ``:myimage.png``

**Comment by simon-roderus** [comment]
Can you tell me at what configuration I need to look?

**Comment by angystardust** [comment]
Hi @turnermm I'm also having a strange bug when uploading an image in the editor...
As you can see from the image below, after the upload (which correctly creates the file on the server) the image appears to be broken.

![fcedito bug](https://cloud.githubusercontent.com/assets/1568397/16621231/cdc2f25c-4395-11e6-940b-0c98d5153b43.png)

![fc bug](https://cloud.githubusercontent.com/assets/1568397/16621230/cd5b427e-4395-11e6-90ed-6db50eb4ccba.png)

Why the hell I'm seeing my local docroot path (/var/www/dokuwiki) instead of the url of my dokuwiki website (http://dokuwiki.mycompany.local)?
Am I missing some configuration directive in the local.php?

P.s.: i'm not using the farm setup

**Comment by turnermm** [comment]
It should be: `/dokuwiki/ib/plugins/ckgedit/fckeditor/userfiles/image`, not `http://dokuwiki. . .`, unless your dokuwiki is installed in the root directory, i.e. `/var/www` and not in `/dokuwiki`.  Otherwise, you haven't given enough information about your setup.

**Comment by turnermm** [comment]
In the htaccess method, your link in the image dialog should look like this:
`/farmer/lib/plugins/ckgedit/fckeditor/<animal>/image/image.gif`
That is, the dokuwiki directory should have a farmer directory and a barn directory and when you point your browser at `http://<your_domain>/barn/<animal>/`, your data is redirected to the animal's data.  What you have, as far as I can tell from the above, is an image that is in the farmer's data/media directory and not an image that is in the animal's data/media directory.

**Comment by turnermm** [comment]
I believe I have found the source of this problem.  It is most likely not your setup but instead a bug that crept into the javascript code when I was working on syncing the master with the farms version.  Please try the current version of farms:
[farms_4.7](https://github.com/turnermm/ckgedit/archive/farms_4.7.zip)
If this solves your problem I am sorry for the inconvenience.

**Comment by simon-roderus** [comment]
Thank you for digging into this issue! I will install the latest ckgedit farm version on monday and write again after I tested it.

**Comment by simon-roderus** [comment]
I just installed the latest ckgedit farm version and now everything works fine and as expected. Thank you once again for your amazing support, your advice and your helpful explanations!
