### ISSUE TITLE
Issue attaching images on a dokuwiki page

### ISSUE THREAD

**Issue by angystardust** [turnermm/ckgedit#221]
Hi @turnermm I'm having a strange bug when uploading an image in the editor...
As you can see from the image below, after the upload (which correctly creates the file on the server) the image appears to be broken.

![ckedit issue](https://cloud.githubusercontent.com/assets/1568397/16896488/f75eff96-4b94-11e6-86eb-aa6cc5f7dd35.png)

![ckedit issue2](https://cloud.githubusercontent.com/assets/1568397/16896496/144578c4-4b95-11e6-98e1-6a50e047ac2f.png)

Why the hell I'm seeing my local docroot path (/var/www/dokuwiki) instead of the url of my dokuwiki website (http://dokuwiki.mycompany.local)?
Am I missing some configuration directive in the local.php?

P.s.: i'm not using the farm setup but just a plain setup in a subdir (/dokuwiki) of my apache's docroot

**Comment by turnermm** [comment]
I would need to know more about your setup.  But the path shown in the link dialog should probably be `/dokuwiki/lib. . .` and not` /var/www/dokuwiki/lib . . .`  and definitely not ` http://etc`.

**Comment by angystardust** [comment]
Hi @turnermm , thanks for your support.
 I hope those are the infos you need to help me:

**Dokuwiki version**: Release 2016-06-26a "Elenor of Tsort"
Dokuwiki is installed in the `/var/www/dokuwiki/` path

**ckgedit plugin version**: 2016-07-19 (just upgraded today)
**Apache version**: 2.4

### Apache Configuration

**/etc/httpd24/httpd.conf**

```
ServerRoot "/opt/rh/httpd24/root/etc/httpd"
Listen 80
Include conf.modules.d/*.conf
User apache
Group apache
ServerAdmin root@localhost
<Directory />
    AllowOverride none
    Require all denied
</Directory>
DocumentRoot "/opt/rh/httpd24/root/var/www/html"
<Directory "/opt/rh/httpd24/root/var/www">
    AllowOverride None
    Require all granted
</Directory>
<Directory "/opt/rh/httpd24/root/var/www/html">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
<IfModule dir_module>
    DirectoryIndex index.html  index.php  /_h5ai/public/index.php
</IfModule>
<Files ".ht*">
    Require all denied
</Files>
ErrorLog "logs/error_log"
LogLevel warn
<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common
    <IfModule logio_module>
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>
    CustomLog "logs/access_log" combined
</IfModule>
<IfModule alias_module>
    ScriptAlias /cgi-bin/ "/opt/rh/httpd24/root/var/www/cgi-bin/"
</IfModule>
<Directory "/opt/rh/httpd24/root/var/www/cgi-bin">
    AllowOverride None
    Options None
    Require all granted
</Directory>
<IfModule mime_module>
    TypesConfig /etc/mime.types
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
    AddType text/html .shtml
    AddOutputFilter INCLUDES .shtml
</IfModule>
AddDefaultCharset UTF-8
<IfModule mime_magic_module>
    MIMEMagicFile conf/magic
</IfModule>
EnableSendfile on
IncludeOptional conf.d/*.conf
```

**/etc/httpd24/conf.d/dokuwiki.conf**
```
Alias /dokuwiki /var/www/dokuwiki
<Directory /var/www/dokuwiki/>
	<IfModule mod_authz_core.c>
		# Apache 2.4
		Require all granted
	</IfModule>
	<IfModule !mod_authz_core.c>
		Order allow,deny
		Allow from all
	</IfModule>

	<IfModule mod_rewrite.c>
		Options +FollowSymLinks

		## $conf['userewrite'] = 1 - not needed for rewrite mode 2
#		RewriteEngine on

		## Not all installations will require the following line.  If you do,
		## change "/dokuwiki" to the path to your dokuwiki directory relative
		## to your document root.
		RewriteBase /dokuwiki

		RewriteRule ^_media/(.*)              lib/exe/fetch.php?media=$1  [QSA,L]
		RewriteRule ^_detail/(.*)             lib/exe/detail.php?media=$1  [QSA,L]
		RewriteRule ^_export/([^/]+)/(.*)     doku.php?do=export_$1&id=$2  [QSA,L]
		RewriteRule ^$                        doku.php  [L]
		RewriteCond %{REQUEST_FILENAME}       !-f
		RewriteCond %{REQUEST_FILENAME}       !-d
		RewriteRule (.*)                      doku.php?id=$1  [QSA,L]
		RewriteRule ^index.php$               doku.php
	</IfModule>
</Directory>

<Directory ~ /var/www/dokuwiki/(conf|inc|bin|data)>
	<IfModule mod_authz_core.c>
		# Apache 2.4
		Require all denied
	</IfModule>
	<IfModule !mod_authz_core.c>
		Order deny,allow
		Deny from all
	</IfModule>
</Directory>
```
**/var/www/dokuwiki/.htaccess**

```
<Files ~ "^([\._]ht|README$|VERSION$|COPYING$)">
    <IfModule mod_authz_host>
        Require all denied
    </IfModule>
    <IfModule !mod_authz_host>
        Order allow,deny
        Deny from all
    </IfModule>
</Files>
<IfModule alias_module>
    RedirectMatch 404 /\.git
</IfModule>
RewriteEngine on
RewriteRule ^_media/(.*)              lib/exe/fetch.php?media=$1  [QSA,L]
RewriteRule ^_detail/(.*)             lib/exe/detail.php?media=$1  [QSA,L]
RewriteRule ^_export/([^/]+)/(.*)     doku.php?do=export_$1&id=$2  [QSA,L]
RewriteRule ^$                        doku.php  [L]
RewriteCond %{REQUEST_FILENAME}       !-f
RewriteCond %{REQUEST_FILENAME}       !-d
RewriteRule (.*)                      doku.php?id=$1  [QSA,L]
RewriteRule ^index.php$               doku.php
```

**/var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/.htaccess**

```
#unix  -- do not change or move
<IfModule mod_authz_host>
    Require all denied
</IfModule>
<IfModule !mod_authz_host>
    Order allow,deny
    Deny from all
</IfModule>

<FilesMatch "\.(gif|jpe?g|png)$"> 
<IfModule mod_authz_host>
    Require all granted
</IfModule>
<IfModule !mod_authz_host>
    Order allow,deny
    Allow from all
</IfModule>
</FilesMatch>

Options -Indexes
```

**Comment by turnermm** [comment]
See: https://httpd.apache.org/docs/current/howto/htaccess.html
```
The use of .htaccess files can be disabled completely by setting the AllowOverride directive to none:
AllowOverride None
```

So as far as I can see, at the moment your .htaccess files have no effect.  So that should be fixed first, though I'm not sure it accounts for your problem.

When you make changes to the apache config you have to restart apache.  Keep a backup of your apache config fies before making changes.

Was your dokuwiki installed by a package manager?

**Comment by angystardust** [comment]
Hi @turnermm 
No, I haven't used a package manager...just a plain zip from the dokuwiki website.
I've have tried different configurations but everytime I see the relative URL of the attached image as a local path (/var/www/dokuwiki/...etc etc )
I've tried to change the $conf['userewrite'] directive to 0 but I have the same issue.

By the way, I've tried to implement `AllowOverride All` on the /dokuwiki Directory stanza of the apache configuration but nothing changes.

This is what i get trying to attach an image from the ckgedit interface (the images were uploaded thoght the dokuwiki media manger (notice all those 404 errors)

```
==> ssl_access_log <==
10.221.2.135 - - [21/Jul/2016:18:59:55 +0200] "GET /dokuwiki/lib/plugins/ckgedit/fckeditor/editor/filemanager/browser/default/browser.html?Type=Image&Connector=https://cobbler1.lispa.local/dokuwiki/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php&CKEditor=wiki__text&CKEditorFuncNum=1&langCode=it HTTP/1.1" 304 -
10.221.2.135 - - [21/Jul/2016:18:59:56 +0200] "GET /dokuwiki/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php?Command=GetDwfckNs&Type=File&CurrentFolder=nothing HTTP/1.1" 200 -
10.221.2.135 - - [21/Jul/2016:18:59:56 +0200] "GET /dokuwiki/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php?Command=GetFoldersAndFiles&Type=Image&CurrentFolder=/&uuid=1469120391378 HTTP/1.1" 200 729
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /dokuwiki/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php?Command=GetFolders&Type=Image&CurrentFolder=/&uuid=1469120392640 HTTP/1.1" 200 662
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /dokuwiki/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php?Command=GetFoldersAndFiles&Type=Image&CurrentFolder=/cyberark/&uuid=1469120392704 HTTP/1.1" 200 1642
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/1.jpg HTTP/1.1" 404 275
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/2.jpg HTTP/1.1" 404 275
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/3.jpg HTTP/1.1" 404 275
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/4.jpg HTTP/1.1" 404 275
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/5.jpg HTTP/1.1" 404 275
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/6.jpg HTTP/1.1" 404 275
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/7.jpg HTTP/1.1" 404 275
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/8.jpg HTTP/1.1" 404 275
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/9.jpg HTTP/1.1" 404 275
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/10.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/11.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/12.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/13.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/14.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/15.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/16.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/17.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/18.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/19.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/20.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/21.jpg HTTP/1.1" 404 276
10.221.2.135 - - [21/Jul/2016:18:59:57 +0200] "GET /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles/image/cyberark/cyberark.jpg HTTP/1.1" 404 282
```

![cheditor](https://cloud.githubusercontent.com/assets/1568397/17032013/5f2117f0-4f77-11e6-9851-1171d26038f6.png)

**Comment by turnermm** [comment]
I thought perhaps some mixup could be happening with this: : `Alias /dokuwiki /var/www/dokuwiki`? But I set up a test case and it seems to work fine.    

You have such a complicated apache setup, I would like to see what happens if you install a fresh dokuwiki in the document root, which is `/opt/rh/httpd24/root/var/www/html`.  Then remove `/etc/httpd24/conf.d/dokuwiki.conf` to another directory so that it doesn't get loaded by apache.  Don't make any changes to your Dokuwiki configuration and install ckgedit using the extension manager.

**Comment by angystardust** [comment]
thanks for your suggestion. I was just thinking about a similar test. I
will do that asap.

Il 22/Lug/2016 02:05, "Myron Turner" <notifications@github.com> ha scritto:

**Comment by atlarep** [comment]
I am the same issue, but I am running IIS; this started about a week ago. The images do not get inserted either.
Any suggestions?

Thanks in advance.

**Comment by turnermm** [comment]
Haae you tried using the nix setup?  See: https://www.dokuwiki.org/plugin:ckgedit#file_browser

**Comment by atlarep** [comment]
You already helped me sort it out in https://github.com/turnermm/ckgedit/issues/228
We are good.

**Comment by turnermm** [comment]
I thought this looked familiar.  No problem.

**Comment by atlarep** [comment]
I do have a question though. Since it's not an issue, I wasn't sure where to post it.

I came across the site below while troubleshooting some stuff for CKGedit.
http://ckeditor.com/addons/plugins/all
Do you know if these add-ons work with this plugin in Dokuwiki? I tried to download a few of them and followed the instructions, but they don't show up in the Editor. Thanks in advance.

**Comment by turnermm** [comment]
To insert a new plugin follow the instructions on the plugin's page.  You will probably have to manually edit the dokuwiki toolbar definition in `config.js.unc` and then either change its name to` config,js` or compress it to` config.js`.  It's not required that it be compressed. See [how_do_i_make_a_change_to_the_toolbar](http://mturner.org/fckgLite/doku.php/faq#how_do_i_make_a_change_to_the_toolbar).  While that refers to an earlier version of the ckeditor, its basic premises are the same.   Almost certainly, few if any of the supplementary toolbar items that affect text formatting will work,

**Comment by turnermm** [comment]
You can only use tools that are compatible with Dokuwiki's syntax.  Anything else requires a Dokuwiki plugin. You can't, for instance, insert a form and checkboxes, etc.  That would require a Dokuwiki plugin.

**Comment by atlarep** [comment]
Thanks, I will look into this. I thought all I had to do was enable them in the Configuration Manager since the add-on pages only mention that part. But this will help me get there. Thanks again.

**Comment by atlarep** [comment]
Is there a way to attach files other than images to a document using the Resource Browser? 
I am not sure what changed, but before, when I clicked in the 'Insert Image' I was able to see other file types in the Resource Browser and attach then, but now I don't.

**Comment by turnermm** [comment]
You use the link dialog and choose `internal media`

**Comment by atlarep** [comment]
Thanks
