### ISSUE TITLE
The server didn't reply with proper xlm data when clicking on "Browse server" for media

### ISSUE THREAD

**Issue by Gnts** [turnermm/ckgedit#223]
https://i.gyazo.com/ff70ad07060399f8431a80e3bf03d73e.png
I couldn't find how to resolve this issue. Does this have something to do with permissions?
I tried placing .htaccess files all over the places but did not seem solve anything.

**Comment by turnermm** [comment]
See if this helps: https://github.com/turnermm/ckgedit/issues/24
