### ISSUE TITLE
Editing dokuwiki tabs with CKG Editor make them broken

### ISSUE THREAD

**Issue by WorldofNyms** [turnermm/ckgedit#224]
Hello !

We have updated our DokuWiki and CKGEdit to the latest versions and we are currently experiencing a bug when we are creating or editing a tab (see attached pictures).

We edit the tab with CKGEdit and save : tab is suddenly broken
If we edit the same page with DW Edit : we can see blanks after the " // "
When removing all the blanks created by CKG Edit (?) and save again with DW Edit, the tab is fixed.

Could you help us to fix this problem ?
Thank you :)

Picture 1 : when the tab is correct
![1_wiki_normal](https://cloud.githubusercontent.com/assets/20888793/17463216/879d54bc-5cc1-11e6-8f7d-4c057297fae0.png)

Picture 2 : after editing the page with CKG Editor (anything)
![2_wiki_bug](https://cloud.githubusercontent.com/assets/20888793/17463217/879e4f3e-5cc1-11e6-9064-ff7f10034c78.png)

Picture 3 : look at the page code with DW Edit
![3_wiki_source_bug](https://cloud.githubusercontent.com/assets/20888793/17463218/879f79cc-5cc1-11e6-86fe-36104c93dbbe.png)

Picture 4 : how to solve the problem - removing blanks manually
![4_wiki_source_corrected](https://cloud.githubusercontent.com/assets/20888793/17463219/87a0d4c0-5cc1-11e6-90bf-9a0fe7e018a3.png)

**Comment by turnermm** [comment]
Attach a copy of the original Dokuwiki table without errors.

**Comment by WorldofNyms** [comment]
A part of the tab without error can be seen on Picture 1 and Picture 4.

Here also a preview, where everything's good.
If I modify something with CKG Edit and save the page, tab will be broken.

![wiki_ok](https://cloud.githubusercontent.com/assets/20888793/17464456/7604c1e0-5cdf-11e6-8918-bce51bfe191b.png)

**Comment by turnermm** [comment]
I need the actual file, not an image. Please attach the file.

**Comment by WorldofNyms** [comment]
1. Here is the file where everything works.
[ambassadeurs.txt](https://github.com/turnermm/ckgedit/files/405806/ambassadeurs.txt)

2. Here is the broken file after editing one line with CKG Editor
[ambassadeurs_KO_after_update.txt](https://github.com/turnermm/ckgedit/files/405807/ambassadeurs_KO_after_update.txt)

**Comment by turnermm** [comment]
There is a conflict with the font styling at the top of your page:
```
===== Référentiel des actions =====

<font inherit/inherit;;#FF0000;;inherit>//A valider / Enrichir / Améliorer//</font>
```

If you remove the font styling the table will parse correctly.   This is a known issue, but in most cases with the complex tables option set to true, you don't have this problem.  But unfortunately this is one of those cases where the problem shows up.

**Comment by turnermm** [comment]
You could use the color plugin:
`<color red/white>A valider / Enrichir / Améliorer</color>`
Note: when you use plugins in ckgedit, they display as plugin markup, but the result shows up when displayed in the browser.  so what you wiill see in the editor is the above.  But in the browser the text will be red.
