### ISSUE TITLE
Default action when pressing return in edit summary is deleting the page

### ISSUE THREAD

**Issue by jakob42** [turnermm/ckgedit#226]
Hi,

just installed ckgedit and it works great so far. But if I simply press return after typing an edit summary, it asks me if I want to delete the page. Is this a general problem or rather a problem with my installation/browser?

Thanks!

Dokuwiki 2016-06-26a "Elenor of Tsort"
_ckgEdit-ckedit_457-16-Aug_07-11_53
Firefox 48.0
Chrome 51.0.2704.106 (without any installed plugins)

**Comment by turnermm** [comment]
You have to click the Save button.

**Comment by jakob42** [comment]
Too bad, thanks tough.
