### ISSUE TITLE
Improve header interface

### ISSUE THREAD

**Issue by stevenmg** [turnermm/ckgedit#227]
Since DokuWiki like just about any other wiki utilizes HTML header tags (h1, h2, etc.) to create a table of contents for each page it would be beneficial if the editor emphasized the headings feature a little more.

I am proposing adding along the top of the toolbar immediately before the bold, italics, etc. buttons that there be three buttons in a group: same level header, lower level header, and higher level header. This is the concept used in DokuWiki's native editor, and I think it would be beneficial here as well. All of this would be possible through a CKEditor extension that could be shipped by default with this distribution.

**Comment by turnermm** [comment]
![header](https://cloud.githubusercontent.com/assets/176447/18145807/5ab5531c-6f92-11e6-8c16-fe9bfbe41817.png)
The tool bar already comes with a header tool as well as a set of [short-cut keys](https://www.dokuwiki.org/plugin:ckgedit#short-cut_keys) that address the headers.  However, if you would like to write such an extension, it could be integrated into the toolbar.  See the ckgedit [configuration page](https://www.dokuwiki.org/plugin:ckgedit:configuration#extra_plugins).

**Comment by stevenmg** [comment]
I found out that this is actually possible using the standard format plugin, and it is simply a matter of configuration :+1:

**Comment by turnermm** [comment]
If you've found a solution, then please share it.  One  way would be to fork a copy of ckgedit and create a pull request.

**Comment by stevenmg** [comment]
Will do. I haven't implemented it myself yet as I've been focusing on the image insert functionality, but once I get around to it I will submit a PR.
