### ISSUE TITLE
Issue Inserting Images

### ISSUE THREAD

**Issue by atlarep** [turnermm/ckgedit#228]
I thought it'd be best to submit a new thread; I am having issues inserting images with the editor. I am able to upload, but the images appear to be broken.

The the 'OK' button doesn't seem to work after selecting the image.
![image](https://cloud.githubusercontent.com/assets/20726009/18145880/1592d2f6-6f9b-11e6-956b-d96022e36da0.png)

The problem seems to go away when I check this box in the Configuration Manager.
![image](https://cloud.githubusercontent.com/assets/20726009/18145950/5eac3cfc-6f9b-11e6-9c8c-053aab870017.png)

However, it used to work properly before when I was able to browse through namespaces.

Can you point me in the right direction?
Thanks in advance.

**Comment by turnermm** [comment]
Have you seen this: https://www.dokuwiki.org/plugin:ckgedit#file_browser?

**Comment by atlarep** [comment]
Is this new? It was working properly until last week.

**Comment by turnermm** [comment]
Not new at all.   I assumed you were a new user.

Have you made any changes to your dokuwiki?  Added any new plugins? Updated?

**Comment by atlarep** [comment]
Thanks for your response. 
No changes made. I didn't touch the weeks for two weeks and I am the only Admin too.
The only update I did was to CKGEDIT, but that was after I noticed the issue I noted above and I thought updating the program would solve it.

**Comment by turnermm** [comment]
Then you may have made some change to your system?  If ckgedit has been working and then failed to work without being changed, something may have changed in your server of desktop system.  Or you changed your browser. You haven't given any details about your system.

**Comment by atlarep** [comment]
That is what I thought initially, but no changes seem to be made to the server either; it's really weird.
What kind of details do you need?
I'm running:
Windows Server 2012 + IIS
DokuWiki version: Release 2016-06-26a "Elenor of Tsort"
Template: Vector
Plugins: 
Addnewpage
Authad
Autostartpage
Bookcreator
Ckgedit
Custombuttons
Discussion
Dw2pdf
Editx
Filelist
Gallery
Groupmanager
Imgpaste
Indexmenu
Infomail
Loadskin
Mediaattachment
Medialist
Move
Nsexport
Nspages
Odt
Orphanswanted
Pagelist
Recommend
Smtp
Socialite
Swiftmail
Talkpage
Tools
Wrap
My CKGEdit version says : 2016-08-24

**Comment by turnermm** [comment]
Unfortunately my experience with Win Server is minimal.  You could try disabling and then reenabling plugins. It's possible aWindows

**Comment by turnermm** [comment]
Sorry I'm on my phone.  Possible an update made a change.

**Comment by atlarep** [comment]
OK, I will take a look one at a time.

Thans

**Comment by atlarep** [comment]
I have tried disabling almost every single plugin (at the same time) and no luck.
I am no sure what else to try at this point.

**Comment by turnermm** [comment]
First check fckeditor/userfiles to see if in fact the links are there.  If not, you can create them either using a topl or from the command line.  This explains both methods: [guide-to-symbolic-linksl](http://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/).  What you want are 2 basic links from fckeditor/userfiles to data/media:  file and image: 
```
  fckeditor/userfiles/image -> /data/media
  fckeditor/userfiles/file -> /data/media
```
Also, see this from the deprecated fckgLite instructions which still applies to ckgedit: http://www.mturner.org/fckgLite/doku.php/docs:auto_install?s[]=symlinks#background.    You most likely need administrator permissions to do this.

**Comment by atlarep** [comment]
These are the files I see in the fckeditor/userfiles folder. 
![image](https://cloud.githubusercontent.com/assets/20726009/18183671/70758182-7063-11e6-9b7c-75a88eaaebf8.png)

I tried creating the links but got the error below:
![image](https://cloud.githubusercontent.com/assets/20726009/18183762/de9c1144-7063-11e6-965f-a92f76a579ab.png)

**Comment by turnermm** [comment]
You seem to have your paths reversed . Hard to read the image but you want:

```
mklink /D  symlink  directory
miklink /D path\to\symlink path\to\media-directory

```
```
mklink /D . . .\userfiles\image dokuwiki\data\media 
mklink /D . . .\userfiles\file dokuwiki\data\media 
```

**Comment by atlarep** [comment]
Oops, sorry. I reversed and got no error this time.
After that, I re-installed the plugin, but the problem still persists, Images are still broken and do not get inserted.
![image](https://cloud.githubusercontent.com/assets/20726009/18208476/a98b19ec-70fd-11e6-9caf-834ec429a4c2.png)

Did I skip a step or something?

**Comment by turnermm** [comment]
I have been seeing some similar issues with Apache 2.4 on a centos server.  There is nothing wrong with using the unix style access to the file browser.  So, if it works on your system then check off the nix_style option now that you have the correct symlinks in userfiles.  It might also help to put a copy of userfiles\.htaccess into data\media.

**Comment by atlarep** [comment]
Ah, good man, checking that box made it work flawlessly this time. 
Thanks a lot for your help. I really appreciate it.
