### ISSUE TITLE
Not compatible with DivAlign

### ISSUE THREAD

**Issue by algorys** [turnermm/ckgedit#229]
Hello,

I'm currently testing your plugin (very good job :+1: ) on a test server, and I encountered the following problem.

I've a Detritus Dokuwiki install with plugin [divalign2](https://www.dokuwiki.org/plugin:divalign2). If I use CKGedit to edit a page who use Divalign2, he duplicate text !

Exemple, if I had a page like this:

```
###
Dokuwiki's media files are secured by an .htaccess file in the data directory which prohibits direct web access to the files stored in the data directory and all of its subdirectories. To by-pass this prohibition, fckgLite accesses the media directory indirectly through symbolic links in the fckeditor/userfiles directory. 
###
```

And I edit it. I've now the following text in FCK editor:

```
###Dokuwiki's media files are secured by an .htaccess file in the data directory which prohibits direct web access to the files stored in the data directory and all of its subdirectories. To by-pass this prohibition, fckgLite accesses the media directory indirectly through symbolic links in the fckeditor/userfiles directory.Dokuwiki's media files are secured by an .htaccess file in the data directory which prohibits direct web access to the files stored in the data directory and all of its subdirectories. To by-pass this prohibition, fckgLite accesses the media directory indirectly through symbolic links in the fckeditor/userfiles directory. ###
```

As you can see, some part of test is duplicate !! I'm not sure it's only divalign2 and not due to the 3 consecutive `#`...

Have you a solution for that ? Or I've to parse all my files to use your plugin after ? :cry:

Thanks for help.

**Comment by turnermm** [comment]
Yes, I see the problem.  I'm not sure when I can get to it.

**Comment by algorys** [comment]
Ok, I'll wait for a fix.

**Comment by turnermm** [comment]
I began looking at divalign2 and discovered that the toolbar button when clicked does not display the four option icons.  If this is your case, then you can replace `divalign2/script.js`  with the one I've posted to the plugin page: https://www.dokuwiki.org/plugin:divalign2#edit_toolbar

**Comment by algorys** [comment]
Yes that's do the trick. I've just to add lib to additionnal icons for me. https://www.dokuwiki.org/plugin:divalign2#edit_toolbar

**Comment by turnermm** [comment]
This should be working now.

**Comment by turnermm** [comment]
Uploaded a further fix for the divalign2 plugin.  Note:  when the text id loaded into ckgedit it will replace the newlines with the macro: `divalNLine`, which will be replaced by newlines on the save.

**Comment by algorys** [comment]
I've update your plugin and now, I've no more button divalign ! :laughing: 

Maybe a problem with my install.

**Comment by turnermm** [comment]
ckgedit has no effect on the installation of the divalign plugin.  All it does now is to make an accommodation for the divalign2 syntax.
