### ISSUE TITLE
Saving a page after File Block insertion fails

### ISSUE THREAD

**Issue by hansharm** [turnermm/ckgedit#234]
Inserting a new file block as explained in the [documentation example](https://www.dokuwiki.org/plugin:ckgedit#geshi_example) and in the [video](https://www.youtube.com/watch?v=bI7x17EBbbI&feature=youtu.be) works as expected. It is possible to save the page after creating the file block.

While editing the page again it is not possible to save changes that were made to the page.

Reproduce the Issue:

_1. Create New File Block_
![2016-09-13 16_16_39-create_file_block](https://cloud.githubusercontent.com/assets/22170406/18478083/4603368a-79d0-11e6-99ad-0188df90291a.png)

_2. New File Block_
![2016-09-13 16_16_59-created_file_block](https://cloud.githubusercontent.com/assets/22170406/18478110/5ee8615c-79d0-11e6-909e-d439aee786fc.png)

_3. Edit and (trying to) Save results in a Type Error in Dev Console of Firefox_ 
![2016-09-13 16_18_00-edit_and_save](https://cloud.githubusercontent.com/assets/22170406/18478149/77c9bec8-79d0-11e6-9a12-9a616112efe2.png)

_Source Code of the page_
```
<dl class="file">
	<dt><a class="mediafile mf_txt" href="/dokuwiki/doku.php?do=export_code&amp;id=playground:playground&amp;codeblock=0" title="Schnipsel herunterladen">test.txt</a></dt>
	<dd>
	<pre class="code file txt">
test



</pre>

	<p>&nbsp;</p>
	</dd>
</dl>
```

OS: Ubuntu 16.04.1 LTS
DokuWiki version: Release 2014-09-29d "Hrun" & Release 2016-06-26a "Elenor of Tsort"
PHP version 5.6.25-2+deb.sury.org~xenial+1
Client: Windows 10
Browser:  Firefox 48.0.2 & IE 11
CKGEdit Plugin: Last updated on 2016-09-11

If you need additional information please let me know.

If this issue might be related to my environment please give me a hint to solve this problem.

Thanks in advance!

**Comment by turnermm** [comment]
I believe I may see the problem.  The debugging output shows a Type error.  This has been fixed. Update the plugin.,

**Comment by turnermm** [comment]
After doing a bit of scouting around, I discovered that this technique doesn't work on Chrome.  There you can insert the file block manually:
```
<file geshi: php tmp.php>
$s=3;
</file>

```
It will then save and reload correctly.  I will have to take a look at the reason why it fails.

**Comment by hansharm** [comment]
Thanks a lot, that solved the issue!
