### ISSUE TITLE
Default internal link relative to current namespace

### ISSUE THREAD

**Issue by stevenmg** [turnermm/ckgedit#235]
I am thinking it would be nice to have the link dialog default to the current namespace when inserting an internal link. If you browse for a link it defaults to the current namespace, but it does not default to the current namespace when entering a new link. This could be changed by simply setting the internal link text field to the current namespace with a : at the end, or a checkbox could be added saying "relative to current namespace" or something like that. I would gladly implement this myself, but I am wondering if you have any thoughts on it @turnermm ?

**Comment by turnermm** [comment]
I'm not following the difference between these two options:

> I am thinking it would be nice to have the link dialog default to the current namespace when inserting an internal link. If you browse for a link it defaults to the current namespace, but it does not default to the current namespace when entering a new link. 

Do you mean, if the document is `:wiki:start` and you select a link named :`system:tech`, the link browser will then start next time in the `system` namespace?

**Comment by stevenmg** [comment]
Sorry if that wasn't clear. What I meant to say is that currently if you open the link browser it is open by default to the current namespace, but if you just chose to enter your page title in the link dialog text field, you would need to enter the entire namespace (or '.').

**Comment by turnermm** [comment]
I see, like the linkwiz, which stays at the last accessed directory. I never noticed that.  But not, the media manager, it seems.   It hadn't actually occurred to me that users might want to insert internal links by entering the text into the text box of the link dialog.  You can in fact enter internal links as text directly into the editor, without using the link tool, as you can with external links.  But I can see that this could be a convenience by saving some typing.
If you would like to do this, I would appreciate it.  Perhaps the check box, defaulting to on, would also be a good idea.  Thanks.

**Comment by stevenmg** [comment]
I'll see what I can come up with. I actually hadn't noticed the inconsistent behavior between linkwiz and media manager. Should that be made more consistent? I like that it stays at the last opened namespace personally, but I could see how some people would not. I believe the current linkwiz behavior is consistent with it's behavior within the default DW editor.

**Comment by stevenmg** [comment]
Here's what I'd like to do.

I would first of all add a checkbox with the label "Relative to current namespace" (localized of course). This checkbox would do two things:

1. Force the Linkwiz/link browser to open to the current namespace
2. Make any text entered directly create a link relative to the current namespace

If this box was unchecked:

1. Linkwiz/filebrowser would open to last namespace (unless it is the first time it is opened in which case it would open to the current namespace). This would reset whenever the editor is reopened.
2. Text entered would be the full link path

I would also see an extra label being added to the link dialog immediately underneath the text field to show the absolute link path. This would make it more obvious to the user what exact page they are linking to.

If this sounds good to you I will go ahead and implement it in the next few days.

**Comment by turnermm** [comment]
It's taken me a little time to get my head around this, because, while I often switch to the native editor, I rarely use the linkwiz and never paid any attention to its behavior.  But this sounds very good to me.

**Comment by stevenmg** [comment]
Awesome. I'll get a PR started hopefully this week sometime.
