### ISSUE TITLE
ldaps-Link - formatting gets broken

### ISSUE THREAD

**Issue by hansharm** [turnermm/ckgedit#236]
Editing a text to ldap like: `ldap://example.com:389` works as expected.

Editing a text to ldap**s** like: `ldaps://example.com:636` seems to get interpreted as a comment and breaks the formatting of the following text.

_1. Edit link text to ldap_ 
![2016-09-14 09_21_32-ldap_link_edit_code_text](https://cloud.githubusercontent.com/assets/22170406/18503732/df2b2866-7a5e-11e6-82e7-de3ee7a1b6fe.png)

_2. Result of the page after saving the changes_
![2016-09-14 09_21_32-ldap_link_saved](https://cloud.githubusercontent.com/assets/22170406/18503736/e3405854-7a5e-11e6-915f-a83ceff36db9.png)

_3. Edit link text to ldaps (it doesn't matter whether to format the text as code text or not)_
![2016-09-14 09_25_12-ldaps_link_edit_code_text](https://cloud.githubusercontent.com/assets/22170406/18503750/f100ae94-7a5e-11e6-95b2-007a3a874c4e.png)

_4. Result of the page after saving the changes_ 
![2016-09-14 09_26_42-ldaps_link_saved](https://cloud.githubusercontent.com/assets/22170406/18503781/17e043da-7a5f-11e6-8d7e-0fbe97e2c811.png)

Please let me know if this is an issue or if this type of text/link is not supported in general.

Thanks in advance!

**Comment by hansharm** [comment]
Same issue when adding a text like:

`logfile = file:///var/log/logfile.log`

Thus the issue might be ralted to the slashes.

**Comment by turnermm** [comment]
This does not appear to be a problem of ckgedit but of the Dokuwiki processor.  This is apparent in the attached image, which show the text as it appears in the native Dokuwiiki editor and then in the preview.  
![unbracketed2](https://cloud.githubusercontent.com/assets/176447/18524217/1f5942a6-7a7d-11e6-9c7e-96d74bb5f837.png)

I don't know if Dokuwiki has a format for this type of link.  You could ask on the mailing list.
If you just want to print it as text, you can simply escap thext with %%. . .%% or nowiki tags.  The way around this is to escape the text.

**Comment by turnermm** [comment]
You can probably do this with an interwiki link:
`ldaps     ldaps://example.com:{PORT}`
Then in you dokuwiki document:
[[ldaps>360]]

**Comment by turnermm** [comment]
I was able to reproduce this only one with multiple atttempts, so it's nto easy to fix.  But I suspect that the problem is the

**Comment by hansharm** [comment]
Thanks for the hint mentioned above! Therefore I searched in the configuration folder for `ldap` in the config files, because there were no issues for `ldap://example.com:389`.

Thus I think the better approach is to add `ldaps` and/or `file` or whatever you may need to `scheme.conf`.

That solved the issue for me. Thanks a lot for your support!
