### ISSUE TITLE
Block quotes don't seem to be supported

### ISSUE THREAD

**Issue by iainhallam** [turnermm/ckgedit#246]
My wiki uses the Docuwiki block quote syntax extensively:

`> Quote`

However, when loading a page that uses block quotes, they are simply displayed as angle brackets in the text. Can ckgedit understand these quotes somehow?

Thanks.

**Comment by turnermm** [comment]
Not sure what you mean by `Docuwiki block quote syntax`.  If you mean code blocks, they are supported and rendered in the editor window.  If you are referring to a plugin that gives you block quotes, then, yes, like all syntax plugins they are not rendered in the editing window but are rendered on the save.

**Comment by iainhallam** [comment]
The quoting syntax, which is part of Dokuwiki's core syntax:

https://www.dokuwiki.org/wiki:syntax#quoting

It's also part of markdown and standard HTML.

**Comment by turnermm** [comment]
![code-blocks](https://cloud.githubusercontent.com/assets/176447/20630720/470c4d62-b2f8-11e6-87f2-5c58129c0f26.png)
This image illustrates code blocks in the editing window.

**Comment by turnermm** [comment]
It's supported.  But to have the sequential quotes appear single spaced, you have the enter them on a single line:
           `> hello >>goodbye>>>have a good day`
Otherwise the editor double spaces between quotes.

**Comment by turnermm** [comment]
However, it seems to accept single spacing it you use the single line space  entry, that is, by holding down the shift-key while hitting enter.

**Comment by iainhallam** [comment]
When I do that, the code that I see is saved in DokuWiki is:

```
> Text\\
> Text
```

Those extra backslashes are causing DW to still double-space the quote when rendering the page as it thinks there's a line break at the end of each one, plus the paragraph break.

**Comment by turnermm** [comment]
## In the ckgedit editor:
![quotes1](https://cloud.githubusercontent.com/assets/176447/20812713/3ced8082-b7d8-11e6-9955-52a958e4ecb2.png)
## In the Browser:
![quotes2](https://cloud.githubusercontent.com/assets/176447/20812735/4ee6e314-b7d8-11e6-9533-a177bf6f5984.png)
## In the Dokuwiki Editor:
![quotes3](https://cloud.githubusercontent.com/assets/176447/20812761/670ccf58-b7d8-11e6-93f3-89ae85f22a7e.png)

These results are consistent in both Chrome and Firefox.

**Comment by jktoole** [comment]
You can hack in presentational support for blockquotes like this:

1.) In action/edit.php, on the line above `if($this->draft_started) return $this->xhtml;`, add:
```
$this->xhtml = preg_replace_callback(
     '/<p>\n> (.*?)<\/p>/ms'
    ,function ($s) {
        $s = trim(str_replace(array("\r\n","\n\r", "\n", "\r"),' ',$s[1]));
        return str_replace('<br />','\\\\',"<blockquote>$s</blockquote>\n\n");
    }
    ,$this->xhtml
);
```

2.) In script.js, on the line above `stack.last = function(){`, add:
```
if(html.match(/<blockquote>/)) {
    html = html.replace(/<br \/>(\r\n|\n|\r)/gm,"\\\\ "); // Replace br's first
    html = html.replace(/<blockquote>([\s\S]*?)<\/blockquote>/gm,function(x) {
        return "\n&gt; " + x.replace(/<p>(.*?)<\/p>/gm," $1 ").trim().replace(/(\r\n|\n|\r)/gm,' ') + "<p>&nbsp;</p>";
    });
}
```

3.) In the configuration settings, add "Blockquote" to plugin»ckgedit»extra_plugins (this will add the button to the toolbar).

Haven't tested this thoroughly and it needs revising to be less hacky, but it seems to work, with the following restrictions/potential issues:

* Blockquotes cannot contain layout elements
* Blockquotes can only contain soft returns (BRs)
* Consecutive blockquotes might become a single blockquote.

**Comment by turnermm** [comment]
Not prepared to inject local code fixes into the HTML Parser. This is not a problem when the Quoting markup is entered directly into ckgedit's editor, as in the Dokuwiki editor.  The only issue is when reading from a native DW page that has the markup.  Then your number 1 could come into play.  Why don't you fork a copy of  ckgedit and make a pull request.

**Comment by jktoole** [comment]
Sorry, I should have explained in my last comment. This is just a quick hack I'd used myself, copied and pasted in case it was useful to @iainhallam, rather than a suggestion for CKGEdit.

**Comment by turnermm** [comment]
Quoting/blockquoting saved to the page file is now compatible with the native Dokuwiki markup.  You still have to mark it up in the CKeditor as you would in the DW editor, i.e. using the angle brackets `>` to start each new level.  But in the saved page, the double backsalsh `\\`  no longer is used.
