### ISSUE TITLE
Not compatible with diagram plugin

### ISSUE THREAD

**Issue by Gonzo4** [turnermm/ckgedit#247]
Hi, 

I'm currently testing the chgedit plugin and I encountered a problem with the [diagram plugin](http://nikita.melnichenko.name/projects/dokuwiki-diagram/index.php?lang=en). 

The diagram plugin has a table like syntax with pipes (''|'') => opening and saving pages with the chgedit-editor will break the diagrams. The complex tables option is set to true.

As workaround it is possible to include the diagrams with die include plugin, but that's a poor solution ;)

**Comment by turnermm** [comment]
Possibly you will have to use the ditaa plugin which is compatible with ckgedit.

**Comment by turnermm** [comment]
I did a few tests and found that you could use diagram but it doesn't retain the color informatioln in ckgedit.

**Comment by Gonzo4** [comment]
Hi,
ditaa is not an option, because we already have a lot of 'diagram' diagrams and because it is possible to put links inside the diagram blocks...
Yes, everything behind the last pipe get lost after saving... Is it possible to ignore everything in between the <diagram> elements, or is it possible to create a tag like ~~DONT_PARSE_START~~ and ~~DONT_PARSE_END~~ ?
 Thanks for the fast answer!

**Comment by turnermm** [comment]
I guess this should be closed since there's not much I can do to support this plugin.
