### ISSUE TITLE
formatted text inside a table gets destroyed or disappears when editing it with a windows browser

### ISSUE THREAD

**Issue by mathias-noethiger** [turnermm/ckgedit#248]
When formatting text inside a table on a Apple System all works fine. When editing the same content on a Windows 10 machine (Chrome, Firefox, Edge) the font formatting gets broken, content disappears in the frontend. When opening the broken content with Windows, all gets displayed correctly content is there again. When saving it, its broken again. When opening the broken content on my Apple machine it gets displayed correctly. When saving it on my Apple machine without editing anything. It gets displays in the frontend correctly again.

Conclusion: formatted text inside a table gets destroyed or disappears when editing with a windows browser

Check it out with this pice of code and you will see:
<table class="inline">
	<tbody>
		<tr class="row0">
			<th class="col0">content</th>
			<th class="col1">content</th>
			<th class="col2">content</th>
			<th class="col3">content</th>
		</tr>
		<tr class="row1">
			<td class="col0"><strike>content</strike></td>
			<td class="leftalign"><span style="background-color:rgb(51, 153, 102)">Green Background</span></td>
			<td class="leftalign">25.01.16<br />
			<span style="color:#FF0000">red text</span></td>
			<td class="leftalign"><span style="background-color:#339966">04.07.16</span></td>
		</tr>
	</tbody>
</table>

**Comment by turnermm** [comment]
http://www.mturner.org/devel/devel/ckgedit/table_formats

**Comment by turnermm** [comment]
http://www.mturner.org/devel/devel/ckgedit/table_formats_chrome

**Comment by mathias-noethiger** [comment]
Try the following.  

... style="background-color:rgb(51, 153, 102)" 
... style="color:#FF0000" ....

**Comment by turnermm** [comment]
I'm not sure what you are trying to prove.  Yes, there are certain conditions under which ckgedit cannot deal with font markup, but see:
https://www.dokuwiki.org/plugin:ckgedit:font_styling#font_styling
And then see this:
http://www.mturner.org/devel/devel/ckgedit/table_formats_chrome
To get the red on two lines, you first have to do the font markup (using ckgedit's font styler) with the text on one line, then using the SHIFT-ENTER technique add the new line.

**Comment by mathias-noethiger** [comment]
Could you comprehend that editing the same table leads to problems on Windows machines? Content which one can see correctly within the CKG Editor just disappears partially at the fronend after saving it with a windows browser? When I edit the content again everything was there again, nothing disappeard. That's very weird. The code example seems to be clean. No encapsulated formatting or so.
