### ISSUE TITLE
Compatibility with plugin "fastwiki"

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#249]
Hi,

there is a problem between "ckgeditor" and the plugin "fastwiki" on trying the section edit. But this is essential for the fastwiki plugin because different users have different knowledge of the dokuwiki syntax and therefore different preferences which editor they use by default.

So what would you think about the following idea, when the fastwiki plugin is installed:

Clicking a section button
 -  starts the ckgeditor always for the whole page if this editor is pre-selected by the user,
 -  starts the fastwiki inline editor for this section if the DW-editor is pre-selected

Best regards
Juergen

**Comment by turnermm** [comment]
You are welcome to implement this if you would like to have it.  But it's not something I want to deal with myself.

**Comment by turnermm** [comment]
You might find this useful:
https://www.dokuwiki.org/doku.php?id=plugin:ckgedit#direct_access_to_dokuwiki_editor
The dw_edit plugin does some of what you want, but it does not work in conjunction with the section edit system.

**Comment by Juergen-aus-Koeln** [comment]
Thank you for your hint
