### ISSUE TITLE
 Content Security Policy

### ISSUE THREAD

**Issue by disque-monde** [turnermm/ckgedit#251]
It doesn't work !
Release 2016-06-26a "Elenor of Tsort"
Debian 8
PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08)

When I click on "Editeur CKG" on the edit page, nothing append !!

Firefox Console:

```
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src https://myhost.net»).  doku.php:6
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src https://myhost.net »).  doku.php:17
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAABzCAYAAABZ/2hDAAAAmElEQVQoz+3IIU5DURRF0X32ff2/oQlp6yDB1CGYAAMgwTCMjhwMDoEr72KYAq5LLlhvHyROIS2hpdN/p1NwitWStGS0OKb0RMYyBVJctovsb6awpLiMjRx2CDsqP5Z93Ee+q4uxDjlskfduuZtIgvlYpn0ilU2Uz/u2nypkdRT9Enn+Cgkl/UrlsYNB+/gGAhJin89c/adf1hUppirdLEYAAAAASUVORK5CYII= (« default-src https://myhost.net »).  (source inconnue)
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src https://myhost.net »).  doku.php:1
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src https://myhost.net »).  doku.php:21
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src https://myhost.net »).  doku.php:100
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src https://myhost.net »).  doku.php:109
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src https://myhost.net »).  doku.php:113
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src https://myhost.net »).  doku.php
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src https://myhost.net »).  doku.php:180
ReferenceError: JSINFO is not defined[En savoir plus]  js.php:23:52130
```
No errors on server side !

**Comment by turnermm** [comment]
What happens if you do not use ckgedit?

**Comment by disque-monde** [comment]
I have the normal DW editor...

**Comment by disque-monde** [comment]
Details of the js error frome Firefox console:

```
dw_linkwiz.init https://myhost.net/lib/exe/js.php:23:52130
	addBtnActionLinkwiz https://myhost.net.net/lib/exe/js.php:23:42035
	initToolbar/< https://myhost.net/lib/exe/js.php:23:40281
	.each https://myhost.net/lib/exe/js.php:3:2859
	initToolbar https://myhost.net/lib/exe/js.php:23:39793
	<anonyme> https://myhost.net/lib/exe/js.php:23:42909
	n.Callbacks/i https://myhost.net/lib/exe/js.php:3:27146
	n.Callbacks/j.fireWith https://myhost.net/lib/exe/js.php:3:27914
	.ready https://myhost.net/lib/exe/js.php:3:29705
	J https://myhost.net/lib/exe/js.php:3:29890

```

**Comment by turnermm** [comment]
See:  https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Yo will not be able to use the standard ckgedit unless your handle the above issue.  But you should be able to use [ckgdoku](https://www.dokuwiki.org/plugin:ckgedit#ckgdoku), which gives you the choice of using the Dokuwiki link and image browsers.

**Comment by turnermm** [comment]
This `dw_linkwiz.init https:` has nothing to do with ckgedit.  The linkwiz is Dokuwiki's link browser.   Are you now saying that Dokuwiki's link browser doesn't work either?

**Comment by disque-monde** [comment]
Ok, thanks for reply but it doesn't work again after installing ckgdoku
[![Screenshot_20170202_222042.png](https://s24.postimg.org/mapdfc1w5/Screenshot_20170202_222042.png)](https://postimg.org/image/yckr9hb4h/)
It's like https://github.com/turnermm/ckgedit/issues/244 , but i am not on cloudflare...

I'have disable Header set Content-Security-Policy "default-src 'self';" in my Apache2 conf and it work !

Happy for my wiki but not for Apache2 security...
Thanks!

**Comment by turnermm** [comment]
Dokuwiki has built-in protection against cross-site injections.  So, I  you might be able to set  your Content-Security-Policy to make an exception for ckgedit.

**Comment by turnermm** [comment]
Place this header at the top of doku/php
`header("Content-Security-Policy: default-src 'self'; script-src   'unsafe-eval'  'self'  'unsafe-inline'  svc.webspellchecker.net; style-src 'unsafe-inline' 'self' svc.webspellchecker.net;");`
The only thing it doesn't seem to catch is the scayt spell checker.  
Place is just before i`f($conf['breadcrumbs']) breadcrumbs()`;

**Comment by jvoisin** [comment]
There is no point in having a CSP policy that allows `unsafe-eval` and `unsafe-inline` :/

**Comment by turnermm** [comment]
CSP issues are a know problem in the CKEditor.  As for inline js, the ckgedit user interface relies on it.  When it was first started, almost 10 years ago, this was not an issue.  I've moved much of the inline into scripts.  But I'm not up to re-writing the ckgedit user interface.  If you or someone you know would like to undertake this project, that would be good.

**Comment by turnermm** [comment]
I did some further checking in the CKEditor's issues and it seems that inline js is also a problem there.  Here is a post from Drupal:  https://www.drupal.org/project/drupal/issues/2789139

**Comment by turnermm** [comment]
See https://github.com/turnermm/ckgedit/issues/404

**Comment by jvoisin** [comment]
You're right, my formulation was a bit rude, sorry about that. I'll see what I can do ♥

**Comment by turnermm** [comment]
It's been done with a simple fix.
