### ISSUE TITLE
how to set image upload default link

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#252]
How to set image upload default link type is "Direct" .
And that all hyperlink target in pages can set  value  to "_blank"  ?

**Comment by turnermm** [comment]
> And that all hyperlink target in pages can set value to "_blank" ?

You do this in Dokuwiki's Configuration Settings under `links`

> How to set image upload default link type is "Direct" .

To do this you will have to make a change in `lib/plugins/ckgedit/ckeditor/plugins/image/dialogs/`  You will find two files there:  `image.js`  and `image.js.unc`;  `image.js`  is a compressed versioin of  `image.js.unc`.  In `image.js.unc` at line 787 change the default from `detail` to `direct`:
```
                        label: editor.lang.common.linkType||"Link Type",
                        'default': 'direct',
                         items: [                                           
                               [ editor.lang.common.linkDetail  || "Detail", 'detail'],
                               [ editor.lang.common.linkDirect ||"Direct", 'direct' ],

```
You can now do one of two things.  You can simply rename `image.js.unc` to  `image.js` or you can compress `image.js.unc`  and copy it to `image.js`.  For instructions on compression see [the ckgedit plugin page](https://www.dokuwiki.org/plugin:ckgedit#compressionl).

**Comment by qwe852147** [comment]
Thanks!!It works!

**Comment by turnermm** [comment]
The problem here is that when you upgrade ckgedit, you will loose your changes.  However, there is little likelihood that image.js will  change, so before upgrading, just save that file and replace the image.js from the upgrade with the saved file.

**Comment by qwe852147** [comment]
Thanks!I'll save it before upgrading ckgedit.
