### ISSUE TITLE
The space following bold links is deleted when the page is saved

### ISSUE THREAD

**Issue by jktoole** [turnermm/ckgedit#254]
If you create a new page with this content:

`This sentence has a **[[:wiki:syntax|bold link]]** in it.`

..then edit that page in CKGEdit (e.g. to add the word "test" to the end of the sentence) and click 'Save', the content is saved as:

`This sentence has a **[[:wiki:syntax|bold link]]**in it.`

The space between 'link' and 'in' has been deleted.

If you change this line in parse_wiki.js (line 1670 in parse_wiki.js.unc):

`results = results.replace(regex,"$1$2$3");`

..to:

`results = results.replace(regex,"$1$2 $3");`

..then everything seems to work OK - but I only tested with that sample and don't know if this fix is breaking something somewhere else.

**Comment by turnermm** [comment]
See https://github.com/turnermm/ckgedit/issues/255
