### ISSUE TITLE
Adding link to another dokuwiki instance is detected as an internal link

### ISSUE THREAD

**Issue by gabrielcossette** [turnermm/ckgedit#256]
Hi,

If we try to add a link to **another** dokuwiki website, the link is wrongly considered as an internal link. I think the logic in [link.js.unc](https://github.com/turnermm/ckgedit/blob/efc0f730c9ec8470b02f6480fd12b6028cd21914/ckeditor/plugins/link/dialogs/link.js.unc) would need to be adjusted so that the domain name part of the address is compared to the running instance (if that is possible at all).

Thanks!

**Comment by turnermm** [comment]
Try this branch: https://github.com/turnermm/ckgedit/archive/urlextern_id.zip.  Use it for a while and please let me know the results.

**Comment by gabrielcossette** [comment]
Thanks for the quick response! It's working but there's a little bug remaining. Once we inserted the link, if we try to edit it again, it's still recognized as an internal link (and if we confirm the dialog, it is converted back to internal link).

**Comment by turnermm** [comment]
Should be fixed in same branch as above--`urlextern_id`

**Comment by gabrielcossette** [comment]
Seems to work now, thanks a lot! I'll let you close it when merged in master branch I guess.
