### ISSUE TITLE
CKGEdit or ckgdoku

### ISSUE THREAD

**Issue by simon-roderus** [turnermm/ckgedit#258]
Do you recomment CKGEdit or ckgdoku for newer versions of dokuwiki and does ckgdoku work with dokuwiki farms?

**Comment by turnermm** [comment]
Either one will work with farms.  I would suggest using ckgedit and if you have trouble with the filebrowser then sitch over to ckgdoku and use the native dokuwiki linkwiz and media manager.

**Comment by simon-roderus** [comment]
Thank you for your answer. I prefer the dokuwiki filebrowser and will therefore try ckgdoku.

**Comment by turnermm** [comment]
Please note that there are two versions of ckgedit dedicated to farms:

https://www.dokuwiki.org/plugin:ckgedit#farms
https://www.dokuwiki.org/plugin:ckgedit#available_versions_of_ckgedit

You should be able to use the standard ckgdoku for a farm install as long as you turn off access to the ckgedit filebrowser.

The farm versions are not always competely up-to-date with the most recent fixes but these are not things which will interfere with use.

**Comment by simon-roderus** [comment]
I didn't know that, thank you!

**Comment by turnermm** [comment]
For ckgedit you have to use the farms veresion.  I am checking ckgdoku to see if it needs anyh updating and will keep you informed.

**Comment by proxymus** [comment]
That would be great! Thank you!

**Comment by turnermm** [comment]
I think that the ckgdoku version is now fully synched with the standard farms version.  This is the one you need:
https://github.com/turnermm/ckgdoku/archive/farms_4.7a.zip

You will always find the current version

**Comment by proxymus** [comment]
> You should be able to use the standard ckgdoku for a farm install as long as you turn off access to the ckgedit filebrowser.

You've mentioned above that it should be possible to use the ckgdoku master for a farm install. I'm using dokuwiki farms. Should I use the ckgdoku farm version or the ckgdoku master?
Currently I use the ckgedit farm version. Is there anything I've to think about before I switch to ckgdoku? Thank you in advance.

**Comment by turnermm** [comment]
> You should be able to use the standard ckgdoku for a farm install as long as you turn off access to the ckgedit filebrowser.

The above is incorrec. Sorry.  You have to use the farms version.

**Comment by proxymus** [comment]
I've made the switch today. For now I think that everything is working. Thank you for your assistance.

**Comment by Juergen-aus-Koeln** [comment]
The idea of ckgdoku is very good, and the result of my tests is, that it works without problems. So my wish is that you integrate this new release into the "normal" ckgedit plugin as soon as possible!
