### ISSUE TITLE
Need to add extra-plugins into the toolbar

### ISSUE THREAD

**Issue by LeGoulu** [turnermm/ckgedit#262]
Hi, first thx for this awesome plugin !

I need help to add the plugin "note" to your plugin, i try to add it into your extraplugins option in the DokuWiki parameters but it doesn't work. Have you an easy tuto for that ?

Best regards,

**Comment by turnermm** [comment]
You can add only CKEditor compatible plugins.  Note is a dokuwiki plugin.  But you can enter the note syntax directly into the ckgedit editor, just as you would in the dokuwiki editor.  You will get the same result.  For instance, using the xamples on the note plugin page.:
```
<note>
This is my note ! Remember it!!
</note>

<note important>
Warning ! You're about to lose your mind ;-)
</note>

<note tip>
The clues are in the images.
</note>

<note warning>
Beware of the cat when you open the door !!
</note>
```
The notes will display in the browser but in the editor they will display as the plugin markup.

**Comment by LeGoulu** [comment]
Ok, thx for all ! =)

Do you know if a CKEditor plugin who can add personnalised syntax like "<note>...</note>" on a new button exist ? This would allow me to bypass "my problem".

**Comment by turnermm** [comment]
Not that I know about.

**Comment by LeGoulu** [comment]
k, thx again ! Have a good day !

**Comment by proxymus** [comment]
Hello,
I've written a plugin which inserts a note into CKeditor. It is working with the native CKeditor. 

![grafik](https://cloud.githubusercontent.com/assets/1539498/23299433/dab855e4-fa81-11e6-99f8-5b591b0e8d40.png)

But currently I've problems to add it to the CKGdoku toolbar. The icon/button won't appear. I've added the plugin to the config.js file:
![grafik](https://cloud.githubusercontent.com/assets/1539498/23299712/e183b534-fa82-11e6-881d-f4020fc26ade.png)
I've also added the plugin to the dokuwiki config
![grafik](https://cloud.githubusercontent.com/assets/1539498/23299736/ff27a168-fa82-11e6-9680-455d385bcbe7.png)

Here you will see the plugin.js code
![grafik](https://cloud.githubusercontent.com/assets/1539498/23299761/1deec694-fa83-11e6-876c-15e2f477acc2.png)
Maybe you can give me a hint, what I'm doing wrong.

**Comment by proxymus** [comment]
I've got it working in my environment. You can give it a try.
https://github.com/proxymus/note_ckgdoku

**Comment by turnermm** [comment]
Did I send you this: https://github.com/turnermm/note_ckgdoku?  With this you can select text in the editor and it will be inserted into the note.
