### ISSUE TITLE
Opening page to edit with CKGedit duplicates horizontal rule

### ISSUE THREAD

**Issue by dantex47** [turnermm/ckgedit#268]
PROBLEM: every time I open page for edit that contains horizontal rule ( ---- ), CKGedit shows WYSIWYG horizontal rule, and under it, it shows "----", which on change to DW editor duplicates.

ENVIROMENT:
- Browser: Google Chrome Version 56.0.2924.87 (64-bit)
- Dokuwiki version: Problem was persistent on last 2 version i have had: Release 2017-02-19a "Frusterick Manners" and 2016-06-26 "Elenor Of Tsort"
- CKGedit version: 2017-03-04 and one before that

STEPS TO RECREATE:
- create a new page (ckgedit) , add a horizontal rule
- save page
- open the page again (ckgedit)
- the editor now shows WYSIWYG line, and under it code for horizontal break "----"
- select DW editor
- you are now back on page overview with double horizontal rule

**Comment by turnermm** [comment]
Can't reproduce this in any way.  Not that it is required, but are you using the ckgedit's horizontal rule tool?

**Comment by dantex47** [comment]
I have reconstructed it on video, with annotations. Sorry if the video isn't clear, I don't have any experience with video editing.

https://youtu.be/DP-7mJinycQ

To clarify, those lines are only persistent when they are shown in CKG, and then you switch from CKG to DW editor. Saving from CKG produces normal page as expected. Shown in this video:

https://youtu.be/HY0Xnd43P00

**Comment by turnermm** [comment]
https://www.youtube.com/watch?v=boczMDvtMJI&feature=youtu.be

**Comment by dantex47** [comment]
What php version are you using? My docker container uses php 5.5
