### ISSUE TITLE
Upload only images when using image dialog: application/pdf

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#271]
Hi,

when I try to upload a pdf file, there comes up the following message in the dokuwiki-mediamanager:
`Upload only images when using image dialog: application/pdf`
When I switch off the ckgeditor plugin, everything works.

I've installed your new ckgdoku version. I've tried some changes in .htaccess because of the problematical media manager, but without success.

Regards Juergen

**Comment by turnermm** [comment]
You can't use the CKeditor image dialog to upload anything but images.  To upload pdf files you  have to use the link dialog.  

As s for the second part of this issue, I'm afraid I can't recall where we were on that.  Post it to the original issue. Or reference that issue here.

**Comment by Juergen-aus-Koeln** [comment]
Sorry for misunderstanding! 

But the second part of my issue was to describe details of my installation: I have installed the ckgdoku branch. And here I want to use the native media manager to upload the files. But this fails!

**Comment by turnermm** [comment]
Use the link dialog and select `internal media` from the `Link Type` drop-down menu.  Click `Browse`.  The media manager will open up and from there you will then be able to upload any non-image files accepted by the DW media manager.

**Comment by Juergen-aus-Koeln** [comment]
Thank you, that's the solution
