### ISSUE TITLE
Conflict with datatables plugin

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#272]
Hi,

we use the plugin ["datatables"](https://www.dokuwiki.org/plugin:datatables). When editing a page with ckgedit the syntax becomes currupt:

Before editing:
`<datatable page-length="15" order='[[0, "asc"]]'>`

After editing:
`<​datatable page-length="​15"​ order='​[[:​redaktionssystem:​vorgaben:​terminologie:0_ckgedit_quot_asc_ckgedit_quot|0, "​asc"​]]'>`​

What can I do?

Best regards
Juergen

**Comment by turnermm** [comment]
I made some tests, and with the basic syntaxes there is no problem.  You can insert your tables at the start using native dokuwiki markup.  And you will need the MULTI_PLUGIN macros:
```
~~MULTI_PLUGIN_OPEN~~
<datatables>
^name^|
^First^Last|
|My|Name|
|Your|Name|
</datatables>
~~MULTI_PLUGIN_CLOSE~~ 
```
The above table is taken from the plugin page.  Once the table is established you can add rows, etc.  However, you may run into trouble when you use plugin markup which conflicts with regular expression syntax. Which is the case with the brackets.  

You can also create the table using ckgedit's table tool and then add the datatable markup at top and bottom.  But again there may be syntax conflicts, as mentioned above, and there is nothing that I can do about that.  Your only way around that, if it happens, is to use the include plugin, keeping your datatables in the native dw environment.

**Comment by Juergen-aus-Koeln** [comment]
Ok, thank you! I'll see how to manage it.
