### ISSUE TITLE
Use my own smileys

### ISSUE THREAD

**Issue by diltigug** [turnermm/ckgedit#274]
Hello, I have added the following icons to the DW editor own icons / smileys. 
(https://www.dokuwiki.org/Smileys)
These are not displayed in ckgedit.
How can I add ckgedit new icons or disable existing ones?
Is that possible? I have no guide or hint found for this.

**Comment by turnermm** [comment]
I answered this on the forum:
https://forum.dokuwiki.org/post/55976

**Comment by turnermm** [comment]
I've uploaded a test branch to handle local smileys:
      https://github.com/turnermm/ckgedit/archive/smileys_local.zip
This branch has support for conf/smileys.local.conf.  For this you have to follow Dokuwiki's instructions:
   https://www.dokuwiki.org/Smileys

There are two additional instructions needed for ckgedit. 
1. you must not remove Dokuwiki's `FIXME` and `DELETEME` smileys.  
2. if you are going to include an oversized smiley, then its text format in conf/smileys.local.conf must be all caps and text only, i.e.  no numbers, punctuation, etc., as in  `DELETEME` and `FIXME`    For instance:
```
DONE       local/done.gif  
DRAFT      local/draft.png  
```
![draft](https://cloud.githubusercontent.com/assets/176447/24067753/b9f26542-0b4e-11e7-8867-0bb44a4d7398.png)
![done](https://cloud.githubusercontent.com/assets/176447/24067769/d142b332-0b4e-11e7-8fd5-861427ef3e51.gif)

**Comment by turnermm** [comment]
The test branch has now been merged into ckgedit and includes some improvements to the handling of smileys.
