### ISSUE TITLE
Tables in DokuWiki 

### ISSUE THREAD

**Issue by shalosh** [turnermm/ckgedit#279]
The tables in DokuWiki are often been (self)destroyed by using the editor.
Sometimes a table is splitted into many pieces, mostly if any text-formatting was used and sometimes the text within the table is centered oder right-aligned by its own.

**Comment by turnermm** [comment]
Not enough information.  Give examples, be specific.

**Comment by shalosh** [comment]
For example: I create a table and write text into the table cells. Then I want the text to be in red. I use the color-function of the editor. After saving the table/wiki page the table is destroyed or a row is missing.
Here is an image of how the table may look afterwards: http://www.rp-tools.at/bilder/wiki-error.jpg
It is splitted into two parts. And you can see that in the second part there is some wiki syntax in it now.

Another example: sometimes after I wrote text into the table - after saving the page - the text was centered or right aligned.
In the HTML-Code I could see that the editor added a class like "right-align" (don't know exactly at the moment) to the table cell even if I didn't do any alignment (couldn't reproduce it at the moment, so I don't have an image yet).

**Comment by turnermm** [comment]
The problem appears to be that the parser cannot handle these large blocks of text that have internal selections of font styling.   In smaller blocks there is no problem:  https://www.mturner.org/devel/playground/font_styling_tables. 

Or you can select the entire block and use a font style: https://www.mturner.org/devel/playground/font_styling_tables
You can't put two large blocks next to each other with font styling.  But you can use Dokuwiki's text formatting tools: bold, italic, etc..


See: https://www.dokuwiki.org/plugin:ckgedit:font_styling#combining_font_styles_with_dokuwiki_formats

**Comment by rpatit02** [comment]
hi

when i have a table (let's say 3x3) and i enter text in it, the editor
is not able to handle unnubered lists.

_*here some screencast:*_

https://mega.nz/#!71sSEJLI!s_gepoHwTMZSLf-G_6tiBnFZ0PhrDl8iX3BvNiPPbfE

https://mega.nz/#!z1cDQY4a!i5LbJGIdhYObWdaIpAh68JxQUC4do3Qtttzmad6Isi4


_*current version installed:*_

Installed Version
    2017-03-31
Last Update:
    Tue, 04 Apr 2017 19:01:39 +0200



Mit freundlichen Grüßen / With best regards
 

	


        Sebastian Pippan
        [Systemadministrator / System Administrator]

EDV-Abteilung / IT Department

rpatit02@rcptgroup.com <mailto:rpatit02@rcptgroup.com>
Tel.: 0043 (0) 4245 / 65900
Fax: 0043 (0) 463 / 2655 2629 24
www.rcptgroup.com <http://www.rcptgroup.com>

(Files attached to this mail ending wit ".asc" are public signature PGP-keys
Mails from this address will always be PGP-key signed) 	


        RP Handels und Service GmbH

Gesellschafter / Shareholders: Christian Riegger 51% / Thomas Pichler 49%
Bahnhofstrasse 10, 9711 Paternion, Austria

UID Nr. / VAT No.: ATU64043216
Steuer Nr. / Tax ID: 146/6343
Firmenbuch Nr. / Comm. Register: 308547x
EORI Nr. / No.: ATEOS1000008440
Firmengericht / Company Court: Landesgericht Klagenfurt

	Logo Facebook <https://www.facebook.com/RPTools.at> Logo Wordpress
<http://blog.rp-tools.com> Logo Twitter <https://twitter.com/rp_tools>
Logo Youtube <https://www.youtube.com/user/RPAUSTRIA>

	


        Öffnungszeiten / Business Hours

Mo-Do / Mon-Thu 9:00 – 12:00, 14:00 – 17:00, Fr / Fri 9:00 – 12:00

	

Bank: BAWAG P.S.K.
Empfänger/Beneficiary: RP Handels und Service GmbH
IBAN: AT271400098410010690
BIC: BAWAATWWXXX

	Logo Leitbetrieb
Logo RCPT-Group <http://www.rcptgroup.com> Logo RP-TOOLS
<http://www.rp-tools.at> Logo RP-SOLAR <http://www.rp-solar.at> Logo
ATLANIS <http://www.atlanis.de>

Diese Nachricht ist vertraulich und nur für den Adressaten bestimmt.
Falls Sie diese Nachricht irrtümlich erhalten haben, verständigen Sie
bitte den Absender und löschen Sie diese Nachricht und alle Anhänge.
Soweit gesetzlich zulässig, schließt die RP Handels und Service GmbH
jede Haftung für Schäden aus Übertragungsfehlern, Viren, fremden
Einfluss, Verzögerungen und dergleichen aus.

This message is confidential and intended solely for the addressee. If
you receive this message in error, please immediately inform the sender
and delete the message and any attachments. To the extent permitted by
law RP Handels und Service GmbH shall in no way be liable for any
damages, whatever their nature, arising out of transmission failures,
viruses, external influence, delays and the like.

**Comment by turnermm** [comment]
Dokuwiki doesn't support lists in tables.
