### ISSUE TITLE
New line in table breaks rendering

### ISSUE THREAD

**Issue by thebhushanp** [turnermm/ckgedit#280]
We are DokuWiki(2016-06-26b "Elenor of Tsort") with ckgedit(_ckgEdit-ckedit_457-16-Nov_18-12_04).

Steps to reproduce issue

1. Create Table

1. Set the background color to text of a cell

1. Save it

1. Edit the same table

1. Press Enter in the middle of text

1. Save it

Strange thing is that its rendering correctly in edit mode but in view mode its looks weird.

**Edit Screen**
![edit](https://cloud.githubusercontent.com/assets/6569492/24694017/e839452a-19fd-11e7-8b0d-fbf5bd5d57df.png)

**View Screen**
![view](https://cloud.githubusercontent.com/assets/6569492/24694039/03a54444-19fe-11e7-89a8-d8cf4798e8ab.png)

**Comment by turnermm** [comment]
There is only limited support for font styling in tables.  You can have only one font styling applied in any one cell.   While `Suresh` and `Pati` have the same styling they are on separate lines and  have most likely been styled separately.  Font styling is not native to Dokuwiki and complex stylings and stylings in things like tables and links may either break the output or not work as expected.
For some examples of tables and styles see:  https://www.mturner.org/devel/playground/font_styling_tables
For  documentation see: https://www.dokuwiki.org/plugin:ckgedit:font_styling
