### ISSUE TITLE
Image titles when hovering (or call it tooltip) erased by saving page with ckgedit

### ISSUE THREAD

**Issue by Funkychunk** [turnermm/ckgedit#281]
Hey, this Plugin is a great complement to DokuWiki, mostly used by our salesperson or employees, who don´t have programming experience. 
We are only desktop-developers in this company, so please be merciful if I´ll lack knowledge.
I couldn´t find the following problem or issue in my research. 

In our wiki, we have one big page with a high number of links for different options.
I have to set an image with a specific hovertext in front of every option.
When I save the page with the ckgedit, all of my hovertexts get erased, even though the ckgedit shows it correctly when editing.
I tested this with the following example to exclude mistakes or errors in the page itself:

{{:public:mynamespace:overall:iconlokal.ico?20x20|Hovertext}}

After saving the page without any changes, the code behind changes into following:

{{:public:mynamespace:overall:iconlokal.ico?20x20}}

The only idea I have thought of, is the setting "Activate algorithm for complex tables by default ...."; but changing this Setting seems to have no effect.
We are
using Release 2017-02-19b "Frusterick Manners"
using ckgedit 4.5.7

if I downgrade to 4.5.1 manually the behaviour will not change. But I could swear, a few weeks ago there was a similar problem solved by an Upgrade.
The image always existed and was shown while testing.

Thanks in advance for any help!

**Comment by turnermm** [comment]
The link  type for the image must be set to either `detail` or `direct`.  When it is, then the hover text will be the name of the image.  There is no way in ckgedit to insert an alternate name for the hover text.

**Comment by Funkychunk** [comment]
Thanks for this fast reply.
But there is no need to set the hovertext with ckgedit.
I only want ckgedit not to delete it, when i save the page.

In editing mode, the ckeditor also can show the hover text I set with DW editor.
The resulting problem is, that the default editor ist ckgedit and when i change to DW editor, it seems to save the page, not considering if there are changes.
Any time a developer changes to DW editor, the page needs a rework, because all hovertexts got erased.

Like i wrote, iam not a web developer. But I would wonder, if the code for saving the page with ckgedit cannot account that.

If there is no chance to fix this, just let me know and close this issue.

Thanks.

**Comment by turnermm** [comment]
> But there is no need to set the hovertext with ckgedit.
> I only want ckgedit not to delete it, when i save the page

The amount of work involved is essentially the same. I'll take this as a feature request.

**Comment by turnermm** [comment]
I seem to have a solution for this sooner than expected.  Try this:
https://github.com/turnermm/ckgedit/archive/imgtooltip.zip
Let me know if it works for yhou.

**Comment by Funkychunk** [comment]
I just tested it a few minutes ago and it works pretty well.
Thank you very much, your help saved me much time!

**Comment by turnermm** [comment]
I've merged the tooltip branch into the master, so it can be updated in the normal way.  I'll leave this issue open for a while, just in case you have anything further to report.
