### ISSUE TITLE
Save and delete button event?

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#284]
HI , I want to save button and delete are clicked beside save content (origin event) and post a message(include article name and writer name) to my server .
Where I can modify to add event? 
By the way, when wiki content in null ,save button will judgment this article be deleted. Where is this Conditional  in .

**Comment by turnermm** [comment]
There is no event.  You would have to do this with javascript in an Ajax call.  You can use Dokuwiki's own ajax protocol (https://www.dokuwiki.org/devel:event:ajax_call_unknown) or your own ajax function.  You would best make the ajax call from the jQuery function which is called when the save is made.  This is found at line 1949 of `scripts/parse_wiki.js.unc`.  You would want to make your call here (line 1955):
```
   else {
/* you ajax call here */
    parse_wikitext('edbtn__save');
   } 

```
Then parse_wiki.js.unc must be renamed `parse_wiki-cmpr.js`,  and if you can, you should then compress it, which is what the cmpr means.  You can save the data that you want to write to your disk in the JSINFO array, which you can set in php as $JSINFO and which will then be passed into javascript as JSINFO. See:
  https://www.dokuwiki.org/devel:javascript?s[]=jsinfo#jsinfo
The file `parse_wiki,js.unc` is automatically used when the $test property of the edit class is set to true.  This is found near the top of action/edit.php.  When you set $test to true, you will get a new button `Test`.  This is used for debugging.  When you turn off testing `parse_wiki.cmpr.js` is used.

**Comment by qwe852147** [comment]
It works but I want to know the article will be delete or save when save button is clicked (content is null the save function willdelete article)

**Comment by proxymus** [comment]
This is the dokuwiki default. An empty article will be deleted when you save it.

**Comment by qwe852147** [comment]
Thanks! I write the function I want in common.php to solve my problem
