### ISSUE TITLE
Table is broken when saved

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#285]
I try to create table which has two rows and five column , and first 、second、third column which rowspan is 2.
it html code is 
```
<table style="width: 500px;">
	<tbody>
		<tr>
			<td rowspan="2">123</td>
			<td rowspan="2">123</td>
			<td rowspan="2">123</td>
			<td>123</td>
			<td>123</td>
		</tr>
		<tr>
			<td>456</td>
			<td>456</td>
		</tr>
	</tbody>
</table> 
```
and I hope it result look as 
```
|   |   |   |123|123|
|123|123|123|---|---|
|   |   |   |456|456|

After I saved ,it show 
|   |   |123|123|123|
|123|123|---|---|---|
|   |   |456|456|   |
```

I don't know what happen....I think it a complex table problem

**Comment by turnermm** [comment]
You can solve this problem by using the HTML_BLOCK feature.  See:

https://www.dokuwiki.org/plugin:ckgedit#html_blocks
https://www.dokuwiki.org/plugin:ckgedit:configuration#htmlblock_ok

HTML_BLOCKs are saved as HTML and can be loaded back into the ckgeditor and edited and re-saved.  Please take note of the htmlblock_ok config option which must be set to true.

**Comment by qwe852147** [comment]
I just paste HTML to describe the table.

I use ckgeditor table tool to draw my table then it happend .
I find this situation happend when ckgeditor parse table content to wiki syntax.

**Comment by turnermm** [comment]
Download the latest version of ckgedit. The follow the instructions in my preceding post, make sure to set the new config option  `htmlblock_ok` to true.

Then create your table using the ckgeditor. Then place the table between  `HTML_BLOCK`s. 
![htmlokbllock](https://cloud.githubusercontent.com/assets/176447/25260396/7e6bb4aa-2611-11e7-931f-eafab48ac199.png)

 Then save.

**Comment by qwe852147** [comment]
Thanks , it work .
But it is inconvenient to writer , they should know this solution to solve complex table.

It's possible to merge to complex table option?
When parse table auto add ~start_html_block~ and~close_html_block~ ,if complex table option is true .

**Comment by turnermm** [comment]
> t's possible to merge to complex table option?

I'm afraid not.  Most of the time it's not needed.

**Comment by qwe852147** [comment]
Thanks, I think it can let user do not  care what time the table should add this tag .
