### ISSUE TITLE
add option to disable double-click function to open dw editor

### ISSUE THREAD

**Issue by Finkregh** [turnermm/ckgedit#289]
i would like to have a option to disable the doubleclick function introduced in commit 1647d3ea2e818505e7c5ae4055b276f19557dea4

**Comment by turnermm** [comment]
I should have thought of that.  You could roll back to the previous commit and I'll let you know when I get this done, but I'll get to it very soon.

**Comment by turnermm** [comment]
I have decided on an alternative to a new configuration option, because there are already too many.  Instead, in conf/userscript.js, place the following line:  
    `JSINFO['dbl_click_auth']  = "";`
If conf/userscript.js doesn't exist, create it.

**Comment by Finkregh** [comment]
ok, thanks so far :+1:

**Comment by Jerk31** [comment]
Thanks for the quick option fix. From a global point of view I'm a bit surprised of this modification which has impacts everywhere in Dokuwiki by default even if you don't use CKGEdit as a default editor...

I'd go for a disable of this feature by default and adding an option in the configuration page even if there are already too many to enable the feature.

Thanks.

**Comment by turnermm** [comment]
If you can show me an example of impacts, I'll make a change.

**Comment by Finkregh** [comment]
Very often people try to mark text by double-clicking it. This is impossible now. :cry:

**Comment by naujoitsc** [comment]
Yes, this "feature" fck me often up...
Please add a config option to disable this "feature"

**Comment by turnermm** [comment]
```in conf/userscript.js, place the following line:
JSINFO['dbl_click_auth'] = "";
If conf/userscript.js doesn't exist, create it.
```
That will do the trick until I decide how else to deal with it.

**Comment by turnermm** [comment]
See https://github.com/turnermm/ckgedit/archive/_tmp.zip, and the new config option.  Let me know if this works for you so that I can merge it into the master distribution

**Comment by turnermm** [comment]
Closed by accident.  Any feedback yet?

**Comment by turnermm** [comment]
Feedback please!

**Comment by naujoitsc** [comment]
Hi, I tested the new version and it works perfectly.

Thanks for the new option.

**Comment by turnermm** [comment]
Thanks for the feedback.  I will put it into the standard version in the next little while, so you will always be able to update.

**Comment by ericb-summit** [comment]
The modification suggested above doesn't work and the double click still is processed.  I want to disable this double click "feature".  How can I do this on the latest version?

**Comment by turnermm** [comment]
https://www.dokuwiki.org/plugin:ckgedit:configuration#dblclk

This should work unless it is cut short by one of your other plugins or your template. 
 See:  https://mturner.org/devel/doku.php?id=wiki:welcome
