### ISSUE TITLE
code cannot be multiline

### ISSUE THREAD

**Issue by kaiaeberli** [turnermm/ckgedit#291]
Hi,

i tried creating codeblocks that are multiline, but it only ever allows one line. Pressing enter just goes to the next row, but its not a code anymore.

**Comment by kaiaeberli** [comment]
never mind, found it: shift enter works

**Comment by turnermm** [comment]
Fixed a bug this morning:  I had hard-coded 'java' into the geshi codeblock form, making all codeblocks I java formatted.

**Comment by kaiaeberli** [comment]
btw: i just checked again: if i try to write '<code python> some code </code> it ignores linebreaks again an d instead shows backslashes

\\  \\ output = [p.get() for p in result] \\  \\

**Comment by kaiaeberli** [comment]
i tried using Geshi plugin to create a codeblock, and it works, but when i reopen the table to edit, it has dissappeared. When i then go on to save, it is disapeared permanently.

**Comment by turnermm** [comment]
https://www.dokuwiki.org/plugin:ckgedit#geshi_plugin

**Comment by kaiaeberli** [comment]
ok thanks, didnt know that.

**Comment by kaiaeberli** [comment]
is there any chance of getting code blocks to work in a table? It is such a useful feature - i store all my code snippets like this.

**Comment by turnermm** [comment]
I&all have to see

**Comment by kaiaeberli** [comment]
thanks

**Comment by turnermm** [comment]
Try this: https://github.com/turnermm/ckgedit/archive/bintbl.zip
It handles basic code/file blocks and geshi code/file blocks, but as yet does not handle code snippets.

**Comment by kaiaeberli** [comment]
it works to the extent that it doesnt remove the code blocks i create manually in the table by modifying the html. However, when creating a code section and pasting into it, it just moves below the table upon saving. I checked the html, and it does create a <pre> section, but does not add class="code".

**Comment by turnermm** [comment]
It has to be used with the the tools provided by ckgedit.  Create a table using the table tool and insert your code blocks using the code tool or the geshi tool.  As of this morning you can also insert code snippets.

**Comment by turnermm** [comment]
Here is a video showing snippets and code blocks, created and saved:

https://www.youtube.com/watch?v=0Filj05Df6s

**Comment by kaiaeberli** [comment]
ok i see - thanks very helpful!
