### ISSUE TITLE
Entities issue

### ISSUE THREAD

**Issue by krakorj** [turnermm/ckgedit#294]
https://www.dokuwiki.org/plugin:tag plugin allows user to list articles related to a specific tag. I use the plugin filter to exclude tag names from the list (parameter `&notags`).  The control used:

```
{{topic>tag1 tag2&nodate&notags}}
```

The issue is the Ckedit allows me to add the control to the article text but when the text is edited again the control is corrupted. The parameter `&notag` is interpreted as 'negative' symbol &not; so the corrupted string output is like this:

```
{{topic>tag1 tag2&nodate-,ags}}
```

The meaning of the HTML entity `&not;` is clear for me. The same situation happens when the text includes something like `&not...`

**Comment by turnermm** [comment]
Unfortunately, the Ckeditor is making this conversion.  Until I look at this more closely, you will have to edit the syntax each time you reload the page into the Ckeditor.  You should probably also subsitute at least `ent.ser` from the attached zip file for the one currently in action/entities.  This will insure that the syntax wll always save correctly, once it has been re-edited.
[ENTITIES.zip](https://github.com/turnermm/ckgedit/files/990358/ENTITIES.zip)

**Comment by turnermm** [comment]
There is a work-around. Instead of:
`{{topic>download tables symlinks&nodate&notags}}`
use:
`{{topic>download tables symlinks&nodate& notags}}`

Leave a space between the `&` and `notags`.  The Ckeditor will ignore the entity and the tags plugin will still recognize the the `notags` flag.

**Comment by turnermm** [comment]
I may automate this in the next update.

**Comment by krakorj** [comment]
Perfect, thank you at least for the work-around.
