### ISSUE TITLE
Failure of Ajax request in config.js

### ISSUE THREAD

**Issue by christianh95** [turnermm/ckgedit#295]
In config.js.unc, line 238 (respectively in config.js) there is an error in `top.DOKU_BASE + '/lib/exe/ajax.php',`. The URL that is requested is just `http://lib/exe/ajax.php[...]` (the host is missing).

A temporary solution is to replace the `top.DOKU_BASE` by an empty `""`. Otherwise the Editor shows a popup saying "error" and in the browser devtools you can see the failed request to http://lib/...

**Comment by turnermm** [comment]
See this: https://github.com/turnermm/ckgedit/pull/296
