### ISSUE TITLE
DW Edit Cause Content Delete with "False" Statement

### ISSUE THREAD

**Issue by PaulLangham** [turnermm/ckgedit#302]
Since I have upgraded CKGEdit for Dokuwiki every time I start and edit and click on the DW Edit button it removes all the content on the page and simply displays "False" at the top of the page. I have to restore from a revision to get the content back.

I am using using:

- Release 2017-02-19b "Frusterick Manners"

- Latest Chrome

- Windows 8.1

I have also disabled and re-enabled CKGEdit, any suggestions? 

I have read lots about potential browser/java issues but it doesnt work in IE/Chrome or Firefox.

**Comment by turnermm** [comment]
You say 'upgraded"--was it working before the upgrade?  

I can't reproduce  this, using the latest Chrome and Frusterick.  It's a javascript error.  Are you able to check for errors?  If so, check and report back.

**Comment by PaulLangham** [comment]
Well I "updated" CKGEdit today and tried to edit a page and thats when I get the issue.

Where would you like me to glean any errors from?

I havent installed any new plugins for a few weeks and it was working however the server was rebooted this week which would have forced the apache services to restart which might be a factor.

**Comment by turnermm** [comment]
You can do two things.  First you can click on F12 and then click  on the console and make sure that it is showing errors.
![chrome_dbg](https://cloud.githubusercontent.com/assets/176447/26733960/1e60d242-4782-11e7-8257-57d2aa851f6f.png)
If nothing shows there, then check the apache error logs.

**Comment by turnermm** [comment]
You might also try clearing out the browser cache and the dokuwiki cache (data/cache).

What OS is  your browser on and what OS runs apache?

**Comment by turnermm** [comment]
Were there any errors prior to these?  If there were, then scrollbars should appear and you can scroll up.  The errors that you are showing are probably the result of an error which occurred before these.

**Comment by PaulLangham** [comment]
There are no scrollbars suggesting previous activity but I ran the edit task again and got these errors reported. This is clicking on the DW Edit button on my doc.

![image](https://cloud.githubusercontent.com/assets/29144846/26783843/37119b06-49f2-11e7-8c69-1e6a8968517d.png)

**Comment by turnermm** [comment]
The type error wouldn't cause a crash.  And the 'reset' that is being referenced here is part of the Dokuwiki core, so it does exist.  And  unsetDokuWikiLockTimer() has been part of ckgedit for many years now.  So something else is happening which isn't showing up.  You could try going back to an earlier version.  I suggest this:
   https://github.com/turnermm/ckgedit/tree/939f46189503
Or  you could try a version which has not been released yet but which has the most recent version of the CKEditor, and if it is a problem arising from CKEditor, then this might fix it:
    https://github.com/turnermm/ckgedit/archive/cked_4.7.zip
Either of these can be installed using the manujal install tab of the  Extension manager.

**Comment by PaulLangham** [comment]
This is what I am getting prior to clicking on the DW Edit button when in simple edit mode:

![image](https://cloud.githubusercontent.com/assets/29144846/26829959/35b5b206-4abf-11e7-93cb-87b191f5ac6d.png)

**Comment by PaulLangham** [comment]
Tried the unreleased version and still the same False statement presented.

**Comment by turnermm** [comment]
Did you try the earlier version?

https://github.com/turnermm/ckgedit/tree/939f46189503

**Comment by PaulLangham** [comment]
The older version states: "Header does not match it's checksum"

**Comment by turnermm** [comment]
Just give it a try. Or download it again.

**Comment by turnermm** [comment]
I downloaded it to windows and unzipped it there and also on linux and no problems.  So just downlaod it again.

**Comment by PaulLangham** [comment]
Installed older version and still the same issue?

Its very strange, has been working for weeks with no issues.

**Comment by turnermm** [comment]
Remove all other plugins that don't come bundled with dw.
		

		Get Outlook for iOS
	





On Tue, Jun 6, 2017 at 9:36 AM -0500, "PaulLangham" <notifications@github.com> wrote:












Installed older version and still the same issue?


Its very strange, has been working for weeks with no issues.

**Comment by PaulLangham** [comment]
My only issue with that is is that I have not installed any plugins for weeks and its been operational in that time?

**Comment by turnermm** [comment]
Install a fresh test dokuwiki and install only ckgedit.  If it works, then there is a problem in your other wiki.  If not, then when you apache restarted, an updated php may have been installed which has  incompatibilities with  your other  plugins and/or ckgedit.  However ckgedit has been tested on all php platforms from 5.3 to 7.0.

**Comment by PaulLangham** [comment]
I eventually found the fix for this... after renaming the cache file (apps\dokuwiki\htdocs\data\cache) and restarting apache the cache folder was re-created and editing functions were restored.
Thanks for your efforts in this, they were much appreciated.

**Comment by turnermm** [comment]
I did  suggest earlier that you clear out data/cache.  Perhaps you didn't realize what I meant, which is to delete all of the files and folders in data/cache.  If  you did that, you should have gotten the same result and if not then that is very strange.

**Comment by PaulLangham** [comment]
Ah yes I see that now... or it makes more sense now, I assumed you ment the local cache.

**Comment by thommierother** [comment]
I see the same error in a fresh installation the latest dokuwiki an ckgedit installation with cleared dokuwiki cache. Therefore we had to deinstall the plugin on our productive wiki.  The basic machine is ubuntu 18.x with apache and php 7.3. Please give me some hints to assist further debugging

**Comment by turnermm** [comment]
What template are you using?

**Comment by thommierother** [comment]
current bootstrap3 from https://www.dokuwiki.org/template:bootstrap3. I have this effect in two installations, sometimes pages can not be edited at all within ckgedit, it looks like some Browser-side javascript error, although I did not check the local debug tools yet (FF 66.x)

**Comment by turnermm** [comment]
This problem with bootstrap3 was reported on the forum, and there is a fix for it.  I've just been waiting for a confirmation before merging the fix into the master copy of ckgedit.   See  
                                   https://forum.dokuwiki.org/post/65866.
The link to the fix is:  https://github.com/turnermm/ckgedit/archive/html5_err.zip

**Comment by thommierother** [comment]
OK, I added the html5_err.zip fix, will do a little testing the next few days and let you know about the results

**Comment by thommierother** [comment]
Tested the fix on two dokuwikis, i still have "blocking edits" and deleted code (replaced by "_false_") in ckgedit, html5_err.zip does not fix the problems with bootstrip3 IMHO

**Comment by turnermm** [comment]
Did you delete the entire cache from the dokuwiki cache folder?   What is on the files which  you are trying to save?  Can you zip up a copy and attach it here? What OS are you on? What javascript errors are you seeing?  And does the error persist if you test on the default dokuwiki template?  Also, I assume you haven't installed any plugins, since these are 'fresh' installs?

**Comment by thommierother** [comment]
issue seems to be fixed, closing is ok ;-)
