### ISSUE TITLE
nested list is lost on save

### ISSUE THREAD

**Issue by kaiaeberli** [turnermm/ckgedit#303]
Hi,

when using the nested list button to indent a line, it shows up in html with a 40px margin, and correctly indents. However, when saving the indent is lost, and the class is removed from the html. I tried installing the tab and wrap plugins like you mentioned elsewhere, but it didnt work. To clarify: I just indented a normal line of text, it was not part of a list. My goal was to create indents without showing bullets or numbers.

Regards,
Kai

**Comment by turnermm** [comment]
I believe I anwered this via email.  You can't indent a line: dokuwiki sees indented lilnes as code and ckgeditg strips away all leading spaces.
