### ISSUE TITLE
Want to get old version

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#304]
Excuse me .
There has old version of this plugin can to download?
The version I want is following 
![ckeditor-version](https://cloud.githubusercontent.com/assets/10329643/26823680/0c383ca6-4ae1-11e7-9c1f-5fc3b471ede2.JPG)

I have modified some code of it .
I want to add it to git to control version but I cannot find it to download now.

Can you provide this version file for me?

**Comment by turnermm** [comment]
https://github.com/turnermm/ckgedit/archive/29ac9591c8c02f5608bf5bf1237fbf286fd77024.zip

**Comment by qwe852147** [comment]
Thanks!!!
