### ISSUE TITLE
config.js loads with wrong urls

### ISSUE THREAD

**Issue by boontwiks** [turnermm/ckgedit#307]
The ckgeditor/config.js file loads some extra files at the url `window.location.protocol + "//" + top.dokuBase + whatever`. This is inherently incorrect, and should be simply `top.dokuBase + whatever`, as the dokuBase already includes the protocol.

For a quick hotfix, how do I remove the timestamp feature to load the updated file?

**Comment by turnermm** [comment]
That in fact isn't  correct.  See  https://www.dokuwiki.org/devel:environment?s[]=doku_base
`dokuBase` is then re-defined in script.js to include the domain.  Hence `window.location.protocol + "//" + top.dokuBase `.
If you are having a errors with this post them here.  See: https://github.com/turnermm/ckgedit/pull/296
