### ISSUE TITLE
Paste image from Clipboard not working

### ISSUE THREAD

**Issue by dziemann** [turnermm/ckgedit#310]
I tried with Chrome 58 and FireFox 53. With both pasting images into the editor doesn't work. 

Tried it with the imgpaste plugin and the original dokuwiki editor and it works.

**Comment by turnermm** [comment]
Works in firefox, not in recent Chrome.
http://www.youtube.com/watch?v=XkrS5lfRmAc

**Comment by dziemann** [comment]
Sorry! Tested with the latest Firefox and is not working. I believe you, it should. But for me it's not.

**Comment by turnermm** [comment]
Out of curiosity:  what Operating System is your Firefox running on?

**Comment by dziemann** [comment]
It's running on Windows 10 - latest build

**Comment by turnermm** [comment]
And the CKEditor's paste tool?

**Comment by turnermm** [comment]
The latest ckgedit has a new CKEditor plugin which enables copy and paste in most browsers.  I've tested Chrome, FF, Opera.  The image has to be copied from a source which enables image copy, i.e. you can't click copy in a file listing: you have to open the image and copy it.

**Comment by dziemann** [comment]
Thank you! Will give it a try!
