### ISSUE TITLE
A problem about insert  internal link

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#311]
I insert two link in my article and I remove the space between two link example following image
before
![01](https://user-images.githubusercontent.com/10329643/27315945-45cf14d4-55af-11e7-8941-2469f70b1550.JPG)
after
![02](https://user-images.githubusercontent.com/10329643/27315943-45c90878-55af-11e7-93d7-1a10c1de77de.JPG)

Then after I saving the first link will be remove .
![03](https://user-images.githubusercontent.com/10329643/27315981-8c11f5f6-55af-11e7-8872-c680528ac83a.JPG)

It has any solution?

**Comment by turnermm** [comment]
After the first link is created, the CKEditor still treats whatever follows as part of the link,  You can see this if you check the link tools, you can see that after creating your link the `Unlink` tool is selected, as in the right-hand image: 
![link_buttons](https://user-images.githubusercontent.com/176447/27332584-f44fd00c-5587-11e7-8205-8c8c0fe4f9de.png)
This means that CKEditor considers the space following the link as part o f the link.  So, the first thing to do is to click on the unlink tool, and then move two spaces over to the  right and create your next link.  

![side_by_side_links](https://user-images.githubusercontent.com/176447/27332773-e3ae19a6-5588-11e7-9053-c503d73f2999.png)

**Comment by qwe852147** [comment]
Thanks! 
But there has any solution to do without space? 
I implement batch insert multi link.
After links being inserted , there have not any space between then .

**Comment by turnermm** [comment]
I don't think so.  You can try to experiment with the CKEditor.  If you are batch inserting, then there must be some code, and you should be able to code two spaces between each insertion.

**Comment by qwe852147** [comment]
It works. Thank your suggestion
