### ISSUE TITLE
The plugin breaks Dokuwiki after upgrade to 2017-06-01

### ISSUE THREAD

**Issue by pbychikhin** [turnermm/ckgedit#313]
Hi,
I've upgraded to the latest version 2017-06-01.
Now I only see a blank page,
Here is the log:
PHP Fatal error:  Call to a member function getConf() on a non-object in /var/lib/dokuwiki/app/lib/plugins/ckgedit/action/meta.php

**Comment by pbychikhin** [comment]
PHP Fatal error:  Call to a member function getConf() on a non-object in /var/lib/dokuwiki/app/lib/plugins/ckgedit/action/meta.php on line 649

**Comment by turnermm** [comment]
First, This confuses me.  If you are having this error then it must be version 2017-06-19.   In this case you should be able to eliminate the error by installing the wrap plugin from Dokuwiki:    The wrap plugin page: https://www.dokuwiki.org/plugin:wrap.  You can install wrap using the search function of the extension manager.  

If you don't want the wrap plugin, you can temporarily remove this error by installing this version of ckgedit: 
https://github.com/turnermm/ckgedit/releases/tag/pre_wrap

**Comment by pbychikhin** [comment]
Thank you a lot for the hint about the Wrap plugin. I didn't know I need it.
Now everything works.
When I said 2017-06-01 I meant the version of ckgedit, which is available in the Plugin Manager.
