### ISSUE TITLE
video can not delete

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#315]
I insert video by internal media .
After saving , it auto convers to screen not a hyperlink like following image
![123](https://user-images.githubusercontent.com/10329643/27951853-e4375014-6338-11e7-8c62-db5c9bfc173a.png)

Then  I want to delete the video . I find I can not delete it  by keyboard include backspace  and delete key.

**Comment by turnermm** [comment]
I have trouble following this. Are you using the link tool?

**Comment by qwe852147** [comment]
Yes , I use the link tool to put the internal media .

**Comment by turnermm** [comment]
Are you aware of this, from conf/mime.conf?
```
# . . . Mimetypes that should be downloadable and not be opened in the {browser]
# should be prefixed with a !

```

**Comment by qwe852147** [comment]
This is my situation
I modify conf/mime.conf to enable upload video(.mp4).
And I can insert video to page with link tool .
But after inserting and saving , I can't remove it when edit mod.

The conf/mime.conf mean we can't insert video with link tool? or need to do something before insert?

**Comment by turnermm** [comment]
For Dokuwiki, you have to place an exclamation mark in front of your mimetype:  `mp4     !video/mp4`
Then it can be downloaded but will not open in the browser.  But the CKEditor doesn't understand that and so it  plays the video.  To delete it you will have to switch to DW Edit mode.

**Comment by qwe852147** [comment]
I try to do this then I find "mp4  !video/mp4" is not working but "!mp4  video/mp4" is work to provide only download feature.

**Comment by qwe852147** [comment]
Then I find the ckgedit does not include mime.cof?
I remove  mp4 !video/mp4 from mime.cof  then dokuwiki media manager can not upload but ckgedit can do it

**Comment by turnermm** [comment]
> I remove mp4 !video/mp4 from mime.cof then dokuwiki media manager can not upload but ckgedit can do it

ckgedit has its own list of allowed extensions which it adds to those in mime.conf.  The mp4 extension is one of those.

**Comment by qwe852147** [comment]
Thanks !When the situation heppend, I had consider I generate some bug after I modifying code
