### ISSUE TITLE
double Headline

### ISSUE THREAD

**Issue by tegger2000** [turnermm/ckgedit#316]
I got double Headers when i going to edit a page

the source is then :
```
<h1>Header</h1>

<p>====== Header ======</p>
```

Dokuwiki is Release 2017-02-19b "Frusterick Manners"

**Comment by turnermm** [comment]
How are you entering the headers into the CKEditor?

**Comment by tegger2000** [comment]
this happen on all pages, the old, with dokuwiki style (=== XXX  === ) and also a new page created with  CKEditor, with the "same level header" Button.

**Comment by turnermm** [comment]
I've never seen this before and can't reproduce it.

**Comment by tegger2000** [comment]
I don't use it active, the CKEditor create it.... when i change to DW Edit, it is

`====== Header ======

====== Header ======
`

could there be a config conflict ? The Problem is the same with Windows IIS7,8 and nginx on ubuntu

**Comment by tegger2000** [comment]
i tried a new blank installation, i got errors, but it seems to be working correct, maybe a conflict with an other plugin

> Unable to create flash link: C:\inetpub\wwwroot\dokuwiki_test\lib\plugins\ckgedit\fckeditor\userfiles\flash
> Unable to create image link: C:\inetpub\wwwroot\dokuwiki_test\lib\plugins\ckgedit\fckeditor\userfiles\image
> Unable to create media link: C:\inetpub\wwwroot\dokuwiki_test\lib\plugins\ckgedit\fckeditor\userfiles\media
> Unable to create file link: C:\inetpub\wwwroot\dokuwiki_test\lib\plugins\ckgedit\fckeditor\userfiles\file
> There was an error when trying to create symbolic links in C:\inetpub\wwwroot\dokuwiki_test\lib\plugins\ckgedit\fckeditor\userfiles\

**Comment by tegger2000** [comment]
it seems to be  reveal.js
https://www.dokuwiki.org/plugin:revealjs

**Comment by turnermm** [comment]
So reveal is what is causing the duplications?
As for the link warnings, that is probably because you are using Windows in a version that doesn't allow the browser to make symbolic links, probably Window 10, because they require an administrative user. That normally does not affect ckgedit in Windows.

**Comment by tegger2000** [comment]
yes, CKEditor creates double headers with reveal installed.

the link warnings are with Windows Server 2008R2 and 2012R2. where should the symbolic link point to ?

**Comment by turnermm** [comment]
Data\media

**Comment by tegger2000** [comment]
So this should be workling ?
```
mklink /D C:\inetpub\wwwroot\dokuwiki\lib\plugins\ckgedit\fckeditor\userfiles\flash C:\inetpub\wwwroot\dokuwiki\data\media
mklink /D C:\inetpub\wwwroot\dokuwiki\lib\plugins\ckgedit\fckeditor\userfiles\image C:\inetpub\wwwroot\dokuwiki\data\media
mklink /D C:\inetpub\wwwroot\dokuwiki\lib\plugins\ckgedit\fckeditor\userfiles\media C:\inetpub\wwwroot\dokuwiki\data\media
mklink /D C:\inetpub\wwwroot\dokuwiki\lib\plugins\ckgedit\fckeditor\userfiles\file C:\inetpub\wwwroot\dokuwiki\data\media
```

**Comment by turnermm** [comment]
Looks right
