### ISSUE TITLE
Editing with ckgedit erases data generated by struct plugin

### ISSUE THREAD

**Issue by kulaw327** [turnermm/ckgedit#317]
With ckgedit, I Tried to edit pages that include structured data generated by the struct plugin.

When I change DW mode to CKG mode, the structure data disappears. Even if I change CKG mode to DW mode, the data remain to be gone. (of course, I could revive the data in the revision history. 

How can I make ckgedit work with struct plugin?

**Comment by turnermm** [comment]
Probably you can't. Try using the include plugin.

**Comment by turnermm** [comment]
See if this helps:
https://www.dokuwiki.org/plugin:ckgedit:discussion_2#configuration_to_use_different_editors

**Comment by Juergen-aus-Koeln** [comment]
I also want to use the struct plugin in combination with ckgedit. But your hint above refernces to the data plugin. So, do you have another tip?

**Comment by turnermm** [comment]
It's the same.

**Comment by Juergen-aus-Koeln** [comment]
Unfortunately not: ~~MULTI_PLUGIN_OPEN~~ and ~~MULTI_PLUGIN_CLOSE~~ can't be used for the struct data.

**Comment by turnermm** [comment]
I'm afraid I have no solution at the moment and you will have to use the include plugin.

**Comment by Juergen-aus-Koeln** [comment]
Ok, thank you anyway

**Comment by mschlenstedt** [comment]
Using Include plugin do not help unfortunately. The struct data itself will be erased from the database if you save the page in CKGEditor.
