### ISSUE TITLE
ckedit doesn't work after last upgrade.

### ISSUE THREAD

**Issue by aelsantex** [turnermm/ckgedit#318]
Hi, after last upgrade (24 Jun) of ckgedit it doesn't work.
I reverted on previous version.

I haven't error on apache log...

**Comment by turnermm** [comment]
What is the previous version?

**Comment by kaiaeberli** [comment]
having the same issue - I get a blank screen when editing. I went back to the pre wrap version which seems to work. 

However, with this version I have the issue that when modifying and then saving a page with some paragraphs <p>, it will just drop the <p> so the contained text becomes inline. For example:

<div class="level2">
<p>- <b>someheader:</b><br />
sometext.</p>

<p>- <b>someheader</b><br />
sometext(<a class="urlextern" href="http://www.cs.toronto.edu/~fritz/absps/imagenet.pdf" rel="nofollow" title="http://www.cs.toronto.edu/~fritz/absps/imagenet.pdf">http://www.cs.toronto.edu/~fritz/absps/imagenet.pdf</a>).</p>

**Comment by aelsantex** [comment]
I have the same problem of kaiaeberli.
Regards!


2017-07-31 12:41 GMT+02:00 kaiaeberli <notifications@github.com>:

**Comment by turnermm** [comment]
1. @aelsantex, you don't say what your previous version is.
2. @kaiaeberli  You can't just enter HTML directly into the cgkedit editor.    For that you have to use ckgedit's HTML blocks:  https://www.dokuwiki.org/plugin:ckgedit#html_blocks

**Comment by turnermm** [comment]
@aelsantex:  what same problem?  That the page crashes?  That you are also directly embedding html into your  pages?

Neither of you have said anything about what browsers you are using and on what operating systems?  And have you checked for javascript errors?

**Comment by jmcbain** [comment]
This is kind of a similar issue so I'll post it here:

Release 2014-05-05a "Ponder Stibbons"
(I know it is not technically supported)
Browser: Google Chrome 59.0.3071.115
When clicking edit page, the editor does not display. The "Save, Delete DW Edit, Cancel.... Editor Height etc." load but the editor does not display.

![wiki_nocontent](https://user-images.githubusercontent.com/30605352/28797090-a9f2e884-7605-11e7-9a1c-3a922a2efcbb.JPG)

This is an error message in chrome dev tools that shows when I attempt to load the page:
config.js?t=G14E:1 Uncaught TypeError: top.hasTags is not a function
    at a.CKEDITOR.editorConfig (config.js?t=G14E:1)
    at l (ckeditor.js:243)
    at Object.<anonymous> (ckeditor.js:243)
    at Object.callback (ckeditor.js:231)
    at f (ckeditor.js:229)
    at Array.x (ckeditor.js:229)
    at A (ckeditor.js:229)
    at ckeditor.js:230


The page / editor works successfully in Firefox 54.0.1.6388

**Comment by turnermm** [comment]
@jmcbain this doesn't really belong here.  It's a different issue.  

The problem is a caching issue.  `top.hasTags()`  has been replaced by  ` top.JSINFO['has_tags']`
Consequently, it isn't being found by the Chrome javascript parser, which thinks you still have the old javscript files.  Clear the cache:  `Ctrl+Shit+Delete.`

**Comment by jmcbain** [comment]
@turnermm Caching - I apologize for wasting your time and cluttering your thread! Thank you very much.

**Comment by turnermm** [comment]
@jmcbain All in a day's work.
