### ISSUE TITLE
How to disable Urlencoded substitution?

### ISSUE THREAD

**Issue by boqa** [turnermm/ckgedit#323]
Hi,

I'm using CKGedit (_ckgEdit-ckedit_457-17-May_19-20_06) for my dokuwiki (dokuwiki 2017-02-19b "Flusterick Manners").

I wish to copy-paste various links containing urlencoded characters, an example could be 
http://www.test.com%26testsite

If I copy-paste that link from my browser and directly into a page being edited by ckgedit, the resulting link will be "http://www.test.com&testsite", i.e. the %26 is substituted by &. This would normally be correct and work fine, but I have a number of links where the unicode cannot be substituted if the links are to work.  
When I use DW Editor, no substitution takes place and thus the links are working (but I prefer to use ckgeditor if possible).

Thus, how can I disable this "feature", such that when I copy-paste a link containing unicode characters, they will STAY urlemcoded characters in the resulting links?

Alternatively, can you point me to where in the code this substitution is taking place? Then I might try myself to edit the code to my liking.

Thanks in advance :)

P.S. If this is the wrong forum to post a question like this, my apologies and feel free to direct me to a more suitable forum :)

**Comment by turnermm** [comment]
I don't see any way around this at the moment.  The CKEditor makes the conversion and there would be no easy way to implement an exception.

**Comment by turnermm** [comment]
You can create a native dokuwiki link in your page:
`[[http://www.test.com%26testsite]]`
But when the link is linked to in the browser, it will automatically be converted to an ampersand in the location bar.  However, the %26 will retain its literal value in the underlying link.

**Comment by boqa** [comment]
Yes, changing the editor to source mode and entering the url as a native link indeed does work and preserves the %26. However, I can't ask users of my DokuWiki to do that for every link, they would want to be able to copy-paste directly into an editor, preferably CKGedit.

You say you don't see any way around this at the moment. Any chance you could point me towards the lines where the conversion takes place?

**Comment by turnermm** [comment]
>  changing the editor to source mode and entering the url as a native link 
No.  Just type the link using native dw syntax directly into the  editor.

**Comment by boqa** [comment]
Nope, that doesn't work either - probably because the link with %26 is to a an internal site and thus doesn't conform to standard webaddresses (e.g. a link might be something like : http://internaldocuments/blabla.asp%26documentnumber 
Using dw syntax for that makes dw think it's a link to an internal site (http://my-dw-site/http/internaldocuments/blabla.asp_documentnumber).

**Comment by turnermm** [comment]
I've been playing around with this and haven't been able to reproduce your result.  If I enter
`http://internaldocuments/blabla.asp%26documentnumber` into the editor, that is what I get in both the ckgeditor and the dw editor.  I don't get an internal link, and I don't get the ampersand conversion.  

http://www.youtube.com/watch?v=-3KtKg29Ixs

**Comment by soft2u** [comment]
Hello, 
Encoded characters substitution is controlled by the **deaccent** option (How to clean pagenames) from admin configuration.
In the **ckgedit/action/save.php** file, after line 93 , please add the following code 
`
$TEXT = preg_replace_callback('/^(.*?)(href\=\".*?\")*(.*?)$/ms', 
                   create_function(
                         '$matches',         
                         '$matches[1] = preg_replace("/%([A-F0-9]{1,3})/i", "URLENC_PERCENT$1", $matches[1]);
                         $matches[2] = preg_replace("/%([A-F0-9]{1,3})/i", "URLENC_PERCENT$1", $matches[2]);
                          $matches[3] = preg_replace("/%([A-F0-9]{1,3})/i", "URLENC_PERCENT$1", $matches[3]);
                          return $matches[1].$matches[2].$matches[3];'            
                    ),
                    $TEXT
                 );
`
With this, encoded characters will be protected also in html links, not only in wiki links, 
A better sollution is to extend the regex `'/^(.*?)(\[\[.*?\]\])*(.*?)$/ms'` (line 94) to catch htlm links also.

**Comment by turnermm** [comment]
@soft2u Thank you for reminding me about the deaccent setting.  I have a very simple solution, but @boqa will have to ask his users to take an additional step when pasting a url into the CKEditor.  They must `unlink` the link using the unlink tool:
![unlink](https://user-images.githubusercontent.com/176447/29186122-12724148-7dd1-11e7-83e3-aed9807c0574.png)
Because when you copy a link from a GUI, like a browser or Microsoft Office, you are copying not only the displayed text but also the underlying HTML, So, even though the link text may show `%26`, in the underlying HTML it will very likely be an ampersand.    This was my initial thought about what was happening.  Once you **unlink** the link, the HTML is removed and you are left with the plain text rendering.

So, that is step one.    The next step is to install the following test version of ckgedit:
   https://github.com/turnermm/ckgedit/archive/deaccent.zip
Here you will find a new Configuration Option in the ckgediut section:  `preserve_enc`: 
> Preserve urlencoding in urls when the dokuwiki deaccent option is active.

Set this option to true.

**Comment by turnermm** [comment]
@soft2u Thank you very much for your work. I hadn't remembered about the `deaccent` option.  If you check the test version, you will find that there is no need for extra code, all that is needed is to apply the `deaccent` code when the `preserver_enc` option is et to true.

**Comment by boqa** [comment]
@turnermm & @soft2u , thank you for your efforts to solve my problem, much appreciated! :-)

It seems that my problem is more related to my local setup than to CKGedit; 
As mentioned in my original post, I'm using a version of CKGedit from May. Before installing @turnermm's test version linked above, first I upgraded to latest version of ckgedit (Aug 3rd). I had not previously upgraded to this version because for some reason the edit window was rendered useable. 
Well, that reason seems to be an incompatibility between the template I'm using (dokubook) and Internet Explorer. When I use the Aug 3'rd version of  ckgedit with e.g. Chrome, it works fine and what's more, I can copy-paste links (i.e. preserving %26 ) that works out of the box (deaccent => "remove accents").

So, the better solution for seems to figure out why dokubook template doesn't work well with the latest version of ckgedit. However, since my DW site already has strange rendering elsewhere when using Explorer (works fine with other browsers), I now consider this an issue with the dokubook template rather than ckgedit (well, actually I consider it an issue with Explorer more than anything, but since this is the browser of choice at my company, I cannot change that).

Hence, as far as ckgedit is concerned, I considered this issue closed. Thanks for your swift help and suggestions though!

Cheers,
Boqa

**Comment by turnermm** [comment]
Dokuwiki does not encourage the use of IE: https://www.dokuwiki.org/browser
