### ISSUE TITLE
Image double pasting in Firefox

### ISSUE THREAD

**Issue by PenguinSSH** [turnermm/ckgedit#324]
Browser: Firefox 54.0.1 without any addons
Operating System: Windows 10 64 bits
CKGEdit: 4.7.1

When pasting a image using CTRL+V, the image is pasted twice.  This does not happen in Internet Explorer. 

Firefox cache has been flushed and run into incognito mode as well.

**Comment by turnermm** [comment]
This is new and happens only in firefox.  There's nothing I can do about it,  you can try to raise this issue with Mozilla.

**Comment by PenguinSSH** [comment]
Ok thank you for your feedback.  I'll try to search for issues in their tracker related to this.

**Comment by turnermm** [comment]
I think I've solved this.  Try this version:
  https://github.com/turnermm/ckgedit/archive/im_paste.zip
If it works, I'll merge it into the master.

**Comment by PenguinSSH** [comment]
I'll try to validate soon.  I'll get back to you.  Thanks for getting back to this!

**Comment by turnermm** [comment]
Just got a response back from user of ckgdoku, which uses the same code for this as ckgedit, and no problems.  The way this works, you can turn the added paste functionality on and off.  In firefox it has to be off, otherwise firefox pastes the image and the added paste function pastes it, so you get two copies of the image.

**Comment by turnermm** [comment]
Merged

**Comment by Juergen-aus-Koeln** [comment]
You wrote

> you can turn the added paste functionality on and off

Can't this be decided automatically by identifying the browser which is in use? I think that "normal" users do not understand this.

**Comment by turnermm** [comment]
Too many variants.

**Comment by turnermm** [comment]
I've made a small change to the cookie handling,  I've set the expiry date off into the next century.  The cookie controls the switching.  This means that if your users opt for a particular image paste setting, then next time they open their browsers the setting will stil be in effect,  as long as they don't flush their cookies from the browser cache.

**Comment by Juergen-aus-Koeln** [comment]
Please, could you implement this in ckgdoku, too?

**Comment by turnermm** [comment]
Extend expiry date into distant future?  Done.

**Comment by PenguinSSH** [comment]
Just did a couple of test using the latest version of 9-20.  The image
still double pastes.  I can't see where you disable this option per user.

Also, if you do CTRL+SHIFT+V, it doesn't paste the image.  But if you then
do CTRL+V it pastes the image only once.

If you do again CTRL+V it pastes the image twice.

**Comment by turnermm** [comment]
You use the checkbox below the editor:
        Turn supplementary image paste support [on/off]
The default is off.
Never heard of CTRL+SHIFT+V, for this.   As for pasting twice after a second CTRL+V, I can't reproduce this in Firefox on Windows, where the double paste first showe up.  It cold be a caching issue. Refresh the cache.   Which browser(s) and system?

**Comment by PenguinSSH** [comment]
Thanks, refreshing the browser cache (forgetting the website in firefox)
cleared the issue.  I can now see the Turn supplementary image paste
support option.

It also seems to have cleared the issue with double image pasting.

Can I just say that I hate browser caching when it comes to this....

**Comment by turnermm** [comment]
`It also seems to have cleared the issue with double image pasting. `
That's because the default is  now 'off', whereas before it was 'on'.  So as long as the old javascript was cached, it was 'on'.

**Comment by PenguinSSH** [comment]
Thanks, this issue can be considered closed as the new option effectively resolves this issue.
