### ISSUE TITLE
blank screen after update

### ISSUE THREAD

**Issue by 4rensiker** [turnermm/ckgedit#325]
Hi there.

Sorry to bother you with that issue. In general I really really like doku wiki and especially ckgedit...  unfortunately, when I upgraded doku wiki to Release 2017-02-19d "Frusterick Manners" yesterday and ckgedit to 2017-08-23 just today I get an empty content div in Safari (Version 10.0 (12602.1.50.0.10)) and Chrome (Version 60.0.3112.101) 

Hope you can help me with that.

Is there anything I need to do after updating in general? I even re-installed, disabled, uninstalled and installed from scratch... btw the config screen of doku wiki isn't working either. maybe the bug is rather dw related?!

**Comment by 4rensiker** [comment]
Update: I upgraded doku wiki to 2017-02-19e "Frusterick Manners" today. The config screen is working, but ckgedit still is showing a blank screen although ckgedit brings 51 hits in source view.

**Comment by turnermm** [comment]
There was a syntax error in lang/en/settings.php, which is fixed.   If you have access to that file, add a semi-colon to the last line.
     `$lang['gui'] = "Select CKEditor GUI.";`

Or download ckgedit using the following url: 
        https://github.com/turnermm/ckgedit/archive/master.zip
Unzip it and replace settings.php from the zip package.

Sorry for the inconvenience.

**Comment by turnermm** [comment]
Let me know the results.  Thanks.

**Comment by 4rensiker** [comment]
thx @turnermm for the VERY quick reply! Checked the file and the semicolon was there. Apparently I re-installed after your fix.....

**Comment by 4rensiker** [comment]
Got it working... In the configuration in

_plugin»ckgedit»extra_plugins
Comma separated list of additional Ckeditor plugins to be added to toolbar. See ckgedit plugin's config page for details_

I removed

`dialog, dialogui, dialogadvtab, table`

**Comment by 4rensiker** [comment]
What happened: When re-installing ckgedit plugin, everything is being removed and reinstalled. So without downloading and re-uploading the ckedit plugins this will happen. 

check `lib>plugins>ckgedit>ckeditor>plugins` for additional plugins.

Moreover it seems `dialogui` is not compatible -> blank screen after enabling.

**Comment by turnermm** [comment]
If you are using the extension manager, all files present in the update over-write the files in the plugin directory.  Files are not removed.  I'm not familiar with dialogui, I believe it is called for if you install the dialog  plugin separately.  But all that you need for CKEditor dialogs is already included in the CKEditor distribution installed with ckgedit.    If you  had installed dialogui earlier, it would still be there and may have conflicted with the current distro,  which now uses ckeditor 4.7, whereas the previous used 4.5.

**Comment by 4rensiker** [comment]
Agree
