### ISSUE TITLE
Unabkle to save when behind a https reverse proxy

### ISSUE THREAD

**Issue by ace007** [turnermm/ckgedit#335]
Running dokuwiki on synology NAS server.
Just upgraded to latest ckgdoku (Installed version: 2017-09-24)
Using with reverse proxy to get https access to http dokuwiki, **https<->proxy<->http**
When the dokuwiki is accessed via a reverse proxy over https and a page is edited the following console log is reported
Blocked loading mixed active content "http://{{server}}/dokuwiki/lib/plugins/ckgdoku/scripts/parse_wiki-cmpr.js"
The **Save** button no longer works.
If I edit the action/edit.php file and change the following line 
  $parse_url = DOKU_URL . 'lib/plugins/ckgdoku/scripts/parse_wiki-cmpr.js'
to
  $parse_url = DOKU_BASE . 'lib/plugins/ckgdoku/scripts/parse_wiki-cmpr.js'
The save button works BUT I now get the following console error
  http://{{server}}/dokuwiki/doku.php
Showing that the Save tried to get to a http rather than https address.
What is the correct way to configure dokuwiki/ckgedit for use behind a reverse proxy ? or is this a bug ?

**Comment by turnermm** [comment]
Consult the plugin page(s) at dokuwiki.org, where you will find answers to many questions.
https://www.dokuwiki.org/plugin:ckgedit#reverse_proxy

**Comment by ace007** [comment]
Thanks for the quick reply
I have come up with a solution which works for access both with a reverse proxy and without.
I set the baseurl to "//".$_SERVER["HOST_NAME"]
This allows the protocol to be defined by the access so it should work for both https and http

**Comment by turnermm** [comment]
There is "SERVER_NAME" but, as far as I am aware there is no "HOST_NAME".  
http://php.net/manual/en/reserved.variables.server.php.  So, all that would yield is `//`

**Comment by ace007** [comment]
Weirdly both seem to achieve the same effect. The web site works as expected either with http or https
I have now set "//".$_SERVER["HOST_NAME"];  in the dokuwiki.php file.
I can't get the correct information set using the config page, it wraps the string like this '"//".$_SERVER["HOST_NAME"]; ' so I have left the tweak in to dokuwiki.php file (and a note to check whenever there is an upgrade) Idealy all URL's should all be relative.
I had a similar issue with MantisBT and found that by setting the X-Forwarded-Host and X-Forwarded-Proto in my reverse proxy the system worked. They have some PHP code that pulls this information from the HTTP_X_FORWARDED_PROTO and HTTP_X_FORWARDED_HOST variables when used with a reverse proxy. (see config_defaults_inc.php file)

**Comment by turnermm** [comment]
If by config page you mean the configuration manager, everything there is plain text.  conf/local.php is of course php.

**Comment by MarekGrossman** [comment]
I added simple this line in <dokuwiki_dir>/conf/local.php
`$conf['baseurl'] = 'https://our.domain.xx';`
Thanks Ace007 for idea.
