### ISSUE TITLE
Double slash problem

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#337]
Double slash in ckgedit will be auto change font to italic.
But sometime I don't want it change .I just want write double slash.
It possible to do?

And double slash in table will cause page to be null after saving

example 
|123//456|789/123|
一一一一一一一一
|123//456|789/123|

**Comment by turnermm** [comment]
Use dokiwuiki's escape sequence:  `%%`, , , ,`%%`
|123%%//%%45|123%%/%%45|
|123%%/%%/45|123%%/%%45|

When reloaded into the  cgkeditor these will be converted to nowiki tags.

**Comment by qwe852147** [comment]
Thanks !
But it possible use '//' directly in future?

**Comment by turnermm** [comment]
No.

**Comment by qwe852147** [comment]
Thanks!

**Comment by turnermm** [comment]
Sorry about that. The escape `%%` characters are needed; otherwise the parsing gets corrupted.

**Comment by qwe852147** [comment]
It's OK, I have this problem is because of some partner usually write slash in table and sometime write double slash carelessly.
