### ISSUE TITLE
page creation from template fails unless edited

### ISSUE THREAD

**Issue by Anonymousdog** [turnermm/ckgedit#339]
I don't know how long this has been a problem, but I'm trying to setup some namespace templates, and I'm running into a problem where the ckgeditor fails to store a new page if it is
- based on a template
AND
- the page is not edited at all after the template is loaded.
No matter how stupid that scenario might sound, you'd be surprised how often that generates a support call.  Is there a way to fix that?  The standard DW editor doesn't do it.

**Comment by turnermm** [comment]
The only thing I can do  for this is to issue a warning above the editor:
`An edit or mouseclick in the editor window is needed to save the template data`

**Comment by turnermm** [comment]
I may have a better, less intrusive solution.  Thinking about it.

**Comment by turnermm** [comment]
Try the following:
https://github.com/turnermm/ckgedit/archive/master.zip
Install using the manual tab of the extension manager.
It addrsses both this template issue and the confusion of OPEN,CLOSE,START,END HTML_BLOCK

**Comment by Anonymousdog** [comment]
Nice!  I'll check it out!

Andy

**Comment by turnermm** [comment]
Probably a good idea to clear th brosser cache.

**Comment by turnermm** [comment]
Ant feedback?

**Comment by Anonymousdog** [comment]
I'm not seeing a warning, or the change in the HTML block
implementation...looks the same...I don't understand why.  I even removed
the plugin entirely and reinstalled manually.

**Comment by turnermm** [comment]
The warning is removed now that ckgedit is designed to recognize a loaded template on a save.  You should try clearing your browser cache and refreshing the dokuwiki cache.

**Comment by Anonymousdog** [comment]
Thanks for chasing this down.

Andy
