### ISSUE TITLE
Alias ~~END_HTML_BLOCK~~ to ~~CLOSE_HTML_BLOCK~~

### ISSUE THREAD

**Issue by Anonymousdog** [turnermm/ckgedit#340]
Any chance I can get you to change the `~~CLOSE_HTML_BLOCK~~` macro to `~~END_HTML_BLOCK~~` (or alias `~~END_HTML_BLOCK~~` to it)?  It's hard to get users to remember the "CLOSE" notation because "close" is not the opposite of "start"; "end" is.  Else alias `~~OPEN_HTML_BLOCK~~` to `~~START_HTML_BLOCK~~`; it's a semantics problem that actually matters.

Thanks,
Andy

**Comment by turnermm** [comment]
https://github.com/turnermm/ckgedit/archive/master.zip
This makes END and CLOSE, and OPEN and START, interchangeable.  So any of these combinations will work: 

```
~~START
~~CLOSE
```

```
~~OPEN
~~CLOSE
```

```
~~START
~~END
```

```
~~OPEN
~~END
```
But the final result in the editor will always be original syntax `START. . .CLOSE`, which is required by the parser.

**Comment by turnermm** [comment]
Somting got lost w hen I uploaded this.  You'll have to wati for it.  But th e other function should be ok.

**Comment by turnermm** [comment]
Should be OK now.

**Comment by turnermm** [comment]
Any feedback?

**Comment by turnermm** [comment]
I didn't hear back from you on this and was doing some house cleaning and deleted the misc_updates branch with the changes.  Do you still have the script.js file from that branch?

**Comment by turnermm** [comment]
I managed to recover it.

**Comment by Anonymousdog** [comment]
This is fantastic!
