### ISSUE TITLE
Conflict with nspages plugin

### ISSUE THREAD

**Issue by papermate** [turnermm/ckgedit#342]
Hello everyone. I have this problem in my home page, it's a simple 3 column wrap with namespaces in:

**What happens:** I have this code in my dokuwiki page:

```
<WRAP group>

<WRAP center round column third info> **[[:personaggi|Personaggi]]**

<nspages personaggi -exclude:c_template -h1 -textPages="" -simpleList -hideNoPages>

**Aggiungi un personaggio**

{{NEWPAGE>personaggi}}

</WRAP>

<WRAP center round third column tip> 
**[[:sessioni|Sessioni]]**
<nspages sessioni -exclude:c_template -h1 -textPages="" -simpleList -hideNoPages>

**Aggiungi una sessione**

{{NEWPAGE>sessioni}}

</WRAP>

<WRAP center round third column todo> **[[:guide|Guide]]**

<nspages guide -exclude:c_template -h1 -textPages="" -simpleList -hideNoPages>

</WRAP>

</WRAP>

```

When I edit with ckgedit, without touching anything, just opening it, it turns like this:
```

<WRAP group>

<WRAP center round column third info> **[[:personaggi|Personaggi]]**<nspages personaggi -exclude:c_template -h1 -textPages=_ckgedit_QUOT__ckgedit> -simpleList -hideNoPages> **Aggiungi un personaggio** __

__{{NEWPAGE>personaggi}} __

__</WRAP> <WRAP center round third column tip> **[[:sessioni|Sessioni]]** <nspages sessioni -exclude:c_template -h1 -textPages=_ckgedit_QUOT__ckgedit> -simpleList -hideNoPages>

**Aggiungi una sessione**

{{NEWPAGE>sessioni}}

</WRAP>

<WRAP center round third column todo> **[[:guide|Guide]]**<nspages guide -exclude:c_template -h1 -textPages="" -simpleList -hideNoPages>

</WRAP>

</WRAP>

```

Of course that breaks the nspages plugin output. Right now I have to press "edit dokuwiki", go to the previous version and edit that, but I feel like that shouldn't be the expected workflow =D

**ckgedit version**: _ckgEdit-ckedit_4.7-17-Sep_24-10_27
** dokuwiki version**: Release 2017-02-19b "Frusterick Manners"

Thank you all for the nice work!

**Comment by turnermm** [comment]
It is not the nspages plugin, but most likely the combination of that plugin with the complex wrap setup.
This markup:
```
<WRAP center round info 60%>
====== Menu ======
<nspages events -exclude:c_template -h1 -textPages="" -simpleList -hideNoPages>

{NEWPAGE events}}

</WRAP
```
Gives this result:
![nspages_wrap](https://user-images.githubusercontent.com/176447/31493797-589cd78e-af16-11e7-81cc-26ea392a2dec.png)

So all three of these plugins work together but the problem comes when you set up the columns, and there's nothing that I can do about that.

**Comment by turnermm** [comment]
I may have found a solution for you:
```
~~MULTI_PLUGIN_OPEN~~

<WRAP group>
<WRAP center round column third info> **[[:playground|Personaggi]]**<nspages playground -exclude:c_template -h1 -simpleList -hideNoPages>
**Aggiungi un playgroundo**
{{NEWPAGE>playground}}
</WRAP>
<WRAP center round third column tip>
**[[:sessioni|Sessioni]]**<nspages sessioni -exclude:c_template -h1 -simpleList -hideNoPages>
**Aggiungi una sessione**
{{NEWPAGE>sessioni}}
</WRAP>
<WRAP center round third column todo> **[[:guide|Guide]]**
<nspages guide -exclude:c_template -h1  -simpleList -hideNoPages>
</WRAP>
</WRAP>
~~MULTI_PLUGIN_CLOSE~~
```
I have removed  `-textPages=""`, which is not necessary to your  output and added the `MULTI_PLUGIN` macros.

**Comment by turnermm** [comment]
I've added a new feature which should help solve this problem no matter what your nspages  or wrap syntax is.  It is a pair of `STET` macros:  
```
~~STET_OPEN~~
<your plugin markup>
~~STET_CLOSE~~
```
In this case you would put your entire wrap markup here:
```
~~STET_OPEN~~
<WRAP group>
</WRAP>
~~STET_CLOSE~~
```
Temporarily you will have to use the following url:
https://github.com/turnermm/ckgedit/archive/misc_updates.zip
Load it into the extension manager using the manu;la tab.

**Comment by turnermm** [comment]
Any feedback?

**Comment by turnermm** [comment]
This is now handled by the stet branch.

**Comment by turnermm** [comment]
Stet has not been merged into master.  See solution proposed above.
