### ISSUE TITLE
nowiki tag inside tables

### ISSUE THREAD

**Issue by jabrugger** [turnermm/ckgedit#344]
The following DW code
```
^Categoría^Parámetro^Especificación|
<nowiki>URL desde donde descargar el archivo farmaclick.upd, utilizado para descargar e instalar las actualizaciones de las tablas del sistema.
Debe contener un caracter '|' entre el nombre del host y el path completo.
p.e. 'http://www.dasu.com.ar|/farmaclick/updates/farmaclick.upd'</nowiki>|
```
gets "broken" when edited by ckgedit (see following screenshot).
![ckgedit table nowiki](https://user-images.githubusercontent.com/21174632/31899858-1912cbe2-b7f3-11e7-9b3f-4027a51066b4.jpg)

**Comment by turnermm** [comment]
It's not the nowiki tags.  It's the content inside the nowiki container.  You can't  include the pipes `|` and the content should not have line breaks but be all on one line.  Nothing to be done about this at the moment.

**Comment by jabrugger** [comment]
The weird thing is I can include pipes inside nowiki content by using  DW editor, and works fine. When using ckgedit is when that content goes crazy.

**Comment by turnermm** [comment]
It's not weird at all.   But I will fix it and let you know when it's done.

**Comment by turnermm** [comment]
Just fixed it.  Update your ckgedit.

**Comment by jabrugger** [comment]
Updated and reloaded (just in case)
Better than before, but it still has issues. Create the nowiki tag, save, edit ir again, and you´ll end with a new column in the table (because of pipe, which it´s not "ignored" for being inside nowiki tag)

**Comment by turnermm** [comment]
I was in too much of a hurry.  It should be ok now.

**Comment by jabrugger** [comment]
Working great now. Thanks a lot.

**Comment by turnermm** [comment]
Thanks for the feedback.
