### ISSUE TITLE
Backslashes disappear in Code Blocks

### ISSUE THREAD

**Issue by PenguinSSH** [turnermm/ckgedit#345]
Browser: Any browser
CKGEdit version: 2017-10-24
Plugins: DataTables, Dw2Pdf, Move, New Page Dialog, Page Query

When putting a path such as C:\Windows\System32

All backslashes are removed from the code block resulting in

C:WindowsSystem32

This was tried in several browsers, clearing cache/cookies.  When we try with the DWEdit editor, backslashes remain and are displayed correctly.

**Comment by turnermm** [comment]
Not sure why you are having this problem.  Here is the ckgedit editor:
![playground_code_block](https://user-images.githubusercontent.com/176447/32029672-bae19f7e-b9bb-11e7-8308-5fe2a2b6ab11.png)
Here is the results:
https://www.mturner.org/devel/playground/code_block

**Comment by turnermm** [comment]
I ran this from apache on windows as well as on linux, using firefox and chrome.  Perhaps it's one of your plugins.

**Comment by turnermm** [comment]
Another possibility is that there is  something else on the page that  is getting run together in the preprocessor  with these back-slashes,  in which case I would need to see the page.  You can test this possibility yourself by creating a clean page with just the code block and the windows path data.

**Comment by PenguinSSH** [comment]
Ok so I seem to have located a bug maybe.  

Start a new page
Create a code block
 with content C:\Windows\System32 or any back slashes
Type a link such as https://google.com
Save the page
Backslashes are saved and shown properly
Edit the page
Add something to the page without editing the code block
Save the page
Backslashes are no longer present
Upon save, the backslashes are removed

I can reproduce these steps before and after disabling all plugins

**Comment by turnermm** [comment]
fixed in  latest update

**Comment by PenguinSSH** [comment]
Awesome, just tested with the latest update and indeed this is resolved!

Thanks a lot for your quick resolution :)

**Comment by turnermm** [comment]
Shold be fixed in latest update.
Thanks.

**Comment by turnermm** [comment]
Missing backlashes in code blocks shoujld be fixed  in latest update.
