### ISSUE TITLE
Link button

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#347]
It can not work when the page have more media ex video.

The picture is after I click line button and the select  file window no show but edit textarea is disabled .
I insert 12 vidoe into page and each video size is around 120MB
![default](https://user-images.githubusercontent.com/10329643/32164723-50791692-bd9b-11e7-9bbe-6666b8126654.png)

Content in picture is important data so I hidden it  not empty

**Comment by turnermm** [comment]
Can't really follow this.  Are the videos all running at the same time in the editor?  What happens if you have only one video?

**Comment by qwe852147** [comment]
Sorry I find the problem which is cause by the video.

The video in edit area will show with video tag.

When I entry to edit mode the video begin downloading .
Before video download completely, the page will stop until complete.

In dokuwiki page, I can overwrite parser function to modify video preload by renderer plugin but in edit page I do not know where to modify video parser function ,Is call dokuwiki  "_video function"?

**Comment by qwe852147** [comment]
I find the problem is also similar dokuwiki page renderer.
When video in page is too many , the browser should waiting all video download that cause the page does not work. 

I find to overwrite _video function in dokuwiki\inc\parser\xhtml.php to add video prelaod config and set it to 'none' will be better.
