### ISSUE TITLE
Image copy paste does not work

### ISSUE THREAD

**Issue by krakorj** [turnermm/ckgedit#358]
Image copy paste does not work on 

* Dokuwiki Release 2017-02-19e "Frusterick Manners") 
* Ckgedit plugin version 2017-12-08
* Chrome Version 63.0.3239.84 (Official Build) (32-bit), 

Work around via Past icon responses 
~~~
Your browser doesn't allow you to paste this way. Press Ctrl+V to paste.
~~~

Is there any way how to copy paste images to the ckgedit?

**Comment by turnermm** [comment]
https://www.dokuwiki.org/plugin:ckgedit#copy_and_paste

**Comment by krakorj** [comment]
Thank you
