### ISSUE TITLE
pasting html tags into geshi makes tags dissappear

### ISSUE THREAD

**Issue by kaiaeberli** [turnermm/ckgedit#359]
When I create a geshi area in a table, and paste in some code that includes any tags, such as <script>, the tags will disappear. In addition, if I paste something like this:
`FOOTER = """    </body></html>"""`
it ends up looking like this:
`FOOTER = """ """`

Am I doing it wrong?

Just to add, the FOOTER part was multiline, but it was disappearing here as well so made it single line.

I use the geshi plugin to do all the pasting

**Comment by turnermm** [comment]
The CKEditor can't handle the overlapping of the html in your code block.  It treats it as html instead of text, and so the html disappears, in the same way that you don't see any of the other html in your pages.

**Comment by kaiaeberli** [comment]
i tried the code - it creates a table with a piece of geshi code inside. However, this was already working before, i.e. i could use the geshi plugin to put code in a table. Could you explain maybe a bit more what you were trying to show?

**Comment by turnermm** [comment]
I think I was just showing that the geshi blocks can handle tables and that also they can be embedded in tables.   But you can't put html tags into a code block because there is no way to escape them, for instance `%%<b?bold</b>%%`, as you can do in dokuwiki.
