### ISSUE TITLE
set teble column width

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#361]
It possible to set table column width ?
I have some trouble when type chinese into table, it will auto break  each chart when column is too many.

**Comment by turnermm** [comment]
I think you need to find a dokuwiki plugin for this.

**Comment by qwe852147** [comment]
Thanks  I  will do it.
But other plugin cannot use with ckgedit.

**Comment by turnermm** [comment]
You can generally use basic syntax plugins with ckgedit.
