### ISSUE TITLE
Links with images get messed up

### ISSUE THREAD

**Issue by benmetz** [turnermm/ckgedit#365]
Since some update (unfortunatly I don't rembember with what version it was still working) something strange happens with internal links that are an image. It even sometimes happens, when switching between DW Edit and CKGEdit without doing something on the page.

A link that is in the source-txt-file like this:

[[:0012:0012|{{:0012:logo_gross.jpg?nolink&}}]]

get's changed to this:

[[.:0012|{{.:logo_gross.jpg]]

(don't mind the 'gross' within the image name, in german it means 'big' - there's nothing gross going on here ;-)

I guess it might be something wrong with the regex-stuff. I know a little php, but I'm not particularly good with regex so I gave up searching where the mishap might happen.

**Comment by turnermm** [comment]
You don't seem to be using relative links.  If not, turn off the relative links setting.  You are using an early version of the relative links implementation, where relative links were turned on by default.  This is not true of current versions.  If you are using relative links, then you will not be able to use images as links until this issue is fixed.

**Comment by benmetz** [comment]
Thank you for your fast reply!
I turned that off now in the configuration-editor ("plugin»ckgedit»rel_links"), but it occurs nonetheless.

**Comment by turnermm** [comment]
Clear out your dokuwiki cache:  delete all the files from data/cache.  And refresh your browser cache.

**Comment by benmetz** [comment]
Deleted everything in the cache-dir.
Error seems to be gone now.
I will be able to verify that with users who complained about the behavier tomorrow.
Thx for the help!
I will close this issue after verification.

**Comment by benmetz** [comment]
I'm sorry to inform you, that the problem persists.
Is there anything I can do, besides reinstalling the whole wiki like deleting the config and reconfigure?

**Comment by turnermm** [comment]
For whom does it persist?  If it disappeared for you then it was fixed.  Are you yourself still getting that result?
If it occurs among your users have them refresh their browser caches. 

The re-formatting of links can occur only if the relative links setting is set to true.  

First, make sure that you have set the relative links setting to off. Then reinstall ckgedit using the extension manager.   Then make sure that the relative links setting is off in the configuration manager.

If it still persists then try ckgdoku.

**Comment by turnermm** [comment]
Let me take another look. I've been assuming it is related to the relative links setting. Perhaps it is a problem independent of the relative links setting.

**Comment by turnermm** [comment]
I believe I've found and corrected the problem, which was  a side-effect of new code handling relative links and useheading.  Install the ckgedit update and again clear out the cache both of the browser and dokuwiki.

Thanks.

**Comment by benmetz** [comment]
Hey Myron,
did what you said.
I'm not able to trigger the link "mutilation" anymore.
The issue is gone now.
Thank you very much and have a nice day!
