### ISSUE TITLE
Copy from word 2 headers one after another

### ISSUE THREAD

**Issue by killersan** [turnermm/ckgedit#367]
When you will copy text from Word where you will have two headers one after another then after pasting it and saving you will receive the issue with formatting:
```
First header
<font 14pt/inherit;;#2f5496;;inherit>Second header</font>
```
After saving and editing it again and moving a cursor to any line and saving again, those extra formatting entries will be removed.

**Comment by turnermm** [comment]
Pasting from Word is a  CKEditor function and a convenience, but ckgedit can't guarantee the results.
