### ISSUE TITLE
horizontal line does not behave correctly with images

### ISSUE THREAD

**Issue by rjmaris** [turnermm/ckgedit#368]
When images are accompanied with descriptive text, a method to ensure that following text associated with next  is forced to get alongside with this image is to simply add a horizontal line.

However, in CKGedit mode, the horizontal line appears as simple part of the floating text. As a result, the appearance can be quite totally different...
(e.g. when images are 300 px wide, they can even appear as a staircase, dependent on the amount of text associated with it..

**Comment by turnermm** [comment]
Not following.  Upload some screen shots of the before and after, and of what you are trying to a ccomlist.

**Comment by rjmaris** [comment]
Here are two screenshots. Hope this makes sense to you.
![render](https://user-images.githubusercontent.com/1149309/35576679-e08353ec-05df-11e8-9a41-6345134b91b0.jpg)
![ckgedit](https://user-images.githubusercontent.com/1149309/35576682-e4313e8c-05df-11e8-8bea-59f32f63b91e.jpg)

**Comment by turnermm** [comment]
For this you will need the wrap plugin.  Here is a schematic for how to achieve you result.
```
====== Page Title ======

<WRAP right 350px>

{{img1.png?350}}

</WRAP>

Lorem ipsum dolor sit amet, aliquet mauris eu ut sit rutrum, neque parturient, dis dui, vel vestibulum lectus felis non gravida. At ante neque blandit purus in pede, ipsum dui aenean, eget ut vel, voluptate hendrerit commodo sit suspendisse molestie. Eu cras nam eu id, fringilla in egestas, amet sem, in donec mauris hendrerit. Dolor ante, nec donec a duis diam, dis nibh sapien est, vel rutrum in parturient, dolor

<WRAP clear></WRAP>

<WRAP left 350px>

{{:img2.png?&350  }}

</WRAP>

sollicitudin urna nullam. Vel ligula magna natoque, ornare arcu lorem velit vestibulum, orci odio pellentesque nulla consectetuer amet luctus, praesent nunc. Tincidunt elit vitae varius enim mattis suscipit. Consequat praesent vitae, velit imperdiet magna, magna nisl in, curabitur lobortis. Vero eu suscipit porta in a, illo nunc sem hic cras, aliquet posuere nullam donec ac, aliquam nonummy congue, wisi sollicitudin eros cras ultricies. Dictum faucibus in vitae aliquam eros sit, mauris sociosqu donec sapien pellentesque elit eget. Erat dignissim wisi etiam dignissim wisi.

<WRAP clear> </WRAP>
<WRAP left 100%>
----
</WRAP> 
<WRAP left 350px>

{{:img3.png?350 |}}

</WRAP>

Donec donec eu aliquam pretium in pellentesque, libero non. Sapien porta laoreet proin vel. Pede elit ultricies maecenas odio turpis elit, ultricies lectus turpis ornare justo pede nibh, lectus dolor sem lacus, felis wisi. Neque vivamus et et ullam. Aliquam congue, amet sed egestas enim integer ad felis, ultricies tellus, aenean in, at purus justo aliquam augue quam sapien. Vivamus magna sem id quisque dolore libero, volutpat diam.


```
Note this:
```
<WRAP left 100%>
----
</WRAP> 
```
Without the horizontal line, there is not enough vertical space between the two images; it's not necessary but better looking.

The ckgedit editor allows for the use of many native Dokuwiki markup elements.  In the case of syntax plugins, it will show the syntax and not the effects.  The effects will show up in the browser.

**Comment by rjmaris** [comment]
Thanks for that. I highly appreciate your comment.
Of course, the WRAP does not show the effects in ckgedit. But in this case, the visual difference for the casual wiki user is too big to be acceptable for them.

BTW: you don't need WRAP in order to wrap a text around an image. Effectively, I use a space before "}}". This has the advantage that it also renders properly in the ckg-editor ;).

For sure, using "----" (wiki source) has the potential advantage of rendering in the ckg editor as well - contrary to e.g. the shortform float clearing <WRAP clear/>, which is automatically inserted by clicking the appropriate button in DW-mode.
And indeed, it does render, but alas not with inherent float clear effect.

To my opinion, this is a minor issue, which - when resolved - would substantially improve the casual user experience.
The alternative could be: creating a table with images in one column and text in another. Here, the editor view renders comparably to the final view. But I won't use a table for this - even not in a special template (I created one for this type of pages where casual users should be able to handle and edit it).

**Comment by turnermm** [comment]
> BTW: you don't need WRAP in order to wrap a text around an image. Effectively, I use a space before "}}". This has the advantage that it also renders properly in the ckg-editor ;).

You can achieve this in the CKEditor by selecting the desired alignment, and when the image is posted to the preview pane the resulting effectg is displayed:
![imgviewr_alignmnt](https://user-images.githubusercontent.com/176447/35600458-95ebda5c-05f3-11e8-814d-a476de4d1278.png)

**Comment by rjmaris** [comment]
Simple solution:

Add the following to the start of `lib/plugins/ckgedit/ckeditor/contents.css`:
```
 @import url("basic.less");
 @import url("userstyle.css");     (optional)
```
Copy `basic.less` from `lib/tpl/dokuwiki/css` (or have the @import relatively point to that file)
The optional part is to accomodate user changes, e.g. https://forum.dokuwiki.org/thread/15563 (suppressing blank line when starting a list).

This is tested for the non-farm-version.

Note: before modifying `contents.css`, I renamed the uncompressed version of this file. It is noteworthy to know that ckedit 4.7.3 includes some reorganisation, e.g. a smaller contents.css that is no longer compressed.

A wiki farm requires a bit modified handing. That's currently under test.
