### ISSUE TITLE
Query String and Display Text on Internal Link doesn't work correctly

### ISSUE THREAD

**Issue by Tungst3n3** [turnermm/ckgedit#369]
Hello,

I have 2 issues with the latest version of ckgedit, which I think is the same problem.

When I create an internal link with ckgedit UI, it works.
But when i want to add a query string to the link created before, the display text change into the name of the page, and the query string doesn't work.
And when i want to change Link Display Text, i cannot validate changes with OK button

The goal is to have a link with readable display text and when you click on it, you are redirected to search page with the keyword in the id instruction of the query string

Thanks for the answers

Screenshots :

**Internal Link Creation :**

![image](https://user-images.githubusercontent.com/35960286/35566507-f5632a94-05c1-11e8-8d01-fe78c1f7d7bd.png)

**Internal Link Display :**

![image](https://user-images.githubusercontent.com/35960286/35566551-1a47effc-05c2-11e8-80da-a279257b3258.png)

**Add a query string :**

![image](https://user-images.githubusercontent.com/35960286/35566602-3da3a6f8-05c2-11e8-8f21-3dacd8b82de1.png)

**Internal Link Display after added a query string :**

![image](https://user-images.githubusercontent.com/35960286/35566649-69bc55a0-05c2-11e8-861c-c128801af3f6.png)

**Add a Link Display Text : [Impossible to validate changes with OK button]**

![image](https://user-images.githubusercontent.com/35960286/35566695-96e7e558-05c2-11e8-8fb6-997d04c2e725.png)

**Comment by turnermm** [comment]
I see that, if you mean that the dialog freezes when you click OK.  In that case, you can simply change the Link Display Text directly in the Editor, without using the link dialog.  This can be done with any link.  If you want ot change the query string, you can do this with the link disalog, and again if you want to change the  Dispaly Text, wait until the query string has been changed and then rename the link in the editor.

**Comment by Tungst3n3** [comment]
Hello,

I have tried your solution with Internal Link.
It's OK for Link Display Text, not very user friendly to change after the link has created, but it works.

Instead of the Query String still doesn't work. Everytime i tried to add a Query String to my link, the Query String doesn't work.

For the moment, the only way I found to add a Query String is to use http / https URL Link type and create a Query String with the all URL of the page 

**Example :** my.domain.com/dokuwiki/doku.php?do=search&id=test

It's a inconvenient for my users, because they don't really want to change the procedure to create this type of link.

Thanks for the answer.

**Comment by turnermm** [comment]
> the Query String still doesn't work

A bug crept into the code recently when I coded for relative links.  I'll let you know when it's fixed.

**Comment by turnermm** [comment]
Try it now, using the link dialog's query string feature.

**Comment by Tungst3n3** [comment]
Hello,

With the latest update (2018-01-31), the Query String works.
And I see Link Display Text works too like before bugs

Thank you for the correction.
