### ISSUE TITLE
bug in bullet list with links and text that starts with "-"

### ISSUE THREAD

**Issue by bcristian** [turnermm/ckgedit#371]
To reproduce, create an empty page and put in the corresponding text file the following:
`  * [[https://www.google.com/]] - google`
Note the space - minus - space between the link and the text
View the page, and it will show as expected, bullet, "external url" class link, space - minus - space google on the same line.
Edit the page, change a letter (or anything), so that a new version of the page is actually saved, and see that the text after the link has been moved in a paragraph instead, breaking the list. The change is present in the txt file as well, where the text after the link is placed on the next line after the link.

The bug does not happen if either the first space is removed or the minus is removed or replaced with another character (tried a letter, a digit, plus).
It also does not happen in the DW editor, so it seems to me that CKG is the most likely source of the issue.

**Comment by turnermm** [comment]
I haven't investigated but I suspect that the parser is mistaking the hyphen for an ordered list mark but can't handle it because it's in the middle of a line.  In the mean time, escape the hyphen:  `%%-%%`.  When the list is loaded back into ckgedit it will look like this: `<nowiki>-</nowiki>` and in the Dokuwiki editor you will  have: 
` * [[https://www.google.com/|https://www.google.com/]] <nowiki>-</nowiki> google`

**Comment by Floffyko** [comment]
Talink about Lists:

- DW - 2016-06-26a "Elenor of Tsort"
- php 5.3.5
- All Browsers

Lists are broken to a second edit sesion.

We have in DW EDit:

```
  * Unordered List
  * Unordered List 2
      * Unordered List 3
```

CKG edit wil transform it in :
`<div class="level2">* Unordered List * Unordered List 2 * Unordered List 3</div> 

What will brake every list ever made with DW EDIt  or ckgEdit. In fact the editor is not usable if in text is any list. it wil all look like this:
`* Unordered List * Unordered List 2 * Unordered List 3 `

Where could be the problem?
Thanks for your nice work :)

**Comment by turnermm** [comment]
I'm afraid I can't reproduce this error.  I tested in Frusterick Manners and an older distribution of Dokuwiki: Detritus.  I also tested  in Safari, on a MacBook.

My tests include use of php 7.1 and 5.6.   I see you went on to test in 5.6, 5.3 is no longer supported.

This is a test page where I made repeated entries into the nested list and repeated saves:
    https://mturner.org/devel/playground/nested_lists

I would suggest that you test against any plugins that you may have installed.

**Comment by turnermm** [comment]
In fact, if the editor becomes unusable, then I suspect an incompatible plugin.

**Comment by Floffyko** [comment]
100 % plugin incompatibility ! You were right.

yalist plugin is incompatible with ckg of any flavour. please write it on the list of incompatible plug-ins. 

Thanks for the tip

**Comment by turnermm** [comment]
The conflict has been listed for some time in the conflicts field of the header of both plugins, just below the Repository listing, where it says `Conflicts with`.

**Comment by Floffyko** [comment]
Dear users, **check** the conflict list **twice** before raising any questions...
