### ISSUE TITLE
Can't save site when a (Samba) share link is on this site

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [turnermm/ckgedit#375]
Hi,

I'm running the latest Dokuwiki (Frusterick Manners) with the latest ckgedit plugin.

When saving sites which contain Samba share links, saving with the ckgedit editor is not possible (with DW Edit no problem). I get an empty page and all edits are lost.

In my PHP error file I see following entry:
[12-Feb-2018 12:06:43 UTC] PHP Fatal error:  Using $this when not in object context in /srv/www/htdocs/dokuwiki/lib/plugins/ckgedit/action/save.php on line 206

The same error occurs when switching from ckgedit to DW Edit. I think that's because ckgedit wants to save first before switching to DW Edit.

ckgedit shows me following source code:
`<a class="windows" href="file://///SERVER/path/to/file.pdf" title="\\SERVER\path\to\file.pdf">TEXT</a>`
Original syntax:
`[[\\SERVER\path\to\file.pdf|TEXT]]`

After removing all Samba share links everything works as expected.

Thanks

Best regards
Tom

**Comment by turnermm** [comment]
See: https://github.com/turnermm/ckgedit/issues/351

**Comment by Speedy-Gonzalez** [comment]
Thanks. I can confirm that this causes the problem.

We'll move to a newer PHP version.
