### ISSUE TITLE
Internal Links = Blank Page

### ISSUE THREAD

**Issue by mobilephone2003** [turnermm/ckgedit#376]
Hi,

Currently getting a blank page on posting internal links.

Release 2017-02-19e "Frusterick Manners"

Only running this plugin and the columns plugin, most else is stock.

Any ideas? Happens on pages where internal links already exist.

Thanks

**Comment by Speedy-Gonzalez** [comment]
See #375 or #351 

Is your PHP version below 5.6?

**Comment by andreyoc** [comment]
Same problem, same release and php-5.3.3

**Comment by turnermm** [comment]
There's no way around this; you will have to upgrade your php to 5.6.

**Comment by andreyoc** [comment]
ok. thanks
