### ISSUE TITLE
Contribute a (German) translation

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [turnermm/ckgedit#377]
Hi,

I've seen that not all strings are translated into German so I would like to contribute the missing strings.

I've found this information about the language support https://www.dokuwiki.org/plugin:ckgedit#language_support

If I read everything correctly I can start translating the missing strings in the file ckgedit/ckgedit/lang/de.js
Is this correct?
But what happens when you pull a new version from CKEditor? Are my translated strings lost or are the merged into the new version from CKEditor?

The strings from the plugin 'headerbuttons' are hard coded into the source code. https://github.com/turnermm/ckgedit/blob/master/ckeditor/plugins/headerbuttons/plugin.js
I'm not a JavaScript programmer but is there an easy way to create translatable strings like this: https://github.com/turnermm/ckgedit/blob/master/ckeditor/plugins/fontAssist/plugin.js
```js
CKEDITOR.plugins.add("fontAssist", {
            init: function(b) {
                    b.addCommand("fontAssistDialog", new CKEDITOR.dialogCommand("fontAssistDialog"));
                    var d = b.lang.fontassist;
                    if (!d) {
                        d = CKEDITOR.lang["default"]["fontassist"]
                    } else {
                        var c = CKEDITOR.lang["default"]["fontassist"];
                        for (var a in c) {
                            if (!d[a]) {
                                d[a] = c[a]
                            }
                        }
                    }
                    b.ui.addButton("FontAssist", {
                        label: d.ToolTip,
                        command: "fontAssistDialog",
                        icon: this.path + "images/fonts.png"
                    });
```

I know that need a variable for dynamically naming the label but I can't figure out, what the variables b or d stand for in the example above.

Thanks.

Best regards,
Thomas

**Comment by turnermm** [comment]
Yes, follow the docs for adding missing strings.  Then create an issue and attach the updated file. Or, if you download a git for ckeditor, create a pull. Then I’ll know abut the updates and can add them the ckgedit.

Truthfully, I haven't looked at the header buttons.  They were installed aby another user,  So I'll see what I can do before you take the time to create new strings for them.
Thanks,

Myron

**Comment by Speedy-Gonzalez** [comment]
What do you mean with:
>Or, if you download a git for ckeditor, create a pull. Then I’ll know abut the updates and can add them the ckgedit.
Why create a clone of ckeditor? ckeditor hasn't the plugins ckgedit has.

My method would have been:
  * Fork ckgedit (already done: https://github.com/Speedy-Gonzalez/ckgedit)
  * Apply my changes
  * Open a PR for ckgedit so you could merge my changes

Is that okay?

**Comment by turnermm** [comment]
> Why create a clone of ckeditor?

Yes that's Okay.  I meant ckgedit.  You can temporarily change the strings to German in  your own wiki , but now that  you've called attention to this, I'll add support for localization.  But I can't do it for a while yet, since I  am try to concentrate right now on another ckgedit issue that has been time-consuming.

**Comment by turnermm** [comment]
I've just added localization to the headerbuttons plugin.  I added the German strings but they have to be vetchecked.  Until they have been checked, I have created a separate branch for them:  
       https://github.com/turnermm/ckgedit/archive/headers_de.zip
You will find the language file in ckeditor/plugins/headerbuttons/lang.de.js.  If you make any changes,  create a pull request.  I can't imagine they don't need editing, but if they don't then let me know, and I'll update the master branch.

As for any other strings which are missing, update the language files as indicated in the dokuwiki.org docs, then as above, create a pull request.  

Thanks.

**Comment by Speedy-Gonzalez** [comment]
They are not bad but need a little fine tuning. I'll open a PR.

Thanks for your help.

**Comment by turnermm** [comment]
Have you done this  yet?

**Comment by Speedy-Gonzalez** [comment]
I will try to do it tomorrow. Did not had time in the last few days.
