### ISSUE TITLE
Conflict with Structured Data Plugin

### ISSUE THREAD

**Issue by FrankGaul** [turnermm/ckgedit#381]
Bonjour,
I have some trouble between Ckgedit and strutured data plugin; it's impossible to display a dataentry like that:

---- dataentry test01 ----
Nom : Horovitz
Prénom : Frank
Titre : Cahiers libres
date : 2017 
----
Have you a solution?
Thank-you very much
FRançois

**Comment by turnermm** [comment]
There's a lot of documentation at dokuwiki.org.  You can search the index for key words: https://www.dokuwiki.org/plugin:ckgedit:index

You'll find several entries for data relating to the data plugin.

**Comment by FrankGaul** [comment]
Thank you very much; i do that and it works👍 

~~START_HTML_BLOCK~~
---- dataentry projects10 ----
Nom : Horovitz 
Prénom : Frank
Titre : Cahiers libres
date : 2017 
----
~~CLOSE_HTML_BLOCK~~
