### ISSUE TITLE
Editor duplicates content when using markdowku

### ISSUE THREAD

**Issue by JulioC** [turnermm/ckgedit#383]
This is the same issue resported in https://github.com/turnermm/ckgdoku/issues/48 and https://github.com/turnermm/ckgedit/issues/343

I was able to track down the conflict to markdowku, I hope this helps solving it.

**Comment by turnermm** [comment]
What is  markdowku?

**Comment by JulioC** [comment]
[markdowku](http://www.tolledomain.ch/dokuwiki/doku.php?id=projects:markdowku) is a plugin to allow markdown rendering on DokuWiki.

**Comment by turnermm** [comment]
You can't run most of the secondary editors together.  It has to be one of the other.

**Comment by JulioC** [comment]
My explanation was too narrow:
It's a plugin that allows rendering markdown on DokuWiki, it doesn't change the editor at all.

**Comment by turnermm** [comment]
The plugin is not hosted on github so I have no easy access to the code.  In any event the problem is something in the way that the markdown plugin overrides native dokuwiki syntax and there's nothing that I can do about that.

**Comment by JulioC** [comment]
Yeah, I wasn't able to find their source code either...

I'll investigate this issue and share any information I find.

If you want, close this issue, please.
