### ISSUE TITLE
Internal link - Create Folder button disappears

### ISSUE THREAD

**Issue by russell-phillips** [turnermm/ckgedit#389]
When creating an internal link, I click the Browse Server button. A button labelled Create Folder is visible when the pop-up window first appears, but then it disappears.

I'm running PHP 5.6, DokuWiki 2017-02-19e "Frusterick Manners".

**Comment by turnermm** [comment]
I think you are referring to `internal media`, where you get a chance to create a new directory into which you can upload media files.

**Comment by russell-phillips** [comment]
I'm referring to the [create_folder](https://www.dokuwiki.org/plugin:ckgedit:configuration#create_folder) option. I've set that to "y".

I'd like to be able to create a new file in a new directory, and link to it. This screenshot shows the pop-up window when it first appears, with a Create Folder button:
![screenshot from 2018-03-15 07-03-11](https://user-images.githubusercontent.com/8222297/37448724-7550f78e-281f-11e8-8af3-e27fa928a088.png)

When the pop-up has finished loading, the Create Folder button has disappeared:
![screenshot from 2018-03-15 07-03-45](https://user-images.githubusercontent.com/8222297/37448741-881bba7a-281f-11e8-8cf0-0f366c7ae35b.png)

I can't see any issue with permissions, and I have the three symlinks (file, image, and media) in fckeditor/userfiles.

I'd like to, for example, create a new directory foo, with file bar inside it, thus creating a new wiki page "bar" in namespace "foo". Is that possible?

**Comment by turnermm** [comment]
That's just a glitch.  It immediately disappears.  Dokuwiki does not allow uploads into data/pages.

**Comment by russell-phillips** [comment]
I don't want to upload, I want to create a new wiki page. Is that not possible?

**Comment by turnermm** [comment]
You can only create new pages with the editor.  That fleeting button appearance has been removed.

**Comment by russell-phillips** [comment]
Shame. Thanks for clarifying, though.

**Comment by turnermm** [comment]
You wouldn't have been able to create a new file using the filebrowser; it doesn't support file creation, only upload.  So you would have had to create a file for upload.
