### ISSUE TITLE
Image copy/paste results in base64 string after saving dokuwiki page

### ISSUE THREAD

**Issue by SamOxyPlot** [turnermm/ckgedit#391]
I do have a problem with COPY/PASTE from a Word document. Can someone help me out?
Thank you in advance!

The preview is OK, but after saving I get a base64 string.
Is there something wrong on my side? 
When I only copy/paste the image there is no problem.

I use: 
•	Dokuwiki version 2015-08-10a “Detritus”
•	Internet Explorer 11
•	CKGEDIT rev_18-Mar_15-20_02
•	PHP 5.4.45 (and also tested with PHP 7.1.7)

This is a sample of a Word document containing a title, image and text.
![ckgedit_screenshot_word_doc](https://user-images.githubusercontent.com/8522340/37760922-0e8c2672-2db0-11e8-9ca2-64650a82addd.png)

Preview:
![ckgedit_screenshot_editor](https://user-images.githubusercontent.com/8522340/37760941-20e6aec8-2db0-11e8-97b9-872c4d6cd5c7.png)

Result after saving:
 
![ckgedit_screenshot_saved_page](https://user-images.githubusercontent.com/8522340/37760947-257f1d9e-2db0-11e8-8902-c0b8e4f6fbff.png)

**Comment by turnermm** [comment]
IE is the only browse which accepts text+img in a copy/paste.  I wasn't aware of this.  The editor as you have found will not accept a text+img, that is the way it was designed.  I'm not sure it's worth the effort to accommodate a browser which is unique in its function and is being phased out.

**Comment by SamOxyPlot** [comment]
We are planning an upgrade of DokuWIKI and the plugins. 
I'm comparing the functionality of both versions.

Currently we are using CKGEDIT version 2014-05-18 on our production server. With that version the COPY/PASTE functionality (text+img) in IE11 works perfectly.

Our WIKI users expecting this behaviour.
Is there something I can change it by myself. Or can you point me in a direction?


Kind regards
Sam

**Comment by turnermm** [comment]
What happens, I have found, is that the MS Word syntax formatting gets applied to the image, which corrupts the image syntax.  You can get around this by selecting the image with your mouse and applying the **Tx** tool to the selected image, which removes the Word formats.  Otherwise there is no  simple way around this.

**Comment by SamOxyPlot** [comment]
Hi 

I can confirm the problem is resolved using the '**Tx**' button in the toolbar when selecting the images one by one.

Thanks for you help!
