### ISSUE TITLE
Space between words deleted when text background changes

### ISSUE THREAD

**Issue by uvemas** [turnermm/ckgedit#392]
In my dokuwiki (release Frusterick Manners) I can observe the following behavior when I use CKGEditor plugin:
- enter a sentence like "This page is under construction"
- select the sentence and change its background color
- save the page
The sentence has been changed to "Thispageisunderconstruction" (all spaces have been removed). 

Notice that it happens very often but NOT always. Any idea about how to fix this problem?

**Comment by turnermm** [comment]
I've never seen this before and am not able to reproduce it.  What other plugins do you have installed?  And what browser on which OS?

**Comment by uvemas** [comment]
It happens at work with Windows 10 and Firefox ESR 38.8. The only installed plugins are those installed by default. I can't reproduce the error at home on my laptop with Ubuntu 16.04 and chromium browser. Maybe the problem is a bad interaction with that Firefox version. Tomorrow I'll try with Internet Explorer or Edge and will tell you.

**Comment by turnermm** [comment]
This has never been reported before, and fonts have been part of ckgedit for at least 5 years and there are lots of users.  So I have to assume it's the implementation of javascript in the browser.  There seem to be more recent versions of that edition of ffox but I don't know anything about it.

**Comment by uvemas** [comment]
It works fine on Windows 10 with Chrome and IExplorer. Seems to be a problem specific to Firefox ESR 38.8. Feel free to close this issue if you want. Thanks for your help.
