### ISSUE TITLE
Cannot read property 'ckg_canonical'

### ISSUE THREAD

**Issue by musdasch** [turnermm/ckgedit#393]
I would like to use the ckgedit plugin but our dokuwiki runs in a IFrame on a different webpage. This results in an error. I have test it without the iframe and the the ckedit runs with out a problem.

The Error is:
Uncaught TypeError: Cannot read property 'ckg_canonical' of undefined
    at a.CKEDITOR.editorConfig (config.js?t=H4P6:1)
    at k (ckeditor.js:246)
    at Object.<anonymous> (ckeditor.js:246)
    at Object.callback (ckeditor.js:236)
    at g (ckeditor.js:234)
    at Array.n (ckeditor.js:234)
    at p (ckeditor.js:234)
    at ckeditor.js:235

I think the problem is in the file config.js and the use of "top.JSINFO.ckg_canonical" / "top.[ something ]". I would suggest to access the object without the "top." or use "window.self."

sincerely
Tim

**Comment by turnermm** [comment]
See this:  https://github.com/turnermm/ckgedit/pull/374.  

You can download this update to config.js at https://github.com/turnermm/ckgedit/pull/374/files.  

I haven’t had time to test in farms, and the original poster hasn’t got back to me on this.  But it should work for you.

**Comment by musdasch** [comment]
thank you very much. The script works just fine.
