### ISSUE TITLE
set cookies as 'httponly'

### ISSUE THREAD

**Issue by sklemer1** [turnermm/ckgedit#395]
https://github.com/turnermm/ckgedit/blob/c21f7daf92dad4a351d5cdde5fc67ebc9d82361a/action/meta.php#L693

Our website security scanner is concerned that the ckgedit cookies are not set 'httponly'. Although it's only about the settings of the GUI editor it shouldn't hurt if you set the very last parameter in every setcookie()-call to 'true'. The impact is that you can't access the cookies via JS anymore. As far as I can see this isn't done anywhere.

The httponly-setcookie() parameter was added in php 5.2 which isn't a problem as you require 5.3.3 already:
https://secure.php.net/manual/en/function.setcookie.php

**Comment by turnermm** [comment]
The likelihood is that this change will break the  ckgeditor filebrowser, which uses javascript to access cookies set in php files.
