### ISSUE TITLE
mathjax ignored

### ISSUE THREAD

**Issue by erincorlez** [turnermm/ckgedit#400]
I'm sorry for a possible duplicate. On the dokuwiki plugin page it says it breaks with mathjax but I couldn't find an issue (solved or open) regarding this.

Issue: the mathjax syntax is ignored. not removed (markup clean up).

Is this because all text is wrapped into an `<p></p>`?

**Comment by turnermm** [comment]
Thanks.  I've removed mathjax from the list of incompatible plugins.  At the time it wasn't working, probably because of the change in url.
