### ISSUE TITLE
Please remove the call to `eval` in the tags.js.unc file

### ISSUE THREAD

**Issue by jvoisin** [turnermm/ckgedit#404]
I'm trying to write a working CSP policy for my Dokuwiki instance, and it seems that the [ckeditor/plugins/tags/dialogs/tags.js.unc]( https://github.com/turnermm/ckgedit/blob/master/ckeditor/plugins/tags/dialogs/tags.js.unc#L17 ) is using the `eval` function.

Since there is [no more call to `eval`]( https://dev.ckeditor.com/ticket/13381 ) in ckeditor, would it please be possible to replace it with a proper function call instead in ckgedit too?

Thank you ♥

**Comment by turnermm** [comment]
Create a pull request, if possible.

**Comment by turnermm** [comment]
Or contact the author of the tag plugin for ckgedit.  You will find his email address in action/tagapi.php.
