### ISSUE TITLE
Internal media without description (using a space) is lost after saving page

### ISSUE THREAD

**Issue by SamOxyPlot** [turnermm/ckgedit#406]
I'm using some big tables with a lot of internal media links. The internal media links don't have a title. I use a space as title.
Saving the page using the CKGEditor make the internal links disappear.

Steps to reproduce:
- Use DokuWiki editor first.
- Add following on a page:
`^Table | {{:playground:test.pdf| }} |`

Result after saving:
![image](https://user-images.githubusercontent.com/8522340/40357751-6f4250c6-5dbd-11e8-9240-0ca797b6efff.png)

- Switch to CKGEditor. Notice the cell is empty. Expected behaviour would be a PDF icon only. 
![image](https://user-images.githubusercontent.com/8522340/40357885-d2d6c68a-5dbd-11e8-813c-1ec2db8fe656.png)

- Result after saving the page:
![image](https://user-images.githubusercontent.com/8522340/40357911-e70f0b58-5dbd-11e8-93a3-b62ff93d3145.png)

Hope this issue can be fixed.

Kind regards,
Sam

**Comment by Speedy-Gonzalez** [comment]
It seems like the CKGeditor can't handle this syntax: `^Table | {{:playground:test.pdf| }} |`

What works for me is to add an text to the link e.g. `^Table | {{:playground:test.pdf| Test.pdf }} |`

or remove the pipe character from the link `^Table | {{:playground:test.pdf }}`

In both situations the file is shown correctly in the CKGeditor.

**Comment by SamOxyPlot** [comment]
Thanks Tom!
