### ISSUE TITLE
V 2018-05-21 broke ckgEdit!

### ISSUE THREAD

**Issue by stigzler** [turnermm/ckgedit#409]
Hi - just updated and now not working. Just presented with blank screen after clicking Edit, with a brief flash of text before going blank. Shame - really like the plugin. 
Using Chrome.

**Comment by turnermm** [comment]
I am not aware of any incompatibility between ckgedit and Greebo.  Check your PHP error logs.

**Comment by turnermm** [comment]
Where dis  you got 2018-5-21?  The last update to ckgedit was  2018-May_17.  There was a May 21 update to ckgdoky.
