### ISSUE TITLE
Disabling Copy as text & Copy from word

### ISSUE THREAD

**Issue by sebastienPoussard** [turnermm/ckgedit#413]
greetings @turnermm 
Since thoses 2 functionnalities doesn't seem to work properly i did succeed to hide thoses buttons.
are you interested in this for a pull request ?

**Comment by turnermm** [comment]
Which buttons?

**Comment by sebastienPoussard** [comment]
" Paste "
" Paste as text "
" Paste from word "
when you click them you have a pop up saying you can't use them for security reason.
according to Mlewand from https://github.com/ckeditor/ckeditor-dev/issues/469
there is no way to make them functional at the moment
so maybe hidding them while it's not functional ?

**Comment by sebastienPoussard** [comment]
FYI
![image](https://user-images.githubusercontent.com/36790379/43324414-53d4f70a-91b4-11e8-840e-c6abcdf022f5.png)

**Comment by turnermm** [comment]
You can still paste Word documents into the editor and to do that you need the Word plugin.  I haven't checked but I assume that the button automatically shows up when the word plugin is installed.  Perhaps you can check how removing the buttons affects the paste operations.

**Comment by sebastienPoussard** [comment]
Pasting from Word documents partially work, for instance, you can't paste texte AND image. 
Anyway my point is, those 3 buttons when clicked show an altert saying you can't use  them for security reasons and you can only use the traditional Ctrl + V to paste content.
this is why i think thoses buttons are useless.

**Comment by turnermm** [comment]
The buttonjs aren't entirely useless because they tell the user what to do, and I believe t he underlying code may be need for certain paste situations.  So again: 
> Perhaps you can check how removing the buttons affects the paste operations.

**Comment by turnermm** [comment]
This issue has been at least partially addressed in the latest ckgedit, which includes a new MS Word tool and hides (but does not remove) the Word code bundled with the CKEditor.
