### ISSUE TITLE
Incompatible with PlantUML Parser plugin

### ISSUE THREAD

**Issue by toneywu** [turnermm/ckgedit#418]
PlantUML is using <uml></uml> tag to mark a UML Diagram
the ckgedit do not encode/decode it correctly.

https://www.dokuwiki.org/plugin:plantumlparser

**Comment by toneywu** [comment]
no, please try the following in native editor

<uml>
|Actor1|
start
:test1;
if (something) then (yes)
  :test2;
else
  |Actor2|
  :test3;
endif
end
</uml>

**Comment by turnermm** [comment]
The only way to deal with this is with the include plugin.  Create a separate page in the dokwuwiki editor with your uml code and then include it in your document that is being edited by ckgedit.

**Comment by turnermm** [comment]
> currently the ckgedit will automatically replace the RETURN while opening the edit page, which makes the UML chart error.

Don't know what your mean.

**Comment by turnermm** [comment]
There's notHing that can be done using the ckgedit editor.  You must use the include plugin.  Create a page in the native dokuwiki editor and then include it in your main page.
