### ISSUE TITLE
Problems with structured data plugin

### ISSUE THREAD

**Issue by stefanobasta** [turnermm/ckgedit#420]
the plugin https://www.dokuwiki.org/plugin:data needs entries like:
  ---- dataentry projects ----
  type            : web development
  website_url     : http://www.microsoft.com
  task_tags       : programming, coding, design, html
  ----
  Text after the end of the data plugin syntax

the ckgedit plugin modify this entries in:
  ---- dataentry projects ---- type : web development website_url : http://www.microsoft.com task_tags : programming, coding, design, html ----Text after the end of the data plugin syntax

with the consequence that the data will not any more fit to the data plugin syntax.

**Comment by turnermm** [comment]
See https://www.dokuwiki.org/plugin:ckgedit:discussion_2#configuration_to_use_different_editors

You should only need the multi_plugin macros

**Comment by turnermm** [comment]
It is  not incompatible with the data plugin.  You should always check back with plugin authors before changing info on the plugin page.

**Comment by stefanobasta** [comment]
You are absolutely right. I had seen the concerning chapter afterwards.


----- Mail original -----
De: "Myron Turner" <notifications@github.com>
À: "turnermm/ckgedit" <ckgedit@noreply.github.com>
Cc: "stefanobasta" <stefanfink@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Samedi 8 Septembre 2018 22:52:18
Objet: Re: [turnermm/ckgedit] Problems with structured data plugin (#420)



It is not incompatible with the data plugin. You should always check back with plugin authors before changing info on the plugin page.
