### ISSUE TITLE
incompatible with the template of sprintdoc

### ISSUE THREAD

**Issue by ichris007** [turnermm/ckgedit#423]
when I apply the dokuwiki template of sprintdoc, there is a bug prompt:
Illegal string offset 'sprintdoc' in /dokuwiki/lib/tpl/sprintdoc/main.php on lien 20

It appears to be an conflict with ckgedit:
https://codesearch.dokuwiki.org/xref/plugin/ckgedit/action/meta.php#787

could you any solution for this?

**Comment by turnermm** [comment]
Line 787 is a simple assignment between DokuWiki globals.    How did you determine line 787 is the culprit when the error is in sprintdoc/main.php. You should contact its author.

**Comment by ichris007** [comment]
@turnermm thx
