### ISSUE TITLE
Horizontal Alignment in Cell Properties missing values in languages other than 'en'

### ISSUE THREAD

**Issue by benmetz** [turnermm/ckgedit#426]
When using the Cell Properties dialog in a table cell, while ckedit is set to a language other then 'en', the values in "Horizontal Alignment" only show "not set" and then multiple empty lines beneath it instead of "Left", "Center", etc.
![cell properties_en](https://user-images.githubusercontent.com/35449611/45613341-46ad6780-ba66-11e8-81d6-55e584ea828a.png)
![cell properties_af](https://user-images.githubusercontent.com/35449611/45613347-5036cf80-ba66-11e8-8629-7d843a73e0dc.png)
![cell properties_de](https://user-images.githubusercontent.com/35449611/45613365-575ddd80-ba66-11e8-9bc6-62e2d597a4c1.png)
![cell properties_en-au](https://user-images.githubusercontent.com/35449611/45613380-63e23600-ba66-11e8-988e-b269d80e2b37.png)

**Comment by turnermm** [comment]
Yes.  There's some kind of slip-up in the CKEditor's language files.  But Dokuwiki doesn't support horizontal alignment or any of these but cell type and the spans.  So, I've removed them from the dialog.
