### ISSUE TITLE
Paragraph inside a list item cause new line in wiki text

### ISSUE THREAD

**Issue by drasco** [turnermm/ckgedit#427]
Minor issue when pasting HTML

`<ol><li><p>lorem ipsum</p></li></ol>`

Results in wikitext of _space space hyphen newline newline_ lorem ipsum

Which after saving and reopening for edit results in

```
<ol>
    <li class="level1">&nbsp;</li>
</ol>

<p>lorem ipsum</p>
```

**Comment by turnermm** [comment]
Haven't been able to reproduce this.  Perhaps it depends on context.

**Comment by drasco** [comment]
That's weird. I just tried again - paste the ol-li-p-p-li-ol html directly into source edit, save the page, go back in and look at the source, and I get ol-li-li-ol-p-p

Recreated in ckgdoku also

**Comment by turnermm** [comment]
Well, yes,  if you paste it into Source.  That accepts what you enter as html.   This is normal.

**Comment by drasco** [comment]
Myron, please read the the bug report properly. 

This issue is not closed.

**Comment by turnermm** [comment]
That's weird. I just tried again - paste the ol-li-p-p-li-ol html directly into source edit, save the page, go back in and look at the source, and I get ol-li-li-ol-p-p

**Comment by turnermm** [comment]
I'm afraid I don't know what you are talking about or what this means:  `Work with me here man`
 
First, if  you are pasting directly into the editor window, as I thought you originally stated, you will find the the plain text html will  be converted to:
  `lt;ol&gt;&lt;li&gt; &lt;p&gt;lorem ipsum&lt;/p&gt; &lt;/li&gt;&lt;/ol&gt;`
In other words the html markup characters have been substituted with html entities.  
Secondly, if you are pasting into the source window, then that is  expected behavior.  
I don't know what you are trying to accomplish.

**Comment by turnermm** [comment]
Dokuwiki cannot accept paragraphs in lists--a new paragraph will be confused with the start of a new list.

**Comment by drasco** [comment]
I'm keen on improving compatibility with external HTML

**Comment by drasco** [comment]
This seems to go well for me - I added some `list_started` conditions on the p tag

In parse_wiki.js -> start
```
  }else if (this.list_started){
    //results += '';//Ideally we'd do p counting, but we can settle for simply putting wiki newline at the end of the paragraph
    return;
  }
```

And parse_wiki.js -> end
```
      if(tag == 'p') {              
        if (this.in_table){
            tag = 'p_insert';
            HTMLParser_TABLE=true;
        }else if (this.list_started){
            results += '\\\\ ';
            return;
        }
      }
```

**Comment by turnermm** [comment]
Seeing the code in isolation, I am not really sure what you are trying to do.  Fork a copy of ckgedit and make a pull request.  As for your desire to see better HTML, that is a function of the dokuwiki parser, not of ckgedit.   As for paragraphs in lists, Dokuwiki has no syntax for placing a paragraph in a list.  As far as I know, the only block leavel element you can insert is a code block.

**Comment by drasco** [comment]
"As for your desire to see better HTML, that is a function of the dokuwiki parser, not of ckgedit"

You're a very strange guy Myron.

I want to be able to paste external HTML - I want to improve the way ckgedit can enable dokuwiki to absorb 3rd party documents - I am not concerned with the HTML that dokuwiki generates.

**Comment by drasco** [comment]
My fork with relevant commit is here

https://github.com/drasco/ckgedit/commit/6443b0b9870fd111cf5f1ccd1bfa9f253b0c1bfe

This worked really well, but I've run into an issue where my source document has an "ol" that uses the "start" attribute. Im pretty stumped how to deal with that for now

My source doc btw is a microsoft documentation - for example https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/deploy-new-installations/install-mailbox-role?view=exchserver-2019

**Comment by drasco** [comment]
"Dokuwiki has no syntax for placing a paragraph in a list"

It does not. But you can fake it using "\\ ", and keeping everything on one line

**Comment by turnermm** [comment]
That's not a paragraph but a line-break and you can achieve the same thing in ckgedit by holding down the SHIFT key and hitting RETURN.

**Comment by drasco** [comment]
"you can achieve the same thing"

Wouldn't you agree that a computer should automate as much as possible?

Take newpagetemplate for example - I "can achieve the same thing" without the auto template, but I would much prefer the computer automate the task of pre-filling the document 

Look. ckgedit is great. I can paste html pages with images and it brings them all in, adds them to wiki media. It's amazing. 

I don't understand your resistance to improving support for external documents.
