### ISSUE TITLE
nonbreaking space is not preserved

### ISSUE THREAD

**Issue by ciradrak** [turnermm/ckgedit#431]
Hi!  Wonderful tool here, thanks for that.

It seems that when a non-breaking space is typed into the ckgedit plugin, that the non-breaking space is not preserved.  It is converted to a regular space.

So, edit ‘:playground:playground’ in ckgedit
Add non-breaking spaces (alt-space / alt+0+1+6+0 / C-S-space / etc), and save.
But no non-breaking spaces show up in dokuwiki/data/pages/playground/playground.txt

By comparison, ‘DW edit’ does preserve the non-breaking spaces.

Humm, I can not use cut-copy-paste on the ckgedit window to recover the non-breaking space, so it seems that they are being purged when typed –– if that helps any.

**Comment by ciradrak** [comment]
I went and tried this on https://ckeditor.com/ckeditor-4/ to see if it was a general problem with the underlying tool.  I was able to easily use non-breaking spaces in the ckeditor4 demo.  So, that does not seem to be the issue.

**Comment by turnermm** [comment]
Dokuwiki doesn't recognize non-breaking spaces, even if the CKEDitor does.

**Comment by ciradrak** [comment]
What do you mean?  Dokuwiki is working with non-breaking spaces for me.  If I type in non-breaking spaces in CKEditor, or using an external tool, I get non-breaking spaces my the wiki pages.  Only ckgedit purges them; seemingly incorrectly.

**Comment by turnermm** [comment]
![nbs](https://user-images.githubusercontent.com/176447/48654264-fb192a80-e9d0-11e8-9cfc-b8717e4e4944.png)

You need a plugin.

**Comment by ciradrak** [comment]
err, no . . .  I’m sorry, I wasn’t trying to be snarky, but you are confused.  Please re-read my original post.  We are not discussing html entities.  And yes, Dokuwiki does support non-breaking spaces very well.  They work great.  I really am sorry if I sound . . . obnoxious.  I’m trying not to be.  Again, you are the one who has done all the work, and I’m grateful for that.  But this is getting really awkward.  (i hate confrontation)

Again, I’m typing literal non-breaking spaces in utf-8 into the editor, not the html entity representing a non-breaking space.  /..\

**Comment by turnermm** [comment]
Yes, we are in fact talking about html entities once we start look at what is happening.

CKEditor sees the byte code for a nonbreaking space and converts it to `&nbsp;` --an html entity.  You can see this by checking the CKEditor's source window.  There is no way around this.  When ckgedit on saving the document sees a `&nbsp;` it converts it to a space.   So if you have three nbsps in a row in the wiki file and load them into ckgedit and then save the document,  you will find that there are in fact three spaces at that location in the wiki file.  But when  HTML finds multiple sequential spaces, it treats them as a single space.  I've tried making changes in the pre-processor to stop the CKEditor from converting the utf8 to html entities but was not successful, for instance by substituting the unicode representation for the html entity.  On the other side I tried handling it in the post-processor but again was unsuccessful. There you have to convert the entity back to utf8.   But when you do that Dokuwiki now sees it as ASCII text.  If you have experience programming, you might try yourself to work out php code that converts  `&nbsp;` back to utf8 and I will see if I can find a place for it in the post-processor.    I'll continue to look around but can't promise anything.  This exercise took a great deal of time, and I pursued it out of curiosity.  But it is a simple task for the nonbreaking space plugin
