### ISSUE TITLE
ckgedit breaks titel of button (DW plugin) when button has CSS styles applied

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [turnermm/ckgedit#442]
Hi,

we're using the latest release of Dokuwiki (Greebo) with the latest ckgedit editor and the DW [button plugin](https://www.dokuwiki.org/plugin:button).

Our problem with this configuration:

When a CSS style is applied to the button the button title gets lost when editing the page with ckgedit.

Buttons without CSS style work without problem. But you need CSS to set the width of a button when a image is attached to the button.

The syntax that's used by the button plugin looks like this:
[[{namespace:image|extra css}wiki page|Title of the link]]

The problem seems to be the second pipe character. All text after the pipe and the pipe itself will be erased when saving the page with the ckgedit editor.

Before saving:
[[{namespace:image|extra css}wiki page|Title of the link]]

And after saving:
[[{namespace:image|extra css}wiki page]]

Is there any setting I can set to avoid this behavior?

Thanks.

**Comment by Speedy-Gonzalez** [comment]
Is there a way to debug ckgedit so I can see for myself what's causing the problem?

**Comment by turnermm** [comment]
I'm not sure what you are doing with this  or how this plugin will work.  The ckgedit buttons are Form inputs type=button, not html buttons.  They are created in edit.php, beginning at line 692.  The  dw edit button starts at line 712.  The jquery code which each button accesses can be examined in  scripts/parse_wiki.js.unc, beginning at line 917.

**Comment by Speedy-Gonzalez** [comment]
I think you got me wrong.

There is a Dokuwiki plugin called 'button' https://www.dokuwiki.org/plugin:button

This plugin enables the placement of buttons inside wiki pages. So instead of links you can create something that looks like a button. You can also add a caption and a picture to the button. 
See this example. This is a normal wiki page with a button (red mark):
![button_on_wiki_page](https://user-images.githubusercontent.com/1389907/49081730-fe6dab00-f247-11e8-8ad6-6a453dbba2e0.png)

To add a button to a wiki page you have to use following syntax:
[[{namespace:image|extra css}wiki page|Title of the link]]

Here an example of one of my wiki pages. On this picture you can see that the button is showing correctly with a nice caption. The button was created with the 'DW edit' editor:
![wanted_pages_with_titel](https://user-images.githubusercontent.com/1389907/49082144-48a35c00-f249-11e8-9b64-4ce230aa1d64.PNG)
In the page source you can see, that the title is set correctly:
[[{:einzel-formular.png?30|width: 12em; height: 4em;}mywiki:wanted_pages|Wanted Pages]]

One this picture you can see that the caption was replaced with the page name and the title is gone. This happens after editing the page with the CKGedit editor. 
![wanted_pages_without_titel](https://user-images.githubusercontent.com/1389907/49082214-81433580-f249-11e8-912e-af0648a9475c.PNG)
The second pipe character and the title is gone (see the yellow mark):
![grafik](https://user-images.githubusercontent.com/1389907/49082419-01699b00-f24a-11e8-8f8d-89eadf8de7f6.png)

So the page source now looks like this:
[[{:einzel-formular.png?30|width: 12em; height: 4em;}mywiki:wanted_pages]]


This happens every time someone is changing anything on that particular page. As long as a change is made on that page, the captions of the buttons are messed up.

**Comment by Speedy-Gonzalez** [comment]
I think the erasing of the pipe and the text happens when the function 'parse_wikitext' from 'parse_wiki-cmpr.js' takes action.

**Comment by turnermm** [comment]
The problem appears to be in the post-processing.  The post processor is in action/save.php. This is too uncommon for me to make an exception for it, but you can do it by creating a regular expression at the top of the script, after current line 38:
      ` $TEXT = $_REQUEST['fck_wikitext'];`

I assume that the problem is that the plugin syntax is confused with standard dokuwiki link/image syntax.  So you will have to disguise this and reverse it back at the end of the script.

**Comment by turnermm** [comment]
Let me know if you need help.

**Comment by Speedy-Gonzalez** [comment]
It didn't work.

But I found the code where the replacement takes place.

In 'save.php' starting at line 184:
```php
          $TEXT = preg_replace_callback(
           '#\[\[(.*?)\]\]#ms',
               function($matches){ 
                    if(preg_match('/(doku|this)\s*>/',$matches[0])) return $matches[0]; // exclude dokuwiki's wiki links
                    global $ID, $conf;      
                    $qs = "";
                    if(preg_match("/\[\[http/",$matches[0])) return $matches[0];  //not an internal link
                      if(preg_match("#\[\[.*?\|\{\{.*?\}\}\]\]#", $matches[0],$matches_1)) {  // media file
                        if(!$this->getConf('rel_links')) { 
                            return $matches[0];
                        }
                      $link = explode('?',$matches[1]); 
                      list($link_id,$linktext) = explode('|', $link[0]); 
                      $current_id = $this->abs2rel($link_id,$ID); 
                      return preg_replace("#$link_id#",$current_id, $matches[0]);                      
                   }                
                
                   $link = explode('?',$matches[1]);
                   if($link[1]) {                       
                       $link_id = $link[0];
                       //list($qs,$linktext) = explode('|', $link[1]);
                   }
                   else list($link_id,$linktext) = explode('|', $link[0]);
                   if($this->getConf('rel_links')) 
                      $current_id = $this->abs2rel($link_id,$ID); 
                    else  $current_id = $link_id;
                    if($qs) $current_id .= "?$qs";
                    
                   //as in _getLinkTitle in xhtml.php
                   if(useHeading('content')) {
                      $tmp_linktext = p_get_first_heading($link_id);
                      if(trim($linktext) == trim($tmp_linktext)) {
                          $linktext = "";
                      }
                   }  
                   $tmp_ar = explode(':',$link_id);
                   $tmp_id = array_pop($tmp_ar);
                   if(trim($linktext,'.: ' ) == trim($tmp_id,'.: ')) $linktext = "";
                              
                   $current_id = $current_id.'|'.$linktext;
                   return '[[' . $current_id .']]';
               },
           $TEXT
         );      
```

I'm not a PHP expert, but maybe I'll find a solution.
Every help is much appreciated.

**Comment by Speedy-Gonzalez** [comment]
I've found a solution.

I've added on top of the file a new function:

```php 
       function startsWith($haystack, $needle)
        {
            $length = strlen($needle);
            return (substr($haystack, 0, $length) === $needle);
        }
```

And added an if statement to check if the variable $matches starts with '[[{'

```php
                   $current_id = $current_id.'|'.$linktext;
                   if(!startsWith($matches[0], '[[{')){#
                       return '[[' . $current_id .']]';
                   } else {
                       return $matches[0];
                   }
               },
```

If you like to you can see the whole file here: https://gist.github.com/Speedy-Gonzalez/be3def6612f87b38cf553f69e272c927

Do you see any problem with these changes?

From what I know no wiki link should ever starts with `[[{` so I don't see any problem with my changes. But time will show...

**Comment by Speedy-Gonzalez** [comment]
Any chance in getting these changes into the official repo?

Like I said I'm not a PHP expert and maybe the code needs improvement to not break anything (I've tested just a few pages yet, but none of them got broken).

Would be nice to see this in the upstream, so I don't have to integrate my patch on every update.

Just let me know what you think of this.

**Comment by turnermm** [comment]
That is a good idea. But I would do something that is probably a little less expensive than defining a new function and a little safer.  
At the top of the file define a new class level variable:
```
class action_plugin_ckgedit_save extends DokuWiki_Action_Plugin {
     var $helper = false;
```
Then at the top of  `ckgedit_save_preprocess`:
```
  function ckgedit_save_preprocess(Doku_Event $event){
        global $ACT,$INPUT;
        $this->helper = $this->loadhelper('ckgedit');

```
 $this->helper = $this->loadhelper('ckgedit');
Then at the top of the function which processes the links add this:
```
   function($matches){ 
           if($this->helper->has_plugin('button') && strpos($matches[0], '[[{') === 0) {    
                   return $matches[0];
             }
```
Of course you already know you have `button` but if this were to go into the ckgedit distribution, this check for `button` would be needed, so that if there are any unintended conequences of this additon, it would affect only users of button.

I've put this all together here:
https://github.com/turnermm/ckgedit/archive/button.zip
If you can report back to me after a few weeks of using it, I'll think about adding it to ckgedit.

**Comment by Speedy-Gonzalez** [comment]
Thank you so much! Looks really good to me.

I'll test it a few weeks and report back to you.

**Comment by Speedy-Gonzalez** [comment]
Works quite nice.

I'll come back to you when we've tested it more intensive.

**Comment by turnermm** [comment]
How are you doing with this?  I just added a pull request for this fix.  If all is going well, I'll merge it into the ckgedit master.

**Comment by Speedy-Gonzalez** [comment]
We had no problems so far. Non of my colleagues reported an error to me.

**Comment by turnermm** [comment]
Thanks.  I've just merge the fix into ckgedit master.

**Comment by Speedy-Gonzalez** [comment]
Thank you!
