### ISSUE TITLE
Whitespaces lost

### ISSUE THREAD

**Issue by roga67** [turnermm/ckgedit#444]
I use the plugin CLI to simulate a bash console to output some stuff like this:

```
~~MULTI_PLUGIN_OPEN~~
<cli prompt='#'>
root@linux ~ # ifconfig
bond0: flags=5123<UP,BROADCAST,MASTER,MULTICAST>  mtu 1500
        ether c2:88:17:2b:4f:0e  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eno16780032: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.241.104  netmask 255.255.255.0  broadcast 192.168.241.255
        inet6 fe80::20c:29ff:fe8d:f3b  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:8d:0f:3b  txqueuelen 1000  (Ethernet)
        RX packets 321  bytes 45099 (44.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 46  bytes 7516 (7.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 12  bytes 792 (792.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 792 (792.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

livecd ~ #

</cli>
~~MULTI_PLUGIN_CLOSE~~
```

But when I save the content, all the formatting with whitespaces are lost and looks like this:

```
root@linux ~ # ifconfig
bond0: flags=5123<UP,BROADCAST,MASTER,MULTICAST>  mtu 1500
ether c2:88:17:2b:4f:0e  txqueuelen 1000  (Ethernet)
RX packets 0  bytes 0 (0.0 B)
RX errors 0  dropped 0  overruns 0  frame 0
TX packets 0  bytes 0 (0.0 B)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
eno16780032: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 192.168.241.104  netmask 255.255.255.0  broadcast 192.168.241.255
inet6 fe80::20c:29ff:fe8d:f3b  prefixlen 64  scopeid 0x20<link>
ether 00:0c:29:8d:0f:3b  txqueuelen 1000  (Ethernet)
RX packets 321  bytes 45099 (44.0 KiB)
RX errors 0  dropped 0  overruns 0  frame 0
TX packets 46  bytes 7516 (7.3 KiB)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
inet 127.0.0.1  netmask 255.0.0.0
inet6 ::1  prefixlen 128  scopeid 0x10<host>
loop  txqueuelen 1000  (Local Loopback)
RX packets 12  bytes 792 (792.0 B)
RX errors 0  dropped 0  overruns 0  frame 0
TX packets 12  bytes 792 (792.0 B)
TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
livecd ~ #
```

instead of:

```
root@linux ~ # ifconfig
bond0: flags=5123<UP,BROADCAST,MASTER,MULTICAST>  mtu 1500
        ether c2:88:17:2b:4f:0e  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eno16780032: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.241.104  netmask 255.255.255.0  broadcast 192.168.241.255
        inet6 fe80::20c:29ff:fe8d:f3b  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:8d:0f:3b  txqueuelen 1000  (Ethernet)
        RX packets 321  bytes 45099 (44.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 46  bytes 7516 (7.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 12  bytes 792 (792.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 792 (792.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

livecd ~ #
```

The same problem occurs, if I use the plugin syntaxhighlighter4.

When I use the DokuWiki Editor all the formattings are ok.

Is it possible to solve this problem?

**Comment by turnermm** [comment]
> Is it possible to solve this problem?

I'm afraid not.  There are some  plugins which do not work with ckgedit.  For this you need to create a code block in the ckgeditor .  Paste your data into the editor, select it with the mouse, and then from the  drop-down `Code` menu, select a code block.

**Comment by turnermm** [comment]
If you want to use the cli plugin, use it with the include plugin, where you can create a page in the Dokuwiki editor that uses the cli plugin and then insert it into the ckgedit page.

**Comment by roga67** [comment]
I gave your idee a try and it's working. It's not the best solution but it helps me to protect the formatting of the cli-plugin to do not be destroyed from ckgedit.

Thank you for this hint.

**Comment by Speedy-Gonzalez** [comment]
@roga67 Maybe you could try to add some line breaks like this:

```
~~MULTI_PLUGIN_OPEN~~

<cli prompt='#'>

root@linux ~ # ifconfig

bond0: flags=5123<UP,BROADCAST,MASTER,MULTICAST>  mtu 1500

        ether c2:88:17:2b:4f:0e  txqueuelen 1000  (Ethernet)

        RX packets 0  bytes 0 (0.0 B)

        RX errors 0  dropped 0  overruns 0  frame 0

        TX packets 0  bytes 0 (0.0 B)

        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eno16780032: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500

        inet 192.168.241.104  netmask 255.255.255.0  broadcast 192.168.241.255

        inet6 fe80::20c:29ff:fe8d:f3b  prefixlen 64  scopeid 0x20<link>

        ether 00:0c:29:8d:0f:3b  txqueuelen 1000  (Ethernet)

        RX packets 321  bytes 45099 (44.0 KiB)

        RX errors 0  dropped 0  overruns 0  frame 0

        TX packets 46  bytes 7516 (7.3 KiB)

        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536

        inet 127.0.0.1  netmask 255.0.0.0

        inet6 ::1  prefixlen 128  scopeid 0x10<host>

        loop  txqueuelen 1000  (Local Loopback)

        RX packets 12  bytes 792 (792.0 B)

        RX errors 0  dropped 0  overruns 0  frame 0

        TX packets 12  bytes 792 (792.0 B)

        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

livecd ~ #

</cli>

~~MULTI_PLUGIN_CLOSE~~
```

Don't know how the page will look then, but CKGedit will not break your page (I hope so). We've had the same problem with the bureaucracy plugin, but the plugin seems to be fine with the extra line breaks and the page looks exactly like it should look like. Maybe this is just fine with the cli plugin too.

**Comment by roga67** [comment]
Add additional line breaks definitely didn't solve the Problem. With the standard dokuwiki editor the page will not be destroyed only when I edit the page with  CKGedit. In my eyes, the problem would be ckgedit.

**Comment by Speedy-Gonzalez** [comment]
> When edit the page with the standard dokuwiki editor the page will not be destroyed only when edit the page with CKGedit. 

I think that's because CKGedit seems to put all lines which are separated only by one line break into one line (without the original line breaks) when editing the page and that's breaking the formatting.

When you have at least one blank line between two lines the editor will interpret them as separate paragraphs and the formatting should be OK when saving the page.
The only problem that will remain is that you will see those extra line breaks in you page and that's possibly not something you want.

I've only written my 'solution' because I had the same problem with the 'bureaucracy' plugin and this was a workaround for me.


But if you're fine with the solution by turnermm stay with it ;)

**Comment by roga67** [comment]
Thank you anyway for your comment. Maybe someone else is happy with your suggestion. Nobody knows it, thanks! :-)

**Comment by turnermm** [comment]
> I think that's because CKGedit seems to put all lines which are separated only by one line break into one line (without the original line breaks) 

The Dokuwiki editor does the same thing, which is why it as the double backslash markup:  `\\` , which preserves the line breaks.   The difference is that it does this when the page is displayed and retains the line-breaks in the  text file.   And that's consistent with the HTML, which has the <br /> tag for creating single line spacing.  The CKEditor is HTML.  To create a <br />,  hold down the `SHIFT-KEY `while hitting `RETURN`.   This is common in  WYSIWYG editors.  But this doesn't always work in syntax plugins, which is the reason the the MULTI_PLUGIN macros.  But the MULTI macros don't recognize indentation, only line breaks, which is why your `cli` text gets moved to the left.
