### ISSUE TITLE
Alignment buttons missing in toolbar

### ISSUE THREAD

**Issue by maba4891** [turnermm/ckgedit#452]
First, thanks for developing and maintaining this great plugin for Dokuwiki!

I installed Dokuwiki only recently and noticed that there are no alignment buttons in the CKEditor plugin. I saw that you mentioned in #42 that "Dokuwiki does not support alignment, except for images. For other alignments you need plugins." but didn't quite understand it. 

Could you elaborate on why Dokuwiki does not support alignment and which plugins enable alignment?

Thanks a lot and happy new year!

**Comment by turnermm** [comment]
I can't speak for the developers of dokuwiki, but they were following the  design of most wikis, which have been conceived of as plain text-based, and alignment falls to WYSIWYG.  There is only one upto-date plugin which is devoted to your question, divalign2.  Even though it is marked as possibly outdated, the plugin is very basic and still works well.  It is simple to use.  You will have to download the updated script.js, which is on the plugin page, and replace the one that comes with the plugin, if you want to have a functioning toolbar button.
