### ISSUE TITLE
CKGEdit internal links

### ISSUE THREAD

**Issue by Balduin94** [turnermm/ckgedit#458]
Hello,

I have recently copy paste data/pages to a new dokuwiki that works with CKGEdit. I am trying to add internal link with the option you gave, the file tree shows my files are here and yet the links keeps redirecting me to "this page doesn't exist yet", it's been 2 days and i am stuck.

I'd be glad if you could help me out.

**Comment by turnermm** [comment]
> with the option you gave,

Don't know what this refers to, or what you are referring to by "file tree".  I'll need more information.  Does it happen in both the ckgedit and the dokuwiki filebrowsers?  And what happens if you switch out of ckgedit and use the dokuwiki editor?

**Comment by Balduin94** [comment]
it was just about the CKGEdit link creator, i found what the pb was and it has nothing to do with CKGEdit

**Comment by turnermm** [comment]
So I will close this issue.  You can always reopen.
