### ISSUE TITLE
FCKeditor not showing img

### ISSUE THREAD

**Issue by Balduin94** [turnermm/ckgedit#459]
Hello,

I use your ckgEditor in 2018-04-22b "Greebo". Material design template. the img that is supposed to be shown in the fckeditor arn't shown and its a problem for me and the poeple using the dokuwiki. 

![screentwo](https://user-images.githubusercontent.com/35695327/52289881-32afc700-296f-11e9-9ffa-1e69adfa2a4e.PNG)

![screenone](https://user-images.githubusercontent.com/35695327/52289871-2d527c80-296f-11e9-98fe-11bdb743f512.PNG)

my conf datas seems to be fine so i really dont get why its not working

![screenthree](https://user-images.githubusercontent.com/35695327/52289924-478c5a80-296f-11e9-83a7-9a433a48ec41.PNG).

CGKeditor is great ohterwise.

**Comment by Balduin94** [comment]
i should have mention it but i already tried as i saw an other issue like mine and nothing happend

**Comment by Balduin94** [comment]
shouldn't the path of the img be build with fetch.php ?

**Comment by turnermm** [comment]
If you are using the dokuwiki media manager, yes.  If you are in the ckgedit filebrowser, no: that fetches the image via url.

**Comment by turnermm** [comment]
See what happens if you switch back to the standard dokuwiki template.

**Comment by Balduin94** [comment]
nothing changed with the vanilla dokuwiki template

**Comment by turnermm** [comment]
You are not really giving enough detail. 
1. What browser(s) are you using?
2. What is your desktop system?
3. What system is your dokuwiki running on?
4.  Do you get the same result with both the ckgedit file browser and the dokuwiki file browser?  
5.  Does this happen only when you are in ckgedit?
6. Try it is both the ckgedit file browser and the dokuwiki and report  back on what in each case you see in the URL field of the link tool.
The following images show what the URL filed looks like in each of the two cases:
### Dokuwiki media manager:
![mediamgr](https://user-images.githubusercontent.com/176447/52364126-1c0a7e00-2a0a-11e9-88fc-c57a488c7101.png)
### Ckgedit Filebrowser:
![image_dialog](https://user-images.githubusercontent.com/176447/52364127-1c0a7e00-2a0a-11e9-87b5-f7f3a6347b3e.png)

**Comment by Balduin94** [comment]
My dokuwiki is on a lunix server that i acces with an ftp on a windows computer. I am using chrome.
i indeed get the same result by setting the media manager to dokuwiki and to ckgedit media manager.

i've done the test you wanted, dokuwiki with and without winstyle and ckgedit with and without wynstyle and y always get the same patch for the files: 

`/data/media/4a48f10ee01e897e7f4788ac1d4a836b.png`

And yes if i am using the default media manager(even if it looks gross) the img are shown (path with the fetch.php? url) but i really wana make yours works as it is much better and much more userfriendly

**Comment by Balduin94** [comment]
if ever it helps, my .htacces in data/media for winstyle is looking like this: 

`#unix  -- do not change or move
<IfModule mod_authz_host>
    Require all denied
</IfModule>
<IfModule !mod_authz_host>
    Order allow,deny
    Deny from all
</IfModule>

<FilesMatch "\.(gif|jpe?g|png)$"> 
<IfModule mod_authz_host>
    Require all granted
</IfModule>
<IfModule !mod_authz_host>
    Order allow,deny
    Allow from all
</IfModule>
</FilesMatch>

Options -Indexes
`

**Comment by Balduin94** [comment]
he seems to never been able to use the winstyle option as i never get a path with userfile

**Comment by turnermm** [comment]
> he seems to never been able to use the winstyle option as i never get a path with userfile

I don't understand this.

This could be a permissions issue, or a corrupt image.  Are you uploading your images with ftp?  Then don't do that.  Use the ckgedit upload functions.

**Comment by Balduin94** [comment]
I use CKG to upload them, the folder and files have 755 as rights so they are supposed to be readable. 
> he seems to never been able to use the winstyle option as i never get a path with userfile
what i meant is i never get img path that use userfiles, i only
get data/media/an_img or fetch?media:=an_img

**Comment by turnermm** [comment]
> /data/media/4a48f10ee01e897e7f4788ac1d4a836b.png

I just noticed that this is incorrect.  It's missing the wiki name, as in my image.  It should be:  
`</your_dokuwiki>/data/media/4a48f10ee01e897e7f4788ac1d4a836b.png`
In my image,` /devel/ `is the wiki name.  The problem may be in the .htaccess file in  your root directory:  what is your `RewriteBase` set to?  Or in the Coniguration Manager `baseurl `

**Comment by Balduin94** [comment]
My base URL is http://wiki.orion.lan
and my basedir is empty

**Comment by turnermm** [comment]
What url do you use to access you wiki?  Also attach a copy of an image that fails.

**Comment by Balduin94** [comment]
http://wiki.orion.lan/doku.php?id=start is my url
![fde71017754bd0588aca42e64ceadb76](https://user-images.githubusercontent.com/35695327/53404668-6b631f00-39b6-11e9-8548-54a1356ef914.png)

here is a copy on an img (they all fail with fckEdit) and they work with the regular DW media manager but its ugly

**Comment by turnermm** [comment]
What do you mean by "ugly"?  

In your case, this is the correct url format for the image in the image dialog:
   ` /lib/exe/fetch.php?media=:wiki:dokuwiki-128.png`
That's because your wiki is in the document root directory, which hadn't been clear earlier.

**Comment by Balduin94** [comment]
![swmediamanager](https://user-images.githubusercontent.com/35695327/53421835-a2e5c180-39de-11e9-9deb-d8fda6a77f6b.PNG)

thats what i meant by ugly, it works but i just wanted to use yours for its clearer and more userfriendly but i still cant get it working so

**Comment by turnermm** [comment]
This doesn't look anything like the standard media manager.  What template are you using?

**Comment by turnermm** [comment]
I don't think I can help you without have some access to your wiki.
