### ISSUE TITLE
ckgedit adds new lines in table layout

### ISSUE THREAD

**Issue by kerlerm** [turnermm/ckgedit#461]
ckgedit-master as of today (190221) fails to handle some specific situation I have in my dokuwiki:

A table contains several rows and several lines, with mixed content (code blocks and normal text). When changing content and saving the page, ckgedit adds newline indicators (double backslashes) to the last line... This happens with every save, so the newlines get more and more...

DW-Code:

https://gist.github.com/kerlerm/81c4794a823be7a6def4435e6c8828d5

How to reproduce:
1. Paste code to playground
2. Save
3. Edit with Ckgeditor
4. Change arbitrary string
5. Save

Resulting DW code:

https://gist.github.com/kerlerm/01e8fd58b454f990adbb3105bf253656

**Comment by turnermm** [comment]
Test this branch to see if it works without any side effects:  
https://github.com/turnermm/ckgedit/archive/cblock_tbl.zip
Please report back.
Thanks.

**Comment by kerlerm** [comment]
Thanks for the zip! The new line problem has disappeared.

But I store strings with three backslashes in a row in the code blocks.Those are shortened to a single backslash... I don't know if this is a side effect of the change. Rather another special case :)

https://gist.github.com/kerlerm/d7aa2000375cf54683118285291f315b

Result:

https://gist.github.com/kerlerm/d3c4880ce2ace1b9c05ca02bc3d273c3

**Comment by turnermm** [comment]
> I don't know if this is a side effect of the change. Rather another special case

No, that's a separate issue.  File a new bug report.
