### ISSUE TITLE
Paragraphs get removed when an unordered list, strong and a minus sign is used

### ISSUE THREAD

**Issue by unmadu** [turnermm/ckgedit#466]
Hello, 

when you save this text with CKGEdit all the paragraphs in the texts get removed and its saved as one line.

This text:

>**bold text**: some text - **bold text**
>
>**bold text**: some text some text - **bold text**
>
>**bold text**: some text - **bold text**
>
>**bold text**: some text - b**old text** some text
>
>   * list**point**

turns into this text:

>**bold text**: some text - **bold text** **bold text**: some text some text - **bold text** **bold text**: >some text - **bold text** **bold text**: some text - b**old text** some text
>   * list**point**

Some things that altered the result:
- I removed the bold part in the list and saved -> no erroneous save
- I removed the minus signs in the texts -> no erroneous save

I cant expect this trial and error from my users to solve this problem but I hope it can give you a hint for the cause of this issue.

Using DokuWiki Release 2017-02-19e "Frusterick Manners" and the latest CKGEdit, updated on 26.02.2019 (Version from 30.01.2019).
 
Greetings and thx for this essential editor.

**Comment by turnermm** [comment]
Not sure when I can get to this, and it may be one of those elusive bugs that's hard to track down, and so may be simplest to make a hack-ish fix.  But in the meantime, you can avoid this by enclosing the dash between the double escape markup: `%%-%%`

**Comment by turnermm** [comment]
This is now fixed.

**Comment by unmadu** [comment]
Thanks a lot, it works.

Greetings
