### ISSUE TITLE
Font colour in table cell causes text to be displayed as code block

### ISSUE THREAD

**Issue by grumpy-gnome** [turnermm/ckgedit#469]
When editing the font colour of some of the contents of a table cell, the markup appears to become corrupted causing the following text in the cell to be displayed as a code block. The incorrect display is fixed when the font colour is removed.

Bizarrely, when the font colour is changed and the page is opened in the editor, it displays correctly!

See the screen grabs:

Table contents before the font colour is changed...
![Before colour change](https://user-images.githubusercontent.com/33554688/54179523-e2a5b200-4490-11e9-9612-144c8b40845d.png)

After the colour change...
![after colour change](https://user-images.githubusercontent.com/33554688/54179528-e6d1cf80-4490-11e9-9423-c0e6a3aab2ca.png)

As it appears in the editor...
![As seen in editor](https://user-images.githubusercontent.com/33554688/54179536-e9ccc000-4490-11e9-92d7-785834f9ce87.png)

**Comment by turnermm** [comment]
Perhaps this will help:
https://www.dokuwiki.org/plugin:ckgedit:font_styling#editing_styles
