### ISSUE TITLE
Enable SCAYT blocks the whole computer

### ISSUE THREAD

**Issue by MrReSc** [turnermm/ckgedit#470]
I have SCAYT activated by default. When I edit a page that has embedded videos {{installation.mp4|installation.mp4}}} then the browser blocks completely.  If I do the same and have SCAYT turned off by default in the settings, then everything works as expected. As soon as I activate SCAYT with the button, the same thing happens again.
Firefox and Chrome behave differently. With Firefox my RAM is very heavily filled. With Chrome this doesn't happen but the CPU load is almost 100% and the browser doesn't react correctly anymore.

![2019-03-29_06-18-53](https://user-images.githubusercontent.com/24952268/55211417-2a943b00-51ec-11e9-8803-bae64d73a761.png)

**Comment by turnermm** [comment]
Scayt is embedded in the CKEditor.  I have no control over its functioning.
