### ISSUE TITLE
Redirect from included pages

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#471]
Hi,

the configuration of the include plugin offers the option "doredirect" to jump back to the original page after editing the included page or section. But this option is ignored by ckgedit.

_Example:_
On the main page `pflege:strukturdetails` there is a subsection which is included by means of the include plugin. The syntax for this is `{{page>technik:strukturaufbau&editbutton}}`. When I click on the edit button for this included section I'll jump to the page `technik:strukturaufbau`, which is correct. But then, after saving I would expect to jump back to the page `pflege:strukturdetails`, but I'll go to `technik:strukturaufbau`.

Best regards
Juergen

**Comment by turnermm** [comment]
Can't help you with this.

**Comment by Juergen-aus-Koeln** [comment]
I don't know what to do about it now! 

I'm currently trying to create a workaround because of the problems using the CKGeditor in combination with the Struct Plugin.

For this I have created a predefined layout for wiki pages with data from the Struct plugin, where you can create text sections using the command "section...". of the Include plugin with the CKGEditor. But this only makes sense if I automatically jump back to the whole page after editing.

**Comment by turnermm** [comment]
I am not familiar with the struct plugin but if it is similar in the syntax structure and function to the data plugin, see this: 
https://www.dokuwiki.org/plugin:ckgedit:discussion_2#configuration_to_use_different_editors
You will have to determine if the target parameter is still in use for the struct plugin in order to enable the by-pass and substitute its name for the data plugin name.

**Comment by turnermm** [comment]
If you are successfuol in the above, please let me know and I wukk build your solution into ckgedit.

**Comment by Juergen-aus-Koeln** [comment]
Sorry, but it wasn't successful. After saving the page the struct data is eliminated.

**Comment by turnermm** [comment]
Was the markup left and just the data missing, or was everything gone?  If I get the time I might look at the struct plugin.  But in the meantime you'll have to  continue using the include plugin.

**Comment by Juergen-aus-Koeln** [comment]
The struct data was gone

**Comment by TrapSpace** [comment]
Researching this proble, 

> Hi,
> 
> the configuration of the include plugin offers the option "doredirect" to jump back to the original page after editing the included page or section. But this option is ignored by ckgedit.
> 
> _Example:_
> On the main page `pflege:strukturdetails` there is a subsection which is included by means of the include plugin. The syntax for this is `{{page>technik:strukturaufbau&editbutton}}`. When I click on the edit button for this included section I'll jump to the page `technik:strukturaufbau`, which is correct. But then, after saving I would expect to jump back to the page `pflege:strukturdetails`, but I'll go to `technik:strukturaufbau`.
> 
> Best regards
> Juergen

@turnermm Currently having this problem too. Traced it back to the following:

For this to work the CKGedit plugin must copy the following input 
`<input` type="hidden" name="redirect_id" value="mcl:cardiologie">`
which is provided to the CKGedit  by the POST form once the user clicks on the edit button to get to the editor. 

The normal dokuwiki editor copies this input and displays it on the editor html page, but it gets dropped on the CKGeditor html page. If I manually add it to the CKGeditor html page, it works fine as expected.

**Comment by turnermm** [comment]
I'm not sure when I will be able to get to this.  There is a major change in store for dokuwiki development, and I am in the process of testing my plugins, some 30 or 40, to make sure they conform to the new requirements.

**Comment by TrapSpace** [comment]
@turnermm Thanks for you reply. Understandable with so many plugins. 
Maybe if you provide me with an idea where in the code this plugin deals with the POST parameters received from the "do Edit" action. I could take a crack at a hotfix / PR. 

Cheers

**Comment by turnermm** [comment]
> which is provided to the CKGedit by the POST form once the user clicks on the edit button to get to the editor

Are you talking about the initial edit button that opens the include? Then that would have to be picked up on the save, unless I'm not understanding this.

**Comment by turnermm** [comment]
In action/edit.php set $test line 20 to true; this will gitve you a test button in the editor

**In scripts/parse_wiki.js.unc:**
   See 1626ff  and 1804ff for how to add a hidden input element to the edit button 
In action/meta.php see the following function for how to capture $_REQUEST variables using the $INPUT class.  Then add your $_REQUEST values to the $JSINFO  array.  In the javascript this becomes JSINFO. 
See the plugin page at dokuwiki.org where you will find info about ckgedit's compression of scripts; the .unc files are uncompressed and are for development not production.  

 **Go to the end of the parse_wiki script:** 
there you will find a group of jquery functions that are activated when dokuwiki had finished load in the browser.  Here you will find examples of the JSINFO array and here is where you will put your additional code.
file_type() 740ff
  $JSINFO becomes JSINFO

**Comment by turnermm** [comment]
I don't know what you are using the include plugin for, but if it's to by-pass the ckgeditor in favor of the dokuwiki editor, then just add the include page or namespace the dwedit_ns option to get what you want.

https://www.dokuwiki.org/plugin:ckgedit:configuration#dwedit_ns

**Comment by turnermm** [comment]
Try this: https://github.com/turnermm/ckgedit/archive/redirect.zip

**Comment by turnermm** [comment]
Try this https://github.com/turnermm/ckgedit/archive/redirect.zip

Please report back. Thanks.

**Comment by turnermm** [comment]
Done in #498
