### ISSUE TITLE
HTML-tags disappear in combination with a plugin that extends syntax

### ISSUE THREAD

**Issue by A-Gov** [turnermm/ckgedit#472]
Hello!

Your CKEditor plugin is a great tool that makes creating documentation for DokuWiki much more convenient and enjoyable.
Instead of keeping the syntax in mind, we can concentrate on thinking through the text. That's great! Thank!

I have been creating knowledge bases on DokuWiki for several years. And now, for the first time, I myself had to create a little simple «plugin» myself. 
Its essence is to create pseudo-lists. It is needed in cases when using another plugin – togglewrap (https://www.dokuwiki.org/plugin:togglewrap) – which "breaks" the lists.
The text of my plugin is below, at the end of the letter.

However, there is one problem. When my plugin is installed - the CKEditor in the edit mode stops displaying the "<>" and "</> tags in the lines whose beginning corresponds to my plug-in.
Regardless of which text is inside the brackets.

This is the text in DokuWiki Editor:
![Example1](https://user-images.githubusercontent.com/50098112/56882448-43eb0a00-6a6c-11e9-8f73-6ae51cce9698.png) 

This is the text in CKEditor - lost tags around text 1.
![Example2](https://user-images.githubusercontent.com/50098112/56882450-4483a080-6a6c-11e9-9f87-9781b98d35e0.png)
 
In the source you can see that the tags are simply not html-converted:
![Example3](https://user-images.githubusercontent.com/50098112/56887138-70595300-6a79-11e9-8d2f-9ad8e61fe2e7.png)
 
I would be very grateful if you tell me which direction in the CKEditor parser code I should to look for a solution to this problem. Perhaps you can offer a solution?

I will also gladly pay for your work on the development of the CKEditor (I have a few more ideas :)) - if you call the price.

Thanks again for the plugin you created.

With a hope for cooperation,
Alexander Govorunov

[sublist.txt](https://github.com/turnermm/ckgedit/files/3126374/sublist.txt)

**Comment by turnermm** [comment]
See https://www.mturner.org/devel/playground/togglewrap
If what you see there is suitable, you  can download the modified plugin from that page.  The modifictation is just a few lines in the jQuery script.  If you don't care for it, then I will give you instructions as to how you can debug and possibly modify the ckgedit parser.  But it's not a project I myself plane to work on.

**Comment by A-Gov** [comment]
Thank you so much!

In fact, the solution you proposed is not exactly what I needed :). My "sublist" plugin - makes **numbered** lists nested in ordinary numbered lists when "togglewrap" plugin incorrectly displayed hidden items.

But thanks to the example shown by you - I understood how to fix the "togglewrap" so that he did everything correctly with hidden points :)

And now my plugin is just not needed :) And there are no problems with displaying tags in the CKEditor either :)

Once again - a big, very big thank you - and for the fact that you quickly responded to the question, and for the useful hint!

I will clarify: did I understand correctly that you are not very interested in developing the CKEditor "customized"?

**Comment by turnermm** [comment]
> I will clarify: did I understand correctly that you are not very interested in developing the CKGEdit "customized"?

Yes.  That's correct.

**Comment by A-Gov** [comment]
I am by no means saying that you did something wrong! On the contrary - I am very grateful to you for guiding me to the decision!

It is a pity, of course, that you are not interested in developing an CKGEdit. Maybe you can recommend a specialist for such tasks?

Or - can I hope for your help with advice, tips etc.?
Provided, of course, that I will not pester you very much :)

**Comment by turnermm** [comment]
> It is a pity, of course, that you are not interested in developing an CKGEdit. Maybe you can recommend a specialist for such tasks?

I'm afraid I can't.  While I've found the occasional person who has made contributions, no one has shown an interest in working on the project as a whole.

**Comment by A-Gov** [comment]
It’s a pity, of course...
I would like to start developing this project, but my knowledge in php and js can’t even be called "base" :(

And, at the same time, there are a lot of ideas ...

If you can, still ask you a few questions :)

"To highlight" the syntax of some DokuWiki plugins in the CKGEdit window (for example, the same "<wrap ...>", or include {{...}}, etc.) - this can be made via jQuery, right? But in which of the scripts and where in the CKGEdit should I add a fragment for highlighting the text?

**Comment by turnermm** [comment]
>  this can be made via jQuery, right? But in which of the scripts and where in the CKGEdit should I add a fragment for highlighting the text?

For this your best choice would be to use css.  In /ckgedit/ckeditor the css file for the editor is contents.css, but it is compressed.  The uncompressed master is contents.css.unc.  For compressing see the ckgedit plugin page at dokuwiki.org.

**Comment by A-Gov** [comment]
Thank you for your time and knowledge!

I apologize, but the plugin syntax fragments are simply text. They are not marked out in any way, no tags. So, to set the style through the css will not work - because there is no selector in the text?

I already climbed into contents.css :) - I corrected the styles of lists. But there were tags ...

**Comment by turnermm** [comment]
Ckgedit does not normally implement plugin output, it only retains the plugin syntax in place so that when the page is displayed the plugin can do its work.  Ckgedit cannot be responsible for implementing the output of some a 1000 or more dokuwiki plugins.

**Comment by A-Gov** [comment]
Without any doubt! Ensuring the processing of a huge number of plug-ins is an unrealistic task. But I want to visualize only some of them - the most frequently used in my work. And to visualize not how they should work. I want just highlight them in the text - so that the user-editor in the total mass of the text could clearly see fragments of the syntactic constructions of plug-ins.

It is not enough to use contents.css for this, because the syntax insertions of plug-ins do not have nodes in the source text of the CKEditor. And the CSS does not have a selector for the text.

Those. I must either specify the CCS at the parsing stage through the jQuery, or add tags at the parsing stage for the CCS to work.

And so far I have not been able to understand the parsing js-scripts: (

**Comment by turnermm** [comment]
It's just not in the cards.   You can ask only because you don't know what you are asking for.
