### ISSUE TITLE
Property dw_users not working

### ISSUE THREAD

**Issue by SamOxyPlot** [turnermm/ckgedit#474]
Hi 

I've made a group named **@dw_editor_priority**.

The checkbox **dw_priority** is checked. For the field **dw_users** I've took the group **@dw_editor_priority**.

However it's not working. When a user of that group edits a page the default editor is **CKG Edit**. I has to be **DW Editor** according to the settings.

I'm using version: **_ckgEdit-ckedit_4-18-Mar_15-20_02**

Hopefully someone can help me out.

With kind regards,
Sam

![ckgedit_vs_dwedit](https://user-images.githubusercontent.com/8522340/57080354-a48b7880-6cf2-11e9-88b8-6e2b4e25808a.png)

**Comment by turnermm** [comment]
First, remove the `@` from  `@dw_editor_priority`.  Second, make sure you have cleared your browser cache.

**Comment by SamOxyPlot** [comment]
Works!

**Comment by SamOxyPlot** [comment]
Seems the problem stays when using IE11.

**I have at least 2 PC's with IE11 that stills don't function correctly after clearing the browsercache.**

Other browsers like Chrome en Edge are working.

The main problem is that IE11 is used as primary browser.

I hope this can be fixed (even for IE11 users).

Thanks in advance!

Kind regards
Sam

**Comment by turnermm** [comment]
I just loaded up IE 11, tested, and it seems to work.  This is IE 11 on Windows 10, which is the only Windows test unit I have.

**Comment by SamOxyPlot** [comment]
It ended up with a **necessary** switch from CKG to DW editor even when the cache was cleared.

Next time the browser was fired up IE11 took the correct editor (DW editor).

**Problem solved!**
