### ISSUE TITLE
Editing CKEditor config

### ISSUE THREAD

**Issue by larryhudson** [turnermm/ckgedit#481]
Hi! Thanks so much for making this plugin.

I've found that by default, this plugin copies font styles from a Word doc. My preferred config is to have it copy semantic info (eg. heading levels and list items) but not font styles.

It looks like changing the 'pasteFromWordRemoveFontStyles' config value in ckeditor/config.js to 'false' will solve this issue.

I've changed the value in lib/plugins/ckgedit/ckeditor/config.js, but it doesn't seem to change ckgedit's behaviour. Do I need to restart or rebuild something in order for the change to take effect?

**Comment by turnermm** [comment]
There are no guarantees of a carry-over from Word to ckgedit.

**Comment by turnermm** [comment]
Current browsers no longer allow you to paste directly from the clipboard using the mouse or a button.  In Windows you have to use ctrL-V, in Mac cmd-V.  CKGEdit has no control over that. The msword toolbar app may be useful in some cases, but it strips out most styles.

**Comment by larryhudson** [comment]
Hmm, I'm just wondering if I can change the internal CKEditor config, because I use CKEditor in Django and it has the functionality that I prefer - If I copy and paste text with the Word Style 'Heading 2' and it's orange Verdana, it gets pasted in a <h2> element but none of the font styles are there. I think it might be the 'pasteFromWordRemoveFontStyles' setting that needs to change.

**Comment by turnermm** [comment]
It's the msword toolbar app that strips out most styles.  It has nothing to do with the ckeditor.  With firefox you can paste directly into the editor--you may have to turn on supplementary paste support.  With Chrome you have to turn on supplementary paste support.  Ckgedit may then strip out some font-related things which are incompatible with dokuwiki, everything else is up to the CKEditor. You are looking for more than is possible.

**Comment by larryhudson** [comment]
Thanks, I'll do some testing with supplementary paste support.

You're saying that ckgedit doesn't follow ckeditor's internal pasteFromWordRemoveFontStyles setting?

So doing the opposite of this (setting it to true instead of false) wouldn't do anything:
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_howtos_pasting.html

**Comment by MrReSc** [comment]
I'm actually trying to achieve exactly the same thing as @larryhudson. Unfortunately without success.
I tried to install the plugin [pastetext](https://ckeditor.com/cke4/addon/pastetext) . Unfortunately I didn't manage that either. @turnermm can you help?

**Comment by MrReSc** [comment]
@larryhudson I've found a solution. See #380

**Comment by larryhudson** [comment]
Thanks @MrReSc - it seems that my original solution in the OP actually did work - I just forgot about clearing the browser cache.

Good to know that we can edit the config.js and have changes stick!

**Comment by turnermm** [comment]
@MrReSc the current geshi tool does what you are asking (I think).
