### ISSUE TITLE
Graphviz with MULTI_PLUGIN_OPEN still malformed

### ISSUE THREAD

**Issue by amc90** [turnermm/ckgedit#482]
It seems that even when wrapped with `~~MULTI_PLUGIN_OPEN~~` the `<graphviz>` plugin output is malformed. For example, if I edit the first line of the page:
```
test

~~MULTI_PLUGIN_OPEN~~
<graphviz dot>
digraph G {
        A->B
        A [label="AAAA"]

        B [label="Two\nlines"]

}

</graphviz>
~~MULTI_PLUGIN_CLOSE~~

test
```

The source becomes:

```
txest

~~MULTI_PLUGIN_OPEN~~

<graphviz dot>
digraph G {
<code>
A->B
A [label="AAAA"]
</code>
<code>
B [label="Two
nlines"]
</code>
}
</graphviz>
~~MULTI_PLUGIN_CLOSE~~

test

```

In particular, backslash n is replaced with a newline followed by n, and `<code>` tags are added.

Is there some way to tell ckgedit to leave a block completely alone?

Thanks,

**Comment by amc90** [comment]
Another example, is this page:
```
~~MULTI_PLUGIN_OPEN~~

<graphviz dot>
digraph G {
A->B
}
</graphviz>
~~MULTI_PLUGIN_CLOSE~~

```

The "dash, greater-than" becomes an actual arrow character.

**Comment by turnermm** [comment]
The **second issue** is from Dokuwiki's entity substitution:
https://www.dokuwiki.org/entities
You might want to remove the right arrow substitution from conf/entities.conf and replace it with a form such as suggested here, if you feel you need the right arrow:
https://www.mturner.org/devel/playground/entities

The **first issue** may need the include plugin.  See:
https://www.mturner.org/devel/playground/include_ditaa

**Comment by amc90** [comment]
The include plugin seems like a working workaround (although I've now got a whole bunch of pages to hand edit!). It would still be nice to have a way to get the editor to completely ignore the contents of multiline plugins, though.

It seems that the entity substitution only affects Ckgedit - the native editor doesn't substitute it inside the <graphviz/> tags. Even if I do type "->" regularly using the native editor, and it is written as an arrow character in the rendered page when I edit the page I can see the two characters "->".

Anyway, thanks for the workaround.

**Comment by turnermm** [comment]
That's because it's inside a syntax plugin.  But ckgedit doesn't parse dokuwiki plugins, it only preserves the markup but, as you can see, only in a limited way.

**Comment by code54nl** [comment]
Just wanted to let you know I have the exact same issue. Also with **graphviz**, also tried `~~MULTI_PLUGIN_OPEN~~`
Would be nice to have this working. That syntax between these Multi-plugin tags as kept preserved.

**Comment by turnermm** [comment]
The multi_plugin macros are for preserving the line-breaks in plugin syntax that uses more than one line, not for creating a kind of sand-box for the syntax.  It is something I've thought about.
