### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by yyhhrr** [turnermm/ckgedit#483]
I'm using the latest Ckgedit, found that can't upload pictures, system prompt "Error creating folder"/var/WWW/dokuwiki/lib/plugins/Ckgedit/fckeditor/userfiles/images/" (mkdir () : Permission denied) ", what should I do? thank you

**Comment by turnermm** [comment]
You can by-pass userfiles  by setting  the ckgedit `winstyle` configuration option to true

**Comment by yyhhrr** [comment]
Thank you,it is solved
