### ISSUE TITLE
don't always keep li tags, when color added on font

### ISSUE THREAD

**Issue by vinsse2001** [turnermm/ckgedit#484]
Hi !
Thanks for your plugin, very usefull ;)
I see that often, when I create a bullet list ("li" tag) if I change color of complete text (more than one line), the bullets are lost, replaced by "*"
If you can look at this bug, thank you !
My plugin ckgedit, and dokuwiki are up to date.

**Comment by turnermm** [comment]
Truthfully, there are no guarantees when using color with complex structures.  Perhaps you can try marking each line individually, rather than grabbing up the two lines at the same time.  I'll look at this eventually, but at the moment I can't get to it .  If you try my suggestion, let me know the result.

**Comment by vinsse2001** [comment]
Hi Myron,

Here some tests :
- I removed all color on a paragraph, put correctly bullets (instead of
'*'), saved, it was ok
- if I change color of all lines, one by one, always the problem
- if I add a space at each end of line and remove its formatting, it is ok
at first save, but if I change again the page (not necessary the paragraph,
but it is included in the modified page), again the problem

So for the moment, I can use this tip : add a space at the end of each line
(if I need to change color of full line, of course), and modify only
paragraphs, not full page...
Not very useful, but your plugin is very helpful, so thanks for your work !
I will not complain ;)

Vincent


Le lun. 24 juin 2019 à 05:26, Myron Turner <notifications@github.com> a
écrit :

**Comment by turnermm** [comment]
I just did a quick test and cannot reproduce this.

**Comment by vinsse2001** [comment]
If it can helps, here is the source code of page.
You will see 2 big paragraphs : one in green, on in purple.

Le lun. 24 juin 2019 à 13:13, Myron Turner <notifications@github.com> a
écrit :

**Comment by turnermm** [comment]
The source code doesn't show up for me.

**Comment by vinsse2001** [comment]
oops, file attachment is KO with mail answer...

I try again
[sourcecode.zip](https://github.com/turnermm/ckgedit/files/3321625/sourcecode.zip)

**Comment by turnermm** [comment]
I see what you mean but as I said at the outset, there's no guarantees with cinpolkex structures,  I would use the color plugin for this or one of the other plugins that offer color.
