### ISSUE TITLE
CKGedit not showing, displaying "error" message in pop-up dialog box, and replacig all content with "false"

### ISSUE THREAD

**Issue by arthurdehavn** [turnermm/ckgedit#489]
Hello,

I just installed CKGedit in my DokuWiki and I am facing trouble making it work.
Installation (online or manual) goes well. But when I try to modify an article, as the editing page opens, a pop-up dialog appears, mentioning "error" (with no more info). If I click on its "OK" button, a second dialog appears with no info at all. When I click on its "OK" button, I can see that CKGedit didn't load.
I can only see the bottom buttons : Save, clear, DW editor,... And if I click on any of these buttons, the article closes and all text is replaced by "false".

The console displays :
```
TypeError: locktimer is undefined 6 doku.php:341:3
TypeError: locktimer is undefined 2 doku.php:341:3
Le script à l’adresse « https://www.mysite.com/testdw/lib/exe/js.php?t=bootstrap3&tseed=5cc5b619c1cad98c6d2ebd445094baeb » a été chargé alors que son type MIME (« text/html ») n’est pas un type MIME JavaScript valide.
doku.php
JQMIGRATE: Migrate is installed, version 3.0.0 jquery.php:20:454
Le script à l’adresse « https://www.mysite.com/testdw/lib/exe/js.php?t=bootstrap3&tseed=5cc5b619c1cad98c6d2ebd445094baeb » a été chargé alors que son type MIME (« text/html ») n’est pas un type MIME JavaScript valide.
doku.php
Échec du chargement pour l’élément <script> dont la source est « https://www.mysite.com/testdw/lib/exe/js.php?t=bootstrap3&tseed=5cc5b619c1cad98c6d2ebd445094baeb ». doku.php:28:1
TypeError: locktimer is undefined doku.php:341:3
ReferenceError: DOKU_BASE is not defined script-cmpr.js:1:706
ReferenceError: DOKU_BASE is not defined doku.php:597:22
TypeError: locktimer is undefined doku.php:341:3
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://undefinedlib/exe/ajax.php?call=geshi_sel. Raison : échec de la requête CORS.

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://undefinedlib/exe/ajax.php. Raison : échec de la requête CORS.

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://undefinedlib/plugins/ckgedit/ckeditor/dwsmileys.php. Raison : échec de la requête CORS.

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://undefinedlib/plugins/ckgedit/ckeditor/get_version.php. Raison : échec de la requête CORS.

TypeError: locktimer is undefined doku.php:341:3
ReferenceError: DOKU_BASE is not defined plugin.js:21:1
TypeError: locktimer is undefined 4 doku.php:341:3
```

I am using Bootstrap3 template, but the problem is exactly the same with default DokuWiki the template. I tried deactivating all other plugins but it doesn't change anything.

I also tried using CKGDoku. It is better, I still can see the two successive pop-up dialogs and when I click on the bottom buttons (save, clear, ...) it keeps erasing everything, but at least the editor is visible (nice work) !

I looked for similar problems but couldn't find a fix that works. Do you have any idea what happens ?

Thanks in advance
![Capture](https://user-images.githubusercontent.com/54690650/63982375-84ae6a80-cac2-11e9-8092-fa45484dcd91.PNG)
![Capture2](https://user-images.githubusercontent.com/54690650/63982378-85470100-cac2-11e9-93c4-2464915bd5a6.PNG)

**Comment by turnermm** [comment]
The origin of this problem seems to be a failure to load  `/testdw/lib/exe/js.php`.  
Also the cross-browser issue may also be a result of the failure to load js.php.

What operating system are you using, what version of PHP and apache.

**Comment by arthurdehavn** [comment]
I am using PHP version 7.2.19 with Apache 2.4.

**Comment by arthurdehavn** [comment]
I tried deleting all content from the folder data/cache but it doesn't help.

I also tried using the html5 fix you posted previously but it doesn't work either.

**Comment by arthurdehavn** [comment]
I found what causes the problem. 
My DokuWiki is integrated into WordPress using [this tip](http://www.tesla-engine.net/2013/06/visually-integrating-doku-wiki-into-wordpress/).
As soon as I add the following code to /inc/load/php (even without adding any more code from the tutorial), it starts messing around:
`require_once(DOKU_INC.'../wp-load.php');`

Do you have any idea how to solve it ?

**Comment by turnermm** [comment]
I do not use wordpress.  But looking at the 'tip', my first question is whether the path is correct:
     require_once(DOKU_INC.'../wp-load.php');
This means that `word-load,php` is one directory above DokuWiki and that you are calling it from a file in the DW root directory.
  Word Press Directory
      wp-load.php
            DokuWikiRootDir 
             -> some.file.php: require_once(DOKU_INC.'../wp-load.php');
