### ISSUE TITLE
Multiple lines within a cell of a table cause trouble

### ISSUE THREAD

**Issue by Bytebier** [turnermm/ckgedit#493]
When using multiple lines within the cell of a table, the text is suddenly right-aligned and messes up the formatting of the table.

In edit mode I add a table with 2 rows, 1 column and a header row:
![afbeelding](https://user-images.githubusercontent.com/6329878/65907722-2a584080-e3c5-11e9-9670-10d9cceaf1b0.png)

When I save, the result is as expected.

Next, I add an extra line to the cell containing "Row 1". In edit mode I place my cursor in the cell and press enter and type the extra line:
![afbeelding](https://user-images.githubusercontent.com/6329878/65907944-a94d7900-e3c5-11e9-8691-69ed35e13acd.png)

When I press save, this is the result:
![afbeelding](https://user-images.githubusercontent.com/6329878/65908030-ceda8280-e3c5-11e9-8b93-fabbe67168f2.png)

Using shift+enter sometimes (wasn't always the case) leads to another unwanted situation where my text is suddenly added as something that looks like it's a piece of code:
![afbeelding](https://user-images.githubusercontent.com/6329878/65908240-51fbd880-e3c6-11e9-8928-dec1b155a6f7.png)

I'm using the latest version (the one released on 30th of September). Thanks in advance!

**Comment by turnermm** [comment]
Try this branch for the cell alignment issue:
https://github.com/turnermm/ckgedit/archive/cell_align.zip
Strange that no one ever encountered this before.  Let me know if this works for you and gives no trouble.
As for the change of font size, I can't reproduce it.  It could be a css issue.   Which template are you using?

**Comment by Bytebier** [comment]
Thank you so much, it works like a charm!!

I'm using the Bootstrap3 Template. But perhaps one bug led to the other.

**Comment by turnermm** [comment]
I've merged the table alignment into the master branch, so it will update. 

 I haven't tried testing the font size change with Bootstrap 3 yet.  Have you any further information about this?
Thanks.

**Comment by Bytebier** [comment]
What do you mean exactly with font size? I thought you were talking about the last screenshot, where the formatting inside a cell was messed up. I can't seem to re-create that sitation any longer since the version you gave me. In case I ancounter it again, I can post it as a new issue?

**Comment by turnermm** [comment]
Your image seems to show a reduction in font-size at the cell marked `Posture/gait`.

**Comment by Bytebier** [comment]
Still can't re-produce the issue. Thanks for the fix!
