### ISSUE TITLE
Pasting images through clipboard not working

### ISSUE THREAD

**Issue by StefanW86** [turnermm/ckgedit#495]
Hello,
if we paste images through clipboard with chrome 75 is not working and is resulting in a string like
 
024e5984-44fc-45c9-8a19-afb58d870d69

**Comment by turnermm** [comment]
Turn on supplementary image paste support.  
See https://www.dokuwiki.org/plugin:ckgedit#copy_and_paste

**Comment by StefanW86** [comment]
great. Thanks. In an older version of ckgedit we had some issues, so we added easyimage as additional plugin. I removed easy image and it seams to be working.
