### ISSUE TITLE
Chrome Picture Properties hängs

### ISSUE THREAD

**Issue by StefanW86** [turnermm/ckgedit#504]
Hello,
with Chrome 77 the Picture property dialog hangs and you cannot change the picture width and height.

With Edge the dialo opens, you can change the image size. But after saving the wiki editor - the image  disappears and we only see some base64 code. See at buttom.

But this only happens if the image is inserted through the clipboard. (in both browsers we activated additional support for pasting images)

`{{data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABKMAAACQCAYAAADUW6gBAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAACfOSURBVHhe7d0LnBVl/cfxHygomnjJG4hCIt7TFEuUbDEq7yWatmqm/k1NLQMNM6UkxTJJwUy8XzLTpQtYaWSBsWWJKRKpAQIFaSJmhJpyU/Z/vs+ZZ/fZ4Zyz5zIzuwuf9+s1e2bmzNm5zzzzey7TZe3atU0GAAAAAAAAZKBr9AkAAAAAAACkjmAUAAAAAAAAMkMwCgAAAAAAAJkhGAUAAAAAAIDMEIwCAAAAAABAZghGAQAAAAAAIDMEowAAAAAAAJCZLgsXLmyK+gEAAAAAAIBUdWnKifoBAAAAAACAVFFNDwAAAAAAAJkhGAUAAAAAAIDMEIwCAAAAAABAZghGAQAAAAAAIDMEowAAAAAAAJAZglEAAAAAAADIDMEoAAAAAAAAZIZgFAAAAAAAADJDMAoAAAAAAACZIRgFAAAAAACAzBCMAgAAAAAAQGYIRgEAAAAAACAzBKMAAAAAAACQGYJRAAAAAAAAyAzBKAAAAAAAAGSGYBQAAAAAAAAyQzAKAAAAAAAAmSEYBQAAAAAAgMwQjAIAAAAAAEBmusyePbsp6gcAAAAAAABS1WXlypUEowAAAAAAAJAJqukBAAAAAAAgMwSjAAAAAAAAkBmCUQAAAAAAAMgMwSgAAAAAAABkhmAUAAAAAAAAMkMwCgAAAAAAAJkhGAUAAAAAAIDMEIwCAAAAAABAZghGAQAAAAAAIDMEowAAAAAAAJAZglGd1OOPPx71tZ+OsAxZY7sDleNagfbEvmh/7IPysa3WP+zT9G2I27ijrzPH/fop6f3aZeXKlU1RPzoRHQgf/vCHo6H20RGWIe744493nw899JD7TFo56zx9+nTr2rWr67p06WJNTU2uU7+6OH337rvvus8hQ4ZEY4vriNu9vfzgBz+I+spzxhlnRH0IddtkedRXnTWrtor6CtsQj1nO046DfdH+2AflY1utfzrqPn3qqaeivtZ69+5tO+20UzSUrmHDhrn0ryiNPHnyZNdfqQ3xvOno68y1bP2U9H4lGNVJdYQTvJpl+O53v2t//OMfm4MzgwcPtq985SvRt7XrCMGo3//+97bJJpvY5ptvbt27d7d33nnHVq9e7YJT3bp1axWQWrt2ra1Zs8befvttN01dXV30TXEd8eLut3u10tpfWXjhhRfspZdesi233NIGDhwYje1cSgWjNu/RN+rLe2vF4qivBcGodW2I69xRsS/aX2fcB8ok+sxnPuPu4eXQ/f7HP/5xNFQ9jtf1TzX79C9/+YsNGDDApSULeeutt2zOnDl20EEHRWMqp2DUBz/4wWiohcZvu+229r73vS8ak5xnnnnGrrrqKpfuCwNRng9IKV35jW98ww488MDom9I2xPOmo69zJctX6jlCGfXDhw+PhlCO+Pbce++97Vvf+lY0lHf55Zfb3/72t2gor5znsVqOu1tvvdUeffRR17/RRhvZ5z//+ZZg1Lx589wX1dpjjz2ivuo999xzds0119iKFSvcsH9o32effWzMmDGuf30UvxgnfSB8//vft2nTpkVDhSkX5Oabb46GylPJMixZssQuuOCCdW46ov08YcIE69WrVzSmeuUEo0455RR78MEHo6HKlLPOmmarrbayo48+2rbYYgsXaFJpqQMOOMAFqRSU8hSM0vePPfaYS1h85CMfib4prtztXm2AqJrAULXz8qqZp7RnyShdk2bOnNkcWPXHtvbxxIkTXX+trrzyyqgvT8fKG2+8Yf/9739t2bJl9p///Mf1r1q7sb3bdRN7ddHz0ZSVKadklA9KEYwqz4a4zh0V+6L91boPdI/RdXbQoEH21a9+NRqbrkIPym1JIiDF8Vqa9ku1pWeqUSxgU4lq9qkvtVRs3m19X45S66bvttlmG+vfv380Jhk6l/VQrIfjUsEoPSTrYbnc9OGGeN5Uss6bbbaZ+1Q6Uvyw+HFSbHw1Klk+HRfF9rWOE2XWE5AqX/hcdtRRR9l5550XDbV222232ZQpU6KhdINRxe6pzcEoHXw+uq6H4uefzz/UbL/99tavXz/Xv2jRInv11VddvwJEPlr/9NNP13zAKkp2yy23REPrqvZhtbMpdTKGKjkQ5s+fb6+88ooLOOkGoAdYUVBGuS6vv/66feADH7Ctt97ajS9XpRcZ6du3r40fP7754V0XlsWLFzfffGoVnnwSbkv1K3ih+Sp4quP9pJNOir4tTznrrJJf2223nTvpFJR688037Te/+Y0LPMWDUcp51fn22muvpRKMqvS8qeY3Et/ulapmnu1FwXKdO6JE2vXXX+/6Rcfwfffd5/p1bJdT0q1Wb65qsu9MXW5vrFxrl31sS+u95cbRN+UjGJW86te50cYdPy73N6ZfvY0dX28DosFMNI6z4yf3yn6+CatuX8T3Q52NeGhE7q/ou8nWa+x4qx8w3xqGj7Qlwx6yEb0bbPjIJTaseTp4tVwDdO884YQToqHs7hfFEs5Kw2y88cb2pS99qeD3tS5fpdvKL6efb9EEfwLpLJXEUYBArr322uaM6DTnGad5Jf0/S2mvYJRKECmNKPH5+0CUpBWMkiTWPa6SdGYl09ZyjRFt73JLYSWl1nmWu856xvfHkkqj6Jn9Yx/7mP3hD39oNS6cTlatWhX1VaeSfdLWvtZ5T0CqfPHnsmLbttzpQtWca6NHj3alPXVP0DOUapLoOq7/1fxUrNwcVS9SFwaFPvWpTzWPV7+nafx4/bZWKrbl3XnnnW5j3HXXXXbhhRdGY5Px6U9/2h3QCsB4//73v93OOP3006Mx2dK8fZcGBZwOO+ww9+Cs0hSig0HFz3URPPzwwysORFVCVfNEgagbb7zRzVv0qWGNVyLGT5cEHT/qwm2qoKpPLCnw86Mf/cgdC0nTPFSsX0ELzWflypVunEpGxTttf336bZKGu+++222HUsHezkrBxUq6JJx66qnuU4nwMBAlOp5GjBjh9rceWLTva6GSUepGjhzpcjVOPvlkl4DQMaPjudcuu9lZ359hfXpuZPts29VGP/Qve3FZbYmH9qaAeXhNVPfAAw+4Lj4+XuS4GgrWK8Eddv/6179cFx+vabNSNyJ/DWvuOnlAqHPJB6IW149t3v5j6xcXDhLm9kr9+IdsBNGn1OhaGpo1a1bUly6fXgjtu+++7trbp08fO+KII6Kx7SsemNFwq2tH1CURwFEgSttF3WWXXRaNTXeeutaHn57ut+H9wHe10rU+/PTCe0HYpcUXBBDVHPF8YQHZZZddor50JB2I6oiUXtd+DIMwWdE8Ne9yqwJXS6XQFFhSp8IHonn7ce9///vdOF3f/Dh1HYmuJY2NjevcDwpSRlp4XRi37p27UvMbhkf/RxlQx1sC/9JpHJfM8hWiGjpeoWtjOC6cNg0KRMn555/vnmUUk1AzPQpqNQejwlynStXyW8/f9A8++GBXT1ne+9732sc//nF3Q0uKTnjN68wzz4zGmJ1zzjnuUyVYklYq+OXnK+HNOy0KjvjtXKwOehpUUkiKXUD8eD9dWnQB1vZVHXhVXVS/Toizzz47miIZ2sZq/0k5Dqqe98QTT7hg07PPPutORt8pQe27NP3iF79wn76OblrCY1hdJeOqpWp3lXS10rHqz6HvfOc77jNOpdu0vzWdL0FVrW9+85uuGzt2rCtKq+ofU6dOdcfMs/P+YWff8pR99KA9bd/tN7I+m3e1XpustdunLIx+3fkouDR79ux1jhGtt7r4eE1bS0BKwSVVe1SCO+xefvll18XHa9osA1KF5RNCPpHVnIaZ32DDjx9uw91346zRDY+zBiWg3LTDrWG+gizRb8PETyzhlk9v5X6vnkUNNnJ4Q26uG5D5S2yx9bNBA1vCfwPqh1mdNdozjdr+CkotsoaR2qbJJkyxLp977zMCbrjhBvfZHpTZ4H3hC1+I+jqWYkGaNDLfvDTnqWt9+OkVC4DVStf68NML7wVhlxZVkfOUfldzF6qdEtZE2WGHHaK+ZIRBtrD7+9//Hk2RrST2Zym6z2cV3C5Fy6BlSYtKPnlh7QyVhFLnAwUdLQAVp3Nez1Wl5INGi61+rL8mjLX6xbk0zgaWjtlzzz3t3HPPbXUO6Zrshf2aRtPqN2lRBr6CnZ/4xCeiMXmf/OQnW4JRKj1RrVp+6/mSIX/+859d0d8ZM2Y0P/QlSW0F+QdFf7MUjfvpT3/q+pOkyLPmVSj4paCU55clzcSCD0rIMcccE/Wlz+9Hv4/j/Pg09nch48aNi/ryVRW/+MUvRkPJ0boop2G//fZzpZ8+9KEPuUSL+hUUUxeWkEqTz73NosrY+s7fBMObeSE+h6HWY1rzUxVPnbsKxqh0l4JS42++wy6+f67tsOm7tt+O3e3peW/Y6/97x5Ys/a81rcq3udcZ6fqv9rZUCsxfE/01WsJxmkbT6jfVWr58uSsq/Ne//rVVwtsLxynwpWn1m/bUOG6kNVi9jVUia0RdblgBkehLW2R9hynx1VKdbIZd6BIaI+oUPFHVstz3Y+utX+Pk/O9c0Kkl4Ta2vp81Ts4l2gbU23gV92mP6oHtbcBAG9RP2ysMMqmanrajSkJp+/bLbTNV04u+RipU+l7XUWVOKvNI6YU0Mg7LoXlrOULvec97or6OI81SSgr+azuoU1rdS3OexcQDYGkL7wfqshA2Tq4XpahZC2///feP+pIVD7apU/MeaQWkigUyfZfWc5GqyKkEdOjFF1+0pUuX1tz0TCn635qH5hXSsmiZ0qDz1QeefPpVNTf0jKrOB6tUJbqj8CUvL730UvdZnkZ7uGGR1Y0I783RPXtRgz3s7ufxDCRl0gXpKJeR54+/QqWh44JMvnD6Ev/HBcyi8a33eJHMxiqE12ddi4sJvwt/kzRl4Bdq/1sFNko/UWXoiiuucJ9KdCgQpQ3iL1CTJk1y3yWhR48e7uaoE9NTv8apDYCkqWqJ/r/Wyx9c4ucpWd24f/nLX0Z9Zscdd1zUlz6/rYs9mKsUkYT7pFZ+W5c6Ab00gkFaV1/qSTkOepBV1x4lo1QkUtshzNH1dONTVcnOyO/jSrskKLpfiopEe76dvWroDSLKRVDOgR7Ezjj1SPvcJ3ew/frNtkP7vG4H9OnhAlHb9+xuU59aYGtXLbdRn00ngZolJdTC62KhTtMkRbmBhRLgYeevU1lxRbebj1ufkJlvS3LPInXDouBQ3bFW32+RzZjpU1H9rFfvqNdpKd3Tu1c//TCfQBvQy5rfkaig00MtCbcBvVq/PbGjULX98DxWF97TkpWvepcP9rXMb0Mv/ZTtPsjzpaD8m0r1MCXFqp2nuYxqI0pGjRpl1113neu/5JJL3GchWW6vJNNPpey1114unarOtxeVhS9/+ctRXwstQ3hPSEKpIFP8npAF7VdlasZpPyTRREq5tL5pBaSUXg73Y7wr9uxQLaXJtJ8VhIlT+7r//Oc/XVVITZNk4Fv/S/9T/1vz0LzitEyappZ0YyFqosUHnnxzLWpGwlfHU5vCEpagCmV97Vd14Llz57p+vbG67Leuu1LNdXbgOnnv+XGNz7R1E2+0cSMbrG/UTMKIutxwyRJV+ZLSFk3vqvO7hEL+/1hU1b/V/2kcZ/mv9JsDNWkzl9nYd4T7zbqZjbVx/zPXefHh9qAaO7qOt3swygecSr0tTw0C+4M/qQh5eHFL+kIXKhX8yirx4CkKLppvlrl5gwcPdp/FGp3zb8Y58cQT3Wct/MnV1knmjyffJU3bOCz55NuGKta1l6uvvtp+97vfrZNDg8L8ORuWaizEvyRA9BKIRCybYjbzYNt02UQbuv/udnLTMfbveZNcIOrXT8y1plXL7fvDP2Kbdk8+qJ41VT2In6PxLsnqCXqxgBKAYae3FIqCUBr21cezeghp3WaUL+n0si1Z5HoiA6x17Kiv9WrODZT4cGGtAl8dNOKi6tRhJkp8OBV1UaJQ3dh6W5xgwrAzynof/O9//4v6zJUQ1fHp0zEaLiTNZfzoRz/qPufmHpJ8icxS9+8st5fSlOubsMSMSgTF0//h92FXLV3n/afvQuH4sEub7k9x7VEizwek0hLfd7Xsy6ToXFf1yFrpf+h/tReVqvOBJ5/eV/MxvrSUH6c3e/txPvAvWV7LFHjWmxR98P/rX/+6LViwwL2RvU0vL7FWSaSAy5BrS+Mz1hgEs+qOrbd+i5bkUl5FzJ9pMxa1TD+gfrwLIvmg2LAoly//f2aY8g3n53MUowzAOju23i+XmgHIjWmZuctsXJJe7c12oxpKOr99plK7B6PiORu+U+PSai/K00Ogxtd6w/XtNXn+4VLj0iz6nVXwqxg1fujnm2VulviIthITusj45dCnGmb+xz/+4YazbMcqPNYk6Zue1i0s+TRz5kz31knfaVilktTp+7SPCbUzpPrAIbVn5ud70UUXuc9aaBuGXSXjqhHuw0q6WvhXHLeVOPntb38b9SWn6d3V1rTFIdZ99xG2cc8t7T0H3WV171xg855+wGzVcrvl0qGpBKL0Fj3/Jj2JDydJ1Vn1YgVVRSy0z8JxmkbT6jfV0tsudS4q59nndqtT48T6Tg8aevjVOLU1p+G57ZigzCWnrHV6Kl9SqiaN42xcY74Kmtu2Skh1UD4BnGZC2FEbWvGgXFR1b31MGFYis32QE74gQqVN9TIW3/iu7l3FAgFpLOOgQYOiPnPVg1Vt2tNLJYrJcnutb8LnA73oJp7+L/b8UC1d5/2n70Lh+LBLm9KMcUkGwfS/kvx/HZ0yCLXfCpUC0n0/Pl6BnFqqr+m3+h8hzUPzitN4LVtimZiRsBSYf7GOSmb50lIKUuk5QWlcFSDQeRT+RrK4lumt/f4N60OHDnXjVCpWNZfKat+rdy8rFnJ6uXVOXglBtbuRDZZbIltSLBOqWPArPj4ojd7WcrRkDo60htyki4vOvDLxZ674cJZUNU+0n3W8dZhqevG3TikwoTfp+WBRUsIHcp1supn5eXzuc59zn/HcllqUCn6pMdys/PznP4/6zI499tioz+yqq66K+vJUNDJ+AUqCop9ad5+7pfXXZ9gYsNrDCRN41VJJn/amdVWOqS6iOtHUbpOqWumNlPo88sgjXUPXepBWl3Yw6uabb3bFfrXN9akH+fDtHZp/rQ18h4lBdZWM6yzUkLg/h4sVUV6zZk1zLlNZOTllanp3hTVZD2ta8aw1/e8J23iT1daj/3m240Zz7fbLj0itRNRbKxYX7NKg64/awfDXXt+piqK6+HhN618zXg093Pbs2bM5MR4myrWfN910U5cj99prrzWP12/aT74klGvTSYOND+cSK60b2q7NfGuY3DFLRnmZPNTXHWh1LkgXDUu0rVtXg9wwZRVY8Q8eSqeorSJdf/V6aAUmpNhLJCTpZVTGmUyZMsVV0dO89WYnaavdyTS3V5ie8vy4eBdOU605c+a4/6Nu3rx50dh05ymFmhOIzzMJpYJLhe4TadLzg5p3UPpsyy23bA5+qV8UpKq10Wv/P0utd9aS2pdtUY2FnXbaKRrK0/1d47U91O6r0gBSy4tL/G/1v/Q/9b81j3haQsui8WlQsMnz/b6klDqViNIb5bVsCrwfddRRrX7jpX3t1xskfRtRmpd89rOfdc+ligm0WZPEBX3yJYzyGq3BFWeOlToKuVJMAbWT2eo5pUTbkMWCX/HxwTxKl9BSW5ThvB+y8UVnXlr4ttNS51T4XfibNPlj/+KLL3b31g4TjKqvr7ezzjrLNVapYqB6c8QjjzyS+EP6dttt5z7DxsrVrpPsuuuu7jPMbalVqeBXEm/3Kld449RrFD2VzPGJBTWsrqKRCxcm/zauXr16uXXXvLX+fhvoAXP33Xd3/aJ9oVzHWvzkJz+xm266KRoyd4GN84mXtG56Om6VkFZRftWJ1fbX2wIff/xx96nxakxfx8SvfvUrVxUorYCU3nbp/7c+dUwqQR0XvvGxs1AAs5KuVjpuv/a1r7l+vbjBR/c9la486aSTXL8SFfG3RtSi6Z23bG2X9+SujZvb2m6H2MrX37XVyxfYZ084br2omucpuOSvv77TW7TUxcfXEojydFP0iXHf6XolSjiqOoQvvanvirWpkJW6EWOt3hpspK5f4xpjDXVWwRUF9zmBN+ee8IJi6UpQbYhv0zOVFBthuY3Scq9wjbz7ba0Sav5teu4HSJjaKBFdc+Nt5vgXsChDJc1qQ15YWuL222+3J5980nXhy1B23HHHqC9bPr0aph/CNGzYaXytdM3VvNSFDy5pzrOY+DzTFr9PpElpc5US8e1ChdXSfZpZwQ01ep1FYCwrPk2eVto8Tm0lFQtw+OCRAiS1FB7Qb/U/wuBWnJbBt9uUNgV29azt6UU5p512mmuHTG+0//a3v51KoYRyHXrooe4649u2Uul0tdMX1pYqLl/trbmtpfm5bbpkZO54GmeNdSMsLPjt24+aP3NGSykmZUQ1N3Se+841NF6iEfNY8MtNr/RSNH5ylEBofLjBFvUbZMo3HDBwUMsLZHLTqMH1PFX3y6UrWmbuGkCvtuWEuXPnuvtVeC6F18mwX9NoWv0mC9dcc42b/2GHHeaGu6xcuXKdJ2A9KKvUhihA4R/sVX/zjjvucP06kGupHhHX1oVHOVFh0CJN8WWp5SanB3+VRFHwyzeQrkCb3uKm3L1qG49WUCMMKtVCwSglLJTou/fee5tzXdqS5DKoBEmYw6P2owoFkcrl96HqPOvNFVo3RWB14Pvv/H6ND5dSzjrrNdSar9qXUCJWb99RwkIlonwQLiypVqlyt7vWS6XgHn744WhMeao53jWv+O9qGddRKVdendoy0fGp80Y3bt3ExQd21Vi8rqH6zgevarXquYvslSUv2Da2xN5p2tS6bL6Pdem+nW3x/pHWddN8e0bV6rZJbW+IW7Nq3eLmoSSvFVkLE/rKsIi/TauYzrzO6xv2RfurdB/oAU7XV7W7WaihZmWeqPrL1ltvHY1Jnk8b6R6lTJ0//elPduutt0bf5ildoWCZSsr+7Gc/c+NqvZ9Vsq20bKK0hQ/8+OWOC6epVvi/s5qnTyP4T81L/7PYPGvd/rrmK9hU6LOQcgJTlR7/fp6iKl5qGsAP64FRpVb82/Q07T777NOqjZ9qhfMtpK3vy6H9GD7ThftXz0aqfq9MaZ9h679vS63XeaXTi5VM0j5Q9f1qlPptqXmWo9J1VlU8Ff7QsXL//fe7a6hqBal6nkpEqfRpWGuiVpVey8L97LeNSpaFpcjKOh5iVe3rcuu8uEEBoejtwAr0uCp4KghVb30bZlgvn9kUfJcvqZQfr0DTyCXD7KERva1h+EhbMkwNk8enz2dkuZhXsfE57n+5IFTu/9f3tYYlB0ZNJKhB9Hz1POlXP7bqklHaTqFi26zc6UK1nmtqvkcFX1QgRed8q2CUcpj0AK1giVr6Fz1M+4i83l7kX2u9yy67uESCivaVmzgvRaVIpk2b5lbQP7CLIsVqvCzLXKdyL3ztqdwDoZwEghoWVw6MVLLetR6McXrrW9gWT0PuwlEsF6EcOjZ141TpFa2vggIKoPoTz69rfLiUctZZRfeVeNb5odxUXdh9zksSx1a52z1+gSlXNctXaL1qGVeuSks71VoaUcuqc0olnpQY1LmjCL8Sgv57FSlWIErXShU3ViPxyhGrhn7rcody5/DQ9/3ODh98iG26+8W2Uc9kA/MEo9al89ZXE1LiW6VGlUOnovTl5GB2xnVeX7Ev2l9n3AfF0k+lKNMxLHlfjUq2VS33z2qomp4vkaq3XmfdBqn4YFRWkgjAVHr8a556tlIGiPqVpvTBJz2f6XlMy6TnNr3hrtbl89pa1yS2haoeXnnlla5fx25bx3C5x/iGeJ2vdJ27du3qSjSqhoZ/m5/ap1JpJLXRl2QgStK4lmV9zeustJ08Vbs877zzoqHW1GxLWFsm7XNNzTIpICo+FtEqGKUIaVtviYpTtTcd3OuTcAcmkauThqQuuoqIKwdy/Pjx7sFa66tqbr4UVylpXPhVEs8fg8oVUUCnVqpnrDaTPL9//QkXHy6lnHVWkVdtR50X+hT/myQuomls91qF50w1OsuNpdDDyZ133tn8prVC20HV+bbZZptoqDpNq19zn12611YCqhiCUYUp4a123/w9Tjl1yojx+7uUzrrO6yP2Rfsrdx+EGQz+/lksQ03C75Ju+kDV51VKQ9oKSvnlUSCq1qq8lRyv/p6j+XfEtGoaNoRglEpfK/DnxeevgI6OT9E9Kam3y2pd25JU4MtrK+hb7rG9IV7nq1lnPd9dcsklze3rDhkyxG644YbEA1FSzbWsHJ3lmaE9xbenXgKithdDylhQRmsoqWfhUvw5r4zdCRMmFK6mh44vqYuuDghVFdTNzA+r3qhvW6uUtC78apRRpQ98uy1pKHTRS/sEVOPlPsFay4U0re3eGWVdMmp9RTAqeZynHQf7ov2Vuw9qadtvfbm+c7yuf9in6dsQt3G166yAlH8pQ9JV80Ic9+unJParXvbUrVs3108wqpPqCCc4F/72wcUdnQ3XCrQn9kX7Yx+Uj221/mGfpm9D3MYdfZ057tdPSe9XglEAAAAAAADIzPrV2BMAAAAAAAA6NIJRAAAAAAAAyAzBKAAAAAAAAGSGYBQAAAAAAAAyQzAKAAAAAAAAmSEYBQAAAAAAgMwQjAIAAAAAAEBmCEYBAAAAAAAgMwSjAAAAAAAAkBmCUQAAAAAAAMgMwSgAAAAAAABkpsvs2bObon4AAAAAAAAgVV2acqJ+AAAAAAAAIFVU0wMAAAAAAEBmCEYBAAAAAAAgMwSjAAAAAAAAkBmCUQAAAAAAAMgMwSgAAAAAAABkhmAUAAAAAAAAMkMwCgAAAAAAAJkhGAUAAAAAAIDMEIwCAAAAAABAZghGAQAAAAAAIDMEowAAAAAAAJAZglEAAAAAAADIDMEoAAAAAAAAZIZgFAAAAAAAADJDMAoAAAAAAACZIRgFAAAAAACAzBCMAgAAAAAAQGYIRgEAAAAAACAzBKMAAAAAAACQGYJRAAAAAAAAyAzBKAAAAAAAAGSGYBQAAAAAAAAyQzAKAAAAAAAAmSEYBQAAAAAAgMwQjAIAAAAAAEBmCEYBAAAAAAAgMwSjAAAAAAAAkBmCUQAAAAAAAMgMwSgAAAAAAABkhmAUAAAAAAAAMpNyMGqFLfjV9XbGjdOjYQAAAAAAAGzIUgpGrbAFj02wC+oOtCO+NMEef/XdaDwAAAAAAAA2ZOkEo15osEvPud4efWl1NAIAAAAAAACgzSgAAAAAAABkiGAUAAAAAAAAMtOlKSfqj1G7Tw324I8m2dS/LLCXlvsqd5vZ9n23s/fte6Kd9PkT7dj9drRu0Tdm0+yK/udaQzRUyP6jptiks3aPhiQ/n7vvvNcenfWSudl038r6HHCEnfn5/7P6j+5mPfITtjLtiv52rp/R/qNsyqSzbOcFj1nD3XfavY/Oyi9v7v/sceip9sWvXWBH71bovwAAAAAAACBLXS/95WJbEw00WzPHJp431I44Z4zdO/1vQSBK3rZXFy+2Jx+5wb4y7HA77XtP22vRNxVb8azdc9qH3HwmPhkFomT1cnvpyYk25pwj7EOnTbCn25zBO7Zo4nk29IhzbMzEJ1uWN/d/5k2fYF86YqhdMa3qpQQAAAAAAEBCuv5s+Ck2OhaoeeH+K+zyqUujoVJW28wbL7I7Z6wTzirDC3bfGSfbmBlvR8OFvT3jejv9gntsTqlZzLnBvnz5VCu+xEut4dLb7PFqFhMAAAAAAACJ6eoCNV+/01riSbPs1z+cHfXn7H+h3ffYLJu7cKEtzHVzZz1m9315oG21/cF2zMVj7K6fPGgXDPQV9YbaNZpuyijbPxrj1N/ufqvOV9F7ceK19u2ZLSWuNht0SfN85s56xL57Yh/rHn23euZ1NnbSi9FQAatX2+rc1HucfpM9Mmtubj7P2fSb6m2H6Gtn+f029Y9RPwAAAAAAANpFvgHzpT+wX/7eR6OW2dLFUa9st7P1792zuV2obj372uCLfmwzn3jAvnfhKTbkwL7Ws6XRqDK9YFMnNlpzKGqr/7Nb7r3ABvfNz6dbzz1t2HV32KXNEa3V1jhxau5XxXU/+jq7b/TRtqdbmB6289Gj7ep6H86S1fafN1+P+gEAAAAAANAeorfprbZfPzUz32s7225hsaapl9ng/Qba0Wd/1W5+cLo9s3CZrYi+qtqSWfaHoPCVHTnIPrxOQGt3G3TU3lF/zuw/2KwlUX8BnzzuSNs26s/rZjvvtlfUn/ev18qpeggAAAAAAIC0RMEos+UvLLZ8rGd3O+7CWBU31xD4T+2GUWfbSZ/4oO27l4JTV9s9jy2oLjD1ylJbFPU6Deda//791+mOvfZv0QQy2/4Rlthqpbv16F5x8SwAAAAAAABkrDkYZcvftjej3m2HjrYHx9fbrptFI+JccOreCt52F7NsqRWNKxW13N58K+pdx17Wt3fUCwAAAAAAgA6rJRjVSjfre9w19ttnZtkj94+xi4852PpsFba/1EJvuzvvtsetohfVbb6FbRX1AgAAAAAAYMPR1b/lbuGksyz/nrtAt5625yGn2IXfe8AaZ86x5576jf3kLgWn9rWw0NTy+6daRS+q26639Y96neBte6W6a4ZG0wMAAAAAAKBTKlIyqrAe2/S3A4coOHWtXRS0LW6r19i7UW9Z+h9gQ3aL+uXXM+zxiopWAQAAAAAAoDPq+tWbH7Tpzyy2N3wwaM0btvT5J2zyPVfb2ccdYgNP/o499nzwBr0Vy+z5ybfbPWHb4vvvZjtHvQU9Pduezv2DNW8stcWvvJ4b8X477oxD89/J8rvt/DNvsMfmvpGv7pdbhsV//J6dPPAQO/Wi79o9k5+w55fV/A4/AAAAAAAAtLMuu+66a5PZDnb6XVNs9JAtbc2s79mxn77RFkQTtK3lty2m2+i9zrYfro4GA91Pv8vmjB5itmaO3XPaCTZmZoGJCug+8Er7+Y8/11yVcNoV/e3chmjA9rdRUybZWbF6hi/cc4IdNWZ2NJSbatQUmxSfCAAAAAAAAJnpat372InjH7QromBStwPOt9vHn2h9CrdXHrODfexbdzX/tsVgO/KMHaL+1lavWJ0v/dRtLztrwh12zh5tz2izQZfYDye0BKIAAAAAAADQOXWd/Lupdt1xfa1bNCL/Jr3rbOqTj9gdo863Yw7uG3uT3ma2fd+9bciZV9t906fZbZ/ZK/it180GXTLJHhh1rO29vW/qvLtt1edgO2afnvZ2NMa2/bBd9vMn7ZGbLnbzaZ40Z7Pt+9reQ860UXc8an/+0QV20LbRFwAAAAAAAOi0ujTlRP0AAAAAAABAqip6mx4AAAAAAABQC4JRAAAAAAAAyAzBKAAAAAAAAGSGYBQAAAAAAAAyQzAKAAAAAAAAmSEYBQAAAAAAgMwQjAIAAAAAAEBmCEYBAAAAAAAgMwSjAAAAAAAAkBmCUQAAAAAAAMgMwSgAAAAAAABkhmAUAAAAAAAAMkMwCgAAAAAAAJkhGAUAAAAAAIDMEIwCAAAAAABAZghGAQAAAAAAIDMEowAAAAAAAJAZglEAAAAAAADIDMEoAAAAAAAAZIZgFAAAAAAAADJi9v/pKqUKjxW2SQAAAABJRU5ErkJggg==?nolink&700x85}} `

**Comment by turnermm** [comment]
You can't manipulate a pasted image until it  has been saved to the editor.
