### ISSUE TITLE
Error when trying to modify a page.

### ISSUE THREAD

**Issue by keibo** [turnermm/ckgedit#512]
Hello, when i try to modify a page i got no menu or icons and some strange text.

When i click on the CKG editor, i got a blank square with an error.

I cant find where the problem is.

Can you help me please ?

He is some screenshots of the errors : 

![accueil_wiki_sur_lautonomie_-_Mozilla_Firefox](https://user-images.githubusercontent.com/44374083/70851053-015a2e80-1e91-11ea-9699-acf4450a3ce5.png)

![accueil_wiki_sur_lautonomie_-_Mozilla_Firefox_2](https://user-images.githubusercontent.com/44374083/70851055-0323f200-1e91-11ea-9ba0-dec8c3296206.png)

![accueil_wiki_sur_lautonomie_-_Mozilla_Firefox_3](https://user-images.githubusercontent.com/44374083/70851057-04551f00-1e91-11ea-9ceb-fff04393f1f8.png)

Thank's for you help.

**Comment by turnermm** [comment]
There seems to be a javascript error.  Can you check the javascript console?  Before you so, it can be helpful to turn off javascript compression in the dokuwiki Configuration settings.

**Comment by keibo** [comment]
Thank's for you help.

Here is the error i got.

That seems to be an error on Doku base.

![JS_console](https://user-images.githubusercontent.com/44374083/70853456-a1728080-1eae-11ea-8091-34071933921e.png)

**Comment by turnermm** [comment]
The problem probably starts at the top of the output, with the syntax error.  But it may not be coming from ckgedit.  The output shows that it is coming from jquery.php, but I doubt that there is an error in jquery. All of the following errors are recognizable as related to ckgedit.   So it is very possible that the error is originating elsewhere, corrupting jquery and spilling over into ckgedit.  

These are some of the things that occur to me:
1. What version of ckgedit are you using? What version of Dokuwiki?  And how did you install it?
2. Have you installed any other plugins?  If so disable them.
3. What browser are you using?  Have you tried another browser?  If not try another.  See if you get the same error.  

What operating system are you using for your desktop system?

**Comment by keibo** [comment]
I've find the solution.

The problem was php 7.4 because the {} were deprecated.

Switch to 7.3 fix the problem.

Thank's a lot for your help :)
