### ISSUE TITLE
Nested lists with links breaks down

### ISSUE THREAD

**Issue by PankajRasgania** [turnermm/ckgedit#516]
A nested list in which the parent list item has a link gets broken.
I have the following text in CKGEdit
![2](https://user-images.githubusercontent.com/19621227/71880738-01c7ab80-3157-11ea-93e6-3d216e062eb5.PNG)
After saving the result is this
![3](https://user-images.githubusercontent.com/19621227/71880820-1dcb4d00-3157-11ea-95bf-64f4923c666c.PNG)
The list works fine if the link in parent item is removed or if there is no text after link. For e.g. this works fine
![1](https://user-images.githubusercontent.com/19621227/71880930-579c5380-3157-11ea-87ac-877885b0a8fb.PNG)

**Comment by turnermm** [comment]
Yes, I see this, but my test gives a slightly different result:

![image](https://user-images.githubusercontent.com/176447/71948122-97cdf700-3194-11ea-9db2-5a531a9a0038.png)

The error percolates down into subsequent lists but the topmost list remains in tact.  I see what is happening to create this error but won't have time to find out why for a few weeks.  If you don't hear back from me by the end of the month please post a reminder here.

**Comment by PankajRasgania** [comment]
Just another observation: This happens only when the first item of a list contain link followed by text. The same case in second item doesn't show any unexpected behavior. 
For example, the following works fine
![list1](https://user-images.githubusercontent.com/19621227/71996370-1a70b800-3262-11ea-9e4e-5abfecba1771.PNG)
Take your time. Will remind you as said.
Anyways thank you for taking out time and commiting to this project in the first place.

**Comment by turnermm** [comment]
I couldn't find the exact souorce of this problem, but I made an effort to fix this.

**Comment by PankajRasgania** [comment]
Yes, it is working now for most of the cases. But the case that I had is still showing weird behaviour.

**This is what I type in editor**
![two](https://user-images.githubusercontent.com/19621227/72588940-da739a00-391f-11ea-9cfa-d86ca996f5c1.png)

**This is what I get**
![three](https://user-images.githubusercontent.com/19621227/72589187-84ebbd00-3920-11ea-9b23-1d765854f0f6.PNG)
 The weird thing is the list part works fine if there is not paragraph before the list.
 
**The following case works fine**
![one](https://user-images.githubusercontent.com/19621227/72589236-a8af0300-3920-11ea-9b80-0a1799bf6534.PNG)

**Comment by turnermm** [comment]
To regular expression processing
 

>    List item `Link` text 

is very different from 

>    List item |`Link`|`Link`|

  It's fixed to deal with most, if not all,  cases.
