### ISSUE TITLE
Color text code block

### ISSUE THREAD

**Issue by tuxmika** [turnermm/ckgedit#518]
Hello

I'm trying to put text in color in "code block" and instead of having color, I only have html code.

![Capture](https://user-images.githubusercontent.com/44813941/72140184-7a657c80-3390-11ea-808a-cc420ee2eabf.PNG)

**Comment by turnermm** [comment]
Ckgedit doesn't support color in code blocks.  Nor Does dokuwiki, outside of geshi blocks, where the color is applied by geshi and not dokuwiki.
