### ISSUE TITLE
Bad translation from DW syntax to HTML if text contains an open bracket (less than <)

### ISSUE THREAD

**Issue by cpholt** [turnermm/ckgedit#519]
Using CKGEdit mode, create a simple page with this content.

```
patch -px <file
```
Save, and it appears correct.  Edit the page. It now appears like this:
```
patch -px
```

Note that it's truncated. Look at the "Source" view.  You will see this:

```
<p>patch -px <file> </file></p>

```

If you try and Save, you will get a Parse Error:
```
Uncaught Parse Error: <file> </file></p>

```
The  generated HTML should have been this:
```
<p>patch -px &lt;file</p>
```
Somewhere, there is a missing conversion from '<' to '&amp;lt;'.

**Comment by turnermm** [comment]
%%patch -px <file%%

**Comment by cpholt** [comment]
The %% turns into <nowiki> tags.  This works as a workaround, but it still seems like a bug.

**Comment by turnermm** [comment]
https://www.dokuwiki.org/wiki:syntax#no_formatting
