### ISSUE TITLE
Bug with <code> block including | (pipe)

### ISSUE THREAD

**Issue by jpdlor** [turnermm/ckgedit#522]
Hi,

Just came into a bug that seems related to a `<code>` block including a 'pipe' character (ckgedit version: 2020-01-17)

The following DW code:
```
====== Title ======

==== Sub1 ====

<code>
tr -cd 0-9A-Za-z </dev/urandom | head -c 80

</code>

==== Sub2 ====

<code>
code2

</code>

```
becomes:
```
====== Title ======

==== Sub1 ====

<code>
tr -cd 0-9A-Za-z </dev/urandom | head -c 80

</code>

==== Sub2 ====<code>

ls -F

</code>
```
after any modification in CKG (note the 'Sub2' `<code>` tag position).

This is annoying because putting the `<code>` tag on the same line as a sectioning part makes it regular text for DokuWiki (i.e. the prefix and suffix `====` appear in the final page display and the line lose the sectioning font).

Please note that the culprit seems the `|` (pipe) character in the previous 'Sub1' code snippet since everything remains OK for both Sub sections if I remove it.

**Comment by turnermm** [comment]
This should be fixed in updated version.

**Comment by jpdlor** [comment]
It was fast!
It works perfectly. Thank you.
