### ISSUE TITLE
Issues loading with Brave browser

### ISSUE THREAD

**Issue by runegang** [turnermm/ckgedit#523]
I am testing out the Brave browser and use ckgedit, but it is not loading. It is just showing a grey box where I expect the editor. 

I have tried to enable javascripts and more, but it is still not working. Any clue to what can be causing this?

**Comment by turnermm** [comment]
No, I'm afraid not.

**Comment by kalenpw** [comment]
On macOS 10.14.6 with Brave 1.2.41 it works.  Brave is based on Chromium so it should work fine. Have you tried disabling all your browser extensions?

**Comment by runegang** [comment]
Seems to have been a missconfiguration on my client. Removed all settings and started over. Now it works.

Sorry to have bothered you.
This is a great plugin!

**Comment by turnermm** [comment]
No Problem. I'll close this now.
