### ISSUE TITLE
Bug: when a footnote is present, the editor adds an extra <hr> on every save

### ISSUE THREAD

**Issue by jorbig** [turnermm/ckgedit#527]
I love your plugin, but there's an annoying bug: when a footnote is present on a page, your editor adds an extra <hr> everytime the editor is loaded and the page is saved, until I delete them manually at the bottom of the page.

**Comment by turnermm** [comment]
That's Dokuwiki

**Comment by jorbig** [comment]
No, the default DokuWiki editor and the Prosemirror editor don't do this. I'm not complaining about the horizontal line DokuWIki displays above footnotes, but about the EXTRA lines your editor creates on one and the same page.

**Comment by turnermm** [comment]
![Opera](https://user-images.githubusercontent.com/176447/75774919-980eec80-5d16-11ea-8ea3-79b948d726a8.png)

**Comment by turnermm** [comment]
![Opera](https://user-images.githubusercontent.com/176447/75775019-c391d700-5d16-11ea-9d7b-8df571e00238.png)

A screen shot from the Dokuwiki.org playground

**Comment by jorbig** [comment]
![image](https://user-images.githubusercontent.com/49766553/75775770-f48ffd00-5d52-11ea-8177-35c78e4294ce.png)

![image](https://user-images.githubusercontent.com/49766553/75775822-14272580-5d53-11ea-9a50-7bb0d70cafe4.png)

![image](https://user-images.githubusercontent.com/49766553/75775905-39b42f00-5d53-11ea-87c1-6a04788392b0.png)

**Comment by jorbig** [comment]
Look at the second and third image I posted. I ONLY wrote some more text lines in the editor, but didn't add the extra horizontal lines myself: the editor did that automatically.

**Comment by turnermm** [comment]
![Greebo](https://user-images.githubusercontent.com/176447/75778841-2a66be80-5d1e-11ea-8247-0f7132d6b1ee.png)

I'm afraid I have not been able to duplicate your issue.

**Comment by turnermm** [comment]
This may have something to do with the template you are using.

**Comment by turnermm** [comment]
![Greebo](https://user-images.githubusercontent.com/176447/75779581-854ce580-5d1f-11ea-8230-6ba642b586a4.png)

I tested to see if there might be some carry over from the H1 Header, but there's not.  All my tests are done with the default dokuwiki template.

**Comment by turnermm** [comment]
![Greebo2](https://user-images.githubusercontent.com/176447/75779786-e4125f00-5d1f-11ea-928a-7207c83a057c.png)
I tested to see if there might be some carry over from the H1 header, but there' not, at least not with the  default dokuwiki template, which is where I do my testing.

**Comment by jorbig** [comment]
OK, and you saved it after typing each new line?
Then it must be a compatibility problem with the popular Bootstrap3
template I'm using...
Thanks for testing though!

Op di 3 mrt. 2020 om 14:24 schreef Myron Turner <notifications@github.com>:

**Comment by jorbig** [comment]
It happens even without clicking save. Look at this GIF video:
![image](https://i.imgur.com/LruJ7XO.gif)

**Comment by turnermm** [comment]
It's bootstrap3:
![2020-03-04_08h30_22](https://user-images.githubusercontent.com/176447/75889474-99154c00-5df2-11ea-89c8-e5d4636c66fc.png)

**Comment by turnermm** [comment]
> Or do you know an easy fix?

I haven't the slightest idea.  Bootstrap3 is complex with all  kinds of features that interact with plugins and output, the author has previously had to provide a fix when a conflict occurred.  I would write to him.

**Comment by jorbig** [comment]
OK thanks. There's only one thing left that bugs me: how to remove the red
Magic Line that inserts a new paragraph?

Op wo 4 mrt. 2020 om 15:55 schreef Myron Turner <notifications@github.com>:

**Comment by turnermm** [comment]
Ask the CKEditor developers
