### ISSUE TITLE
Footnote bug

### ISSUE THREAD

**Issue by jorbig** [turnermm/ckgedit#528]
When changing an existing footnote, I can't make anything **bold**, and I also can't add a linebreak. Because upon saving, CGKedit didn't parse the changes correctly. I'm using the default Dokuwiki template, so that couldn't be the problem.

**Comment by jorbig** [comment]
This also means that CKGedit automatically messes up the layout of footnotes that are set up using the default DW editor.

**Comment by turnermm** [comment]
I suggest that you switch to the prosemirror plugin.  That might give you more of what you need.  It attempts to stick closer to the native dw editor.

**Comment by jorbig** [comment]
I came from Prosemirror, but that plugin is still too much buggy and beta
as well: empty headings on a page break the entire editor etc.
I guess a fully stable WYSIWYG editor for dokuwiki does not (yet) exist?

Op do 5 mrt. 2020 om 17:30 schreef Myron Turner <notifications@github.com>:

**Comment by turnermm** [comment]
ckgedit has been around in different forms for at least 10 years and has a large user base.  It has limitations because of the complexities of converting html in the browser into markup and the myriad possibilities that might be encountered. But it is not unstable. 

 See https://wysiwyg.wiki.cosmocode.de/doku.php?id=en:why

**Comment by jorbig** [comment]
Yes, I'm aware of that, and I admire your work on it. It sure is stable,
just not the footnote section: make something in a footnote bold or italic,
or try to add a newline, and it will disappear after saving. So that part
is just not very 'wysiwyg' yet... Keep up the good work though!

Op do 5 mrt. 2020 om 17:45 schreef Myron Turner <notifications@github.com>:

**Comment by jorbig** [comment]
Just letting you know that I 'fixed' this by using a workaround: the RefNotes plugin in combination with some custom CSS work great for my purpose. So I'm a very happy user of CKGedit now!
