### ISSUE TITLE
RSS feed request

### ISSUE THREAD

**Issue by Aephir** [turnermm/ckgedit#529]
I am trying to add an rss feed (https://www.dokuwiki.org/rss), but it seems that embedding RSS in ckgedit is not supported. I'd like to to request this feature.

EDIT: You can add it on a page, but if you try to edit the page afterwards, it messes up the RSS completely.

**Comment by turnermm** [comment]
I've handled this by escaping rss makrup in editor, so that the rss is live only in browser.

**Comment by Aephir** [comment]
Nice, thanks!

I think there might be a small issue though, if I click edit, it changes the format (inserts a whitespaces after each the first two curly brackets. If I remove the whitespaces, then it reverts to the old behavior, if I leave them, then it just becomes text after the edit.

Cheers!

**Comment by turnermm** [comment]
> {{rss>https://eutils.ncbi.nlm.nih.gov/entrez/eutils/erss.cgi?rss_guid=1NKSH3UhXTz_tdDqcwuvpieH4Q_Oz2KlegANFrtFlmZX1y9Mi_}}

**Comment by turnermm** [comment]
[rss-t.txt](https://github.com/turnermm/ckgedit/files/4494554/rss-t.txt)

Save this file to data/pages.  Make sure it is read/write to the web server.  Open it in ckgedit.  \save and then open it in the dw editor.

**Comment by turnermm** [comment]
The point is not to change what the editor has done.  The white space and `Feed` are there  for a reason. When you save , the original syntax is restored.  That's the point of the file and instructions above.

**Comment by turnermm** [comment]
https://www.dokuwiki.org/plugin:ckgedit#rss_feeds

**Comment by Aephir** [comment]
Great, thanks a lot!
