### ISSUE TITLE
Geshi block adds extra lines when editing

### ISSUE THREAD

**Issue by injectx** [turnermm/ckgedit#530]
So first of all; DokuWiki with ckgedit is just great, thanks for that!
I have an issue though. When I insert a code block using ckgedit, everything is just fine, it displays correctly on the page. But when I edit the page again, there seems to be blank lines added to every code block.

![Screen-Recording-2020-03-07-at-1](https://user-images.githubusercontent.com/5892320/76146112-756f3180-6090-11ea-99c6-7d05d8d733a5.gif)

This is the code:

```
<p>
This is example JavaScript:
</p>
<pre class="code javascript"><span class="kw1">var</span> test <span class="sy0">=</span> <span class="nu0">5</span><span class="sy0">;</span>
&nbsp;


</pre><p>&nbsp;</p>
```

**Comment by turnermm** [comment]
The extra line feeds enable editing at the bottom of the block.  They are removed on save

**Comment by turnermm** [comment]
In Editor
![geshi-1](https://user-images.githubusercontent.com/176447/76147272-2d381b00-6060-11ea-9b0a-1d12c9e91e6b.png)

After save
![GESHI SAVED](https://user-images.githubusercontent.com/176447/76147313-a7689f80-6060-11ea-8f3b-f0ce7c3b3084.png)

**Comment by injectx** [comment]
Makes sense. Thanks!
