### ISSUE TITLE
doubling of heading, conflict with reveal.js

### ISSUE THREAD

**Issue by TimFFischer** [turnermm/ckgedit#531]
Hi,

I found a conflict of CKG Editor with the plugin reveal.js.

📝 detailed reproduction steps

1. install the dokuwiki-plugins ckgeditor5 and reveal.js (version 2018-09-02; most present one)
2. generate a page with multiple headings in DW editor
3. open ckgeditor ("Edit") and press button "DW editor" (without doing changes to the sourcecode)
4. open DW editor ("Edit") again

✔️ Expected result

- no changes expected

❌ Actual result

- each heading got doubled (already in the editor of ckgedit)

📃 Other details

- Browser: Chrome
- OS: CentOS Server
- CKEditor version: 2020-02-13
- Installed CKEditor plugins: none

**Comment by turnermm** [comment]
First ckgedit does not use ckeditor5, just to clarify.
As for a conflict with reveal.js -- this is an external framework.  If you are using the revealjs plugin, I suggest you post an issue with them; if not, then try it.

**Comment by TimFFischer** [comment]
Thanks, just in case, somebody else has the same problem. 
A quickfix can be found here:
[neuralyzer github issues](https://github.com/neuralyzer/dokuwiki-plugin-revealjs/issues/20)

**Comment by turnermm** [comment]
Thanks for the update.
