### ISSUE TITLE
ckgedit removes explicit title for a link

### ISSUE THREAD

**Issue by PankajRasgania** [turnermm/ckgedit#532]
I am facing an issue where ckgedit removes the explicit title provided for a link when it is same as the page name.
So` [[.:pagename|pagename]]` gets replaced with `[[.:pagename|]]`
When using "Useheading" for pagename setting, the link always start with a capital alphabet as the first heading of the page starts with a capital alphabet. This happens even when link title is provided explicitly in lowercase, but ckgedit removes it if it matches the pagename. This is an undesired behaviour. How can we correct it?

**Comment by PankajRasgania** [comment]
Line 238 in /action/save.php seems to be culprit here. Does it serve any other purpose? Can I safely comment it out?

**Comment by turnermm** [comment]
> Can I safely comment it out?

I haven't thoroughly tested, but I believe so.

**Comment by turnermm** [comment]
If you use it for a while without any side effects, please let me know and I will make the change permanent.  Thanx.

**Comment by PankajRasgania** [comment]
It's working fine since I removed (or converted to comment) the line 238. No side-effects observed.

Though the reason why this behavior might have been introduced was to ensure that links are **always** represented by Headings of the page if useHeading setting is on. This may be desired if one often changes the heading. But since the heading is displayed as it is, we may sometime explicitly need the link text (or heading of the page) to be in lowercase especially in the middle of a paragraph. This is where this behavior is undesired. 

You should decide which case scenario more fits the general one so as to make permanent changes.

After removing line 238. (Supposing the link `:page_name` has heading Page Name)
` [[.:page_name| page name]]` remains ` [[.:page_name| page name]]` (since linktext and heading is not an exact match, we should retain the linktext)
` [[.:page_name| Page Name]]` gets replaced with `[[.:page_name|]]` (since its an exact match, we might not need the linktext.)

This behavior works well for me.

**Comment by turnermm** [comment]
try
https://github.com/turnermm/ckgedit/archive/usehead_sup.zip

**Comment by turnermm** [comment]
I've included this in latest master:
https://github.com/turnermm/ckgedit/commit/4168e69578b673d066cd4b898afd55a63d0ca546
