### ISSUE TITLE
FCK_NmSp cookie causes problems

### ISSUE THREAD

**Issue by jorbig** [turnermm/ckgedit#533]
What is the FCK_NmSp cookie for? In some situations (eg. when rewriting ?do=edit to /edit using htaccess) it makes that the default Dokuwiki editor is loaded for users that should only have access to CKGedit. How to completely remove and disable it?

**Comment by jorbig** [comment]
The problem seems to be solved by removing these lines from action/edit.php:

`        $Fck_NmSp = "!!NONSET!!"; 
        if(isset($_COOKIE['FCK_NmSp'])) {
          $Fck_NmSp = $_COOKIE['FCK_NmSp'];
        }`

**Comment by turnermm** [comment]
Set the following configuration options:

plugin»ckgedit»**allow_ckg_filebrowser** : `all`
   (Select which file/media browser(s) users can use)
	
plugin»ckgedit»**default_ckg_filebrowser** : `ckgedit`
   (Select which file/media browser is the default.)
 	
plugin»ckgedit»**dw_edit_display**: `admin`
   (Controls which users have access to the "DW Edit" button.)   

plugin»**ckgedit»dblclk**:`off`


This will remove the native dokuwiki editor from all users except admins and managers.

**Comment by jorbig** [comment]
Thanks, that did indeed solve the problem!
I had everything you mention, except for plugin»ckgedit»
*allow_ckg_filebrowser*, which I had on 'ckgedit' instead of 'all'.


Op vr 27 mrt. 2020 om 18:01 schreef Myron Turner <notifications@github.com>:
