### ISSUE TITLE
Pasted and resized images changed to base64 string

### ISSUE THREAD

**Issue by lwpiotr** [turnermm/ckgedit#535]
I am using ckgedit in dokuwiki with Firefox 74 on Fedora 31. When I simply paste a copied image, it is attached to the webpage properly. When I paste it, change its size with a mouse and save, it is turned to base64 string, which is displayed as a simple string, not an image.

**Comment by turnermm** [comment]
Can't be fixed.  You have to save the image first by saving your document.

**Comment by lwpiotr** [comment]
Thanks. Maybe some info in the docs?

**Comment by turnermm** [comment]
Good idea. I'll check and see what's there.

**Comment by Speedy-Gonzalez** [comment]
> Can't be fixed. You have to save the image first by saving your document.
What do you mean with 'saving your document first'?

Paste image, then save document and after that I can start changing size, etc.?

**Comment by lwpiotr** [comment]
> > Can't be fixed. You have to save the image first by saving your document.
> > What do you mean with 'saving your document first'?
> 
> Paste image, then save document and after that I can start changing size, etc.?

It seems to work like that in my case.

**Comment by lwpiotr** [comment]
> Can't be fixed. You have to save the image first by saving your document.

Perhaps then a saving that does not close the editing window could be implemented? But I guess if this was possible, then also automatic pre-saving of pasted images would also be possible...

**Comment by turnermm** [comment]
The image is processed for saving in Dokuwiki as part of the page which is being saved.
