### ISSUE TITLE
Problems with the saved content when using double underscore

### ISSUE THREAD

**Issue by lwpiotr** [turnermm/ckgedit#537]
Hello,

I am not certain if this is a ckgedit issue or ckeditor.
When I use a double underscore in my text, a lot of bad things happen after saving. A lot of stuff gets underscored, but also part of the source syntax is pulled out and placed as standard text (for example explicit ==== instead of header 3, * instead of numbering, and returns before these things deleted).
It happens since I paste a lot of filenames that have double underscore in them, like something__050320__some_thing.else

**Comment by turnermm** [comment]
ckgedit mistakes the double underscore for the start of italic.  What you are getting is what happens when it doesn't find the matching double underscore.    I'll have to see if I can do anything about that.

**Comment by turnermm** [comment]
Text corruption can also happen in the native dokuwiki editor in some of these circumstances.
