### ISSUE TITLE
Problem with right click menu on mobile 

### ISSUE THREAD

**Issue by karoljas96** [turnermm/ckgedit#539]
There is no way to select text while editing page on mobile device (Chrome Android). When I tap and hold it shows context menu for 0,5sec. No possibility to copy, change color or bold. I'm begging you to fix it.

**Comment by turnermm** [comment]
Nothing I can do about this.

**Comment by karoljas96** [comment]
But it's basic functionality :( Mayby just simple solution (e.g. get the device width) to prevent displaying context menu on mobile phones. This menu doesn't work on touch screen at all but makes impossible to select text.
