### ISSUE TITLE
Problems with No Formatting handling "%%"

### ISSUE THREAD

**Issue by wikiwiki95** [turnermm/ckgedit#540]
**Problem**
writing content using ckgedit with the syntax 

`%%text%%`

it is saved to 

`<nowiki>text</nowiki>`

In dokuwiki both forms are supported to escape text from wiki processing. ckgedit should let the code as the user has typed it: `%%text%%`

**Why weed need the original syntax**
we are using the const-plugin to wirte a constant on top of a page an reuse text on several parts of the wiki page. the const-plugin uses the form %%const%% the reference to the constant string.

**Comment by turnermm** [comment]
I suggest that you contact the author of the const plugin to offer you an alternative. That would be very much simpler to do there than in ckgedit.

**Comment by Michaelsy** [comment]
@wikiwiki95 
At my point of view it is a real mistake for the const plugin to use an already used syntax.
