### ISSUE TITLE
Multiple lines in a cell + Text color

### ISSUE THREAD

**Issue by denisdeun** [turnermm/ckgedit#542]
Hello,

Here an issue related to tables.

1) I create a simple table, with a cell containing a line break (shift + enter)
<img width="59" alt="table issue 1" src="https://user-images.githubusercontent.com/64741790/80919690-b66f8380-8d6b-11ea-80b7-1e45f3531185.PNG">

The generated code is 

```
|A| |
|B|1 \\ 2|
|C| |


```

2) Then i change the text color in the first cell. I get this strange result :
<img width="110" alt="table issue 2" src="https://user-images.githubusercontent.com/64741790/80919710-d69f4280-8d6b-11ea-9d9c-4ce326e67447.PNG">

the generated code is :

```
|<font inherit/inherit;;#3498db;;inherit>A</font>| |
|B|1 \\
   2|
|C| |


```

Regards
Denis

**Comment by turnermm** [comment]
Use of font styling comes with multiple warnings:
https://www.dokuwiki.org/plugin:ckgedit:font_styling#important_preliminaries
It should be reserved for simple contexts.  For this reason it is turned off by default.
