### ISSUE TITLE
Latex Plugin Incompatibility

### ISSUE THREAD

**Issue by Blitzbirnep** [turnermm/ckgedit#544]
In my current setup I am using the ckgeditor and [latex plugin](https://www.dokuwiki.org/plugin:latex?s[]=latex) both in the latest versions. With the latex plugin it is possible to include latex code in order to generate tikz pictures like flowcharts. The syntax for this is 
<latex> code </latex>
However, after saving the page and reopening again the ckgeditor places code block environments within the <latex> </latex> tags automatically. Saving the document causes the latex renderer to fail due to the code tags.
I tried to use the  MULTI_PLUGIN_OPEN directive, but no success. Below you can find the content included with the native editor of dokuwiki and the modified content of ckgeditor.
[example_correct.txt](https://github.com/turnermm/ckgedit/files/4602712/example_correct.txt)
[example_auto_modified.txt](https://github.com/turnermm/ckgedit/files/4602713/example_auto_modifyed.txt)

Is there a way to prevent auto modification?

**Comment by turnermm** [comment]
Plugins which cannot work in ckgedit can be inserted into the page using the include plugin with the Dohuwiki editor.  You can also set a directory (or directories) where the Dokuwiki editor opens automatically.
