### ISSUE TITLE
Automatic text replacement

### ISSUE THREAD

**Issue by Blitzbirnep** [turnermm/ckgedit#546]
Is it possible to deactivate the automatic replacement of certain symbols? Or is it possible to configure which text combination will be transformed? 

For example "-->" is transformed to –> and "->" to →

**Comment by turnermm** [comment]
This done through dokuwiki's `conf/entities.conf`, which converts various character combinations to html entities.  You can redefine these by creating a file named `entities.local.conf` in the `conf/ `directory.  If you want them to keep the characters as typed, simply redefine them as themselves in entities.local.conf.
```
->    ->
-->   -->
```

**Comment by Blitzbirnep** [comment]
Thank you very much it worked
