### ISSUE TITLE
Display text for internal media and URLs

### ISSUE THREAD

**Issue by vic-t** [turnermm/ckgedit#548]
When creating a new link in DocuWiki, no matter if to an internal or external resource, the following syntax is used that allows us to give the link another name than the link URI itself. 

[[http://www.example.com|My Website]]

From what I can gather, CKGedit only supports this kind of separate display text for internal links. Neither for internal media nor for URLs does it seem possible to change the display text to something other than the link itself. At least not from within CKGedit, you can still very easily change it from the DW editor. 

Which is why it's not a showstopper. But it would be nice if CKGedit could do this, too. 

And thank you for your work on this plugin. It's a really great addition to DocuWiki.

**Comment by turnermm** [comment]
I've added a text box for an optional link text for URLs.  But in fact this was not actually needed since all that was needed was to edit the link's text in the editor.  You can do that for internal media.

**Comment by vic-t** [comment]
Ok, that's what I expected originally but my changes in the editor are not 
saved. If I change the link text in the editor and exit the editor, it goes 
back to showing the actual link. I'm on Greebo BTW.

**Comment by turnermm** [comment]
Don't know why that's so.

**Comment by turnermm** [comment]
I have temporarily had to remove this feature as it had unintended side-effects, corrupting media links.

**Comment by turnermm** [comment]
This feature has been re-enabled.
