### ISSUE TITLE
Not working with hogfather 

### ISSUE THREAD

**Issue by trasba** [turnermm/ckgedit#549]
Maybe with reference to #541 but I have no empty scripts
I updated to Release rc2-2020-06-01 "Hogfather" RC2 and since then I can't use ckgedit at all.
It just overwrites the pages with false.
Console gives:
```
script-cmpr.js:1 Uncaught ReferenceError: DOKU_BASE is not defined
    at script-cmpr.js:1
    at script-cmpr.js:1
```
I did a little debugging but with no success. I installed Release rc2-2020-06-01 "Hogfather" RC2 from scratch and just installed ckgedit -> same result
I uninstalled all plugins -> no change
![image](https://user-images.githubusercontent.com/14924356/83696425-c09bd080-a5fc-11ea-985b-a8d35105ac15.png)

Further Info:
```
VM4313 script-cmpr.js:1 Uncaught ReferenceError: DOKU_BASE is not defined
    at VM4313 script-cmpr.js:1
    at VM4313 script-cmpr.js:1
(anonymous) @ VM4313 script-cmpr.js:1
(anonymous) @ VM4313 script-cmpr.js:1
doku.php?id=testing2:1 Error while trying to use the following icon from the Manifest: https://my-domain.com/lib/exe/fetch.php?media=wiki:dokuwiki.svg (Download error or resource isn't a valid image)
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
Navigated to https://my-domain.com/doku.php?id=testing2&do=edit
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
doku.php?id=testing2&do=edit:149 Uncaught ReferenceError: jQuery is not defined
    at doku.php?id=testing2&do=edit:149
(anonymous) @ doku.php?id=testing2&do=edit:149
doku.php?id=testing2&do=edit:188 Uncaught TypeError: Cannot set property 'reset' of undefined
    at unsetDokuWikiLockTimer (doku.php?id=testing2&do=edit:188)
    at doku.php?id=testing2&do=edit:706
unsetDokuWikiLockTimer @ doku.php?id=testing2&do=edit:188
(anonymous) @ doku.php?id=testing2&do=edit:706
script-cmpr.js:1 Uncaught ReferenceError: DOKU_BASE is not defined
    at script-cmpr.js:1
    at script-cmpr.js:1
```
It looks like this
![image](https://user-images.githubusercontent.com/14924356/83696674-559ec980-a5fd-11ea-859f-eeb9ba7079b6.png)

I'll switch back to my productive environment but keep this instance. And disable ckgedit for the meantime. :pensive: Everything else works then.
Let me know if I can help debugging.

**Comment by RaphaelWimmer** [comment]
The root problem seems to be that from Hogfather on, all of DokuWiki's JavaScript is loaded with the "defer" attribute to speed up page loading. However, ckgedit's JavaScript is loaded immediately:
```
#<script charset="utf-8" src="https://code.jquery.com/jquery-3.5.0.min.js" defer="defer"></script>
<script charset="utf-8" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" defer="defer"></script>
<script charset="utf-8" src="/lib/exe/js.php?t=REDACTED" defer="defer"></script>
<script type="text/javascript" charset="utf-8" defer="defer" src="/lib/plugins/ckgedit/ckeditor/ckeditor.js"></script>
<script type="text/javascript" charset="utf-8" src="/lib/plugins/ckgedit/scripts/mediamgr.js"></script>
```

However, just adding the "defer" attribute to these script elements is not sufficient. 
The rest of the JS code in the document needs to react nicely to deferred loading of the .js files - probably by also adding the "defer" attribute to all script elements.
One might also need to change the LoadScript() calls in the document to LoadScriptDefer() calls.

**Comment by PaulLangham** [comment]
I too have the same issue even after restarting services and recreating the cache. Only remedy seems to be to disable this plugin?

**Comment by RaphaelWimmer** [comment]
> I too have the same issue even after restarting services and recreating the cache. Only remedy seems to be to disable this plugin?

Yes. Given that @turnermm is actively maintaining this plugin, I hope that a fix will be available rather soon :)

**Comment by splitbrain** [comment]
For now you can revert DokuWiki's script loading behavior by disabling the `defer_js` feature flag.

**Comment by trasba** [comment]
> For now you can revert DokuWiki's script loading behavior by disabling the `defer_js` feature flag.

Thanks
I didn't know that. This is a feasible work around. Until the plugin is adapted.

**Comment by PaulLangham** [comment]
> For now you can revert DokuWiki's script loading behavior by disabling the `defer_js` feature flag.

Sorry, where do I edit this script?

**Comment by RaphaelWimmer** [comment]
> > For now you can revert DokuWiki's script loading behavior by disabling the `defer_js` feature flag.
> 
> Sorry, where do I edit this script?

On the configuration page of your wiki:

→ https://YOUR_WIKI/start?do=admin&page=config#_feature_flags

see also https://www.dokuwiki.org/config:defer_js

**Comment by splitbrain** [comment]
@turnermm I had a quick glance at the code. @RaphaelWimmer's analysis is quite correct.

Following the code is a bit difficult but I think the following course of action should work:

1. There should be no JavaScript code be injected from PHP that actually executes any JS functions

In fact I would rewrite all initialization code to simply create an array of configurations that you need for the editor. Only output that from your PHP code.

Eg. something like

```php
$config['url] = DOKU_URL . 'lib/plugins/ckgedit/scripts/script-cmpr.js';
if(($ACT == 'login' || $this->session_id == false) && $this->getConf('preload_ckeditorjs')) {
     $config[url2] = DOKU_BASE.'lib/plugins/ckgedit/ckeditor/ckeditor.js';
}

echo '<script type="text/javascript">';
echo 'var CKGEDIT = ' . json_ecode($config) . ';';
echo '</script>'
```

(This is only one of the places I found, but you get the idea)

2. Move all your actual JS code to separate JavaScript files

These files can then be loaded either from your main `script.js` using the include mechanism (see https://www.dokuwiki.org/devel:javascript#include_syntax) or by calling a loader from the `script.js` code.

Eg. your code would check if `CKGEDIT.url` is set, and if so call `LoadScript` with it.

The trick here is that all the code in your `script.js` file is only executed when the rest of DokuWiki has been loaded, too. It takes care of the `defer` stuff for you.

3. If you want to load your own files you need to adjust your `LoadScript()` function.

You can not use `document.write()`. But that's no problem. You can instead simply append to the DOM.

Something like this should work:

```javascript
    function LoadScript( url )
    {
        jQuery('head').append('<scr' + 'ipt type="text/javascript" src="' + url + '"><\/scr' + 'ipt>');
    }
```

Hope this helps. It's not so overwhelming as it seems at first. Take your time and don't feel pressured. People can use the feature flag for now and you can work on it on your own time.

Let me know when you need help. Cheers Myron :beers:

**Comment by turnermm** [comment]
@RaphaelWimmer
This version should be ok until I work through the suggestions made by@splitbrain:
  
https://github.com/turnermm/ckgedit/archive/hogfather_rc.zip

**Comment by WernerAUT** [comment]
thanks for the quick temp fix, but i have one issue, i can't use the internal link option anymore, it shows me no links inside? Could this be a permission issue or is it a issue with your build?

**Comment by turnermm** [comment]
I've been working on the compatibility problem, and I've had to restructure some of the code.  For simple plugins, the changes required were minimal, but for ckgedit, they were substantial.  But I now  have a new update, which will be usable both by users who have not updated to hogfather and those who have, and which is much better in terms of coding standards and hopefully, therefore, more error-free:
https://github.com/turnermm/ckgedit/archive/hogfather_rc3.zip
As the `rc3` indicates, this is the third revision.   When the dokuwiki developers issue their final version of hogfather, this will become the master version of ckgedit.

**Comment by WernerAUT** [comment]
great thanks for the quick answer and for the new version, i tested it and it seems to work as it should, one thing i still have with internal link, it seems to use still the DW Media Manager for internal links, which is not a big issue, but when i choose a internal link and then press OK the Link will get created but the window doesn't close, so i need to abort.

**Comment by turnermm** [comment]
You may have to clear the cache, both browser and dokuwiki (here I would delete all the directories in data/cache).
  In this most recent version, when you have selected a link from the linkwiz, its `id` will appear in the link dialog in the `Link Display Text` box, as shown in the image:
![2020-06-15_08h26_05](https://user-images.githubusercontent.com/176447/84662975-25e79f80-aee2-11ea-8fdd-57d354be3382.png)
Then click `OK`.  I haven't gotten around to updating the label yet, but this gives you the idea.

**Comment by WernerAUT** [comment]
yeah i know but here is the problem, i can click "OK" but the window doesn't close, it makes the correct action so the link gets included but with OK just the window doesn't close so i need to hit abort to get out of it.
I deleted the cache and still the same.

**Comment by turnermm** [comment]
Which browser and which system is it on?

**Comment by WernerAUT** [comment]
tested it now with opera, firefox and chrome
Debian 9.12 Root Server, never had issues only since update to hogfather

**Comment by turnermm** [comment]
Double Click might be the ticket. On Centos, it requires a double click in Chrome, but not in FF.  In Ubuntu 18.04 it works in both FF and Chrome as in Win10, a single click.  Didn't bother trying it with Opera.  So you'll have to test it out to see if the double click works for you in Debian.

**Comment by WernerAUT** [comment]
no double click doesn't work, anyway that is not a big issue anyway, but thanks for your help

**Comment by turnermm** [comment]
Unfortunately I only have access to debian distros via command line, so I can't test this on debian.   But this a.m. when I went to test again on Centos the problem disappeared.  But on centos this a.m. I turned off defer_js in the configuration settings and that seemed to make a difference.  So you can try that.  But it puzzles me as to why that would make a difference to the ckeditor, especially at that late point in the execution of the ckeditor's link app.

**Comment by turnermm** [comment]
Most of this has been fixed. Thje remaining is left is handled in other issue requests.
