### ISSUE TITLE
Installation instruction improvement (powershell command due to continued deprication of cmd in wndws env)

### ISSUE THREAD

**Issue by meliorit** [turnermm/ckgedit#550]
Hi,
Your installation instructions include a guide on how to deal with creating symbolic links for linux and windows.  It might be prudent to add powershell information.

`New-Item -ItemType SymbolicLink -Path "media" -Target "\path\to\media"`

**Comment by turnermm** [comment]
Thanks for the tip.  At the moment I'm tied up with trying to get ckgedit to work as well as possible with the latest dokuwiki upgrade hogfatherc RC2.  You could update the ckgedit page if you have a login, which you can get by signing up for the forum.  There may be  a few days delay after signing up before you can edit or create pages.

**Comment by turnermm** [comment]
Thanks for the tip.  At the moment I'm tied up with trying to get ckgedit to work as well as possible with the latest dokuwiki upgrade hogfatherc RC2.  You could update the ckgedit page if you have a login, which you can get by signing up for the forum.  There may be  a few days delay after signing up before you can edit or create pages.

**Comment by turnermm** [comment]
I've done this.  Thanks.
