### ISSUE TITLE
Images - Browse Server Issue

### ISSUE THREAD

**Issue by coffeesurfers** [turnermm/ckgedit#552]
On a freshly installed copy of Dokuwiki (Release 2018-04-22b "Greebo") running on a Synology NAS, I've come across a frustrating issue with the image / browser server screen.

The issue is that within all browsers (safari, chrome, Firefox) the thumbnails sporadically show.
Most of the time, just the image file name(s) will be listed and where the thumbnail should be is a question mark
<img width="1236" alt="FCKeditor - Resources Browser 2020-06-08 19-40-02" src="https://user-images.githubusercontent.com/66641609/84068453-dfb1ae00-a9c0-11ea-83a0-b835f13ead3f.png">

Again more often than not, this screenshot is how the browser server window appears
On the odd occasion will the thumbnails show.  Have tried several browsers, cache clears and there doesn't seem to be any consistency with this happening.

Even re-installed the plugin, re-installed DokuWiki to no avail.  Even restarted the NAS!

Furthermore, when this thumbnail issue is occurring, am able to browse to and upload further images, however on selecting the OK button, nothing happens.  
<img width="451" alt="browse" src="https://user-images.githubusercontent.com/66641609/84069583-a712d400-a9c2-11ea-858c-3851d39d1146.png">

**Comment by turnermm** [comment]
You may have an htaccess file that prevents the image browser from accessing images.    Otherwise,  set the winstyle configuration option to true.

**Comment by coffeesurfers** [comment]
you got me at the win style config option... where does one edit this?

**Comment by turnermm** [comment]
In the ckgedit section of the Dokuwiki Configuration Manager under Administration

**Comment by coffeesurfers** [comment]
Ya beauty! Worked a treat, I can now use the image function without any further thumbnail/insertion issues! ![image](https://user-images.githubusercontent.com/66641609/84082206-5f4a7780-a9d7-11ea-94b6-8cb26215ae6f.png)
