### ISSUE TITLE
Wampserver image upload issue

### ISSUE THREAD

**Issue by coffeesurfers** [turnermm/ckgedit#553]
Have installed dokuwiki and then ckgedit, however when attempting to upload images, the plugin just times out, on attempting for example to choose a file, get the below error.

dokuwiki was installed via wampser if that has any bearing on troubleshooting
_NOTE - The built in media manager does not have any permissions issues controlling media_

Is this a bug, permissions issue, wampserver issue?
![Capture](https://user-images.githubusercontent.com/66641609/84910333-a9ee8280-b0ae-11ea-9bc3-f57863806ec8.PNG)

**Comment by coffeesurfers** [comment]
Actually just reinstalled and saw this note...


Because of changes to hogfather, the ckgedit media browser does not work. Until this issue is solved, you wlll have to use the DokuWiki media manager. To do this, go to the Configuration Manager, in the ckgedit section, and set both “default_ckg_filebrowser” and “allow_ckg_filebrowser” to dokuwiki

**Comment by turnermm** [comment]
If you are using hogfather, there is a distribution of ckgedit dedicated to hogfather: 
https://github.com/turnermm/ckgedit/archive/hogfather_rc3.zip
Please see https://www.dokuwiki.org/plugin:ckgedit#note_on_hogfather, which describes how to install, in case you are not wholly familiar with the extension manager.

**Comment by coffeesurfers** [comment]
Thanks mate, pointed the manual plugin install to the zip link which worked perfectly thanks
