### ISSUE TITLE
GeShi not complete

### ISSUE THREAD

**Issue by LMS235** [turnermm/ckgedit#555]
It seems that the GeShi plugin is not fully implemented. The texts do not yet fit completely (see title: "Abbreviation Properties") and also the fields are not filled in completely.

![image](https://user-images.githubusercontent.com/8693550/85582541-cefa6c80-b63d-11ea-92d5-79ab085693b9.png)

Besides, nothing happens when you enter a file name (in the Dokuwiki it should be a `<code language file>...</code>`)

**Comment by turnermm** [comment]
The breaking of code snippets has been an intermittent problem, making it almost impossible to fix, since I have not been able to reproduce it.  I tested again this a.m. after your post on both Win 10 and Centos Linux but again could not reproduce the problem.  Since you seem to be getting this consistently and have coding experience, perhaps you could take a look at it. Thx.

**Comment by LMS235** [comment]
Unfortunately my development skills are not sufficient for this. Which version of Dokuwiki and also php do you use? Maybe the problem can be narrowed down?

We currently have 
- Release 2018-04-22b "Greebo"
- 7.2.19 (via FastCGI)

**Comment by turnermm** [comment]
Greebo  22c and various versions of php from 5.6 to 7.4.7

See https://www.mturner.org/devel/playground/geshi.  The bottom version (made with the geshi tool) I just inserted today. My site (mturner.org) runs on Centos 5.6.  But I've also tested on various generations of ubuntu, Centos and Windows servers.  But it's more likely the browser and OS on which the browser is running.

If there's any connection to the server, the only difference I can see is that you are running fastcgi.

**Comment by turnermm** [comment]
I should add thath I've also tested on hogfather RC3.

**Comment by LMS235** [comment]
Unfortunately I have no edit rights on the playground, so I can't test this.
As a client I have tested Chrome (83.0.4103.116), FF (77.0.1) and Edge Chrome (83.0.478.54). Both on Windows 10 2004 and Windows 10 1909.

**Comment by LMS235** [comment]
@turnermm fixed? or why closed?

**Comment by turnermm** [comment]
You can reopen this if you have something to add.  But I can't try to fix something I can't see.
