### ISSUE TITLE
A line break is added when editing page with table and paragraphs

### ISSUE THREAD

**Issue by PankajRasgania** [turnermm/ckgedit#556]
When we edit a page having content that is mix of table and paragraphs, ckgedit adds a line break at the end of the page.  The wiki source of such a test page looks like 
```
====== Test ======

ABCD

|A|B|
|C|D|
|E|D|

TEST

\\
```
This issue can be reproduced by -
1. Create a page with some text and a table and save.
1. When the page is first created, no extra line break is added.
1. Edit the page using ckgedit and add some text or delete some text and save.
1. After saving, ckgedit adds an extra line break at the end.

May be this issue is related to #461 but this happens outside the table block.

**Comment by turnermm** [comment]
I'm afraid you'll have to live with that

**Comment by PankajRasgania** [comment]
Okay. Thanks 👍
Looks like I will have to do some CSS styling to hide extra line breaks for the reader 😅

**Comment by turnermm** [comment]
I thought I'd take a look at this.  That extra line-break has been there for some years.  It seems harmless so I'd never looked at it.  But I did find a quick fix. My server is without an internet connection  until probably Friday, and I'm stuck with a hotspot from my cell phone to my laptop. So I can't make the change to the ckgedit distribution.  But you can download the relevant file, attached here: 
[save.zip](https://github.com/turnermm/ckgedit/files/4852939/save.zip)
Unzip this and replace the current file (save.php) which is in the ckgedit/action directory with this save.php.
Let me know how you make out.

**Comment by PankajRasgania** [comment]
Great. This is working very good. Thanks a lot.

**Comment by PankajRasgania** [comment]
Now it seems to remove even explicit line brakes on save by the user.
`\\` will not work in ckgedit after this.

**Comment by PankajRasgania** [comment]
I found a solution.
Before the function ckgedit_save_preprocess returns, you added `$TEXT = preg_replace('#(\s*(\\\\)\s*)+$#ms', "",$TEXT);`
Instead of this, if we add the following, it should work
```
$TEXT=trim($TEXT);
if(substr($TEXT, -2) == "\\")
{$TEXT=substr($TEXT,0,-2);$TEXT=trim($TEXT);}
```
This ensures linebreak will be removed only if exists at the very end of the text (and hence not needed in any case).

**Comment by turnermm** [comment]
Yes, that was my intention, to strip away sequences of DokuWiki line-break characters at the end of the file.  This, I think, would do what you want:
 $TEXT = preg_replace('#((\\\\){2}\s*)$#', "",$TEXT); 
It strips out only the final `\\` followed by any spaces.  Unfortunately, I didn't have any success with your suggestion.

**Comment by PankajRasgania** [comment]
Something is amiss.  This expression is not working. I am not very familiar with regular expressions, could you please tell what the `#` means in this expressions. 

I tried an online php compiler ([here](https://www.onlinegdb.com/online_php_interpreter)) to test this line but getting this error
```
PHP Warning:  preg_replace(): Compilation failed: missing ) at offset 12 in /home/main.php on line 10      
```

Also I must point out that when things like `~~COMPLEX_TABLES~~` are replaced by "", it leaves the preceding line breaks ('\n' and not `\\`) as it is.  So I have noticed that ckgedit creates a text file that always has two lines breaks ('\n') at end. This is why, I trimmed $TEXT before looking for `\\` at the end of string. Anyways I think it will be good to trim the $TEXT once all string replacements have been done.

**Comment by turnermm** [comment]
You must have mis-copied, because copying the exact text I sent you above and pasting it as follows into the online interpreter linked to in your post:
```
$TEXT = "Hello World";
$TEXT = preg_replace('#((\\){2}\s*)$#', "",$TEXT);
```
I get the following result:
    `...Program finished with exit code 0 `
That is, no errors.  

In the meantime, I will leave things as they are.  You are, of course, welcome to alter the code as you need.  Let me know what you decide to do.

**Comment by PankajRasgania** [comment]
Found the problem.
`$TEXT = preg_replace('#((\\\\){2}\s*)$#', "",$TEXT);`
This works. The issue was that `\\` in php string generated a single `\` which made the regular expression invalid. 
I added a `\s*` before the backslash block to match any preceding spaces too. 
So now,
```
$TEXT = preg_replace('#(\s*(\\\\){2}\s*)$#', "",$TEXT);
$TEXT=trim($TEXT);
```
This code seems to works fine for me.
Check if this is correct.
Also I suggest to trim $TEXT in all cases before return as there are always trailing '\n' in it.

**Comment by PankajRasgania** [comment]
I think the whole misunderstanding regarding the expression arose because you did not put the code in code block in [this comment](https://github.com/turnermm/ckgedit/issues/556#issuecomment-652406749) and `\\\\` was replaced by `\\` by the github markup renderer.  😂😅
Thank you for your help.

**Comment by turnermm** [comment]
Yes, you're correct: 4 backslashes.  Each single backslash requires four in a regular expression.  Backslashes have to be escaped.  So the two right-most backslashes represent a single backslash, and the two left-most another single which escapes the backslash on the right.  So this: 
`'#((\\\\){2}\s*)$#`
represents two escaped backslashes followed by any number of spaces at the end of the text being matched.

**Comment by turnermm** [comment]
The update is currently in this branch:  https://github.com/turnermm/ckgedit/archive/delFinalNL.zip

**Comment by PankajRasgania** [comment]
In your commit, you have used multi line mode `$TEXT = preg_replace('#(\s*(\\\\)\s*)+$#ms', "",$TEXT);` which is removing even explicit `\\`  after a line by the user.

**Comment by turnermm** [comment]
I fixed this in the most recent version of the above branch.  You can enter the fix yourself in save.php:
  `$TEXT = preg_replace('#((\\\\){2}\s*)$#', "",$TEXT);`
This leaves out the `/m` flag and just removes the final instance of `//` at the end of the file.

**Comment by PankajRasgania** [comment]
Okay
