### ISSUE TITLE
It should not be allowed to insert a big amount of data via "Paste from Word"

### ISSUE THREAD

**Issue by g-user** [turnermm/ckgedit#557]
It is allowed to paste really big images (or other data)  via the "Paste from Word" (which is forbidden via CTRL-V)- [tested it with 20Mb png data with firefox] .  This will not insert the data and will sometimes delete the page after saving. The image (or other data) is definitely not saved to the page.

So I suggest to remove the different treatment of "Paste from Word" in script.js:

```
  html =  html.replace(/(<img.*?src="data:image\/\w+;base64,\s*)(.*?)(\/>)/gm,
                  function(match, p1, p2) {  
                  var skip = false;
                   if(p1.match(/msword/) ) {
                       skip = true;
                       match = match.replace(/msword/,"");
                   }
                   if(p2.length > 2500000 && !skip ) {
                        jQuery('#dw__editform').append('<input type="hidden" id="broken_image" name="broken_image" value="' + p2.length +'" />');
                        return  '{{' + broken_image + '}}';       
                    }                        
                    return match;
           });
```

**Comment by turnermm** [comment]
If you have a change, fork ckgedit and make a pull request.

**Comment by g-user** [comment]
Hi,
sorry I don´t have a patch for that - I only saw, that you handle CTRL-V and "Paste from Word" different. But also pasting a big amount of data in the "word paste window" will crash the page - in the same way as ctrl-v does.

**Comment by turnermm** [comment]
I am closing this in favor of #567

**Comment by turnermm** [comment]
https://github.com/turnermm/ckgedit/archive/master.zip

Try using your upload with the above version.  It syncs the hogfather versions with the master.  I was not successful embedding images in the editor.  The first message said that there was a successful upload, but a second said it could  not save to the namespace.  I did have one successful upload with a gif but it failed on the second try. 

I tried both the master (above) and a version of stable-master, which I have not uploaded to github, and two different dokuwikis.  Maybe you can work out the problem.

**Comment by g-user** [comment]
I´m afraid, that I don´t understand the intention of reopen this. Did you mix this with #567?
I opened this (#557) because of a crash, if you import large images via "Paste from Word" menu entry in ckgedit. 

To reproduce the problem:
1. Download the wikipedia-image  and open it in paint.exe https://upload.wikimedia.org/wikipedia/commons/2/2c/Desiccation-cracks_hg.jpg
2. copy the image in paint.exe to the clipboard (step 1 and 2 are important, otherwise you would copy the external link)
3. edit any page with ckgedit and open the "paste from word" entry from the ckgedit-menu
![crash1](https://user-images.githubusercontent.com/21956057/88566764-c3340880-d036-11ea-87e7-e720f4347ec7.jpg)
4. click "ok" 
5. if you switch in editor to source view, you can see a big amount of base64-data.
![crash2](https://user-images.githubusercontent.com/21956057/88567168-671db400-d037-11ea-8f96-49b41ec0d042.jpg)
6. if you click "save", the image will not be saved (you have to click save 2 times)

So it should not be possible to import such an image via "paste from word" - you implemented  a similar "forbidden behavior" for  images that are pasted via CTRL-V in commit "Implements size checking for ctrl-v image insertions"  from 2018/11/21
