### ISSUE TITLE
FCKeditor Resources Browser error

### ISSUE THREAD

**Issue by taizoli** [turnermm/ckgedit#558]
Hi,

i have a problem with FCKeditor. I can not upload any Pictures. I dont see my data.

Apache Logfile:

PHP Fatal error:  require_once(): Failed opening required '/dokuwiki/inc/Input.class.php' (include_path='.:/usr/share/php:/usr/share/pear') in dokuwiki/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/input_utils.php on line 9, referer: https://mysite/lib/plugins/ckgedit/fckeditor/editor/filemanager/browser/default/frmfolders.html

Could you please help me!
Thank You

Regards 
Zoltan

**Comment by taizoli** [comment]
I use DokuWiki Release rc-2020-06-09 "Hogfather" RC3

**Comment by turnermm** [comment]
See https://www.dokuwiki.org/plugin:ckgedit#note_on_hogfather.  
Use: https://github.com/turnermm/ckgedit/archive/hogfather_rc3.zip
