### ISSUE TITLE
popin don't close with internal file pdf

### ISSUE THREAD

**Issue by vinsse2001** [turnermm/ckgedit#559]
Hello,

I updated to last version of dokuwiki (Release rc-2020-06-09 "Hogfather" RC3) and ckgedit manual installation (from https://github.com/turnermm/ckgedit/archive/hogfather_rc3.zip).
I copy .htaccess.security from /lib/plugins/ckgedit/fckeditor/userfiles to /data/media/ after modifying list of authorized files (I added pdf, doc, odt, xls, see code before).
I upload some PDF documents and when I put a link on text, as internal file (choosing a PDF file), when I click OK, link is added but popin window don't close. If I close it manually, I have a warning ("beware : modifications will be lost...") but link stay (hopefully ;).

Here is the error message (showed in Chrome console) :
```
link.js?t=J39A:1 Uncaught ReferenceError: url_text is not defined
    at CKEDITOR.dialog.<anonymous> (link.js?t=J39A:1)
    at i (jquery.php?tseed=5bb1a98b139b46abd22c69cae01d7704:2)
    at CKEDITOR.dialog.onOk (link.js?t=J39A:1)
    at CKEDITOR.dialog.<anonymous> (ckeditor.js:601)
    at CKEDITOR.dialog.p (ckeditor.js:10)
    at CKEDITOR.dialog.fire (ckeditor.js:12)
    at button.onClick (ckeditor.js:624)
    at button.<anonymous> (ckeditor.js:563)
    at button.p (ckeditor.js:10)
    at button.fire (ckeditor.js:12)
```

And here is the .htaccess modified :

```
#unix  -- do not change or move
<IfModule mod_authz_host>
    Require all denied
</IfModule>
<IfModule !mod_authz_host>
    Order allow,deny
    Deny from all
</IfModule>

<FilesMatch "\.(gif|jpe?g|png|pdf|doc|odt|xls)$"> 
<IfModule mod_authz_host>
    Require all granted
</IfModule>
<IfModule !mod_authz_host>
    Order allow,deny
    Allow from all
</IfModule>
</FilesMatch>

Options -Indexes
```

**Comment by turnermm** [comment]
There has been a problem with some browsers and some systems that I have not been able to fix because I cannot reproduce the error on mymachines.  You can go to the configuration options and set `defer_js` to false and install the main version of ckgedit from the extension manager.  I hope that will help.

**Comment by vinsse2001** [comment]
Thank you for your answer Myron, I tried but no change on Chrome.
On Firefox, it is ok, no bug... so I can use it 😉
Bye, thanks for your plugin ! very useful

Le jeu. 2 juil. 2020 à 16:48, Myron Turner <notifications@github.com> a
écrit :

**Comment by turnermm** [comment]
Sorry I could not be more helpful,

**Comment by vinsse2001** [comment]
no problem ;)

Le sam. 15 août 2020 à 21:58, Myron Turner <notifications@github.com> a
écrit :
