### ISSUE TITLE
CKGedit probably ignores settings at DokuWiki's config file scheme.conf

### ISSUE THREAD

**Issue by mirakrejci** [turnermm/ckgedit#560]
Hello,

CKGedit plugin ignores url scheme listed at the config file scheme.conf and corrupts external links to the Hansoft application.

``
example:   hansoft://hansoft.pub.i3.cz;I3CZ;c6afaab2/Task/54163?ID=385
``

If I change the hansoft:// scheme to http:// for example, then CKGedit works well with it.

> 
scheme.conf:
#Add URL schemes you want to be recognized as links here

http
https
telnet
gopher
wais
ftp
ed2k
irc
ldap
hansoft

> 

Thanks for the fix.
Mira Krejci

**Comment by mirakrejci** [comment]
I would like to emphasize that this is a general problem when using the protocol in the url (hansoft:// I mentioned only as an example). The Dw editor respects the url schema settings in the conf / scheme.conf configuration file, but CKGedit does not.

**Comment by turnermm** [comment]
I have a new branch with support for  schemes in the link dialog:
   https://github.com/turnermm/ckgedit/archive/link-schemes.zip
It uses the schemes it finds in `conf/scheme.conf`.   Please let me know if it works for you.

**Comment by mirakrejci** [comment]
Hello,

unfortunately it doesn't work for us.

I installed the plugin manually and selected Upload Extension from the link-schemes.zip file.
The behavior is exactly the same as before. If I edit a page that had a working hansoft:// link (created by DW editor) url and then save it here, the link is corrupted (instead of the original url, for example [[hansoft://hansoft.pub.i3.cz; I3CZ;c6afaab2/Task/51734?ID=7248|External Hansoft Link]] is here [[.: External_hansoft_link|External Hansoft Link]].

If I want to create a link for hansoft:// in CKGedit, it don't offer it at all. In the drop-down menu I see only http, https, ftp and news under the protocol.

Thanks.
Mira Krejci

**Comment by mirakrejci** [comment]
Hello,

when I create a link in CKGedit (new branch with support for schemes), I can already select the hansoft:// protocol, so CKGedit started respecting the settings in conf/scheme.conf.

Unfortunately, if I enter some url, it is not saved correctly. Similarly, the hansoft:// link created earlier in the DW editor is corrupted by CKGedit (see my previous comment).

Thanks for the fix!

Mira Krejci

**Comment by turnermm** [comment]
I've removed the schemes from the current branch because there's no simple way to handle them.  Because of the new hogfather distribution of dokuwiki, ckgedit has required complex and innumerable hours of refactoring.  Moreover, I'm author of upwards of 40 other plugins, all of which have to be tested against the hogfather upgrade.  So you'll have to forgive me if your request is not at the top of my to-do list.

**Comment by mirakrejci** [comment]
That fix is really very important for us, but I understand that you have a lot of work to do. 
What is your estimate of when you would find the time for those schemes? Thanks.

**Comment by turnermm** [comment]
I have a solution that will work until a solution is found for the schemes.  Ckgedit understands interwiki links.  If you are not familiar with them check the syntax  page.

In conf/interwiki.conf insert one or both of the following:
```
hansoft   hansoft://hansoft.{NAME}
hsoft     hansoft://{NAME}```

For NAME, you substitute your url content.  In the first form:
`pub.i3.cz;I3CZ;c6afaab2/Task/54163?ID=385`

In the second form:
`hansoft.pub.i3.cz;I3CZ;c6afaab2/Task/54163?ID=385

In the dokuwiki editor you would use
```
[[hansoft>pub.i3.cz;I3CZ;c6afaab2/Task/54163?ID=385]]
[[hansoft>hansoft.pub.i3.cz;I3CZ;c6afaab2/Task/54163?ID=385]]
```
In the link tool of ckgedit you will select `interwiki link` from the link type drop down menu and fill in the link content in the replacement text box. When you reload the link after saving, you may occasionally see reduced size italic text after a forward slash.  You can ignore this, it will right itself.

`

**Comment by turnermm** [comment]
If you decide to go with this, create a file in the conf folder named interwiki.local.conf and insert the hansoft interiwiki  urls there.  

Since I've already done it, attached
[interwiki.local.zip](https://github.com/turnermm/ckgedit/files/5063173/interwiki.local.zip)
 is a copy of mine.

**Comment by mirakrejci** [comment]
Hello,

thanks a lot for your efforts to help us, but unfortunately your proposed workaround does not work for us. We tested it for a long time, but we didn't break through it.
DW editor works with interwiki links perfectly after editing interwiki.conf or interwiki.local.conf.

When we use the link tool in CKGedit and select the "interwiki link", interwiki type "hsoft", then only text after the last slash is taken from any url entered in the replacement text.

For example:
replacement text: host.any.domain/path1/path2/anything
link created by CKGedit: hansoft://anything

Thanks.
Mira Krejci

**Comment by turnermm** [comment]
It had worked for me using the example you gave and another that I found on the web. But there was a bug in the interwiki code which I have since fixed, and generally updated the code that handles interwikis.  The changes are now in the current standard distribution, `hogfather-merged`, which you can get by clicking the` re-install` button in the extension manager.

**Comment by mirakrejci** [comment]
You're right. After the update to the current version, the links already work (the url is not shortened).
It's a pity that when using this workaround, it is not possible to use a link title with text different from url text.

Thank you
Mira Krejci

**Comment by turnermm** [comment]
>It's a pity that when using this workaround, it is not possible to use a link title with text different from url text.

**Comment by turnermm** [comment]
The fixes for the interwiki urls have now been merged into the main branch, which is what you get when you reinstall using the extension manager.

**Comment by mirakrejci** [comment]
Great!! It works nicely!
Thanks!

**Comment by turnermm** [comment]
Glad we got this sorted out.

**Comment by mirakrejci** [comment]
Please, do not close this issue, because the solution by interwiki links is only workaround (until a solution will be found for the schemes) as you wrote at comment 12 days ago.

Thank you.

**Comment by turnermm** [comment]
I'm not sure when I will get around to that.  It's somewhat more complicated than using interwiki links, which Dokuwiki itself uses:
```
[[doku>interwiki]] | links to the DokuWiki wiki
[[this>feed.php]]   | links to your wiki's URL
```
In anther words, they are perfectly valid Dokuwiki constructs. The reason I moved over to interwiki links
is that they do the same job that schemes  and would require less complexity and less work to implement.  As it is, I  spent a great deal of time on this.  If it's so important to you and you work for a company that has a budget, I suggest you consult [wikimatrix]( https://www.wikimatrix.org/) and see if you can hire a consultant.
