### ISSUE TITLE
CKGedit corrupts markup if stylized links are used

### ISSUE THREAD

**Issue by mirakrejci** [turnermm/ckgedit#561]
Hello,

CKGedit plugin corrupts links that are stylized. We know that it is written about here:

``
https://www.dokuwiki.org/plugin:ckgedit:font_styling#conflicts_with_dokuwiki_links
``

, but the problem is that people cannot work with it. Browser
often does not display a warning to give them a chance to change something.
Is there anything you can do about it?

Thanks!
Mira Krejci

**Comment by turnermm** [comment]
You can't use styles for links inside the link markup in Dokuwiki, ie. bold, underlined, etc. and neither can you do this with ckgedit.

**Comment by mirakrejci** [comment]
I apologize. The previous comment was incomplete and inaccurate.
We only noticed the problem when using Chrome browser on Windows. Saving a page with a stylized link will corrupt the page (markup) in this case. Is there anything you can do about it?
Using Windows with Firefox or using both browsers under Linux is not problematic.

Thank you very much!
Mira Krejci

**Comment by turnermm** [comment]
![link-style-conflict](https://user-images.githubusercontent.com/176447/86390239-560e9c80-bc5d-11ea-80cc-301d9fc0e1db.png)

The above is the result in Chrome.  What version of ckgedit are you using?

**Comment by mirakrejci** [comment]
Hello,
we use the latest version (stable-master_20-Jun_22-12_30).
I will try to get more information from our Windows users for more detailed description of the issue.

Mira Krejci

**Comment by mirakrejci** [comment]
Hello,

I'm giving you steps for reproduce: 

1. create an easy document in the wiki (the word test written in italics):

  //Test//

2. now edit the document in ckgedit
3. select "Test"
4. type some link e.g. https://example.org/ (will replace the selected text; note Italics formatting button is pressed)
5. save the document (browser do not show any warning)
6. the resulting document's markup is corrupted (extra //) are added

**Comment by turnermm** [comment]
This is happening because of the final forward slash ` https://examp:le.org/ `.   Just leave it off.

**Comment by mirakrejci** [comment]
Hello,

no, it happens always, even if the final forward slash is not present (https://example.org). 
Mira

**Comment by turnermm** [comment]
There's nothing I can do about this.

**Comment by mirakrejci** [comment]
We'd like to pay for solution of this problem.

When you write "There's nothing I can do about this", does that mean that the error is not on CKGedit's side? Is this a DokuWiki problem? I know I'm obtrusive, but that functionality is really important to us.

Thank You!

**Comment by turnermm** [comment]
The question is how much time it's going to take and how much time together with your other request (https://github.com/turnermm/ckgedit/issues/560), which is certainly valid.  I have many plugins that I have to test against the hogfather upgrade and I'm in the midst of other upgrades to ckgedit. Unfortunately, there are not many programmers who are familiar with ckgedit, but if you want to pay, check out [wikimatrix](https://www.wikimatrix.org/consultants/).  Or post to the forum.

**Comment by turnermm** [comment]
The question is how much time it's going to take and how much time together with your other request (https://github.com/turnermm/ckgedit/issues/560), which is certainly valid.  I have many plugins that I have to test against the hogfather upgrade and I'm in the midst of other upgrades to ckgedit. Unfortunately, there are not many programmers who are familiar with ckgedit, but if you want to pay, check out [wikimatrix](https://www.wikimatrix.org/consultants/).  Or post to the forum.

**Comment by turnermm** [comment]
![2020-07-08_16h35_14](https://user-images.githubusercontent.com/176447/86973405-20c0ed80-c13a-11ea-8a87-f5cd06a185c1.png)

![final italic-url](https://user-images.githubusercontent.com/176447/86973457-333b2700-c13a-11ea-87b3-317b76f8f53a.png)

**Comment by turnermm** [comment]
Try this sequence.  
1. Open the link tool and enter your url followed by the forward slash.
![2020-07-08_16h35_14](https://user-images.githubusercontent.com/176447/86973802-c6745c80-c13a-11ea-88f0-489f4dbef09c.png)

2. Click `OK` to insert the link in your document.  Select the link with your mouse and select the italic tool Now you have the selected link in italics.

![italicurlresult](https://user-images.githubusercontent.com/176447/86973976-16ebba00-c13b-11ea-8b21-ffb24c3a8012.png)

3. Save your work and you have an italicized link with a forward slash:
![final italic-url](https://user-images.githubusercontent.com/176447/86974435-f5d79900-c13b-11ea-8bcb-c442f9529a22.png)

**Comment by turnermm** [comment]
Try this sequence.  
1. Open the link tool and enter your url followed by the forward slash.
![2020-07-08_16h35_14](https://user-images.githubusercontent.com/176447/86973802-c6745c80-c13a-11ea-88f0-489f4dbef09c.png)

2. Click `OK` to insert the link in your document.  Select the link with your mouse and select the italic tool Now you have the selected link in italics.

![italicurlresult](https://user-images.githubusercontent.com/176447/86973976-16ebba00-c13b-11ea-8b21-ffb24c3a8012.png)

3. Save your work and you have an italicized link with a forward slash:
![final italic-url](https://user-images.githubusercontent.com/176447/86974435-f5d79900-c13b-11ea-8bcb-c442f9529a22.png)

**Comment by turnermm** [comment]
Using the technique outline above, we can get this image--bold, italic, underlined-with final forward slash. 


![bui](https://user-images.githubusercontent.com/176447/86978191-da708c00-c143-11ea-9aa9-599ff6fa18fb.png)

This is because it enables the parser to create a syntax that Dokuwiki understands:
`__//**[[https://mturner.org/|https://mturner.org/]]** //__`

**Comment by mirakrejci** [comment]
Thanks you very much for your answer. 
# 560 has a much higher priority for us than this problem, but I have this observation:

If a link without a style is made first and then a style is assigned, everything will turn out well (see your example - it doesn't matter if a backslash is used at the end of the url or not):
``
[[http://example.com|TEXT]]       ->       **[[http://example.com|TEXT]]**
``

However, if the procedure is reversed and the stylized link is at the beginning, then the subsequent creation of the link will damage the markup:
``
**TEXT**          ->         **[[http://example.com|TEXT**]]**
``

The only problem is that the editor inserts extra ** after the link text.

Thank you.
Mira

**Comment by turnermm** [comment]
>if a link without a style is made first and then a style is assigned, everything will turn out well (see your example - it doesn't matter if a backslash is used at the end of the url or not):
[[http://example.com|TEXT]] -> \*\*[[http://example.com|TEXT]]\*\*  

This is exactly how you would do it in the native DokuWiki editor.  I will try to get to your other issue when I've finished with hogfather, which has required a major, time-consuming restructuring of ckgedit.  I'd like some typical examples of  hansoft links, other than the one you provided in #561
