### ISSUE TITLE
issues with file browser on hogfather and greebo

### ISSUE THREAD

**Issue by kjguenther** [turnermm/ckgedit#565]
I have installed the special version of ckgedit that you designed for Hogfather rc3. It is listed as a 2020-06-13 release in my dokuwiki. When we use the DW file browser in ckgedit under Hogfather RC#, we are not able to use the search function in the browser. When we use the search function, and the file we want appears, clicking on it does nothing. The only way to insert the code is to manually scroll down to the right file and then select it. Once the code has been inserted into the dialog window, the "OK" button will not close the dialog window. We have to click on the "x" in the top right corner and ignore the error message - "You have changed some options. Are you sure you want to close the dialog window?". The code is inserted, but the error message gives you the impression that the process is incomplete.
I also tried to revert my dokuwiki to Greebo because of the frustration of using ckgedit under Hogfather. I installed the stable version of ckgedit (rather than the special version above), but when the ckgedit file browser opened, no files or pages were shown. I get this error message when I try to search - "The server didn't reply with a proper XML data. Please check your configuration."

**Comment by turnermm** [comment]
Not all here is entirely clear.  So let's take it step by step.
>  we are not able to use the search function in the browser. When we use the search function, and the > file we want appears, clicking on it does nothing.

1. When you speak of the browser, you are talking about when the media manager is open?  If so, that is a problem we have been working on a  closely related problem.  See https://github.com/turnermm/ckgedit/issues/543.  Download the mediamgr.zip update by @PankajRasgania and replace `ckgedit/scripts/mediamgr.js` .  See if that helps.

2. As for the sticky dialog window, this is a problem have not been able to solve. See https://github.com/turnermm/ckgedit/issues/559

**Comment by kjguenther** [comment]
Thanks for your quick response. Yes, I am talking about the search feature in the media manager (when you want to link to internal media in ckgedit). Sorry, but the new mediamgr.js update did not make a difference. Still the same behaviour. I tried with Chrome, Edge and Firefox. Chrome and Edge do nothing when you click on an item that appears when you enter search criteriaFirefox actually inserted a link of sorts but it is not correct. It puts "/lib/exe/fetch.php?media=:filename" into the "link to media file" box.  The filename goes away when you save the wiki page and you are just left with /lib/exe/fetch.php. 
I set `defer_js` to false, and that also did not solve any problems.

**Comment by g-user** [comment]
I cannot reproduce the problem with the new mediamgr.s and hogfather. 

But it sounds a little bit as my experience, when I´m played with media-uploads, but my replacement was always "/lib/exe/fetch.php?media=:grafik.png".
I was fooled by the caching mechanisms of dokuwiki and/or Firefox! 

So please try the following steps after you replaced "mediamgr.js" and disabled defer_js (these helped me with a similar problem):

1. clear the dokuwiki cache (either press save in the "configuration settings" or delete the contents of /dokuwiki/data/cache)
2. clear the firefox cache by deleting "cookies and site data" AND "cached web content"
3. open a new browser window and login in your wiki again

especially 2) and 3) was important to fix problems...

**Comment by turnermm** [comment]
Are you using the latest ckgedit, stable-master_20-Jul_06-13_34?  Attached is the latest mediamgr.js from stable-master_20-Jul_06-13_34.

**Comment by PankajRasgania** [comment]
Check this version of `scripts/mediamgr.js`
[mediamgr.zip](https://github.com/turnermm/ckgedit/files/4885055/mediamgr.zip)
Hopefully this shall solve the problem.

The url that we changed to work for search worked only for image as the parameters `onselect=ckg_edit_mediaman_insert&ckg_media=img` were there. I have made the changes for links.

**Comment by PankajRasgania** [comment]
@turnermm I removed the condition check `jQuery(document).ready` as it was to be executed after `windows.onload ` had happened. I think after `window.onload` there is no need to check for  `jQuery(document).ready` . Correct me if I am wrong.

**Comment by turnermm** [comment]
@kjguenther 

@PankajRasgania and I had been working on mediamgr but unfortunately I hadn't gotten around to including the fixes in hogfather_rc3.  That's done now, and you should be OK.

**Comment by turnermm** [comment]
@PankajRasgania  I think you are right.  It's basically superfluous becuase by the time windows.onload is called, jQuery seems to have everything it needs. See: https://stackoverflow.com/questions/3698200/window-onload-vs-document-ready.

**Comment by kjguenther** [comment]
@turnermm I tried the new  stable-master_20-Jul_06-13_34 and the media manager selector box did not work with Hogfather either. Then I installed the https://github.com/turnermm/ckgedit/archive/hogfather_rc3.zip and I was back to the previous behavior. I replaced the mediamgr.js file with the latest version provided by @PankajRasgania and the problems still have not been resolved.  Nothing has changed. Firefox continues to insert "/lib/exe/fetch.php?media=:filename" if you select a internal media file after entering search criteria. Edge and Chrome continue to enter nothing into the "link to media file" box if the selection is made after a search.  I have repeatedly deleted my cookies and cache in the browsers.

**Comment by PankajRasgania** [comment]
@kjguenther When you click on search button in file browser, what url do you see in the url bar of the popup?

**Comment by PankajRasgania** [comment]
Also try to check using browser develop tools (Ctrl+Shift+J in chrome based browsers), that the mediamgr.js loaded in your browser has same code as provided in the following comment.

> Check this version of `scripts/mediamgr.js`
> [mediamgr.zip](https://github.com/turnermm/ckgedit/files/4885055/mediamgr.zip)
> Hopefully this shall solve the problem.
> 
> The url that we changed to work for search worked only for inserting image as the parameters `onselect=ckg_edit_mediaman_insert&ckg_media=img` were there. I have made the changes for links.

Open developer tools, go to sources, on the left sidebar browse the tree to find mediamgr.js (under (yoursite) -> lib->plugins -> ckgedit/scripts)

**Comment by turnermm** [comment]
@PankajRasgania I have been looking over your new changes.  By "links" do you mean non -image files, like zip and tgz?  For these, using the link dialog, they seem to work without the changes you've made to the latest mediamgr. Unless I'm missing something.

Probably a minor point:  this new mediamgr.js removes the `value =""` check:
```
                 var valu = jQuery("#dw__mediasearch  input[type='text").val();
                 if(valu == ""){
                     var url = jQuery("form#dw__mediasearch").attr('action'); 
                      jQuery("form#dw__mediasearch").attr('action', url+_action); 
                 };
```
It checks that this code applies only to files which have been accessed through the search box.  I'm not sure it matters, but it seemed the safe ting to do.

**Comment by turnermm** [comment]
@PankajRasgania 
>  For these, using the link dialog, they seem to work without the changes 
But on second thought, the changes seem to be the logical thing to do.

**Comment by turnermm** [comment]
@PankajRasgania 
>they seem to work without the changes you've made to the latest mediamgr

Or are there cases where they don't?  It does, however, seem to be the logical ting to do.

**Comment by PankajRasgania** [comment]
No by "links" I mean using the insert internal media link option in CKGEdit. 
There are two cases where dw filebrowser popup is opened. 

One when inserting images (using image button in options on top of CKGEditor). In this case the _action variable should be 
```
?ns=&edid=wiki__text&onselect=ckg_edit_mediaman_insert&ckg_media=img&CKEditor=wiki__text&CKEditorFuncNum=1&langCode=en'
```

Another case is when inserting links using the link option  on top of CKGEditor. In that if we choose internal media, filebrowser opens up. In this case the _action variable should be 
```
?ns=&edid=wiki__text&onselect=ckg_edit_mediaman_insertlink&ckg_media=link&CKEditor=wiki__text&CKEditorFuncNum=1&langCode=en'
```

The `onselect` and `ckg_media` has to be different in both the cases. 

In #543 discussion we fixed the issue by using the same _action value for all cases. But it will not work for including links as `onselect` has to be different.

In the mediamgr.js that I have uploaded on this thread changed the  _action value as per the case.

**Comment by PankajRasgania** [comment]
> Probably a minor point: this new mediamgr.js removes the `value =""` check and the reference to the mediasearch form

This is strange, I never came across this` value=""` condition check in `mediamgr.js`. Was this in stable-master branch or in hogfather-rc3? Anyways adding GET parameter to a url will not break any intended behavior as they will be ignored on server side if they are not used. So I think no condition check is required.

Let's see what @kjguenther finds in debugging. I think it's a cache issue on the server side if not on the client side. The issue did exist earlier and it was the same as in #543 and I was able to reproduce it on my side. It was resolved on dokuwiki instance after I made the above mentioned changes. I checked it on a chromium based browser (Brave) and Firefox.

**Comment by kjguenther** [comment]
> @kjguenther After you click on search button in file browser, what url do you see in the url bar of the popup?
@PankajRasgania 
Before I click on search button, I see - https://senduwiki.org/lib/exe/mediamanager.php?ns=&edid=wiki__text&onselect=ckg_edit_mediaman_insertlink&ckg_media=link&CKEditor=wiki__text&CKEditorFuncNum=1&langCode=en
After I click on search button, I see https://senduwiki.org/lib/exe/mediamanager.php

**Comment by kjguenther** [comment]
> Also try to check using browser developer tools (Ctrl+Shift+J in chrome based browsers), that the mediamgr.js loaded in your browser has same code as provided in the following comment.
> 
> > Check this version of `scripts/mediamgr.js`
> > [mediamgr.zip](https://github.com/turnermm/ckgedit/files/4885055/mediamgr.zip)
> > Hopefully this shall solve the problem.
> > The url that we changed to work for search worked only for inserting image as the parameters `onselect=ckg_edit_mediaman_insert&ckg_media=img` were there. I have made the changes for links.
> 
> Open developer tools, go to sources tab, on the left sidebar browse the tree to find mediamgr.js (under (yoursite) -> lib->plugins -> ckgedit/scripts)

@PankajRasgania  Yes, that version of mediamgr.js is loaded in the browser.

**Comment by PankajRasgania** [comment]
@kjguenther  Fortunately, the link that you provided enabled me to open dw file browser of your website. The issue is that the script inside the `mediamgr.js` is not executed despite getting loaded. This happened because the code is inside `window.load` triggered function. In Hogfather, the scripts loading is being delayed, and therefore by the time `mediamgr.js` gets executed the `window.load` has already been triggered and any handler that we try to attach to `window.load` will be fired only for future events which will never happen. The fix is to use `jQuery(document).ready`  instead of `window.load` function as it fires even long after the DOM has loaded and JQuery handles all the DOM state checks for us.

[mediamgr.zip](https://github.com/turnermm/ckgedit/files/4895278/mediamgr.zip)
This file contains the above mentioned changes, try it.

@turnermm See [https://api.jquery.com/ready/](url) This should be used instead of `windows.load` in all of the scripts.

**Comment by kjguenther** [comment]
@PankajRasgania Thank you! That worked. Now the search function works as it is supposed to in the media manager. 
I hope that you can also figure out why the dialog box won't close when you click on "OK" but that is another problem, I understand.

**Comment by kjguenther** [comment]
@PankajRasgania and @turnermm. I have made an additional discovery. If I enter the search criteria and click on "Search" before the little circle in the top left corner has stopped rotating, clicking on the search results produces the former results (nothing is entered into the search dialog box). If I wait for the circle to stop rotating and the icon appears, and then enter the search criteria, everything works as it is supposed to. This is true in both Chrome and Edge. In Firefox, the icon appears much more quickly (no rotating circle), but the same problem occurs if you don't wait for all the messages (transferring data, waiting) in the bottom left corner to stop flashing.

**Comment by PankajRasgania** [comment]
@kjguenther This is because the script is executed once the page has loaded. But if the page has too many contents, it will take time to load. You will not get the desired behaviour unless the page is fully loaded. My suggestion is to use search option only after the page has loaded.

**Comment by PankajRasgania** [comment]
@kjguenther  There is a simple hack tough if the root page contains too many images. Search for any random string first ignoring the loading page. The search result page will be smaller than root page and hence will load quickly. Now search for the file you were searching.
