### ISSUE TITLE
enable ckedit-uploadimage via dokuwiki media-upload

### ISSUE THREAD

**Issue by g-user** [turnermm/ckgedit#567]
Hello Myron,

as I wrote in my desastrous pull-request, I want to have activated the internal ckeditor4 uploadimage-plugin via the dokuwiki media_upload process.

This has the advantage, that the via ctrl-v inserted base64-image-data is automatically grabbed and uploaded to the server, so that dokuwiki only has to deal with the image-link (and not the whole base64-data). It´s the same mechanism as the imagePaste in the dw-editor. So this overrides the restriction of 2500000 bytes of image-size, that you implemented to save the browser from a crash.

Thats why I changed /action/edit.php and added a "wrapper" script called imageupload.php, that sits in the base plugin directory (like "version" or "helper.php")

What I did:
1. I activated the "filebrowserImageUploadUrl"  for ckeditor uploadimage-plugin in edit.php (see below)  
2. To use the security-token I relay on the concept of dokuwiki. You ask for getSecurityToken();  - that function is inherited from dokuwiki, you don´t need anything extra, it´s available in the context of edit.php.
3. I used a "wrapper"-script to translate the output of the dokuwiki-media_upload and the input, that ckeditor demands. This wrapper-script is called via filebrowserImageUploadUrl.

Here are the changes:
(part of the diff, so you can find the lines in edit.php). In fact I added only a special "filebrowserImageUploadUrl" to $fbOptions.

> //setup options
> +$sectoken=getSecurityToken();
> +$fbOptions = "filebrowserImageUploadUrl: \"$doku_url/lib/plugins/ckgedit/imageupload.php?sectok=$sectoken&ns=$ns\",";
> +
>  if ($fb == 'dokuwiki') {
> \-    $fbOptions = "filebrowserImageBrowseUrl: \"$doku_url/lib/exe/mediamanager.php?ns=$ns&edid=wiki__text&onselect=ckg_edit_mediaman_insert&ckg_media=img\",
> \+    $fbOptions = $fbOptions."filebrowserImageBrowseUrl: \"$doku_url/lib/exe/mediamanager.php?ns=$ns&edid=wiki__text&onselect=ckg_edit_mediaman_insert&ckg_media=img\",
>      filebrowserBrowseUrl: \"$doku_url/lib/exe/mediamanager.php?ns=$ns&edid=wiki__text&onselect=ckg_edit_mediaman_insertlink&ckg_media=link\"";
>  } else {
> \-    $fbOptions = "filebrowserImageBrowseUrl :  \"$doku_url/lib/plugins/ckgedit/fckeditor/editor/filemanager/browser/default/browser.html?Type=Image&Connector=$doku_url/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php\",
> \+    $fbOptions = $fbOptions."filebrowserImageBrowseUrl :  \"$doku_url/lib/plugins/ckgedit/fckeditor/editor/filemanager/browser/default/browser.html?Type=Image&Connector=$doku_url/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php\",
>      filebrowserBrowseUrl: \"$doku_url/lib/plugins/ckgedit/fckeditor/editor/filemanager/browser/default/browser.html?Type=File&Connector=$doku_url/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php\"";
>  }
>  if($this->getConf('style_sheet')) {`

The wrapper-Script:

> \<?php
> \/**
>  \* DokuWiki AJAX call handler for ckgedit uploadimage plugin
>  \*
>  \* @license    GPL 2 (http://www.gnu.org/licenses/gpl.html)
>  \* @author     Andreas Gohr <andi@splitbrain.org>
>  \* @author     community
>  \*/
> 
> if(!defined('DOKU_INC')) define('DOKU_INC', dirname(__FILE__) . '/../../../');
> require_once(DOKU_INC . 'inc/init.php');
> 
> //close session
> session_write_close();
> 
> // default header, ajax call may overwrite it later
> header('Content-Type: text/html; charset=utf-8');
> 
> 
> global $INPUT;
> $INPUT->post->set('mediaid',"");
> $INPUT->post->set('ow',false);
> 
> 
> $_FILES['qqfile']=$_FILES['upload'];  // really needed!!!
> $filename=$_FILES['upload']['name'] ;
> 
> ob_start();
> new \dokuwiki\Ajax("mediaupload");
> $call_ret = json_decode(ob_get_clean());
> 
> $ret = array("uploaded"=>0, "fileName" => $filename,"url" => "lib/exe/fetch.php?media=".$NS.":".$filename);
> 
> if ($call_ret->success)
> {
>  $ret["uploaded"]=1;
> }else
> {
>  $ret["error"]["message"] = "Error uploading the file \"".$filename."\" to namespace \"".$NS."\"";
> }
> 
> echo json_encode($ret);

**Comment by g-user** [comment]
Here are the changed files (build from hogfather_rc3).

[imageupload.zip](https://github.com/turnermm/ckgedit/files/4886683/imageupload.zip)

You can see the difference, if you paste an image and then switch to the source-view.

Without the changes: you can see a lot of base64-data
With: only a link to the uploaded file is there

and the second advance is, if you insert an image via ctrl-v, you can immediately change the image properties (width/height/link type ...)

**Comment by turnermm** [comment]
I downloaded the zip and have replaced the original edit with your.  Where does the imageupload script go?

**Comment by g-user** [comment]
it must go to the base ckgedit-plugin (were also helper.php, locktimer.js, renderer.php, plugin.info.txt, ...) exists

**Comment by turnermm** [comment]
I have been working on another issue for the past few days, but will get back to this as soon as possible.  Thanks.

**Comment by g-user** [comment]
No, probem, take your time. I know that the dokuwiki-hogfather release produced a lot of of problems also for the ckgedit-plugin.

When you are working at this, maybe you have better ideas to implement the ckgedit-uploadimage-plugin. I used a wrapper plugin, that calls the inherited media_upload procedure  from the dokuwiki environment. The reason was only security concerns, I didn´t want open security holes with a new file-upload implementation. But this seems to produce a lot of overhead, sometimes I saw a javascript-vm size of 700Mb in my browser. And also the restriction of the amount of data, that can be pasted into the editor (2500000 bytes ) comes up sometimes (but can be ignored most of the time, I commented it out)

**Comment by g-user** [comment]
Hi,

is there a reason for closing this? Do you need some more information? It is a  standard  ckgeditor-uploadimage-plugin, it is included the version that you use for the dokuwiki-ckgedit, but not properly activated here.

**Comment by turnermm** [comment]
I initially tried adding the code myself, but was unsuccessful.  If your believe this is an important update, you are going to have to fork a copy and make a pull request. It's too complex to handle in the cut-and-paste fashion that you would prefer.  Here's the proess:

You log into your account.  Navigate to turnermm/ckgedit and click the fork button.  That will load turnermm/ckgedit into your account.  Then you clone your copy to the desktop, create a new branch, where you make your changes, then push this branch back to your account.  Then on your account's copy of ckgedit, you choose new your branch from the drop down menu of branches and then make the pull request. It will be posted to the turnermm/ckgedit.
