### ISSUE TITLE
Selection from the Media Manager is not taken over

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#570]
Hello,

In Firefox and Chrome we have recently encountered the following problem (MS-Edge works):

On the wiki page we want to embed an image. To do this, we click on the icon of the media manager (we use the dokuwiki media manager). The first thing I notice now is that the media manager does not open as a separate browser tab. Then we select an image that is already available on the server and try to load it with the default settings for links. But then nothing happens, the link is not transferred to the CKG editor. It is only possible to press the back button and nothing is taken over.

One more thing: In MS-Edge the media manager opens as separate browser tab, and everything works fine.

We use ckgedit in version 2020-07-14

With kind regards
Jürgen

**Comment by turnermm** [comment]
Clear your browser cache and the dokuwiki cache directory (data/cache).  Reinstall ckgedit.  You may have reinstalled before I had corrected an omission.

**Comment by Juergen-aus-Koeln** [comment]
Sorry, but nothing is different than before

**Comment by turnermm** [comment]
1. What version of ckgedit are you using
2. Which browser and on which desktop
3. On which server is your dokuwiki running
4. which version of dokuwiki are you using

**Comment by turnermm** [comment]
By the way, if you have upgraded to hogfather, there is a special version of ckgedit for hogfather.    
Check the plugin page at dokuwiki.org.

**Comment by Juergen-aus-Koeln** [comment]
Because of the problems in many fields with hogfather I'm still at Release 2018-04-22b "Greebo"

**Comment by turnermm** [comment]
Then what precipitated this problem? Did you update ckgedit? Install some new plugin?  You say you are using 2020-07-14 (that's the date but not the full version which you get in the version file).  Had you been using that without any problems or did the problems start when you updated to 2020-07-14?

 And you still haven't  answered my questions.

**Comment by Juergen-aus-Koeln** [comment]
Oh, sorry, your questions, I had overlooked:

1.) What version of ckgedit are you using
2020-07-18 / stable-master_20-Jul_18-09_07

2.) Which browser and on which desktop
Google Chrome / Version 84.0.4147.89 (Offizieller Build) (64-Bit)
Firefox 78.0.2 (64-Bit)
Microsoft Edge 44.19041.1.0 / EdgeHTML 18.19041 (this is the only browser where the CKG-editor works correctly)
We use Windows 10 pro / Version 2004 19041.239

3.) On which server is your dokuwiki running
The server specification is unknown for me, I have to ask our IT tomorrow
PHP version 7.1.19

4.) Which version of dokuwiki are you using
DokuWiki version: Release 2018-04-22b "Greebo"

Unfortunately, I cannot say when this problem occurred. I myself use the CKG editor rather rarely, because I work a lot with special syntax elements. For my colleagues, however, it is the standard editor. But they only work sporadically in Dokuwiki, so that the time from when the error occurred can hardly be determined.

As described before, I think the main problem is that the browser does not start a new instance of the Media Manager. Instead, it loads into the same tab as the ckg editor. And that causes problems when trying to jump back into the editor.

**Comment by turnermm** [comment]
> The first thing I notice now is that the media manager does not open as a separate browser tab.

It never did.  It opens in a new window. 

As for this issue, both  ckgedit's own media browser is available and also the  dokuwiki media manager.  Try both.  And since you can't pin point the time at which this problem first occurred, there's not much I can offer but offer suggestions.  I have not seen this problem myself.  

If you are not using the dokuwiki template but one of the others, see what happens if you switch to another. Then you could also try uninstalling your plugins and re-installing them one at a time to see whether there's a plugin conflict.

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much for your tips on this!!

It is the combination of the structured data plugin and the draw.io plugin. Only if both are activated, the bug occurs

With kind regards, Juergen

**Comment by turnermm** [comment]
> draw.io plugin.

I seem to recall a conflict with draw.io in an earlier issue of question on the forum.  Thanks for the feed-back,
