### ISSUE TITLE
Code blocks showing extra lines in editor

### ISSUE THREAD

**Issue by megaman5** [turnermm/ckgedit#572]
After creating text and placing it in a code block, then editing the page again, 4 extra line breaks are inside the code block.

As created in editor, also what shows when viewed
![view](https://user-images.githubusercontent.com/46542906/88960408-0fff2580-d269-11ea-9664-f4fc523dd917.png)

Shown in code
![dw_code](https://user-images.githubusercontent.com/46542906/88960386-0a094480-d269-11ea-8df4-2e7a3c6b836a.png)

Shown in editor
![editor](https://user-images.githubusercontent.com/46542906/88960415-11c8e900-d269-11ea-9c39-43a7794e3de5.png)

**Comment by megaman5** [comment]
I was able to replicate here too
https://installatron.com/dokuwiki/demo/backend

**Comment by turnermm** [comment]
This is needed  by code blocks in the editor to improved their accessibility to editing and disappear when the file is saved.
