### ISSUE TITLE
CKEditor not functioning, throwing error codes

### ISSUE THREAD

**Issue by thepraetorian** [turnermm/ckgedit#574]
CKEditor was working on our site http://wiki.ftd.gg a few days ago, now it's giving a generic pop-up error "wiki.ftd.gg says 'error'" on loading. When you attempt to save you hit it twice and nothing actually writes to the page. I'm fairly new to both dokuwiki and coding but it was working before and I hadn't changed anything that would directly affect it, to my knowledge.

**Comment by thepraetorian** [comment]
Further information: other admins say they don't have the same issue, and mine is across all browsers.

**Comment by turnermm** [comment]
Seems to be a Windows system error.
http://www.cleanerrors.com/fix/error-574/

**Comment by turnermm** [comment]
If it's a syste merror, as 500 errors  are, changing browsers won't make any difference.

**Comment by thepraetorian** [comment]
The 574 is the ticket number github puts on the post, not the error received. The error received is literally just "error" with no further descriptors. When I check console on chrome it shows the following:

The deferred DOM Node could not be resolved into a valid node.
js.php?t=argon&tseed=ddb1af331f6769fe0d818e5d689fa498:1 Uncaught TypeError: jQuery(...).perfectScrollbar is not a function
    at js.php?t=argon&tseed=ddb1af331f6769fe0d818e5d689fa498:1
(anonymous) @ js.php?t=argon&tseed=ddb1af331f6769fe0d818e5d689fa498:1
DevTools failed to load SourceMap: Could not parse content for https://wiki.ftd.gg/lib/tpl/argon/assets/css/agd.css.map: Unexpected token < in JSON at position 0
start?do=edit:1 Error while trying to use the following icon from the Manifest: https://wiki.ftd.gg/_media/wiki/dokuwiki.svg (Download error or resource isn't a valid image)
jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2 POST https://undefinedlib/exe/ajax.php net::ERR_NAME_NOT_RESOLVED
send @ jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2
ajax @ jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2
S.<computed> @ jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2
l @ config.js?t=J39A:1
CKEDITOR.editorConfig @ config.js?t=J39A:1
k @ ckeditor.js:273
(anonymous) @ ckeditor.js:273
callback @ ckeditor.js:261
e @ ckeditor.js:259
y @ ckeditor.js:259
v @ ckeditor.js:259
(anonymous) @ ckeditor.js:260
setTimeout (async)
CKEDITOR.env.ie.e.$.onload @ ckeditor.js:260
load (async)
x @ ckeditor.js:260
load @ ckeditor.js:261
a @ ckeditor.js:261
(anonymous) @ ckeditor.js:261
k @ ckeditor.js:273
h @ ckeditor.js:275
(anonymous) @ ckeditor.js:272
(anonymous) @ ckeditor.js:30
setTimeout (async)
setTimeout @ ckeditor.js:30
a @ ckeditor.js:271
a @ ckeditor.js:359
CKEDITOR.replace @ ckeditor.js:363
ckgedit_onload @ start?do=edit:179
load (async)
(anonymous) @ start?do=edit:211
jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2 POST https://undefinedlib/plugins/ckgedit/ckeditor/dwsmileys.php net::ERR_NAME_NOT_RESOLVED
send @ jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2
ajax @ jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2
S.<computed> @ jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2
i @ config.js?t=J39A:1
CKEDITOR.editorConfig @ config.js?t=J39A:1
k @ ckeditor.js:273
(anonymous) @ ckeditor.js:273
callback @ ckeditor.js:261
e @ ckeditor.js:259
y @ ckeditor.js:259
v @ ckeditor.js:259
(anonymous) @ ckeditor.js:260
setTimeout (async)
CKEDITOR.env.ie.e.$.onload @ ckeditor.js:260
load (async)
x @ ckeditor.js:260
load @ ckeditor.js:261
a @ ckeditor.js:261
(anonymous) @ ckeditor.js:261
k @ ckeditor.js:273
h @ ckeditor.js:275
(anonymous) @ ckeditor.js:272
(anonymous) @ ckeditor.js:30
setTimeout (async)
setTimeout @ ckeditor.js:30
a @ ckeditor.js:271
a @ ckeditor.js:359
CKEDITOR.replace @ ckeditor.js:363
ckgedit_onload @ start?do=edit:179
load (async)
(anonymous) @ start?do=edit:211
jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2 POST https://undefinedlib/plugins/ckgedit/ckeditor/schemes.php net::ERR_NAME_NOT_RESOLVED
send @ jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2
ajax @ jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2
S.<computed> @ jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2
c @ config.js?t=J39A:1
CKEDITOR.editorConfig @ config.js?t=J39A:1
k @ ckeditor.js:273
(anonymous) @ ckeditor.js:273
callback @ ckeditor.js:261
e @ ckeditor.js:259
y @ ckeditor.js:259
v @ ckeditor.js:259
(anonymous) @ ckeditor.js:260
setTimeout (async)
CKEDITOR.env.ie.e.$.onload @ ckeditor.js:260
load (async)
x @ ckeditor.js:260
load @ ckeditor.js:261
a @ ckeditor.js:261
(anonymous) @ ckeditor.js:261
k @ ckeditor.js:273
h @ ckeditor.js:275
(anonymous) @ ckeditor.js:272
(anonymous) @ ckeditor.js:30
setTimeout (async)
setTimeout @ ckeditor.js:30
a @ ckeditor.js:271
a @ ckeditor.js:359
CKEDITOR.replace @ ckeditor.js:363
ckgedit_onload @ start?do=edit:179
load (async)
(anonymous) @ start?do=edit:211

**Comment by turnermm** [comment]
I have no idea what is going on here.  It looks as though ckeditor has become the casualty of something prior to it.    Errors in Javascript often percolate down instead of exiting at the point of origin. As you can see from this output, there is a set of prior errors before ckgedit is involved.  Since the CKEditor is written wholly in javascript errors would eventually begin to show up there.  This seems to be borne out by the fact that changing themes solves the problem.   My only thought would be to make sure you have the latest version of your theme and the latest ckgedit.  

What theme by the way are you using?

**Comment by thepraetorian** [comment]
I was using Argon and it was also recently updated which I also updated and
that's when the problem seems to have started...

**Comment by turnermm** [comment]
It will not be the first time that a template caused problems since hogfather.

**Comment by cathoderaydude** [comment]
Just FYI, if it's of any use, I found that ckgedit is setting paths to many things beginning with n.dokuBase which is apparently not set by Argon theme, but is set by default doku theme. Enabling canonical URLs (which causes ckgedit to use n.DOKU_BASE instead) fixed it.

**Comment by turnermm** [comment]
It's been a few years since looking at canonicals in ckgedit, but if it's working for you without any side effects I'm glad to hear it.
