### ISSUE TITLE
Pasting copied images just ends up being text

### ISSUE THREAD

**Issue by vic-t** [turnermm/ckgedit#578]
My apologies if this is not the right forum to post this. 

I'm using Firefox 80 on Windows 10 with DocuWiki Hogfather, ckgedit enabled. When pasting an image from clipboard in the ckgedit editor and then saving the page, half of the times the image will not show but just its base64 representation, i.e. a very long string beginning with {{data:image/png;base64,iVBORw0KGg........ I have tested this only with screenshots that are up to 100KB large if saved on disk. 

I couldn't make out a clear rule when this happens. What's noticeable, though, is that it breaks the layout for everything that follows the image as everything below is turned into regular DocuWiki syntax with all line breaks stripped away, leaving one big mess that must be corrected manually. 

It's really not such a problem when something is pasted in the end of a section or a page, this can easily be corrected. But when it breaks large parts of a page, it's a huge nuisance. Not sure what to do about it.

**Comment by turnermm** [comment]
I am unable to duplicate your experience, doing some quick testing in Windows 10 with both firefox and chrome., both greebo and hogfather.  In FF you can copy and paste directly from the desktop and in chrome you have to copy from an image editing program like photoshop.  Chrome requires the additional image paste support, firefox does not.  Perhaps you should think of clearing a space for the image before pasting.  It's also possible that something on your page is causing a regex conflict.

**Comment by turnermm** [comment]
I thought  was waiting for you to fork a copy of ckgedit and add your changes.  I raised this point in one of our exchanges. That's the only practical way to proceed.

**Comment by vic-t** [comment]
> I thought was waiting for you to fork a copy of ckgedit and add your changes. I raised this point in one of our exchanges. That's the only practical way to proceed.

I assume you meant to leave this comment somewhere else, you and I never had such an exchange.

**Comment by turnermm** [comment]
Sorry.  It was meant for another use  in another issue.

**Comment by vic-t** [comment]
Hi Myron, just wanted to mention that I keep having the same issue, even on new computers, and not limited to Firefox. 

DokuWiki and CKGEdit are current, I believe there have been updates since September but the problem remained. 

Unfortunately, I still can't give you an exact reason why this seems to happen.
