### ISSUE TITLE
impossible to switch to ckgedit

### ISSUE THREAD

**Issue by vinsse2001** [turnermm/ckgedit#582]
Hi Myron,
I have 3 installs of dokuwiki (version : 2020-07-29 "Hogfather"), each with ckgedit (the more recent update), but I don't know why, one of my installs can't switch to ckgedit when I edit a page and click on "CKG editor" button (edit mode switch to off, and if I try to modify again, I only have dokuwiki editor).
I re-install dokuwiki, no change. I tried to uninstall ckgedit and re-install it, no change.
What can I do to solve this problem ?
Thanks for help
Vincent

**Comment by turnermm** [comment]
1. Clear out all the directories in data/cache.
2. Refresh your browser cache.

**Comment by vinsse2001** [comment]
yep, it is ok now, thanks !
