### ISSUE TITLE
Conflict with drawio and svgedit plugins

### ISSUE THREAD

**Issue by EthanCod** [turnermm/ckgedit#583]
Hello

It seems it has some conflict with other editor plugins.
when I install the [drawio](https://www.dokuwiki.org/plugin:drawio) or [svgedit](http://www.dokuwiki.org/plugin:svgedit) plugins ,the ckgedit filemanager doesn't work properly!

There isn't any recource...

![ckg-filem](https://user-images.githubusercontent.com/71581697/95322257-13d2a800-08a9-11eb-9921-c34af811df4e.png)

**Comment by turnermm** [comment]
Nothing I can do about that.  Not all plugins are compatible.  I would open issues with the drawio and svgedit plugins.
