### ISSUE TITLE
Why bottom text area is editable?

### ISSUE THREAD

**Issue by srudakov** [turnermm/ckgedit#584]
When user edits page he can see raw page code in bottom text area. And he can edit code there, but after pressing save button all that changes disappear.

**Comment by turnermm** [comment]
Don't know what you are talking about.  There is no bottom text area.

**Comment by srudakov** [comment]
![top_and_bottom](https://user-images.githubusercontent.com/23479423/95490856-81fa9600-09a1-11eb-854c-4ad13e6ecf7b.png)

**Comment by turnermm** [comment]
Very strange.  That should be the reverse.

**Comment by turnermm** [comment]
Strange.  I've never seen that before.

**Comment by turnermm** [comment]
There is no split screen.  Unless you have found an output method that I am not aware of.
