### ISSUE TITLE
New lines can be lost

### ISSUE THREAD

**Issue by srudakov** [turnermm/ckgedit#586]
Sometimes if page code is like
```
some text
another text
```
then in edit text area user both texts are displayed in same line.

For example for [folded](https://www.dokuwiki.org/plugin:folded) plugin its correct to write
```
++title|
<del>text</del>
++
```
and is not correct to write
```
++title|<del>text</del>++
```
but first page code example is displayed like second while editing and if user will change text and save it, that block becomes incorrect.

**Comment by turnermm** [comment]
Hold the shift key down and then press Return.  This will give you a Dokuwiki newline.

**Comment by srudakov** [comment]
I indestand that user can create block with DokuWiki newlines. But my question is how can he edit such block after creation and saving without restoring new lines manually each time.

**Comment by turnermm** [comment]
See #585
