### ISSUE TITLE
New Fatal Error

### ISSUE THREAD

**Issue by cdukex23** [turnermm/ckgedit#587]
This started popping up recently (I can disable ckgedit and am still able to function, so I don't think it's affecting anything else):

Fatal error: Uncaught TypeError: Argument 1 passed to action_plugin_ckgedit_meta::preprocess() must be an instance of Doku_Event, instance of dokuwiki\Extension\Event given, called in C:\xampp\htdocs\DokuWiki\inc\events.php on line 229 and defined in C:\xampp\htdocs\DokuWiki\lib\plugins\ckgedit\action\meta.php:433 Stack trace: #0 C:\xampp\htdocs\DokuWiki\inc\events.php(229): action_plugin_ckgedit_meta->preprocess(Object(dokuwiki\Extension\Event), NULL) #1 C:\xampp\htdocs\DokuWiki\inc\Extension\Event.php(93): Doku_Event_Handler->process_event(Object(dokuwiki\Extension\Event), 'AFTER') #2 C:\xampp\htdocs\DokuWiki\inc\Extension\Event.php(132): dokuwiki\Extension\Event->advise_after() #3 C:\xampp\htdocs\DokuWiki\inc\Extension\Event.php(195): dokuwiki\Extension\Event->trigger(NULL, false) #4 C:\xampp\htdocs\DokuWiki\lib\plugins\ckgedit\action\edit.php(720): dokuwiki\Extension\Event::createAndTrigger('HTML_EDITFORM_I...', Array) #5 C:\xampp\htdocs\DokuWiki\lib\plugins\ckgedit\action\edit.php(178): action_plugin_ckgedit_edit->_p in C:\xampp\htdocs\DokuWiki\lib\plugins\ckgedit\action\meta.php on line 433

This happened after I updated CKGEdit recently. Prior to this, everything was working fine. I'm going to attempt to roll-back the version of ckgedit in the meantime.

**Comment by turnermm** [comment]
When was recently?  Line 433 of action/meta.php should look like this:
    ` function preprocess(Doku_Event $event, $param)`
If it looks  like this
` function preprocess(&$event, $param)`
then your version is not current.

**Comment by cdukex23** [comment]
I just updated last week. Previous version was from august I believe.

I also ran another update this morning.

I’ll check what you said in a moment.

Regards,
Chase Henson
Alignment Quality Consulting
Phone: 505-317-6894
Email: chase@alignment-qc.net

On Oct 12, 2020, at 09:37, Myron Turner <notifications@github.com> wrote:

﻿

When was recently? Line 433 of action/meta.php should look like this:
function preprocess(Doku_Event $event, $param)
If it looks like this
function preprocess(&$event, $param)
then your version is not current.

**Comment by cdukex23** [comment]
Looks like I'm running the current version: 


![Screenshot 2020-10-14 122932](https://user-images.githubusercontent.com/72751541/96030219-f9ed1400-0e18-11eb-9c3f-7edb2b27c3e1.png)

**Comment by turnermm** [comment]
This will take you back to July 22: https://github.com/turnermm/ckgedit/archive/stable-master.zip, before ckgedit was merged with hogfather-merged.  

I would try first to clean out data/cache of all directories and then refresh your browser cache.

But I am somewhat confused, because as far as I can determine `inc\Extension\Event.php` does not come into DokuWiki until hogfather.

**Comment by turnermm** [comment]
Check to see if you have `$this->_print();`   at line 178 of edit.php,  

I am also  a bit confused by your saying that you are on Greebo, since as far as I can determine `DokuWiki\inc\Extension\Event.php`  (see te error message) doesn't appear in DokuWiki until Hogfather.
