### ISSUE TITLE
Regression dw_priority/dw_users with DokuWiki version Hogfather

### ISSUE THREAD

**Issue by SamOxyPlot** [turnermm/ckgedit#588]
Hi Myron

I've seen there is an issue with the **dw_priority/dw_users**  settings with DokuWiki version **Hogfather**:
[https://github.com/turnermm/ckgedit/commit/91857b8e5ae7ca8c215b1f7b00d5049facc23b97](link)

The point is that the **admins** only want to use the **standard DW editor** while the **'regular' users** want to use the **WYSIWYG CKGeditor**.

There is no detailed description of the bug in the Hogfather version.

I hope that this nice feature can be introduced again.

**Thanks in advance.**

Kind regards
Sam

**Comment by turnermm** [comment]
There are thee other ways to control access to the native dokuwiki editor.  See https://www.dokuwiki.org/plugin:ckgedit:configuration#dw_edit_display
