### ISSUE TITLE
Problem with uploading (PDF) files with ckgedit

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [turnermm/ckgedit#589]
Hi,

we are facing a problem with uploading PDF files with ckgedit. 

We are using the browser Edge Chromium (Version 86.0.622.48). Following error occurs:

![grafik](https://user-images.githubusercontent.com/1389907/96684967-c06a5a80-137c-11eb-894e-e4066acb2441.png)

I don't see any PHP errors in our log file.

Have you any tips where I can look for any errors to help investigate this problem more deeply.

If I can provide any more information just let me know.

**Comment by Speedy-Gonzalez** [comment]
Deleting Edge cookies and temporary data helps, but only for an initial upload. All further uploads will cause the above mentioned error again.

**Comment by Speedy-Gonzalez** [comment]
Edge is working in IE-Mode because we need the functionality to open samba links directly without copying it into the Windows Explorer.

**Comment by turnermm** [comment]
This is usually a dokuwiki error message.
Suggestions:
1. Are you using link dialog (not the image dialog)?
2. See what happens if you switch over to the ckgedit filebrowsers.

**Comment by Speedy-Gonzalez** [comment]
> 
> 
> This is usually a dokuwiki error message.
> Suggestions:
> 
>     1. Are you using link dialog (not the image dialog)?
Yes it is the link dialog. The user wants to insert an internal media.

>     2. See what happens if you switch over to the ckgedit filebrowsers.
I will try that.

**Comment by Speedy-Gonzalez** [comment]
> > 2. See what happens if you switch over to the ckgedit filebrowsers.
> 
> I will try that.
It seems to work. I will let the affected users test it tomorrow and will reply here soon

**Comment by turnermm** [comment]
I'm curious as to whether you had the same problem using dw's media manager, because, as I said, that message is from dokuwiki.  The ckgedit file browsers are independent of the media manager, except for the types of file that are allowed to be uploaded.

**Comment by Speedy-Gonzalez** [comment]
>  PC. I will let the affected users test it tomorrow and will reply here soon

It also works for the affected users. Thanks for your hint about the ckgedit filebrowser!

> I'm curious as to whether you had the same problem using dw's media manager, because, as I said, that message is from dokuwiki. The ckgedit file browsers are independent of the media manager, except for the types of file that are allowed to be uploaded.

I'll try that next week.

**Comment by Speedy-Gonzalez** [comment]
> I'm curious as to whether you had the same problem using dw's media manager, because, as I said, that message is from dokuwiki. The ckgedit file browsers are independent of the media manager, except for the types of file that are allowed to be uploaded.

The problem also exists in dw's media manager. After uploading the first file I always get the error.

![grafik](https://user-images.githubusercontent.com/1389907/97309551-75f84a80-1862-11eb-9dd0-790eb1ce6da7.png)

**Comment by turnermm** [comment]
The problem, then, is not with ckgedit.  Make sure both of the following settings are set:
upload_max_filesize
post_max_size
See https://www.tecmint.com/increase-file-upload-size-in-php/

**Comment by Speedy-Gonzalez** [comment]
> 
> 
> The problem, then, is not with ckgedit. Make sure both of the following settings are set:
> upload_max_filesize
> post_max_size
> See https://www.tecmint.com/increase-file-upload-size-in-php/

Thanks. I'll check that.

Yep, it's not a ckgedit error so I'll close this issue.
