### ISSUE TITLE
Unable to link to internal link : "server didn't reply with a proper XML data"

### ISSUE THREAD

**Issue by webafrancois** [turnermm/ckgedit#592]
I use a dogfather dokuwiki version with ckgedit up-to-date
When I try to make a link, the link manager say : 
```
The server didn't reply with a proper XML data. Please check your configuration.
```
I can make a link manually with :namespaces:mypage
But the windows doesn't show me the webpages.

I use dokuwiki in french.

![Sélection_421](https://user-images.githubusercontent.com/19719849/99406284-03710c80-28ee-11eb-8a43-54aa4a78809f.png)

Which XML is it ?
I didn't find any XML in the plugins ckgedit.

Thanks.

**Comment by turnermm** [comment]
This message appears when there isn't a correct path to the  directory where your image and/or documents are stored.  First make sure that you have the required links in ckgedit/fckeditor/userfiles: media, file and image, and that they point to your data/media directory.  See  https://www.dokuwiki.org/plugin:ckgedit#file_browser.
If this does not solve your problem, then if you are using a linux/unix based machine, in the Configuration Manager, select the [winstyle](https://www.dokuwiki.org/plugin:ckgedit:configuration#winstyle) option.  If you are in a windows machine, select the [nix_style](https://www.dokuwiki.org/plugin:ckgedit:configuration#nix_style) option.  Again make sure there are the correct links in userfiles.

If these solutions fail, switch over to the dokuwiki file and image managers. Set both `allow_ckg_filebrowser` and `default_ckg_filebrowser` to dokuwiki.

**Comment by webafrancois** [comment]
Yes I already manually made the links to the good way from `file, flash, image and media` and with '`ln -s`' to the `media/data` directory.
My dokuwiki is hosted on a web hosting on a Linux server. So I check the `winstyle` option, copy the `.htaccess.security` in `data/media/.htaccess` (like the doc says), empty the dokuwiki cache but I can't make a link and have the same error.
I delete the plugins and reinstall it (and made the links) and the same error is already here.

I don't know from where came this error.

I change the dokuwiki file and image manager and it works (But not with ckgedit :disappointed: )

**Comment by turnermm** [comment]
> change the dokuwiki file and image manager and it works (But not with ckgedit 😞 )

By this you mean that you can't get the ckgedit file and image manager, but that you still can use the ckgedit's editor?

**Comment by turnermm** [comment]
Did you check your browser's console to see if it reports any errors?

**Comment by webafrancois** [comment]
Yes I've got ckgedit and dokuwiki window in same time.
I Set both allow_ckg_filebrowser and default_ckg_filebrowser to dokuwiki.

![Sélection_422](https://user-images.githubusercontent.com/19719849/99454810-3b487600-2927-11eb-8798-afacf7a13e6d.png)

Il my browser console, in the ckeditor I see this : 
```
connector.php:1:668
Erreur d’analyse XML : mal formé
Emplacement : https://ladoc.cemea.org/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php?Command=GetFoldersAndFiles&Type=File&CurrentFolder=/&DWFCK_Browser=local&uuid=1605649914373
Numéro de ligne 1, Colonne 668 :

browser.html:1:668
Erreur d’analyse XML : mal formé
Emplacement : https://ladoc.cemea.org/lib/plugins/ckgedit/fckeditor/editor/filemanager/browser/default/browser.html?Type=File&Connector=https://ladoc.cemea.org/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php&CKEditor=wiki__text&CKEditorFuncNum=1&langCode=fr
Numéro de ligne 1, Colonne 668 :

```

I note that I use the rewrite rule in htaccess of dokuwiki to have nice url : 
section added : 

```
RewriteEngine on

RewriteRule ^_media/(.*)              lib/exe/fetch.php?media=$1  [QSA,L]
RewriteRule ^_detail/(.*)             lib/exe/detail.php?media=$1  [QSA,L]
RewriteRule ^_export/([^/]+)/(.*)     doku.php?do=export_$1&id=$2  [QSA,L]
RewriteRule ^$                        doku.php  [L]
RewriteCond %{REQUEST_FILENAME}       !-f
RewriteCond %{REQUEST_FILENAME}       !-d
RewriteRule (.*)                      doku.php?id=$1  [QSA,L]
RewriteRule ^index.php$               doku.php
```

**Comment by turnermm** [comment]
Is your code being compressed?  There is no column 688 in `connector.php`.

**Comment by webafrancois** [comment]
This problem seems to become with directories with "_" underscore.
It works in directories without.

I've got many directories with it.

I use the last version : 2021-01-30

![Selection_2021020101:23:38](https://user-images.githubusercontent.com/19719849/106402907-3b3b1b00-642c-11eb-9ca7-ea752497a7fa.jpg)

**Comment by turnermm** [comment]
Have you tried using the winstyle option, as earlier suggested?

**Comment by webafrancois** [comment]
Yes, I made the copy : 
```
copy cp lib/plugins/ckgedit/fckeditor/userfiles/.htaccess.security data/media/.htaccess
```
And change the settings in the admin web page. And look that change is present in conf/local.php : 
```
$conf['plugin']['ckgedit']['winstyle'] = 1;

```
But error is the same...

**Comment by turnermm** [comment]
This copy is done automatically for you when you choose the `winstyle` option.

**Comment by turnermm** [comment]
Check your error logs.  This error could mean that there has been a server or php error.

**Comment by webafrancois** [comment]
I'm sorry for the noise. The problem came from my web host OVH.
It block some request with firewall security : https://www.dokuwiki.org/install:ovh.com

It works fine, now. Sorry.
