### ISSUE TITLE
Code block issue - downloadable snippet not working

### ISSUE THREAD

**Issue by bsncubed** [turnermm/ckgedit#593]
Hi,

Does anyone know why i cant get the downloadable snippet to work? When that option is selected, i click OK and nothing happens. Is something broken, or have i done something wrong?

![image](https://user-images.githubusercontent.com/58550277/100485790-89465080-3155-11eb-94fd-b793537bb7dd.png)

**Comment by turnermm** [comment]
You don't seem to have given the snippet a file name.

**Comment by bsncubed** [comment]
I've just added a snippet file name, and still no luck

![image](https://user-images.githubusercontent.com/58550277/100491783-8d389980-317a-11eb-9ffc-9c0ed19d5966.png)

**Comment by bsncubed** [comment]
i believe that it is permission related, as on a different wiki that i control, that was set up differently, it works fine. on the wiki which it works, i have a security/access issue. 
![image](https://user-images.githubusercontent.com/58550277/100525941-57e28900-3218-11eb-87dd-22de64d55128.png)


I'll keep investigating

**Comment by turnermm** [comment]
What you are seeing here is a response to the lack of security in the directories which hold your data and shouldn't affect the downloading of a snippet to your desk top.

**Comment by bsncubed** [comment]
Do you know of anything else that might be causing the issue? Something else that i can look into? i can send you the link to the site if you want to see for yourself

**Comment by bsncubed** [comment]
this is the error that i received in the console when hitting ok https://pastebin.com/QjEkx5nH

**Comment by turnermm** [comment]
If I understand you correctly, the plugin had been working on a different system but not on you current system.  So there must be something in your current system that is causing the problem.  Your print-out of the error doesn't help very much since it is being read against a compressed file, and all the errors are therefore at line1.  You can try renaming geshi.js.unc to to geshi.j in the geshi directory: 
       ckgedit/ckeditor/plugins/geshi/dialogs/
That is the original, uncompressed geshi js file.  It will at least give the line numbers where the errors occur.  

How did you install ckgedit? And which system were you using when it worked? And which system are you using now?

**Comment by turnermm** [comment]
If all else fails you can still create geshi blocks, as described here:
https://www.dokuwiki.org/plugin:ckgedit:deprecated

**Comment by vic-t** [comment]
Same issue here. 

- Current versions of DokuWiki and CKGEdit
- Working with Firefox 83.0 and Edge (Chromium) on Win10 

![image](https://user-images.githubusercontent.com/13408858/101509001-9692e480-3978-11eb-9fe4-cad94752b4b2.png)
Pressing OK does nothing. If I switch from snippet to codeblock, it works. Snippet and plain text does not. 

Console shows the following error: 
```
Uncaught TypeError: o is null
    a https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/plugins/geshi/dialogs/geshi.js?t=J39A:1
    l https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/plugins/geshi/dialogs/geshi.js?t=J39A:1
    onOk https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/plugins/geshi/dialogs/geshi.js?t=J39A:1
    dialog https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:601
    p https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:10
    fire https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:12
    onClick https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:624
    onClick https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:563
    p https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:10
    fire https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:12
    click https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:562
    button https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:554
    p https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:10
    fire https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:12
    a https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:68
    on https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:68
    button https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:554
    button https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:554
    p https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:10
    fire https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:12
    fireOnce https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:12
    show https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:611
    setTimeout https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:30
    setTimeout handler*setTimeout https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:30
    show https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:611
    openDialog https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:647
    openDialog https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:647
    e https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:259
    y https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:259
    v https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:259
    onload https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:260
    setTimeout handler*x/e.$.onload https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:260
    x https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:260
    load https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:261
    openDialog https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:647
    exec https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:643
    exec https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:213
    execCommand https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:285
    click https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:685
    execute https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:686
    k https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:687
    addFunction https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:32
    callFunction https://wiki.exmp.com/lib/plugins/ckgedit/ckeditor/ckeditor.js:32
    onclick https://wiki.exmp.com/doku.php?id=wiki:playground&do=edit:1```

**Comment by bsncubed** [comment]
When i use the uncompressed  geshi js file, as you suggested, this is the console result in Firefox, and below that, the console log for google chrome. Sorry about the late reply, life got in the way.

Firefox
`Uncaught TypeError: matches is null
    getHref https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/plugins/geshi/dialogs/geshi.js?t=J39A:23
    downloadable_header https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/plugins/geshi/dialogs/geshi.js?t=J39A:42
    onOk https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/plugins/geshi/dialogs/geshi.js?t=J39A:239
    dialog https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:601
    p https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:10
    fire https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:12
    onClick https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:624
    onClick https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:563
    p https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:10
    fire https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:12
    click https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:562
    button https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:554
    p https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:10
    fire https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:12
    a https://apointlessspace.net/lib/plugins/ckgedit/ckeditor/ckeditor.js:68
geshi.js:23:12
`

Chrome:
`geshi.js?t=J39A:1 Uncaught TypeError: Cannot read property '0' of null
    at a (geshi.js?t=J39A:1)
    at l (geshi.js?t=J39A:1)
    at CKEDITOR.dialog.onOk (geshi.js?t=J39A:1)
    at CKEDITOR.dialog.<anonymous> (ckeditor.js:601)
    at CKEDITOR.dialog.p (ckeditor.js:10)
    at CKEDITOR.dialog.fire (ckeditor.js:12)
    at button.onClick (ckeditor.js:624)
    at button.<anonymous> (ckeditor.js:563)
    at button.p (ckeditor.js:10)
    at button.fire (ckeditor.js:12)
a @ geshi.js?t=J39A:1
l @ geshi.js?t=J39A:1
onOk @ geshi.js?t=J39A:1
(anonymous) @ ckeditor.js:601
p @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
onClick @ ckeditor.js:624
(anonymous) @ ckeditor.js:563
p @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
click @ ckeditor.js:562
(anonymous) @ ckeditor.js:554
p @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
(anonymous) @ ckeditor.js:68
`

**Comment by bsncubed** [comment]
quick note, this issue is now occurring on both sites

**Comment by turnermm** [comment]
Try this upgrade to ckeditor 15.1
https://github.com/turnermm/ckgedit/archive/ckeditor.15.1.zip
I have done some testing with 15.1 but there may be some things which I haven't caught, but in the meantime the question is whether this solves your problem. If it does, any other issues can then be taken care of.

**Comment by vic-t** [comment]
@turnermm 

Even with 15.1., I still experience the exact same issue, both on Firefox and Edge. Tried it in InPrivate-Windows to make sure no cookies got in the way. Firefox gives back the following error: 

`Uncaught TypeError: o is null (geshi.js:1:258)`

Just fyi, using the [deprecated way](https://www.dokuwiki.org/plugin:ckgedit:deprecated) of entering a geshi snippet works fine, it's just a pain to edit it afterwards.
