### ISSUE TITLE
Pasting images no longer possible after Edge update

### ISSUE THREAD

**Issue by vic-t** [turnermm/ckgedit#595]
After Edge was updated to Version 87.0.664.57 (Official build) (64-bit), I can no longer paste images into CKGEdit using the copy paste function. It still works fine in Firefox. And it worked today in Edge before the update. 

On one computer, I get no error message whatsoever when trying, on the other I get the following error message in the console. 

```
doku.php?id=wiki:playground&do=edit:1 
Not allowed to load local resource: file:///C:/Users/myuser/AppData/Local/Temp/SNAGHTMLa7781.PNG
```

**Comment by turnermm** [comment]
Version 87.0.664.57 (Official build) (64-bit) --No problem pasting image. 

 Make sure you haven't hit a maxsize/memory  limit in php.ini and make sure to turn on supplementary image paste support.

**Comment by vic-t** [comment]
Apparently, what happened was that the supplementary image paste support was turned off after the update even though I turned it on before. Turning it on again solves the issue.
