### ISSUE TITLE
Code blocks in list

### ISSUE THREAD

**Issue by Skywalker1-CZ** [turnermm/ckgedit#599]
Hi,

we are using dokuwiki with this awesome plugin (ckgedit), but we have some problems with syntax.

We need to use code blocks in list, but if we are using ckgedit, after save the file, the result isn't good :/

Example:

after using Ckgedit we get somethink like this:

  *

<code>
test

</code>

  *

<code>
test

</code>

But we need this one :) 

  *<code>
test
</code>

  *<code>
test
</code>

So I think the problem is a blank line in original dokuwiki syntax...

Can you please fix this? (if we using this many times in our pages, it isn't good to replace it manually :/

Thanks 

Filip Langer

**Comment by turnermm** [comment]
For this you will need to use the HTML_BLOCK macros: 
~~START_HTML_BLOCK~~
<the block to be saved>
~~CLOSE_HTML_BLOCK~~
See https://www.dokuwiki.org/plugin:ckgedit#html_blocks
