### ISSUE TITLE
Issue with save operation when changing from CKG Edit to DW Edit

### ISSUE THREAD

**Issue by jcbeppler** [turnermm/ckgedit#600]
Hello,

When I edit a page and want to switch to the original DokuWiki editor with the **DW Edit** button, it will first save (even if I didn't make any modification) and then switch to it. The problem is that some pages doesn't work well with the CKG Editor and when I switch to the DW editor, first it will save some incorrect syntax (breaking the original code) and then switch, then I would need to either correct everything or restore a previous version. 

I expect that a save operation is not performed together when switching between editors.

Thanks!

**Comment by turnermm** [comment]
You should get this warning:
`To Save your edits click OK; to Discard click Cancel`

**Comment by turnermm** [comment]
This is what you should get

https://ttprivatenew.s3.amazonaws.com/pulse/turnermm03/attachments/15899389/TinyTake31-01-2021-10-50-12.mp4

**Comment by jcbeppler** [comment]
Hi @turnermm 
If I go from the DW Editor to CKG Editor, I receive a message "Leave or Cancel", which would be better to have 3 buttons (Leave, Cancel, Discard). If I go from  CKG Editor to DW Editor, I don't receive any message.
Could this be, because I am using the Bootstrap3 theme?

**Comment by turnermm** [comment]
The first instance is a system message function which comes with only two options.

As for the second instance, I can take a look at it but make no promises.

**Comment by jcbeppler** [comment]
Hi @turnermm I just discovered that indeed the box just doesn't appear when using Chrome! When using Firefox it appears and works as I expected!

**Comment by turnermm** [comment]
There's no fix for this.  You will have to use firefox. Chrome made a change after version 56 which causes loss of data in these instances.  Edge seems to  have followed suit.  I was able to make a workaround but it fails in Chrome.
