### ISSUE TITLE
Mixed active content error when loading javascript

### ISSUE THREAD

**Issue by jsubhi** [turnermm/ckgedit#601]
Error:
Save and other Buttons do not work in ckgedit 
Console reports "mixed active content error" when loading "'http://mydomain.com/dokuwiki/lib/plugins/ckgedit/scripts/parse_wiki-cmpr.js"

Environment: 
ubuntu 20.4, Apache 2.4
Site served via https behind a jumpgate that prevents rewriting every incoming url to https

Possible Fix:
I replaced "DOKU_URL" with "DOKU_BASE" in "action/edit.php" line 141 and 142
This avoids the hardcoded "http://" in the url thus avoiding loading mixed http/https content.

This works for me - but I have no Idea whether it will break things for other setups.

**Comment by turnermm** [comment]
could you make a pull request for this?

**Comment by jsubhi** [comment]
Will try - just starting out with git, though...
