### ISSUE TITLE
CKGEdit sometimes doesn't respect section editing

### ISSUE THREAD

**Issue by mirakrejci** [turnermm/ckgedit#613]
At times, when section editing is requested (by clicking the 'Edit' button next to a document section), the CKGEditor incorrectly opens  other sections below instead the intended one.

**Comment by turnermm** [comment]
I have not been able to reproduce this.  It may have something to do with the content of your page.

**Comment by mirakrejci** [comment]
It is interesting that it does not happen with the same section repeatedly every time, but only sometimes. I will try to find out more information and come up with some deduction.

**Comment by mirakrejci** [comment]
I did not find any clue. Sometimes it happens, but problematically reproducible.
