### ISSUE TITLE
ckgedit and extra_plugins ShowBlocks

### ISSUE THREAD

**Issue by jjancel** [turnermm/ckgedit#614]
Hello
with the kama theme the ShowBlocks icon is not the correct one in the menu bar 
I tried to correct the \ckgedit\ckeditor\skins\kama folder
but that doesn't change anything
can you guide me

**Comment by turnermm** [comment]
I have almost zero experience with kama.  I'm afraid you'll have to sort this out  yourself.  I don't know what the show blocks plugin does and whether it comes with the install or had been added later.
