### ISSUE TITLE
markdown support

### ISSUE THREAD

**Issue by mckaygerhard** [turnermm/ckgedit#619]
please any hint for markdown support?

**Comment by turnermm** [comment]
You might try to use the markdownextra plugin in its block form or the mdpage plugin.  But ckgedit itself cannot deal directly with markdown syntax; it would need an entirely new parser. This, using `mdpage` seems to work:
```
~~MULTI_PLUGIN_OPEN~~
<markdown>
[internal link](:start)
[interwiki link](doku>plugin:mdpage)
![internal image](:wiki:dokuwiki-128.png)
> quotation
</markdown>
~~MULTI_PLUGIN_CLOSE~~

```
The MULTI_PLUGIN macros are needed to retain the line-breaks between the lines of the markdown syntax.

**Comment by mckaygerhard** [comment]
err my dokuwiki install pretty understand very good markdown, that is not the problem..  i requested that editor understand those pages in markdown

**Comment by turnermm** [comment]
Iunderstand  what you requested.  But you didn't seem to understand that ckgedit cannot do what you want.  Instead you will have to use a plugin, as illustrated above.
