### ISSUE TITLE
bug: bullets or numbering procesed two times

### ISSUE THREAD

**Issue by mckaygerhard** [turnermm/ckgedit#620]
whe we used bullets or numbering.. it procesed twice as bold , see image attached, we are using lasted stable dokuwiki and lasted stable plugin from plugin installer at 20210228

![imagen](https://user-images.githubusercontent.com/1571724/112631498-56fbe580-8e0d-11eb-9edb-b6f3f76a15e9.png)

**Comment by turnermm** [comment]
I am afraid I cannot reproduce this:
https://www.mturner.org/devel/playground/tests/lists

Some things to consider.  First, I use the moono gui but I also tested using, as you are doing, thje moono-lisa gui.  You'll have to give use more information.  Do you see any errors in your error logs, from ckgedit or any other source?  Are there any javascript errors showing up in you browser console and which operating system is your wiki on? and which browsers do you use?

**Comment by mckaygerhard** [comment]
i guess is that cannot interact with theme, i m using parallax theme,   there is no error.. let me check some js on the browser client side..  and post feedback here

**Comment by turnermm** [comment]
As I said  before I can't t reproduce this.But one thing I noticed is that your markup is corrupt. Are you using the Roman alphabet?

**Comment by mckaygerhard** [comment]
this ckedit only works with default theme that's the problem. also the ckedit is not working with lasted doku

**Comment by turnermm** [comment]
That in fact is not true.  Here are two dokus that use ckgedit and alternate templates:

sprintdoc: mturner.org/xdevel/ 
mturner.org/xdevel/ 

Here is a page with multiple lists using the monochrome template with ckgedit.  Something else is going on in your wiki for which I don't have enough information.

**Comment by mckaygerhard** [comment]
this but are not in interest of upstream .. what a shame.. closing is more easy than tesolving.. there's more than one user repórtig problems and rest just dont report anything due the current responses
