### ISSUE TITLE
Option for extra lines in code blocks

### ISSUE THREAD

**Issue by iseidel** [turnermm/ckgedit#621]
I am very fond of ckgedit and use it a lot - thank you for that!

I am only having some issues with code blocks where extra lines are inserted.  I have seen that this has been reported in the past and is not a bug: https://github.com/turnermm/ckgedit/issues/572 and https://github.com/turnermm/ckgedit/issues/530

> The extra line feeds enable editing at the bottom of the block. They are removed on save

With many small snippets in code blocks, the page in edit mode becomes quite long and is more cumbersome to navigate. Would it therefore be possible to make the insertion of these extra lines optional? E.g. through a configuration option.

And where is the relevant code located in the code base, so that I could play around with it? Thank you!

**Comment by turnermm** [comment]
> And where is the relevant code located in the code base, so that I could play around with it? 

In action/save.php, starting at around line 345.

**Comment by iseidel** [comment]
Thank you, but I was not successful with experimenting in action/save.php.

However, I found the following section in action/edit.php:

https://github.com/turnermm/ckgedit/blob/6900a33563e01f3a430460c62479e38b61b97e52/action/edit.php#L1280-L1281

Removing the three `\n` did the trick for me! One question though, might there be unintended side effects when replacing `_ckgedit_NL` with an empty string? I guess the other change (removing the `\n` before the closing `pre` tag) should be safe.

**Comment by turnermm** [comment]
If you don't find any side effects, then it should be OK, except that the new lines in a code block help to allow additional entries at the bottom of a code block when editing the page, if the block is the final item on the page..
