### ISSUE TITLE
Pasting from Word

### ISSUE THREAD

**Issue by aalsraimi** [turnermm/ckgedit#622]
After copying from word and pasting. It had a lot of new lines in the paragraphs and between bullet points. <p> for example. 

Is there a way to disable it?

**Comment by turnermm** [comment]
> Is there a way to disable it?

Afraid not.  You can try to use the Word tool.

**Comment by aalsraimi** [comment]
I did and it gives puts <p> In my paragraphs. When though my paragraphs
don’t have any new lines in between.

**Comment by turnermm** [comment]
I have no other suggestions.  Ckgedit is designed to convert its own html to dokuwiki markup.  How well it can handle Word files depends on the Word file.
