### ISSUE TITLE
Can't use filemanager at all

### ISSUE THREAD

**Issue by xeonxu** [turnermm/ckgedit#627]
My environment is docker+bitnami/dokuwiki+ckgeditor.

When I press the image button and try to insert  an image file, I will get a dialog like this.
![image](https://user-images.githubusercontent.com/504239/117772037-56a69500-b269-11eb-83a8-337b0a68f817.png)
Then if I try to click the "Browse" button, instead of poping a new window, it will open a filemanager in current window. Like this:
![image](https://user-images.githubusercontent.com/504239/117773021-670b3f80-b26a-11eb-9da3-788dde98f4bb.png)

Though I can select an image I want, but I can't back to edit mode. If I force back to edit mode by browser's backward button, ckgeditor will disappear. 
![image](https://user-images.githubusercontent.com/504239/117773405-d97c1f80-b26a-11eb-936e-82a1b76bd8aa.png)

Did I miss some configurations?

**Comment by xeonxu** [comment]
> I'm afraid I can't help. I am not familiar with the docker environment. Other uses in past has also had trouble with docker. You might try searching through the closed issues and googling ckgedit/docker.

This issue is not related with docker. Instead, I try a lot and find that ckgedit conflict with some plugins. Like drawio, bookcreator etc. And if I try to use them together, will cause this issue.

**Comment by turnermm** [comment]
There is a list of plugin conflicts on the plugin's page.  draw.io is one of them; from your experience it seems that bookcreator is another.  Nothing can be done about these conflicts from the ckgedit side.  Check with the authors of the other plugins and see if there is anything they can do for you.
