### ISSUE TITLE
Adding font styling for linked text breaks HTML output

### ISSUE THREAD

**Issue by Mediazept** [turnermm/ckgedit#63]
If I add a font style (text size) for a paragraph, the HTML code breaks (see screenshot):

![code problem ckgedit plugin](https://cloud.githubusercontent.com/assets/1333429/5700850/29a05bb6-9a44-11e4-82d0-9edb050c3074.png)

I duplicated the paragraph of "Translation in History" and added a font size. It looks fine in editor, but after saving two square brackets are added at the end of the line. Line 1 and the last line are even more garbled. 
The resulting HTML code looks like this:
```html
<p><b><a class="wikilink1" href="/doku.php?id=start" title="start"><span style="color:inherit"><span style="font-size:18px"><span style="font-family:inherit"><span style="background-color:inherit">Start</span></span></span></span> </a></b></p>

<ul>
	<li class="level1"><a class="wikilink1" href="/doku.php?id=events" title="events">Events</a></li>
	<li class="level1"><a class="wikilink1" href="/doku.php?id=references" title="references">References</a></li>
</ul>

<h2>Groups &amp; Networks</h2>

<div class="level2">
<p><a class="wikilink2" href="/doku.php?id=translation_in_history-historical_geography" rel="nofollow" title="translation_in_history-historical_geography">Translation in History/Historical Geography</a></p>

<p><span style="color:inherit"><span style="font-size:16px"><span style="font-family:inherit"><span style="background-color:inherit">Translation in History/Historical Geography]]</span></span></span></span></p>

<p><b><a class="wikilink2" href="/doku.php?id=translation_in_history-historical_geography" rel="nofollow" title="translation_in_history-historical_geography"><span style="color:inherit"><span style="font-size:16px"><span style="font-family:inherit"><span style="background-color:inherit">Translation in History/Historical Geography</span></span></span></span> </a></b></p>
```

This issue seems related to linked text only. Standard text is not affected.

I'm running DokuWiki latest  (Arctic theme) with latest ckgedit version from plugin repository on a Linux host.
Tested with Firefox (latest) and Google Chrome (latest) on Win 8.1 x64.

**Comment by turnermm** [comment]
It's for situations like this that you need the ```Edit Fonts``` button, where you can edit the font styling manually; that requires some knowledge of the font plugin markup, which you can find on the dw web site: https://www.dokuwiki.org/plugin:ckgedit:font_styling.  After editing the style manually, you should also include the ```~~NO_STYLING~~``` macro, which is also noted on the font-styling page.   Here is an example of how to markup links:
![styling](https://cloud.githubusercontent.com/assets/176447/5704534/08e39c14-9a38-11e4-80e9-df18f8102dd6.png)
The result is found here:  [font_styling_with_links](http://www.mturner.org/devel/doku.php?id=playground:fonts#font_styling_with_links)

If you plan to use the ```Edit Fonts``` button, you should download the very latest version of ckgedit from github.

**Comment by Mediazept** [comment]
Thanks for your help.
Latest version from Github (08-14-Dec_15-16_19) seems to fix it, even without applying any special font formatting using "Edit fonts".
