### ISSUE TITLE
ckgedit version 2021-08-30 does not stick

### ISSUE THREAD

**Issue by kjguenther** [turnermm/ckgedit#633]
In my extension manager, I see that there is a new version (2021-08-30) available. When I click to update, the notice does not go away.  I get the message "Plugin ckgedit updated successfully" at the top of the screen, but the installed version is still 2021-06-16.

**Comment by obel1x** [comment]
yes, the content of https://github.com/turnermm/ckgedit/archive/current.zip is not up to date with the version of https://www.dokuwiki.org/plugin:ckgedit
@turnermm could you file a new release to current.zip ?

**Comment by turnermm** [comment]
Thanks for the heads up.  It should be OK now with all current changes.

**Comment by obel1x** [comment]
Worksfor me! Great work, thank you!
@kjguenther do you agree to close this issue?
