### ISSUE TITLE
Break numbered list

### ISSUE THREAD

**Issue by TonyRos** [turnermm/ckgedit#634]
There is a break in the numbered list if you insert a code or file block into the list.

![image](https://user-images.githubusercontent.com/90394103/132686594-210525be-d6f7-4ea5-bbbc-580eebfc2e97.png)

After save 
![image](https://user-images.githubusercontent.com/90394103/132686640-d48e1c60-d41b-4456-a2e4-dfcbff2f8e44.png)

CKEditor 4.11.4 (revision e1836357e)
DokuWiki "Hogfather"

**Comment by turnermm** [comment]
For this you will have to use an html block
https://www.dokuwiki.org/plugin:ckgedit#html_blocks

**Comment by TonyRos** [comment]
It is works, thanks!
