### ISSUE TITLE
does not work with drag and drop?

### ISSUE THREAD

**Issue by exxosuk** [turnermm/ckgedit#637]
When using the default DW editor drag-and-drop works with the "dropfiles" plugin, however when using the CKG editor drag-and-drop no longer works ?

**Comment by turnermm** [comment]
You have to turn on the the supplementary paste support and use copy and paste, instead of drag and drop

**Comment by exxosuk** [comment]
Where exactly is this setting as I cannot find it anywhere in the configuration page?

**Comment by turnermm** [comment]
On the main screen. Below the editor and editor buttons and above the edit summary textbox.

**Comment by exxosuk** [comment]
ahh ok thanks. 

![Capture](https://user-images.githubusercontent.com/22227683/140393563-9c72b931-2436-4f6e-89b2-3807ac39b48f.JPG)

So control-V pasting now works for images in chrome!

so is there any plans possibility of actually doing drag-and-drop ? this does work with the "dropfiles" plugin, to assume it should be possible ?

**Comment by turnermm** [comment]
In earlier versions of the ckeditor, drag and drop worked very effortlessly. But the developers made current versions much more restrictive.
