### ISSUE TITLE
Formatting doesn't work inside table cells

### ISSUE THREAD

**Issue by Grief** [turnermm/ckgedit#639]
Steps to reproduce:
1. Make something like that in ckgedit:
![image](https://user-images.githubusercontent.com/7239315/141074929-a3ff45e4-b315-47de-b5b3-7e2a9646eb5b.png)
2. Save it
3. Page looks like that:
![image](https://user-images.githubusercontent.com/7239315/141075113-bc5062cc-f01f-4f06-a97a-bcc73fc15c2b.png)
5. This is how the page was saved in the file:
```
|some text_PARA__TABLE_INS_with newline and **formatting:**   * item1
  * item2
|cell2|
|cell3|cell4|
```
6. This is how I expected it to be saved based on your [old comment on the forum](https://forum.dokuwiki.org/d/9110-is-it-possible-to-use-list-or-carriage-return-inside-table-s-cell/6):
```
|<WRAP>
some text
with newline and **formatting:**
  * item1
  * item2
</WRAP>|cell2|
|cell3|cell4|
```
7. This file is rendered correctly as
![image](https://user-images.githubusercontent.com/7239315/141076385-35baea60-e852-4c35-a3e6-c0ede40993b3.png)
8. But you cannot open it in ckgedit:
![image](https://user-images.githubusercontent.com/7239315/141076477-3e11c77d-c495-4257-8a12-332643eefd6f.png)
9. Could you please add the support for WRAPs inside tables for formatting or point me to the direction to how to configure my installation to make it work?

**Comment by turnermm** [comment]
Try  using https://www.dokuwiki.org/plugin:ckgedit#html_blocks

**Comment by Grief** [comment]
@turnermm first of all, this option requires enabled **htmlblock_ok** which is recommended not to enable on public wikis: https://www.dokuwiki.org/plugin:ckgedit:configuration#htmlblock_ok
Secondly, I am not sure how this scenario would be fixed, could you please exmplain a bit?

**Comment by turnermm** [comment]
htmlblock_ok applies only to ckeditor and its current use applies only to html blocks.  But if you don't trust your users then don't enable it.  As for using it, the plugin page explains how to use it.

**Comment by turnermm** [comment]
You just place the htmlblock start and end macros on either side of the html you want to preserve.

**Comment by Grief** [comment]
But I'd like to preserve
```
|<WRAP>
some text
with newline and **formatting:**
  * item1
  * item2
</WRAP>|cell2|
|cell3|cell4|
```
this formatting, not html.

**Comment by turnermm** [comment]
Dokuwiki doesn't support lists in tables.  But the latest version of ckgedit has a fix which preserves the data but not the table formats
