### ISSUE TITLE
ACL UTF-8 groups in Filemanager

### ISSUE THREAD

**Issue by drTr0jan** [turnermm/ckgedit#64]
I've ACL Auth plugin "AuthAD" and there's a group "*Тестовая группа*" in ActiveDirectory.
There's a string "`*   @Тестовая%5fгруппа   8`" in *acl.auth.php* (`0xD0A2 D0B5 D181 D182 D0BE D0B2  D0B0 D18F 25 35 66 D0B3 D180 D183 D0BF D0BF D0B0`).
The upload images to DokuWiki via standard Media Manager is successful. But when I upload images through ckgEdit's Filemanager I get an error: "You do not have permission to upload files to this folder. If you think this is incorrect please notify your administrator."

If I set `$DWFCK_con_dbg = true;` in *fckeditor/editor/filemanager/connectors/php/config.php* i get *nix_paths.txt* with the content:
>...
>[DWFCK_usergrps] => ........_......;;user
>...

where "`........_......`" is  `0xF2 E5 F1 F2 EE E2 E0 FF 5F E3 F0 F3 EF EF E0`

When I use a group "*Test group*" Filemanager works successful.

dokuwiki 2014-09-29b "Hrun"
ckgEdit-ckedit_43-15-Jan_13-20_12

**Comment by turnermm** [comment]
I'm afraid I have no direct experience with Active Directory.  The closest I could come was to create a user assigned to the Тестовая группа group.  Dokuwiki converted that to lower case with an underscore for the space:  ```тестовая_группа```.    I was able to upload to a directory in which that group had upload permission.   That group was represented in acl.auth.php as  ``@тестовая%5fгруппа``, where %5f is the underscore.  The output for nix_paths.txt:
```[DWFCK_usergrps] => user;;тестовая_группа```
I don't know what active directory is doing, what kind of conversion it is making, and I have no way of testing for it.

**Comment by drTr0jan** [comment]
Huh, I've changed group name in acl.auth.php. to lower case and It has started work success!
Thx.

**Comment by turnermm** [comment]
If you assign the group using the Use Manager the group names are automatically converted to Dokuwiki format, which is all lower case and ```sepchar``` for spaces.   

I'm glad to know it is working and what the solution is.
