### ISSUE TITLE
Style Attributes breaks DokuWiki parsing

### ISSUE THREAD

**Issue by cluigDE** [turnermm/ckgedit#641]
Installed version is from 2021-11-06.

This problem only persists in the newer versions. I can only confirm, that on my dev system the old version from 2020-08-** didn't produce this error at all.

So, everytime I modify anything at the start of a new paragraph with style attributes, like font-family, size, color, etc, DokuWiki is incapable of identifing it's own elements like Header or divider and will save and misrender the whole document.

My example:

```
<h1>TEST</h1>

<hr />
<div class="level1">
<p><span style="font-size:10px"><span style="font-family:Arial,Helvetica,sans-serif">dasdasd</span></span></p>
</div>

```

![image](https://user-images.githubusercontent.com/28597501/143444133-aef453b9-26f9-4593-ac75-29886c77b02f.png)

This will actually parse into the following:

![image](https://user-images.githubusercontent.com/28597501/143444589-902f8a3f-1ddf-46b1-ae6f-af88c1e7c7bc.png)

It breaks the divider completely and saves it as a long line. This will also happen to any other DokuWiki element.

```
<h1>TEST</h1>

<p><span style="font-size:9px;">asdasda</span></p>

```

![image](https://user-images.githubusercontent.com/28597501/143444874-2fc80bb5-9ca4-46af-8a7d-09736b7dfbd9.png)

renders into:

![image](https://user-images.githubusercontent.com/28597501/143444920-c750f5ca-a3a6-42bb-a5e9-f2b0703d5db6.png)

**Comment by turnermm** [comment]
Should be fixed.

**Comment by cluigDE** [comment]
You mean, should be fixed in the next release?

Thank you already for the fast reply and you did amazing work.

**Comment by turnermm** [comment]
It's already posted
