### ISSUE TITLE
ckedit converts --> to ndash

### ISSUE THREAD

**Issue by mlcampbe** [turnermm/ckgedit#644]
I am trying to use the outliner plugin to create folded content. The required syntax for outliner is like this:

--> this is a title
content
<--

When using the dwedit this works just fine. But when using ckedit the --> are converted into an &ndash;&gt; entry which then breaks the folded content after saving it.

Is there a way to prevent ckeditor from encoding these on every page save?

**Comment by turnermm** [comment]
These are the result of the conf/entities.conf file.  Comment out the following entries like this:
```
#->      →
#<-      ←
#--      –
```
After doing this you  will have to add some content to the page and re-save it.  You can then remove the extra content if it isn't needed.

**Comment by turnermm** [comment]
Also, you will need the multi-line plugin macros:

https://www.dokuwiki.org/plugin:ckgedit#multi-line_plugins

**Comment by mlcampbe** [comment]
That seems to only half-way work.

When I make the initial edit and save it then all is good. The string is not replaces with the ndash. But if I edit the page a 2nd time and make a change and save it then it reverts back to saving the ndash syntax.

Note that I didn't have a conf/entities.conf file but I did have action/entities/utils/entities.conf. I modified that file and also copied it to the conf directory if that tells you anything.

**Comment by turnermm** [comment]
Note that I didn't have a conf/entities.conf file but I did have action/entities/utils/entities.conf. I modified that file and also copied it to the conf directory if that tells you anything.

**Comment by mlcampbe** [comment]
Sorry, that was my bad. You said conf/entities.conf so I assumed you meant an entities.conf file under the ckgedit plugin folder lib/plugins/ckgedit/conf which I now see is not what you meant. I do have a dokuwiki conf folder with the entities.conf file and modification to that file seems to work correctly for me now. Thanks for the quick reply, you can close this now.
