### ISSUE TITLE
Broken format with 2 styled span paragraphs next to each other

### ISSUE THREAD

**Issue by cluigDE** [turnermm/ckgedit#648]
Hi, 

I have encountered an issue with the formating.
There seems to be an issue, where ckgedit doesn't like 2 paragraphs with span style modifications next to each other.

The moment the second one gets wrapped by a "b" or "strong" tag, the bug is gone.

Thanks in Advance.

The following source code produces:

```
<p><span style="font-size:36px"><b>KB NEWS</b></span></p>

<hr />
<p><span style="font-size:10px">14.12.2021</span></p>

<p><span style="font-size:36px"><b>Neue Stationsk&ouml;rper f&uuml;r die Energiezentrale</b></span> </p>
```

![image](https://user-images.githubusercontent.com/28597501/146190636-81075ba0-4689-414b-a31b-4ead1156c256.png)

While this source code produces this output:

```
<p><span style="font-size:36px"><b>KB NEWS</b></span></p>

<hr />
<p><span style="font-size:10px">14.12.2021</span></p>

<p><b><span style="font-size:36px">Neue Stationsk&ouml;rper f&uuml;r die Energiezentrale</span> </b></p>
```

![image](https://user-images.githubusercontent.com/28597501/146190772-6a3433ff-94e0-44f3-8916-237e778be850.png)

**Comment by turnermm** [comment]
Where do the spans come from? The font selection?

**Comment by cluigDE** [comment]
I guess so.

This is the toolbar with the opened dropdown, which creates the span:

![image](https://user-images.githubusercontent.com/28597501/146199850-9f94e2b7-d506-423e-826d-d6a3b876196d.png)

**Comment by turnermm** [comment]
Not clear what output you want to achieve.  A screen shot would help

**Comment by turnermm** [comment]
I think I now see what you are trying to achieve. I'll see what I can do

**Comment by turnermm** [comment]
Truthfully, I still am not sure where the problem is.  I think I see it but you have not really made it clear.  So a screenshot of the problem output and a screenshot of the desired output would help.

**Comment by cluigDE** [comment]
Well. The two source code snippets I posted before are almost identical.
The only difference is, that in the seccond snippet the <b> encapsulates the <span>.

The output I want to see is the second one. Regardless of the snippet used.
Since in the ckgedit you get different outputs based on the sequence on changes.
If you select a text and make it font-size 10 and then make it bold it creates:
<b><span...
if you make it bold first and then make it font-size 10 you get:
<span...><b>
But this method somehow ends up with merging both paragraphs into one (as you see in the first screenshot)

I hope you understand what I mean.

If I save this:

```
<p><span style="font-size:36px"><b>KB NEWS</b></span></p>

<hr />
<p><span style="font-size:10px">14.12.2021</span></p>

<p><span style="font-size:36px"><b>Neue Stationsk&ouml;rper f&uuml;r die Energiezentrale </b></span></p>
```

it will be parsed after saving into this:

```
<p><span style="font-size:36px"><b>KB NEWS</b></span></p>

<hr />
<p><span style="font-size:10px">14.12.2021</span> <span style="font-size:36px"><b>Neue Stationsk&ouml;rper f&uuml;r die Energiezentrale </b></span></p>
```

**Comment by cluigDE** [comment]
This is my expected result.

![image](https://user-images.githubusercontent.com/28597501/146224343-e3eb52e2-f310-4462-b9b0-7e121f577ac0.png)

![image](https://user-images.githubusercontent.com/28597501/146224274-69f71cb9-48ab-4dcf-bbbd-fa4e07e727e9.png)

**Comment by turnermm** [comment]
### As seen in ckgedit
<img width="553" alt="Microsoft​ Edge_ckg" src="https://user-images.githubusercontent.com/176447/146238630-4a3acfa0-fee3-42b3-8cb8-b47ecf365ec3.png">

### As displayed in browser

<img width="589" alt="2021-1Microsoft​ Edge_browser" src="https://user-images.githubusercontent.com/176447/146240711-44421ced-fad0-4250-8ebb-399a28a888d7.png">




### MULTI_PLUGIN Macros
These macros are used to preserve newlines between blocks of markup, and it would seem, if I understand you correctly, in the current case that is what is needed.

**Comment by cluigDE** [comment]
So, what is the solution to this problem?
I don't quite understand.
Is there something I have to configure in this plugin to avoid paragraph merging?

**Comment by turnermm** [comment]
>> is there something I have to configure in this plugin to avoid paragraph merging?

Have you actually never used ckgedit?  If you had, then you would know that this is a non-question.  The problem in your example is the horizontal rule abutting the font markup, and I've given you a solution.  Or you can use an HTML_BLOCK:  https://www.dokuwiki.org/plugin:ckgedit#html_blocks

**Comment by cluigDE** [comment]
Well, you are totally right. I don't use ckgedit.
I'm a developer with clients, who use ckgedit. They encounter weird behaviours and I have to dig into it to present some kind of work-around or fix.

I will take a look into the MULTI_PLUGIN Macros thing.
Thanks already.
```
  ~~MULTI_PLUGIN_OPEN~~

  ~~MULTI_PLUGIN_CLOSE~~
```
This is the way I am supposed to use this?

![image](https://user-images.githubusercontent.com/28597501/146366514-6f6b606b-d50b-4141-a5d8-a3a25de44810.png)

**Comment by turnermm** [comment]
As illustrated above: https://github.com/turnermm/ckgedit/issues/648#issuecomment-995034523_
Both the horizontal rule and the date have to be enclosed within the MULTI_PLUGIN macros.  

### KB NEWS

~~ MULTI_PLUGIN_OPEN ~~

----------------------------------------------------------------------
~~ MULTI_PLUGIN_CLOSE ~~

~~ MULTI_PLUGIN_OPEN ~~
14.12.2021
~~ MULTI_PLUGIN_CLOSE ~~

### Neue Stationskörper für die Energiezentrale

**Comment by cluigDE** [comment]
Amazing.
Thank you for your effort to help me sorting this out.
Is there any way I can tip you?

**Comment by turnermm** [comment]
Dokuwiki is run by volunteers.  In some cases it's possible that someone might need special attention and then can hire someone to help.  But this kind of problem is simply standard user help.  It's possible if you want to do so, to contribute from the donation link on the plugin page.
