### ISSUE TITLE
copy word contents , pictures missed

### ISSUE THREAD

**Issue by lilarcor** [turnermm/ckgedit#649]
Hello,
I tried to copy and paste from word file to DW, in preview mode, everything showed fine. But all pictures were missed after saving. Is there any tip for this ?

**Comment by turnermm** [comment]
Ckgedit doesn't have a preview mode.

**Comment by lilarcor** [comment]
oh, for the preview mode I thought it's the view before I click "save"

**Comment by lilarcor** [comment]
in a word file or in a web, if I right click a picture and select "copy", then paste it into DW, everything is fine. If I select a word combined with a picture to copy and paste them into  DW, the text was kept and pic was missed.

**Comment by turnermm** [comment]
In Chrome use the `"Turn supplementary image paste support on"` check box.  In Firefox you will have to copy and paste image text and separately. After pasting text, place your cursor on the image, right-click and choose copy image.  A few years ago the CKEditor stopped enabling direct copy/paste so workarounds have been needed. You may have to experiment. \

**Comment by lilarcor** [comment]
thanks for your reply, I tried this , still didn't work well. So far, I found a temp solution, save web to webarchive in devonthink, convert it to rtfd, then convert to html, open html in firefox, then copy and paste
