### ISSUE TITLE
Wrongful auto change of links with Korean, Chinese, Japanese char set

### ISSUE THREAD

**Issue by pureiris** [turnermm/ckgedit#65]
Hi,
I found a problem with Korean, Chinese, Japanese char set.
If I update 'link info' which is in Korean or Chinese, ckgedit change it automatically in a wrong way.

First of all, I can use an internal link in Korean char set like the following.
```
http://localhost/dw0/doku.php?id=나의일기
http://localhost/dw0/doku.php?id=%EB%82%98%EC%9D%98%EC%9D%BC%EA%B8%B0
```
Both are exactly the same. Basic DokuWiki editor change '나의일기' to '%EB%82%98%EC%9D%98%EC%9D%BC%EA%B8%B0' automatically and it works fine.

나의일기 means My diary. 我的日记(in Chinese) / 私の日記(in Janpanese)

The problem is the following.
Here is a sample code.
```
<p>Go to <a class="wikilink2" href="localhost/dw0/doku.php?id=mydiary" title="mydiary">mydiary</a> page</p>
<p>Go to <a class="wikilink2" href="localhost/dw0/doku.php?id=나의일기" title="나의일기">나의일기</a> page.</p>
<p>Go to <a class="wikilink2" href="localhost/dw0/doku.php?id=我的日记" title="我的日记">我的日记</a> page.</p>
<p>Go to <a class="wikilink2" href="localhost/dw0/doku.php?id=私の日記" title="私の日記">私の日記</a> page.</p>

<p><a class="wikilink2" href="/dw0/doku.php?id=mydiary" title="mydiary">mydiary</a></p>
<p><a class="wikilink2" href="/dw0/doku.php?id=나의일기" title="나의일기">나의일기</a></p>
<p><a class="wikilink2" href="/dw0/doku.php?id=我的日记" title="我的日记">我的日记</a></p>
<p><a class="wikilink2" href="/dw0/doku.php?id=私の日記" title="私の日記">私の日記</a></p>
```

After saving this code, it works fine.
But if I **change a link info in the Second ~ Forth line**, ckgeditor change a link information into a wrong format.
Such as **:eb_82_98_ec_9d_98_ec_9d_bc_ea_b8_b0**
Then the link does not work. 

Interesting point is that only link info **in a sentence** is changed.
The links in the **Fifth~Eighth lines** are not altered.

Here are captured JPGs.

1. Sample code
![error1](https://cloud.githubusercontent.com/assets/10451185/5953169/92aa459a-a7c8-11e4-8c8d-f7e240b6c61f.JPG)

2. works fine, but change any link in senctence... save and reload
![error2](https://cloud.githubusercontent.com/assets/10451185/5953175/b714b7da-a7c8-11e4-996c-d9bef74ef859.JPG)

3. link info changed into a wrong way
![error6](https://cloud.githubusercontent.com/assets/10451185/5953203/fc078ec6-a7c8-11e4-85a4-ec0ebb1b076f.JPG)

In summary:
Normal DokuWiki system change these safely.
```
나의일기 =>  %EB%82%98%EC%9D%98%EC%9D%BC%EA%B8%B0
我的日记 =>  %E6%88%91%E7%9A%84%E6%97%A5%E8%AE%B0
私の日記 =>  %E7%A7%81%E3%81%AE%E6%97%A5%E8%A8%98
```

But ckgedit make a change in a different way.
```
나의일기 =>  :eb_82_98_ec_9d_98_ec_9d_bc_ea_b8_b0
我的日记 =>  :e6_88_91_e7_9a_84_e6_97_a5_e8_ae_b0
私の日記 =>  :e7_a7_81_e3_81_ae_e6_97_a5_e8_a8_98
```

<cases>
good!
```
<p><a class="wikilink2" href="/dw0/doku.php?id=나의일기" rel="nofollow" title="나의일기">나의일기</a></p>
```

good, too!
```
<p><a class="wikilink2" href="/dw0/doku.php?id=%EB%82%98%EC%9D%98%EC%9D%BC%EA%B8%B0" rel="nofollow" title="나의일기">나의일기</a></p>
```

not good...
```
<p>Go to <a class="wikilink1" href="localhost/dw0/doku.php?id=:eb_82_98_ec_9d_98_ec_9d_bc_ea_b8_b0" title=":eb_82_98_ec_9d_98_ec_9d_bc_ea_b8_b0">나의일기</a> page.</p>
```

**Comment by turnermm** [comment]
This should be fixed in the current update.  Get it here from github.

**Comment by pureiris** [comment]
Now it works well~! thank you for great contribution : )
