### ISSUE TITLE
SVG smileys with the coming DokuWiki release.

### ISSUE THREAD

**Issue by Klap-in** [turnermm/ckgedit#650]
The coming release of DokuWiki uses SVG instead of GIF-images for the smileys. The gif-images are already removed in coming release, maybe a bit quick, does that bother you?

https://github.com/splitbrain/dokuwiki/pull/3344

https://github.com/turnermm/ckgedit/blob/6900a33563e01f3a430460c62479e38b61b97e52/ckeditor/config.js.unc#L231-L250

**Comment by turnermm** [comment]
Thanks for pointing this out.  I have a test installation of the update, but it hadn't occurred to me to test out the smileys. Fortunately, all that was needed was an update to the css.
