### ISSUE TITLE
Image link inserted by ckgedit causes logout when editing the page

### ISSUE THREAD

**Issue by misterjmw** [turnermm/ckgedit#651]
Environment:
IIS 10
Windows Server 2016
Dokuwiki & ckgEdit - Latest (Hogfather)

A user inserted an image into a page using ckgedit. In turn it inserted a string that reads:

**{{https://wiki.ourorg.org//wiki/lib/plugins/ckgedit/fckeditor/_userfiles/image/division/usdivision/pauls/th-1pmginformation.png?nolink&960x720}}**

This page is rarely changed and was last modified March of 2021. 

Upon trying to update it this year, all users (including admin) found that if they login then click the edit button, they become logged out and receive a page indicating that the page is read-only, because they are not logged in.

![image](https://user-images.githubusercontent.com/1383647/151006415-c442836a-ee8c-4950-ba77-8319dc3e4dbd.png)

![image](https://user-images.githubusercontent.com/1383647/151006379-0b6249b8-aa31-464b-ba89-5fb36f6104c4.png)

All users (with permission) can repeat these steps over and over again. 

I edited the txt file for the page itself and found the above link, and changed it to read:
**{{:division:usdivision:pauls:th-1pmginformation.png?nolink&960x720}}**

Editing the page now works as expected.

**Comment by turnermm** [comment]
Not sure why this is happening.  There really is no way I can test for it unless I know what kind of image you are trying to paste into the editor.

**Comment by turnermm** [comment]
Post

**Comment by turnermm** [comment]
And is it all images or just the one

**Comment by turnermm** [comment]
And see this https://www.dokuwiki.org/faq:brokenimages

**Comment by misterjmw** [comment]
> And is it all images or just the one
We do not have the image, as far as I can tell it never existed. 
The filename being linked to does not exist in our system. 

The logout only occurs when a page is loading the link: {{https://wiki.ourorg.org//**wiki/lib/plugins/ckgedit/fckeditor/_userfiles/image**/departments/nope.png?nolink&960x720}}

For this test NOPE.PNG does not exist.

Here is a video showing me editing the page that doesn't have the link.
Then I add the link, and try editing the page again, and I am logged out:

https://streamable.com/4q7eix

**Comment by misterjmw** [comment]
By a process of elimination, the problem is the underscore prior to userfiles. This creates a non-working link.

First, I put the file nope.png into the data\media\division path. 
Loading this page calls up a DW page that the page is not found:
{{https://wiki.ourorg.org//wiki/lib/plugins/ckgedit/fckeditor/_userfiles/image/division/nope.png}}

Altering the link to read: 
 {{https://wiki.ourorg.org//wiki/lib/plugins/ckgedit/fckeditor/userfiles/image/division/nope.png}}

... and the image is found and editing works.

**Comment by turnermm** [comment]
I am glad you found a fix. I am confused, because first you said the image didn't exist but now it does. Also, your link is not the kind that the media manager creates. But good that it is now solved.

**Comment by misterjmw** [comment]
> I am glad you found a fix. I am confused, because first you said the image didn't exist but now it does. Also, your link is not the kind that the media manager creates. But good that it is now solved.

I never said the file existed. 

I said that a user inserted an image in a page March of last year. Even in the closing statement, I state that I corrected the link to a normal DW format and we can edit the page again. The image never mattered except that somehow, a user got a link got a link that points at the files under ckgEdit. And that link causes DW to log the user out if they try to edit the page.
