### ISSUE TITLE
ckgedit only works once until i clear the browser cache

### ISSUE THREAD

**Issue by vmario89** [turnermm/ckgedit#652]
Hi,
having installed the latest ckgedit, the editor only works once. After clicking edit on the page again the menu bars disappear in the editor and the page content is not rendered anymore. I have no idea what behaviour does this cause. Any idea where i could check? The browser debug console does not show errors or warnings 

i am using the Hogfather release. the issue persists regardless of the setting "defer_js"

**Comment by turnermm** [comment]
Check your browser javascript log.  There may be some hjel[p there.  But I can't reproduce your experience in any browser.  As for the defer flag, ckgedit has been updated for hogfather.

**Comment by vmario89** [comment]
the behaviour is not redoable by me at the moment. ckgedit often fails to display and i already checked a lot of different things like
* resave config
* delete caches. lock files, tmp files
* set lock time to 0
* reinstall the plugin
* disable plugins
* checking file/folder permissions
* ...

**Comment by turnermm** [comment]
Ckgedit leaves file locking to Dokuwiki.  What is you OS, which browser? Have you checked your error logs? Have you checked the browser console for javascript errors?

**Comment by vmario89** [comment]
some info: the reason finally was https://github.com/dryoo/dokuwiki-plugin-shortcutkey - seams it registered some hook which grabbed actions from ckgedit
