### ISSUE TITLE
Manual install throws error

### ISSUE THREAD

**Issue by g-wenzel** [turnermm/ckgedit#655]
In my Dokuwiki I have to install plugins manually as it is located behind a corporate firewall and connections to the extension repo are blocked.

Everytime I try to install the plugin, the UI shows an error (with a somewhat inconclusive error message). Uploading other plugins works fine. It does also not seem to be related to the browser (happens with Firefox and Chromium).

![grafik](https://user-images.githubusercontent.com/53309805/153488146-83182fd9-f58f-40cc-a2fc-7273514e3f80.png)

![grafik](https://user-images.githubusercontent.com/53309805/153488171-6179670a-4a0e-4adb-8ff6-210293e273fd.png)

**Comment by turnermm** [comment]
Manually how?  From the command line or from the manual tab of the browser?

**Comment by g-wenzel** [comment]
From the manual tab in the browser (shown in the first screenshot, error message in the second).

**Comment by turnermm** [comment]
Sorry.  I wasn' t paying attention.  Try the command line.

**Comment by g-wenzel** [comment]
The newly bundled file worked perfectly. Thanks a lot!

**Comment by turnermm** [comment]
And truthfully, I don't know why.
