### ISSUE TITLE
jscript error on clicking geshi button

### ISSUE THREAD

**Issue by jsheridan1980** [turnermm/ckgedit#656]
when clicking on the geshi button the popup fail to render
Release 2020-07-29 "Hogfather"
Bootstrap3 Template v2021-03-11 (stable/20210311)

uninstalled ckgedit and reinstalled - till i found it's probably a jscript error:

Uncaught TypeError: **_Node.appendChild: Argument 1 is not an object._**
    append http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:101
    appendTo http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:75
    dialog http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:604
    openDialog http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:647
    openDialog http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:647
    e http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:259
    y http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:259
    v http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:259
    onload http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:260
    setTimeout handler*load/x/e.$.onload http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:260
    x http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:260
    load http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:261
    openDialog http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:647
    exec http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:643
    exec http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:213
    execCommand http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:285
    click http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:685
    execute http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:686
    k http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:687
    addFunction http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:32
    callFunction http://<<mywiki>>/lib/plugins/ckgedit/ckeditor/ckeditor.js:32
    onclick http://<<mywiki>>/doku.php?id=archlaptop&do=edit:1

disabled all dokuwiki extensions to rid out the possibility it is a incompatibility
cleared cache; error in latest firefox + edge (same error)
tried out also on a different page within the dokuwiki - same.

it tried somehow to add to "this"  ("$": div#cke_dialog_title_119.cke_dialog_title) the param a which is "undefined".
 
b+"(?\x3d\\s|$)"),"").replace(/^\s+/,""))?this.setAttribute("class",c):this.removeAttribute("class"));return this},hasClass:function(b){return a(this.$.className,b)},append:function(a,b){"string"==typeof a&&(a=this.getDocument().createElement(a));b?this.$.insertBefore(a.$,this.$.firstChild):this.$**_.appendChild(a.$)_**;return a},appendHtml:function(a){if(this.$.childNodes.length){var b=new CKEDITOR.dom.element("div",this.getDocument());b.setHtml(a);b.moveChildren(this)}else this.setHtml(a)},appendText:function(a){null!=

Any idea how what went wrong?

edit: created a dokuwiki from scratch (downloaded again, only the ckgedit installed in a blank wiki) - same error

**Comment by turnermm** [comment]
Can't reproduce this either in firefox or chrome.  It could be a conflict with botstrap3, though I did try it out in a fresh install of the template without trouble.  You'll have to do some more searching.
