### ISSUE TITLE
Not all pasted images are saved

### ISSUE THREAD

**Issue by Grief** [turnermm/ckgedit#658]
Steps to reproduce:
1. make a screenshot, I reproduced it with this one:
![image](https://user-images.githubusercontent.com/7239315/153870582-c56662f2-065a-4955-85ea-bce6ae0e28f6.png)
2. paste it ten times to the page (that supposed to be how-to-article with the screenshot examples)
3. save the page
4. observe, that some images were not parsed
![image](https://user-images.githubusercontent.com/7239315/153870634-de4869ba-21f7-4bd5-8713-99b9d2e9ddcf.png)

**Comment by turnermm** [comment]
Maybe 10 times is a bit too much for it to handle! Moreover, the images might be over-written if they are exactly the same.

**Comment by vmario89** [comment]
This issue occures at our instance too. But it only happens if you post an image from clipboard and when you resize that image in the same step. You can omit breaking your images when pasting, saving the page, then editing the size. I wanted to report this as a bug but this issue already contains my point

**Comment by vmario89** [comment]
Hi. yes i thought that too. Is there some way to omit that? A regular user will never know by himself that a newly pasted image will break if resizing in the same step. I got that pain first when i created a page with 10 screenshots at once

**Comment by turnermm** [comment]
I don't see how that can be done since the image does not have a name until it has been saved to the server.

**Comment by proxymus** [comment]
@turnermm I've noticed the problem of Gerif too. When you paste two different pictures from the clipboard into one article, only the last one is saved. The pictures haven't been modified before the page was saved.
