### ISSUE TITLE
Save page on keypress combination

### ISSUE THREAD

**Issue by vmario89** [turnermm/ckgedit#661]
Hi,
for some days now i try to find the right place to add some keyboard shortcut to have a key combination for CTRL + S. I want to be able to quickly save the page after editing. I already crawled the whole web for doing this. Unfortunately i am not a javascript pro. I messed in ckgeditor.js.unc (replaced the ckgeditor.js) and tried to add some stuff to conf/userscript.js as well. No working results except catching the keypress triggers fine.

however, doing sth. like this does not work because it will not submit the form with the changed content. it will only display a popup information.

```
 jQuery(document).keydown(function(e) {
	if (window.event) var g=window.event,f=g.srcElement,nn=f.tagName;
        else var f=g.target,nn=f.nodeName;/* GET FOCUS */
		if (nn!='INPUT'&&nn!='TEXTAREA') {
  	        if (e.which == 83) {
                form = document.getElementById('dw__editform');
		        form.submit();
		        //alert(e.which);
		        }
			}
	});
```

does anybody has a clue how to add that?

cheers, MArio

**Comment by turnermm** [comment]
Windows itself already captures ctrl-s.

**Comment by vmario89** [comment]
Hi, that does not matter. It might be also some other combination lilke CTRL + SHIFT + S, ALT + CTRL + S, ALT + SHIFT + S. The technical solution is my point. I dont know how to trigger the event correctly so the entered input from form will be applied.

**Comment by turnermm** [comment]
Install the master branch from the manual tab and use Ctrl-X

**Comment by vmario89** [comment]
Hi @turnermm, thanks for that commit .I tested from masterbranch. It works perfectly!

**Comment by turnermm** [comment]
I've changed this to CTRL-E (for Exit), because CTRL-X interfered with in-line text deletions.
