### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by PMP161316** [turnermm/ckgedit#67]
Hi,

thank you for this great plugin.
I have a strange problem here:
When I paste text from an old webpage which was created with Microsoft Word I am not able to save the wikipage. Clicking on the Save button just does nothing.
I nailed it down to a strange HTML Tag < o:p >< /o:p >
When I change to source code and remove this tag the wikipage will save normally.

Is it possible to add a function to remove those tags before saving?

Kind regards,
PMP161316

**Comment by turnermm** [comment]
There is a paste-from-word tool in the toolbar.
![paste](https://cloud.githubusercontent.com/assets/176447/6082577/195e75e6-ade8-11e4-9334-77770ceadaa7.png)
Have you tried that?
