### ISSUE TITLE
Problem with PHP8

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/ckgedit#673]
Hi,

after updating the dokuwiki server to PHP8 the ckgedit plugin fails with the following error message when I go to the konfig page of the admin console:
```
dokuwiki\Exception\FatalException: Declaration of renderer_plugin_ckgedit::header($text, $level, $pos) must be compatible with Doku_Renderer_xhtml::header($text, $level, $pos, $returnonly = false)
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the ckgedit plugin.
```
What can I do?

Best regards
Juergen

**Comment by turnermm** [comment]
See if this works for you:
https://github.com/turnermm/ckgedit/archive/refs/heads/php8.zip

Unfortunately, I don't have php8 installed for testing.  But this hopefully will work.

**Comment by turnermm** [comment]
@Juergen-aus-Zuendorf 
Have you tried the fix?

**Comment by Juergen-aus-Zuendorf** [comment]
Unfortunately, I did not have access to the test server yesterday.

So here is the test result from today. Unfortunately, an error message appears again:
```
dokuwiki\Exception\FatalException: Declaration of renderer_plugin_ckgedit::header($text, $level, $pos) must be compatible with Doku_Renderer_xhtml::header($text, $level, $pos, $returnonly = false)
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the ckgedit plugin.
```

**Comment by Juergen-aus-Zuendorf** [comment]
The code on line 68 is
`function header($text, $level, $pos, $returnonly = false)`
What shall I do now?

**Comment by shawnblues** [comment]
Hi,I'm having the same problem as you, but I've solved it. Just replace `$text, $level, $pos `with `$text, $level, $pos, $returnonly = false`. You can huave a try.

**Comment by JorgeCarousel** [comment]
> See if this works for you: https://github.com/turnermm/ckgedit/archive/refs/heads/php8.zip
> 
> Unfortunately, I don't have php8 installed for testing. But this hopefully will work.

This worked for me, but it's time to switch to PHP 8, as per this: https://www.php.net/supported-versions.php PHP 7 will reach EOL in a couple of months.

**Comment by turnermm** [comment]
commit 8df8f21bd33c1101246718d34188b97e427f883c

This was fixed in the above commit.   Make sure you have the “current” branch, not the master

**Comment by JorgeCarousel** [comment]
I did, until it stopped showing me there were updates available.

**Comment by turnermm** [comment]
Sometimes it could be that I hadn't gotten around to updating the plugin page or the version date in the plugin.txt file. You can always see the most recent commits on the plugin page and use the reinstall button in the extension manager for the latest version.

**Comment by JorgeCarousel** [comment]
I deleted the previous folder, put in the "current" I downloaded and hit re-install, let's see how it goes.
