### ISSUE TITLE
Media browsing and farm setup bug?

### ISSUE THREAD

**Issue by cactux** [turnermm/ckgedit#68]
This plugin works fine, except one thing:
On a Dokuwiki installation as a farm (see https://www.dokuwiki.org/farms), when browsing the media from a "animal" wiki, I see the media of the farm, not those of the animal wiki.
When browsing media from a "animal" wiki, I should see the media from this "animal" only.
I don't know if it is a Dokuwiki bug, or a ckgedit one?

**Comment by turnermm** [comment]
This, from the fckgLite web site, applies to ckgedit as well:

http://www.mturner.org/fckgLite/doku.php?id=farms

**Comment by turnermm** [comment]
I just checked and see that the farms code was never updated for the most recent versions of ckgedit.  I'll see what I can do.

**Comment by cactux** [comment]
Thanks, it works fine :+1:
Sorry I missed this part of the doc.
An update would be awesome, I'll watch here :)

**Comment by turnermm** [comment]
I've just uploaded an update to the most recent ckgedit: http://www.mturner.org/fckgLite/doku.php?id=farms&#instructions
