### ISSUE TITLE
Tons of warnings with PHP 8.1

### ISSUE THREAD

**Issue by JorgeCarousel** [turnermm/ckgedit#680]
Hey guys,

I have CKGEdit from your github on my Dokuwiki and I have been seeing these lines in Apache's error.log (mostly on file edit.php line 71), can you do something about it?

Thanks.

`[Thu Sep 15 13:35:10.936461 2022] [fcgid:warn] [pid 8236:tid 184] [client 192.168.1.111:61659] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71
[Thu Sep 15 13:35:11.079512 2022] [fcgid:warn] [pid 8236:tid 184] [client 192.168.1.111:61659] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Thu Sep 15 13:35:11.140861 2022] [fcgid:warn] [pid 8236:tid 184] [client 192.168.1.111:61659] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Thu Sep 15 13:35:11.246541 2022] [fcgid:warn] [pid 8236:tid 184] [client 192.168.1.111:61659] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Thu Sep 15 13:35:11.426169 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.111:61660] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Thu Sep 15 13:35:11.476570 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.111:61659] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Thu Sep 15 13:35:38.669511 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.111:61662] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/start
[Thu Sep 15 13:35:38.722066 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.111:61661] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/start
[Thu Sep 15 13:35:40.694271 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.111:61662] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/start?do=search&id=start&q=frame
[Thu Sep 15 13:35:40.745835 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.111:61661] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/start?do=search&id=start&q=frame
[Thu Sep 15 13:37:10.940813 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.111:61673] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/carousel_systems/tech_internal_wiki/technology/saas/frameio/frameio?s[]=frame
[Thu Sep 15 13:37:10.993904 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.111:61672] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/carousel_systems/tech_internal_wiki/technology/saas/frameio/frameio?s[]=frame
[Thu Sep 15 13:37:17.029304 2022] [fcgid:warn] [pid 8236:tid 184] [client 192.168.1.111:61674] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/carousel_systems/tech_internal_wiki/technology/saas/frameio/storage
[Thu Sep 15 13:37:17.034282 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.111:61674] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/carousel_systems/tech_internal_wiki/technology/saas/frameio/storage
[Thu Sep 15 13:37:17.088312 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.111:61674] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/carousel_systems/tech_internal_wiki/technology/saas/frameio/storage
[Thu Sep 15 13:37:17.105235 2022] [fcgid:warn] [pid 8236:tid 184] [client 192.168.1.111:61674] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/carousel_systems/tech_internal_wiki/technology/saas/frameio/storage
[Thu Sep 15 13:37:18.113602 2022] [fcgid:warn] [pid 8236:tid 1060] [client 192.168.1.111:61674] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/carousel_systems/tech_internal_wiki/technology/saas/frameio/storage
[Thu Sep 15 13:37:18.188946 2022] [fcgid:warn] [pid 8236:tid 1060] [client 192.168.1.111:61675] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/carousel_systems/tech_internal_wiki/technology/saas/frameio/storage
[Thu Sep 15 13:37:18.239763 2022] [fcgid:warn] [pid 8236:tid 1060] [client 192.168.1.111:61674] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/carousel_systems/tech_internal_wiki/technology/saas/frameio/storage
[Fri Sep 16 10:02:55.884409 2022] [fcgid:warn] [pid 8236:tid 184] [client 192.168.1.10:8284] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71
[Fri Sep 16 10:02:55.991622 2022] [fcgid:warn] [pid 8236:tid 184] [client 192.168.1.10:8284] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Fri Sep 16 10:02:55.993613 2022] [fcgid:warn] [pid 8236:tid 392] [client 192.168.1.10:8284] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Fri Sep 16 10:02:56.986279 2022] [fcgid:warn] [pid 8236:tid 344] [client 192.168.1.10:8284] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Fri Sep 16 10:02:59.112771 2022] [fcgid:warn] [pid 8236:tid 1060] [client 192.168.1.10:8284] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/start?do=admin
[Fri Sep 16 10:02:59.117747 2022] [fcgid:warn] [pid 8236:tid 344] [client 192.168.1.10:8284] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/start?do=admin
[Fri Sep 16 10:02:59.180470 2022] [authz_core:error] [pid 8236:tid 344] [client 192.168.1.10:8284] AH01630: client denied by server configuration: D:/Apache24/htdocs/dokuwiki/data/dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png, referer: https://wiki.example.com/start?do=admin
[Fri Sep 16 10:06:12.460695 2022] [fcgid:warn] [pid 8236:tid 420] [client 192.168.1.10:8356] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71
[Fri Sep 16 10:06:12.543329 2022] [fcgid:warn] [pid 8236:tid 420] [client 192.168.1.10:8356] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Fri Sep 16 10:06:12.562245 2022] [fcgid:warn] [pid 8236:tid 1052] [client 192.168.1.10:8356] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Fri Sep 16 10:06:13.558513 2022] [fcgid:warn] [pid 8236:tid 1076] [client 192.168.1.10:8356] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Mon Sep 19 09:08:20.096462 2022] [fcgid:warn] [pid 8236:tid 1052] [client 192.168.1.10:36590] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71
[Mon Sep 19 09:08:20.345364 2022] [fcgid:warn] [pid 8236:tid 972] [client 192.168.1.10:36590] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Mon Sep 19 09:08:20.367266 2022] [fcgid:warn] [pid 8236:tid 1052] [client 192.168.1.10:36590] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Mon Sep 19 09:08:21.336653 2022] [fcgid:warn] [pid 8236:tid 900] [client 192.168.1.10:36590] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/
[Mon Sep 19 09:08:24.946741 2022] [fcgid:warn] [pid 8236:tid 900] [client 192.168.1.10:36590] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/start?do=admin
[Mon Sep 19 09:08:24.948731 2022] [fcgid:warn] [pid 8236:tid 996] [client 192.168.1.10:36590] mod_fcgid: stderr: PHP Warning:  Undefined array key "id" in D:\\Apache24\\htdocs\\dokuwiki\\lib\\plugins\\ckgedit\\action\\edit.php on line 71, referer: https://wiki.example.com/start?do=admin`

**Comment by turnermm** [comment]
line 71 was fixed in `current_22-Sep_09-15_17`.  Which is the current download version.

**Comment by JorgeCarousel** [comment]
I should have downloaded it before asking, thanks.
