### ISSUE TITLE
Opening file browser in CKG crashes CKG instrument bar

### ISSUE THREAD

**Issue by NaleVex** [turnermm/ckgedit#682]
When I go into file browser to insert any image, any file browser (doku or ckgedit doesn't matter) opens on same page and cannot be closed. After reloading the page instrument bar is no longer visible and any text on the page transformed into `__false__` if being opened in CKGedit and CKG is switched to Doku editor.
This problem fixes by changing plugin»ckgedit»gui style but only once per style, reinstalling plugin may help sometimes.

**Comment by turnermm** [comment]
This is a JavaScript error and without more specific information I can't help

**Comment by NaleVex** [comment]
What information may I give? Some specifig logs or something else?

**Comment by turnermm** [comment]
Check the server logs and any JavaScript errors reported in the browser log

**Comment by NaleVex** [comment]
Ok, my bad. Looks like there was a problem with some installed plugins or vivaldi browser itself which I use. I'll close this issue. Good luck!
