### ISSUE TITLE
Plugin msword <o:p> Element Error

### ISSUE THREAD

**Issue by cluigDE** [turnermm/ckgedit#699]
Hi,
Customers of mine try to import content from word documents and used to use the msword plugin for ckgedit.

I think something in Word changed in the last weeks and they paste some sort of "<o:p>" into the editor after adding the content into the dialog of the plugin and confirming. This element is not allowed and can't be parsed by your plugin. 

For now I duplicated the msword plugin and modified it myself, which is just a short term solution. Would you do me a favor and integrate the removal of that element into the plugin?

Or do you have an idea of integrating this myself as a longterm solution?

```js
            inner = inner.replace(/(<\/o:p\s*>)+/gm, "");
            inner = inner.replace(/(<o:p\s*>)+/gm, "");
```

**Comment by turnermm** [comment]
Would you create a pull request for this? I will merge it into ckgedit

**Comment by cluigDE** [comment]
#700
