### ISSUE TITLE
Internal Link creation with additional pageheader not working

### ISSUE THREAD

**Issue by poulpoulsen** [turnermm/ckgedit#70]
hello,
i try to insert internal links e.g. [[name of wiki page|pageheader]], but unfortunately the editor corrupted it.
the result is [[name of wiki page#pageheader]]
pageheader words are connected with the char _ 

How could i insert internal wikilinks with pageheader?

I use newest dokuwiki release with firefox 35 on windows 7 or 8.

Any help or clues?

Thanks
Poul

**Comment by turnermm** [comment]
Not entirely sure I understand your problem or, perhaps, how you encountered it.  But to the extent that I understand you, these links are part of the core utility of ckgedit and the problem has not been raised as an issue  before.  I uploaded a video which show various ways to create Named Internal links.
* (1) You can simply use the standard Dokuwiki markup
* (2) You can type any text you want into the editor, select it with your mouse, and choose a file from the link tool.
* (3) The same as above but the link text can also be edited after the link as been created by the link tool.

Please view the video: https://www.youtube.com/watch?v=FqpYW3pqJm0

**Comment by turnermm** [comment]
I just realized what you are referring to.  You used the link tool's advanced tab and selected headings.  Those heading are converted to HTML anchors,so that when you click on the link, instead of being directed to the top of the page, you are redirected to the place in the page where the header occurs, just as you are when you click on a header in the table of contents.

**Comment by poulpoulsen** [comment]
Hello,
thank you for your fast reply.
Yes, you realized it the way i supposed to :-) Sorry for my bad english 
- i'm not a native speaker (come from germany).

I know, that the # sign marks a link to a pageregion, but without an 
internal link in the form [[dokuwiki pagename|header]] i only see the 
unified pagename inside my text. The pageheader is not visible with the 
# notation. Because i renamed the pageheader for clarification, i love 
this dokuwiki feature.

How could i create links the dokuwiki way with included | ?

Regards
Poul

Am 16.02.2015 um 02:09 schrieb Myron Turner:

**Comment by turnermm** [comment]
Are you referring to the ```useheading``` feature?
```useheading:  Use first heading for pagenames```
Ckgedit doesn't support this feature.  But there is no reason that you cannot do this manually.

**Comment by poulpoulsen** [comment]
Hello,

yes i'm referring about this feature.
It's bad that ckgedit doesn't support this nice feature.
Any chance for it in the future?
Is your other editor fckgLite support this feature?
I can't install this editor, because dowiki warns about not supported 
saferencoded pagenames (not sure about correct message). A corrupted 
wiki could be possible. So i decide not to install it.

How could i do this manually?
I think to copy the header manually is a little bit annoying. Is there 
any other way?

Many regards
Poul

Am 16.02.2015 um 14:30 schrieb Myron Turner:

**Comment by turnermm** [comment]
I am looking at how to include the useheading option.  I will let you know what I can do.

**Comment by turnermm** [comment]
Try this:
http://www.mturner.org/fckgLite/doku.php?id=dailies&#useheading

**Comment by poulpoulsen** [comment]
Hello,

Thank you for this version.
I tested it and it works - WOW!
If anything goes wrong, i will write to you, but it looks fine until now.

Best regards
Poul

Am 17.02.2015 um 05:39 schrieb Myron Turner:

**Comment by poulpoulsen** [comment]
Hello,
i used the new version today for a longer time and want to give you a 
first feedback.

First of all, it works.
But something of handling is a little bit strange:
If i create an internal link with pageheader i can save it correctly.
After that i see a line with some # signs inside the link.
Now i have to load the wikipage with the new link inside (not the linked 
page!) again in edit mode.
After that inside the editor i see the link correctly without any # signs.
A final save works well and the wikipage is linked in the correct way.
Why do i have to go inside the editor two times? Is it always 
neccessary, or only a temporalely workaround?

Regards
Poul

Hello,

Thank you for this version.
I tested it and it works - WOW!
If anything goes wrong, i will write to you, but it looks fine until now.

Best regards
Poul

Am 17.02.2015 um 05:39 schrieb Myron Turner:

**Comment by turnermm** [comment]
I've made some changes for efficiency in the latest version, which is on github.  It compresses the javascript files that links use and by-passes an unecessary step.  It may make for greater speed.
