### ISSUE TITLE
unicode image metadata gets broken

### ISSUE THREAD

**Issue by NitroNerd** [turnermm/ckgedit#704]
hi, after saving, metadata for images turns to this:
`{{:pics:01975-4092562812-content_aware_fill_deep_space.jpg?200|UNICODE��c�o�n�t�e�n�t� �a�w�a�r�e� �f�i�l�l�,� �d�e�e�p� �s�p�a�c�e�

�S�t�e�p�s�:� �3�1�,� �S�a�m�p�l�e�r�:� �E�u�l�e�r� �a�,� �C�F�G� �s�c�a�l�e�:�

�7�,� �S�e�e�d�:� �4�0�9�2�5�6�2�8�1�2�,� �S�i�z�e�:� �1�2�4�8�x�7�0�4�,�

�M�o�d�e�l� �h�a�s�h�:� �0�d�a�c�7�0�8�9�e�1�,� �M�o�d�e�l�:� �1�_�G�S�R�Z�N�,�

�D�e�n�o�i�s�i�n�g� �s�t�r�e�n�g�t�h�:� �0�.�7�5�,� �M�a�s�k� �b�l�u�r�:� �4�,�...}}"`

is there any way to block reading, parsing and saving metadata? or make dummies like " " ?
I need to kepp good links without additional information:
{{:pics:01975-4092562812-content_aware_fill_deep_space.jpg?200}}

**Comment by turnermm** [comment]
https://forum.dokuwiki.org/d/21534-retiringGet Outlook for Android

**Comment by NitroNerd** [comment]
> https://forum.dokuwiki.org/d/21534-retiringGet Outlook for Android

no, thanks. I already hacked it

**Comment by turnermm** [comment]
Perhaps you could share for other users
