### ISSUE TITLE
Newline lost after saving

### ISSUE THREAD

**Issue by moneytoo** [turnermm/ckgedit#705]
This is my source document, as edited in DW Edit:

```
> a

b\\
c
```

![image](https://github.com/turnermm/ckgedit/assets/1071643/4d5535f3-d7fb-49e4-b758-b5d46882a874)

Steps to reproduce:

1. Open it in CKEditor and it shows exactly as it should
2. Add new paragraph containing text "d" at the end of the document
3. Save the changes

Content of the editor looks fine before saving:

![image](https://github.com/turnermm/ckgedit/assets/1071643/50f6b838-b450-4fd1-9a28-f76eec63f0cf)

But newline is lost after saving:

![image](https://github.com/turnermm/ckgedit/assets/1071643/a1686859-649c-48de-b83c-182fe28aaaa8)

```
> a

b
c

d
```

If do the same changes in DW Edit, newline doesn't get lost.

Using:
CKEditor 4.11.4 (revision e1836357e)
Modified for use with Dokuwiki: current_22-Oct_06-11_22

Browsers:
Google Chrome 116.0.5845.180 or Firefox 117.0 on Windows 11

**Comment by turnermm** [comment]
https://forum.dokuwiki.org/d/21534-retiring
