### ISSUE TITLE
MULTI_PLUGIN_OPEN

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#72]
Hi,
if there are several commands 
```
~~MULTI_PLUGIN_OPEN~~
...
~~MULTI_PLUGIN_CLOSE~~ 
```
only the first one works correctly. In the ckgeditor the next commands are replaced by the first one. 
Example:
```
~~MULTI_PLUGIN_OPEN~~
---- dataentry techn_mitteilung ----
Titel                   : TB-Mitteilung
Thema                   : Werkstück-Entnahmehandling, Greiferabfrage / Aufsatzbacken
...
----
~~MULTI_PLUGIN_CLOSE~~

===== Beschreibung =====
...

~~MULTI_PLUGIN_OPEN~~
---- datatemplatelist ----
template: vorlagen:emailverteiler
cols : email_mail
filter : abteilung ~~ TB, TC, SSC
and : personalfunktion >
----
~~MULTI_PLUGIN_CLOSE~~

```
becomes
```
~~MULTI_PLUGIN_OPEN~~
---- dataentry techn_mitteilung ----
Titel : TB-Mitteilung
Thema : Werkstück-Entnahmehandling, Greiferabfrage / Aufsatzbacken
...
----
~~MULTI_PLUGIN_CLOSE~~

===== Beschreibung =====
...

~~MULTI_PLUGIN_OPEN~~
---- dataentry techn_mitteilung ----
Titel : TB-Mitteilung
Thema : Werkstück-Entnahmehandling, Greiferabfrage / Aufsatzbacken
...
----
~~MULTI_PLUGIN_CLOSE~~
```

Regards
Juergen

**Comment by turnermm** [comment]
If I remember correctly, you can only use one of these on any page.  I 
have no way of  testing at the moment because my test machine is down 
and will take some time to restore.  sorry.


On 3/2/2015 9:39 AM, Juergen-aus-Koeln wrote:
> Hi,
> if there are several commands
>
> |~~MULTI_PLUGIN_OPEN~~
> ...
> ~~MULTI_PLUGIN_CLOSE~~
> |
>
> only the first one works correctly. In the ckgeditor the next commands
> are replaced by the first one.
> Example:
>
> |~~MULTI_PLUGIN_OPEN~~
> ---- dataentry techn_mitteilung ----
> Titel                   : TB-Mitteilung
> Thema                   : Werkstück-Entnahmehandling, Greiferabfrage / Aufsatzbacken
> ...
> ----
> ~~MULTI_PLUGIN_CLOSE~~
>
> ===== Beschreibung =====
> ...
>
> ~~MULTI_PLUGIN_OPEN~~
> ---- datatemplatelist ----
> template: vorlagen:emailverteiler
> cols : email_mail
> filter : abteilung ~~ TB, TC, SSC
> and : personalfunktion >
> ----
> ~~MULTI_PLUGIN_CLOSE~~
>
> |
>
> becomes
>
> |~~MULTI_PLUGIN_OPEN~~
> ---- dataentry techn_mitteilung ----
> Titel : TB-Mitteilung
> Thema : Werkstück-Entnahmehandling, Greiferabfrage / Aufsatzbacken
> ...
> ----
> ~~MULTI_PLUGIN_CLOSE~~
>
> ===== Beschreibung =====
> ...
>
> ~~MULTI_PLUGIN_OPEN~~
> ---- dataentry techn_mitteilung ----
> Titel : TB-Mitteilung
> Thema : Werkstück-Entnahmehandling, Greiferabfrage / Aufsatzbacken
> ...
> ----
> ~~MULTI_PLUGIN_CLOSE~~
> |
>
> Regards
> Juergen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turnermm/ckgedit/issues/72>.
>


-- 
Myron Turner
http://mturner.org/
https://github.com/turnermm

**Comment by turnermm** [comment]
Yes, you can use only one of these on a page.  This is something I will look at to see if I can fix it.

**Comment by Juergen-aus-Koeln** [comment]
Ok thank you for the moment

Regards Juergen

**Comment by turnermm** [comment]
I have a version which works with multiple MULTI_OPENs on a page.  I have not posted it to github yet but instead uploaded it to the fckgLIte web site:  [ckgEdit-ckedit_43-15-Mar_13-14_53.tgz](http://www.mturner.org/fckgLite/lib/plugins/fckg/fckeditor/userfiles/media/ckeditor/ckgEdit-ckedit_43-15-Mar_13-14_53.tgz).  It required some refactoring of the code and so I hope you will try it out for a while and let me know if you have any trouble with it.  If all goes well I will update github.

**Comment by turnermm** [comment]
Also can be downloaded from [Sourceforge](http://sourceforge.net/projects/fckglite/files/ckedit/ckgEdit-MULTI_OPEN-refactor.tgz/download)

**Comment by turnermm** [comment]
Also now available from the ``multi`` branch here on github:
https://github.com/turnermm/ckgedit/archive/multi.zip

**Comment by Juergen-aus-Koeln** [comment]
Thank you

Regards Juergen

**Comment by turnermm** [comment]
Have you been using this version and, if so, is it working OK?

**Comment by Juergen-aus-Koeln** [comment]
Yes it works, thank you very much
