### ISSUE TITLE
list properties not supported

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#73]
Hi,

when I modify the property of a numbered list from default ("1, 2, 3 etc.") to "A, B, C etc." it is displayed correctly in the ckg-editor. But after saving the default property for numbered lists will be set again.

Regards Juergen

**Comment by turnermm** [comment]
Lists are governed by the Dokuwiki css.

**Comment by turnermm** [comment]
I've removed the context menu item which enables changing the list style in the CKEditor.

**Comment by Juergen-aus-Koeln** [comment]
ok, thank you

Regards Juergen
