### ISSUE TITLE
Customize Height of Edit Window

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#75]
Customize Height of Edit Window

The hight of my editing section is pretty short. I usually have to drag the bottom right corner to make it longer. As a non-programmer I don't know how to include the code into the js-file:

I've put the command config.height = '400px' into the code of the file config.js in front of b.colors=new Array(…), but the only result ist that the editor window is empty and remains white.

Isn't there a chance to make the window higher as default?

Regards Juergen

**Comment by turnermm** [comment]
First, it accepts just the number: 400, without the px.  Secondly, you have to have a semi-colon after the number:
   config.height=400;
because this is a compressed file and you could be bumping into whatever follows your new entry.  The safest place to add an entry  is in config.js.unc.  That is the uncompressed version of the config file. Then replace the compressed version with this by renaming ``config.js.unc`` to ``config.js``.

**Comment by turnermm** [comment]
There is a simpler solution, which requires adding a line to the action/edit.php file.  At line about 478, you will find:

```
$ckeditor_replace =<<<CKEDITOR_REPLACE
		   ckgeditCKInstance = CKEDITOR.replace('wiki__text',
		       { 
                  toolbar: '$toolbar' ,  
                  filebrowserImageBrowseUrl :  '$doku_url/lib/plugins/ckgedit/fckeditor/editor/filemanager/browser/default/browser.html?Type=Image&Connector=$doku_url/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php',
                  filebrowserBrowseUrl: '$doku_url/lib/plugins/ckgedit/fckeditor/editor/filemanager/browser/default/browser.html?Type=File&Connector=$doku_url/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php',                                
               }
		   );
           FCKeditor_OnComplete(ckgeditCKInstance);
```
under ``toolbar: '$toolbar' ,  ``, add this line:   ``height: 250,``
```
                  toolbar: '$toolbar' ,  
                  height: 250,
```
You can change 250 to whatever you need.

**Comment by Juergen-aus-Koeln** [comment]
Ok, thank you, that's really a simplier way. I've changed to a height of 600. This works for me at the moment.

But another problem is that with each update of the plugin the height will be changed again to the standard value. I don't know how difficult this is, but the best way should be if the hight would be adapted to the actual window size.

Regards Juergen

**Comment by turnermm** [comment]
You can always use the Maximize button.

**Comment by turnermm** [comment]
I've added a new text field for specifying the editor window height:

![editor_height](https://cloud.githubusercontent.com/assets/176447/8253144/6aa7d10e-1652-11e5-8458-5d2f985fa011.png)

Enter the new height into the text box and reload the page. To reload you can click on 
Save, Cancel, or Edit Fonts.  Clicking Delete will do the same thing but will, of course, delete your page.
The height defaults to 250 pixels.

**Comment by Juergen-aus-Koeln** [comment]
The idea is really good. But when re-starting the browser, the value is again 250px.

**Comment by boutmos** [comment]
In google chrome console : 
CKEDITOR.instances.wiki__text.container.$.querySelector('#cke_1_contents').style.height = "800px";

It works but, I when I try include this line in a  custom JS file, my javascript file is never executed.
I follow this : https://www.dokuwiki.org/devel:javascript

autogenerated JavaScript (language strings, config settings, [toolbar](https://www.dokuwiki.org/toolbar))
lib/scripts/*.js
lib/plugins/*/script.js
lib/tpl/<currenttemplate>/script.js
conf/userscript.js (placed at the end of the code block)

Thanx
