### ISSUE TITLE
Sometimes no image is inserted

### ISSUE THREAD

**Issue by ol8vil** [turnermm/ckgedit#76]
When I insert image from my server and save changes, image doesn't appear or appears small part of it. I am using dokuwiki Release 2014-09-29d "Hrun", latest ckgeditor and Chrome 41.0.2272.89 (64-bit). Thanks in advance.

**Comment by ol8vil** [comment]
I see that CKGEditor image path is */lib/plugins/ckgedit/fckeditor/userfiles/image/image.png* while actually image is in another folder, however inserting of an image works sometimes so I don't know.

**Comment by turnermm** [comment]
There's nothing wrong with that path.  

 If your web server is linux try setting the winstyle option to true:
    https://www.dokuwiki.org/plugin:ckgedit:configuration#winstyle
Be sure to follow the instructions pointed to by the link to the fckgLite web site.

If it is Window, set the nix_style option to true.
   https://www.dokuwiki.org/plugin:ckgedit:configuration#nix_style

**Comment by ol8vil** [comment]
Tried winstyle - still not working.

**Comment by ol8vil** [comment]
Tried again - it seems everything is working now. Thanks for your amazing work!

**Comment by ol8vil** [comment]
Unfortunately, all gone wrong. First, some pages became blank but visible in editor. Then dokuwiki began to degrade and now almost all plugins and settings don't work.

**Comment by turnermm** [comment]
On what server is Dokuwiki running?  What is your desktop system -- name and version? What happens if you disable ckgedit.  You can do this by putting a file named disabled into the ckgedit directory.  Or by removing ckgedit using ftp.   Are you with a hosting company?  If so, which one? And do they have any restrictions?  If your wiki is online, what is its url?

**Comment by turnermm** [comment]
Also, there could be a conflict between ckgedit and one of your other plugins.  The only way to test for this is to disable all your plugins except for ckgedit.  If it works, then re-enable your other plugins one at a time, to see which is causing the conflict.
