### ISSUE TITLE
Complex tables

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#81]
Hi,

again I have a problem with Complex tables.

The code before editing with ckgedit:
```
^  Ladertyp             ^  min. StangenØ in mm  ||||^  Ladezeiten bei 3 m-Stangen in sec  ^
| :::                   ^  4                    ^  5  ^  6  ^  8  ^  10  | :::            |
| Sir 25 / 33 P u. F    |  x                    |     |     |     |      |  ca. 25        |
| Sir 25/ 43 P          |                       |  x  |     |     |      | :::            |
```

and after editing:
```
^  Ladertyp  ^  min. StangenØ in mm  ^^^^^  Ladezeiten bei 3 m-Stangen in sec  |
| ^  4  | ^  5  ^  6  ^  8  ^  10  |
|Sir 25 / 33 P u. F  |  x  |   |   |   |   |  ca. 25  |
|Sir 25/ 43 P  |   |  x  |   |   |   | ::: |
```
The code ":::" in the second line is deleted, so that subsequently the table is corrupted.

Regards
Juergen

**Comment by turnermm** [comment]
I'm afraid you will have to work around this using the include plugin. [See the conflguration Options](https://www.dokuwiki.org/plugin:ckgedit:configuration#complex_tables)

**Comment by Juergen-aus-Koeln** [comment]
It`s not only a problem of the complex table syntax. The same happens if you edit the table within the ckg-editor joining together the two cells of column one and two.

My problem is the following: I want to recommend the ckg-editor to the wiki users because it is a really easy-to-use editor. But then, at the same moment I must tell them, that for tables, which are very simple in the users view (like the example), they have to create separate pages (if they have permission) and use the include plugin with its complicated syntax.

**Comment by turnermm** [comment]
I'm not sure how anyone would consider that a simple table, not at least from the point of view of Dokuwiki syntax.  Most tables parse correctly in the ckgeditor using the editor's table tools.  

The include plugin syntax is not especially complex.  Less complex than a link:
         ```{{page>playground:ctable}}```
You can set all the options from the admin configuration panel, so that the above syntax would show only the table in the page.  

For creating and editing tables, you can give your users direct access to the Dkuwiki editor using one of [several techniques]
(https://www.dokuwiki.org/doku.php?id=plugin:fckg#direct_action_link_to_dokuwiki_editor).

At some time in the future I might look at the complex table issue again but it's not a priority.

**Comment by turnermm** [comment]
If you remove the headers from the table, it does parse correctly:
```
|  Ladertyp  |  min. StangenØ in mm  |||||  Ladezeiten bei 3 m-Stangen in sec  |
| ::: |  4  | ::: |  5  |  6  |  8  |  10  |
|Sir 25 / 33 P u. F  |  x  |   |   |   |   |  ca. 25  |
|Sir 25/ 43 P  |   |  x  |   |   |   | ::: |
```
You might try using other means of emphasis, like bold face.

**Comment by turnermm** [comment]
As to how well the complex tables facility works,  [here's an example page] (http://www.mturner.org/devel/doku.php?id=playground:complex_tables).  The page contains a link to the Dokuwiki page.  You can down load it and test for yourself.   There is the occasional table, such as the olne that you show above that might have problems, but most work.

**Comment by Juergen-aus-Koeln** [comment]
Thank you for the examples (one of myself).

I can see that a lot of problems are processed, and I hope that the users will honour that. But in praxis they tend to grouch. And at the end they will refuse editing the wiki content, because - in this case - for tables excel works more smooth.

**Comment by turnermm** [comment]
The complex tables parsing has occasionally caused problems, so I have thought of a different way to handle complex tables for users who need it.  It by-passes entirely the parsing of the table and instead saves the table as HTML, which is then re-inserted into the file when loaded into the editor.  To do this you place the following macros above and below the table:
```
~~START_HTML_BLOCK~~
<your table goes here>
~~CLOSE_HTML_BLOCK~~
```
The table is then saved to the data file as a code block.  But when loaded into the editor or displayed in the browser, the result is the fully formatted table.  The url for download from github is here:
https://github.com/turnermm/ckgedit/archive/html_block.zip
You will find it on github's ckgedit page under the html_block branch.  It seems to work well; O leave it to you to test it.

**Comment by Juergen-aus-Koeln** [comment]
It's a compromise in case that all other possibilities don't work correctly. But, sorry, it's not a solution for the "normal" end user, because he can't recognize if a table is too complex for normal rendering. 

And furthermore, once a table is generated with this syntax, it can't be edited any more by the native wiki editor without having basic knowledge in programming html.

**Comment by turnermm** [comment]
On 4/16/2015 6:01 AM, Juergen-aus-Koeln wrote:
> It's a compromise in case that all other possibilities don't work
> correctly. But, sorry, it's not a solution for the "normal" end user,
> because he can't recognize if a table is too complex for normal rendering.
>
This is true.  It's just possible that ckgedit is not a solution for 
your firm.

> And furthermore, once a table is generated with this syntax, it can't be
> edited any more by the native wiki editor without having basic knowledge
> in programming html.
>
Not so.  It loads back into the editor and can be edited.
-- 
Myron Turner
http://mturner.org/
https://github.com/turnermm

**Comment by Juergen-aus-Koeln** [comment]
You say "It loads back into the editor and can be edited." So, here is the code shown in the native wiki editor after inserting the new command by ckgedit:

```
~~START_HTML_BLOCK~~

<table class="inline">
    <thead>
   <tr class="row0">
            <th class="centeralign">Ladertyp</th>
            <th class="centeralign" colspan="5">min. StangenØ in mm</th>
            <th class="centeralign">Ladezeiten bei 3 m-Stangen in sec</th>
        </tr>
        <tr class="row1">
            <th class="centeralign"><tab></tab></th>
  ...
</table>

~~CLOSE_HTML_BLOCK~~
```

**Comment by turnermm** [comment]
It should be a code block as here:
```
~~START_HTML_BLOCK~~
<code>
<table class="inline">
    <tbody>
   <tr class="row0">
            <th class="centeralign" rowspan="2">Ladertyp</th>
            <th class="centeralign" colspan="5">min. StangenØ in mm</th>
            <th class="centeralign" colspan="1" rowspan="2">Ladezeiten bei 3 m-Stangen in sec</th>
        </tr>
        <tr class="row1">
            <td class="centeralign">4</td>
            <td class="centeralign">5</td>
            <td class="centeralign">6</td>
            <td class="centeralign">8</td>
            <td class="centeralign">10</td>
        </tr>
        <tr class="row2">
            <td class="leftalign">Sir 25 / 33 P u. F</td>
            <td class="centeralign">x</td>
            <td class="leftalign"> </td>
            <td class="leftalign"> </td>
            <td class="leftalign"> </td>
            <td class="leftalign"> </td>
            <td class="centeralign" rowspan="2">ca. 25</td>
        </tr>
        <tr class="row3">
            <td class="leftalign">Sir 25/ 43 P</td>
            <td class="leftalign"> </td>
            <td class="centeralign">x</td>
            <td class="leftalign"> </td>
            <td class="leftalign"> </td>
            <td class="leftalign"> </td>
        </tr>
 
    </tbody>
</table>

<span class="np_break"><span class="np_break"> </span>

</code>

~~CLOSE_HTML_BLOCK~~
```


If you don't get a Dokuwiki code block ``<code>. . .</code>``, I don't know why.   I've run it in Firefox and Chrome on both Window 7 and Ubuntu, off Ubuntu and Centos Servers.  In Safari on OS X.  It has never failed.

**Comment by Juergen-aus-Koeln** [comment]
Sorry, that was a misunderstanding:

Yes, I see the code block. 
And this is was what I meant as I wrote "And furthermore, once a table is generated with this syntax, it can't be edited any more by the native wiki editor without having basic knowledge in programming html."
