### ISSUE TITLE
when copy tables from excel 

### ISSUE THREAD

**Issue by youwi** [turnermm/ckgedit#84]
excel tables trans-to 
```
<td class="et2" height="19" style="color: rgb(0, 0, 0); font-size: 11pt;">
```
chrome console  ,the warn:
```
Uncaught Parse Error: <td class="et2" height="19" style="color: rgb(0, 0, 0); font-size: 11pt;">
```

how to fix it?

**Comment by turnermm** [comment]
Have you tried using the paste word tool?  
![paste](https://cloud.githubusercontent.com/assets/176447/7273406/0bfff468-e8b9-11e4-98e0-cbe6d6013a01.png)
Paste - Paste_as_Plain_Text -  Paste_from_Word
