### ISSUE TITLE
Bug in Multiple Footnotes

### ISSUE THREAD

**Issue by Akis1910** [turnermm/ckgedit#86]
Hello, 
we use the Dokuwiki for articles with many footnotes. Quite often we quote one footnote several times in one article. My colleague uses the DW-editor and he often used those duplicate quotes. When I try to quote the same footnote several times it first works but after editing or just storing the page again the footnotes are corrupted and they then look like in the second snap shot:
![pic01](https://cloud.githubusercontent.com/assets/12138084/7349623/cda93986-ecfa-11e4-9497-9454b61176e6.png) (1)
![pic02](https://cloud.githubusercontent.com/assets/12138084/7349647/f40ae3f4-ecfa-11e4-874a-bd0ecd26e635.png) (2)
 
Unfortunately the same thing happens when I edit any page of my colleague. I can’t edit a page of my colleague without corrupting his footnotes.

We already tried out the plugin for duplicate notes:
![pic03](https://cloud.githubusercontent.com/assets/12138084/7349674/236fe2b6-ecfb-11e4-8877-62cc5d6f592e.png) (3)
 
But then still many of our footnotes were corrupted and we had a lot of strange errors like text was shown as part of the heading:
![pic04](https://cloud.githubusercontent.com/assets/12138084/7349693/40e2b526-ecfb-11e4-951a-61f2f31dc3f7.png) (4)
 
Before:
![pic05](https://cloud.githubusercontent.com/assets/12138084/7349709/5c2512b6-ecfb-11e4-98b1-f457b3a78863.png) (5)
 
After using the plugin and storing the page:
![pic06](https://cloud.githubusercontent.com/assets/12138084/7349728/75452f74-ecfb-11e4-8c81-5cd5e4995f72.png) (6)

Help would be highly appreciated
Thanx, Akis

**Comment by turnermm** [comment]
You have to set the duplicate notes configuration setting to true:
   https://www.dokuwiki.org/plugin:ckgedit:configuration#duplicate_notes
As far as I know, that solved the problems you are having.

**Comment by Akis1910** [comment]
We already tried that one. But it only helped little (see picture 4). Unfortunately th duplicate notes configuration had strange side effects (see picture 5 to picture 6)

**Comment by turnermm** [comment]
It could be the complexity of the footnotes.  In my own testing I tend to use quick simple instances.  I suggest you go to the dokuwiki forum and zip up a copy of a page that gives trouble and attach it to a post.

**Comment by turnermm** [comment]
Or instead of an image of what is wrong,  paste a list of the footnotes here, in their correct format, so that I can test for myself what is happening.

**Comment by turnermm** [comment]
I've been looking at the possibilities and the best thing would be if you send me a copy of a Dokuwiki page that becomes corrupted.  If you don't want to use the forum, you can get my email address from the file ``plugin.info.txt`` in the ckgedit root directory.

**Comment by Akis1910** [comment]
Hello, 
since we had really strange effects with the duplicate notes plugin. We don't dare putting it on again. With the picture 5 I sent you in the first post, this page was written by my colleague in the dw-editor. When I than stored it with the CKG-editor it looked like picture 6 in the first post.

it is difficult here with the formatting.

This is how it looked like in the DW-editor:
![dweditor](https://cloud.githubusercontent.com/assets/12138084/7412234/d99f4e2c-ef40-11e4-9cff-0b976f34a029.PNG)


===== Use =====

Polyurethanes are used for a variety of applications, including:

  * Low-density flexible foam used in upholstery and bedding
  * Low-density rigid foam used for thermal insulation and RTM cores
  * Soft solid elastomers used for gel pads and print rollers
  * Low density elastomers used in footwear
  * Hard solid plastics used as electronic instrument bezels and structural parts
  * Durable elastomeric wheels and tires
  * Electrical potting compounds
  * Adhesives, sealants and coatings
  * Spandex fibers

I don't dare putting on the duplicate plugin again. But when I then opened this page with the CKG-editor with the duplicate plugin on, it looked like in picture 6 of the first post

**Comment by turnermm** [comment]
I inserted your text in two places on a page with many footnotes, using the duplicate plugin setting, and I did not reproduce your results.  I will need a copy of the whole page.  Errors such as you are describing are the result of contexts, and until I have the complete contexts for your footnotes and your list, I can't test for the errors.

Here is my result for a fairly detailed page with about nine footnotes, including duplicates:
http://www.mturner.org/devel/doku.php?id=playground:multi_notes
There are two instances of your unordered **Use** list:
http://www.mturner.org/devel/doku.php?id=playground:multi_notes#use
http://www.mturner.org/devel/doku.php?id=playground:multi_notes#use1

**Comment by Akis1910** [comment]
I'll ask someone of our IT to post the page the way it was on that date via one of the less public channels you mentioned. What I noted from the examples is that there are only duplicate footnotes but we often have triplicate footnotes or even four times the same footnote. That is what went wrong in picture 4. There was a fine duplicate footnote (5) and 7) presentation by R.Wilken) but more than duplicate didn't work.

**Comment by turnermm** [comment]
With the help of the sample pages forwarded to me by your dokuwiki department, I was able to solve the footnote problems--there were three issues, not just one, and without your sample pages, I wouldn't have known where to look.  

The current version of ckgedit on github has the corrected version.  Download it and try it out.

**Comment by Akis1910** [comment]
Thank you very much :-)
