### ISSUE TITLE
Save button not working

### ISSUE THREAD

**Issue by clemens-schlegel** [turnermm/ckgedit#89]
I've a fresh installation of DokuWiki with Upgrade & ckgedit plugins, I substituted \action\edit.php by the pre_php_5.3 version (my provider runs php 5.2.6). DW edit works fine, however I'm unable to save anything using ckgedit, hitting the "Save" button nothing happens. The JS console says: 
"Uncaught ReferenceError: getComplexTables is not defined" (regardless wether ComplexTables is enabled or not). I'm using Chrome 42 (other browsers not checked up to now). Any idea ?
Best regards,
Clemens

**Comment by turnermm** [comment]
I've corrected the file, and updated it to the most recent version.  Either of the two:
http://sourceforge.net/projects/fckglite/files/ckedit/pre_php_5.3.zip/download
http://sourceforge.net/projects/fckglite/files/ckedit/pre_php_5.3.tgz/download

**Comment by clemens-schlegel** [comment]
Thank you very much for your quick reply. 
Unfortunately your fix did not help: Opening the wiki main page now throws the message:
"Parse error: syntax error, unexpected T_FUNCTION in ...../DokuWiki/lib/plugins/ckgedit/action/edit.php on line 969". In the JS console now there is no message.

**Comment by turnermm** [comment]
I replaced both the tgz and zip files with corrections.

**Comment by clemens-schlegel** [comment]
Now it works, thanks a lot !
