### ISSUE TITLE
unicode waring in php log

### ISSUE THREAD

**Issue by schplurtz** [turnermm/ckgedit#93]
Hi,
on 2015-05-23, I decided to give chkedit a try. I got these messages in nginx/php log.

```
2015/05/23 21:53:48 [error] 2082#0: *407 FastCGI sent in stderr: "PHP message: PHP Strict Standards:  Non-static method SafeFN::encode() should not be called statically in /home/www/mainsite/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/SafeFN.class.php on line 180
PHP message: PHP Strict Standards:  Non-static method SafeFN::unicode_to_safe() should not be called statically in /home/www/mainsite/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/SafeFN.class.php on line 47
PHP message: PHP Strict Standards:  Non-static method SafeFN::encode() should not be called statically in /home/www/mainsite/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/SafeFN.class.php on line 180
PHP message: PHP Strict Standards:  Non-static method SafeFN::unicode_to_safe() should not be called statically in /home/www/mainsite/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/SafeFN.class.php on line 47" while reading response header from upstream, client: 192.168.1.11, server: schplurtz.darktech.org, request: "GET /lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php?Command=GetFoldersAndFiles&Type=Image&CurrentFolder=/&uuid=1432410828357 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "schplurtz.darktech.org", referrer: "http://schplurtz.darktech.org/lib/plugins/ckgedit/fckeditor/editor/filemanager/browser/default/browser.html?Type=Image&Connector=http://schplurtz.darktech.org/lib/plugins/ckgedit/fckeditor/editor/filemanager/connectors/php/connector.php&CKEditor=wiki__text&CKEditorFuncNum=1&langCode=fr"
``` 
It may be related to #87 but I'm not sure at all.

versions in use if that matters
DokuWiki 2014-09-29d Hrun

ckgedit : the one you get via plugin manager

php5-fpm  5.4.39-0+deb7u2       armhf

OS
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy

**Comment by turnermm** [comment]
The problem code is from the Dokuwiki core from when safe encoding was introduced and which I adopted for ckgedit.  I see that they have since modified these two functions as static.  I'll do the same but in the meantime, if you don't need it for your own work, you can get rid of the warnings by removing the E_STRICT constant from php.ini.

**Comment by schplurtz** [comment]
Thanks.

I think I can live for some time with E_STRICT disabled on this wiki, which is for my own use only.

**Comment by turnermm** [comment]
Download: [safefn.class.zip](http://www.mturner.org/devel/lib/exe/fetch.php?media=playground:safefn.class.zip) and substitute SafeFN.class.php for the one in ``plugins/ckgedit/fckeditor/editor/filemanager/connectors/php``. 
Please test it for me before I include it in the ckgedit distribution.

**Comment by schplurtz** [comment]
I tried it, and the warning disappeared as expected.

Now the test with a filename with national chars (This is really new for me, I only use ASCII in filename): 
Create a local file called SÉçà.png, then use ckgedit to insert it in a page and upload the file to DW

DW setting : ```$conf['fnencode'] = 'safe';```
Desktop computer is Linux with FireFox 38.0

the file was uploaded without errors
the file showed in ckgedit preview
but when I saved the file in DW, the image did not appear on the page.

looking in DW directories, it appears the file was uploaded as  ```_1f_4p_5j_5c_.png``` and the text in the .txt file was accordingly ```{{:playground:_1f_4p_5j_5c_.png?nolink&528x102}}```

After that, I disabled ckgedit and uploaded the same file with DW media manager. the file name on the server was "seca.png",

**Comment by turnermm** [comment]
The reason for this is that Dokuwiki normalizes file names but ckgedit takes them as is.  You have two uppercase characters in your file name, so Dokuwiki ignores the file, even though ckgedit accepts it for upload.  I did test using your file name in various configurations and it seems ok.  Thanks.

**Comment by turnermm** [comment]
I'm afraid I spoke to soon.  There seem to be other problems with files that have non-latin character sets.

**Comment by turnermm** [comment]
Both the safe-encoding and the utf-8 apparently broke when I upgraded to one of the newer versions of the CKEditor,  (4.4.3 or 4.4.7). But no problems had been reported.  Fixing it was a big job, and I was almost ready to call it quits on the safe-encoding.  Anyway, it looks OK but I have so far not included these fixes in the main distribution but have created a separate branch, which you can find here: 
  https://github.com/turnermm/ckgedit/archive/filebrowser_update.zip
It also includes the fix for the E_STRICT warnings.  Thanks.
