### ISSUE TITLE
[Question] Will this Bookmarklet work with ckgedit? DW-Editor works

### ISSUE THREAD

**Issue by poulpoulsen** [turnermm/ckgedit#94]
Hello,
i use the following Bookmarklet inside Firefox with DW to save Bookmarks easily.
Unfortunately it is not working, if ckgedit is the standardeditor. I think, that some javascript code inside the bookmarklet do not work correct with ckgedit.
Perhaps you could see any faulty lines? Or do i have to rewrite something to work with ckgedit?

Here is the code:
javascript:
%20Q=document.selection?document.selection.createRange().text:document.getSelection();%20%20L=location.href;
%20%20D=document.title;%20%20P='~~MULTI_PLUGIN_OPEN~~'+'\n'+'----%20dataentry%20projects%20----'+'\n'+'Link_title:%pageid%'+'\n'+'Beetnr:'+'\n'+'Bl%C3%BCtezeit:'+'\n'+'Foto:'+'\n'+'Licht:'+'\n'+'Wuchsh%C3%B6he:'+'\n'+'Farbe:'+'\n'+'geplant:'+'\n'+'gekauft:'+'\n'+'gepflanzt:'+'\n'+'----'+'\n'+'~~MULTI_PLUGIN_CLOSE~~'+'\n';
%20%20d=new%20Date();
%20%20I=d.getFullYear()+':'+(d.getMonth()+1)+'-'+d.getDate()+'--+d.getHours()+'_'+d.getMinutes()+'_'+d.getSeconds();
%20%20%20myWindow=window.open('','dokuwikiadd','scrollbars=yes,resizable=yes,toolbars=yes,width=1024,height=768,left=200,top=160,status=yes');%20%20f=myWindow.document.createElement('form');
%20%20f.method='post';
%20%20f.action='http://localhost:8800/doku.php?id=Lesezeichen:Garten:'+I;%20%20i0=document.createElement('input');
%20%20i0.type='hidden';
%20%20i0.name='wikitext';
%20%20i0.value='===%20'+D+'%20===\n'+'\n'+P+'\n'+'%20%20*%20'+L+'\n'+Q+'\n{{tag>Lesezeichen}}';
%20%20i1=document.createElement('input');
%20%20i1.type='hidden';
%20%20i1.name='do';
%20%20i1.value='preview';
%20%20f.appendChild(i0);
%20%20b=myWindow.document.getElementsByTagName('body')[0];
%20%20%20b.appendChild(f);
%20%20%20f.submit();

Regards
Poul

**Comment by turnermm** [comment]
I am not really familiar with bookmarklets, I've never used them myself.   But I suspect that the problem is that your javascript doesn't have access to the editor.  That is, the editor's ``document`` is not the same as the `` document`` your code is referencing.   You might try the forum, someone there might have had success with this.

**Comment by poulpoulsen** [comment]
Hello,
thank you for your quick answer.
I posted it here, because i noticed that the javascript code works with the plain dokuwiki editor. But if i activate ckgedit, nothing happens :-(
Therefore i thought, that there is something different in calling the editor.

Regards
Poul
