### ISSUE TITLE
Save button not working php 5.4

### ISSUE THREAD

**Issue by Scrupulosis** [turnermm/ckgedit#95]
Just did an update this morning, had November 11th version, and save button is no more working.  Tried the pre-5.3php fix, didn't fixed this problem.  

PHP Version 5.4.39-0+deb7u2
Hrun 2014-09-29d

**Comment by turnermm** [comment]
I've tested in Debian with the following configuration:
PHP 5.4.38-0+deb7ul
 _ckgEdit-ckedit_47-15-May_24-20_02_

Tested both: 
2014-09-29d "Hrun", installed in var/www
Release 2012-01-25b "Angua", installed with apt-get

I had no problems saving. Neither Hrun nor Angua required the 5.3 fix but I tested the 5.3 fix in Angua and it worked as well.  I tested on Debian with Iceweasel and Firefox on windows 7.  Both show javascript errors originating from the scayt spellchecker. You can try disabling it in the configuration manager.  You should also check for javascript errors.

**Comment by andremadar** [comment]
Same issue here as Scrupulosis, but only with Internet Explorer. In Chrome, Save button was working fine. Debian, Hrun 2014-09-29d installed in /var/www, latest PHP. After upgrading to the May 24 ckgedit, the Save button in IE didn't do anything.

**Comment by turnermm** [comment]
Was working in Chrome but is/is not working now?   Which IE?  Which Windows? 
Was working in IE before but not now? If it was, try clearing the browser cache.  Do you know how to use the debugger?  Check for Javascript errors.  Try reverting to the previous version you were using.  What happens then?  You can get it or a near-realtive from the fckgLite web site:
http://www.mturner.org/fckgLite/doku.php?id=dailies&b_disp=1#ckeditor_4

**Comment by turnermm** [comment]
As a follow-up:  You might try using the developer tools (F12) to set the Document Mode to IE9 Standards, and Browser Mode to either IE10 or IE10 Compatibility.  I was just doing a test and see that the IE10 Document Mode fails in the CKEditor core, over which I have no control. And I am using the latest CKEditor version (4.4.7).

**Comment by turnermm** [comment]
I just tested with IE11 on Windows 8.1 and all worked with no special compatibility settings, using the latest ckgedit version: ``_ckgEdit-ckedit_47-15-Jun_01-23-38``.

**Comment by Scrupulosis** [comment]
This may indeed be related to the spellchecker since its menu-icon is messed-up too.  Although putting it off in the plugin parameter didn't fix the problem.  For now I have replaced action/edit.php to the older version I was using and I can now save without problem.

Note that I'm using the french localization of DokuWiki, maybe you could try this turnermm in your test, and by the way so much thanks for taking this time.

**Comment by Scrupulosis** [comment]
Don't know what happen, I end up having to erase /plugin/ckgedit folder all together, update it from the plugin manager, and now everything's find, and the spellchecker menu display correctly.

**Comment by turnermm** [comment]
That's good news. These problems are often because of the cache, and when you re-install a plugin the cache is refreshed and the browser will also be notified of the change and request a new copy of the files.

**Comment by andremadar** [comment]
Hi, sorry to bug you, cleared IE11 cache (Win7) and it's working again.
D'oh.

**Comment by turnermm** [comment]
Not a  problem.
